### ISSUE TITLE
Installation: check return code of the executed SQL statements

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#10]
In Installer.pm there are SQL-statements first collected and then executed. However the return status of the execution is never inspecter. Thus the intstaller GUI might report everything as successful, even when some tables were not created.

TODO: inspect the return code and stop the installationj when there are errors

**Comment by svenoe** [comment]
Agreed.

**Comment by bschmalhofer** [comment]
Broke an INSERT in _scripts/database/otobo-initial_insert.xml_ and got an error when running installer.pl.
That's the wanted result. Closing the issue.
