### ISSUE TITLE
Implement process tickets for the customer interface

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1002]
I will convert this issue to a discussion - please follow the link given above this.

Since this project is a little larger, and several parties are involved, I propose to use this issue as the main issue for planning and discussion, and I will keep this post up-to-date with our vision on how things should work and look on each screen. I also created a project for this, to be able to better organize the individual tasks related to this (https://github.com/RotherOSS/otobo/projects/2).

---

**CustomerTicketProcess**
Should in principle look like CustomerTicketMessage.

---

**CustomerTicketZoom**
We think that the best place for the links to the possible actions would be between the header and the articles, as shown in the red box in the picture below. This is just an example taken from the pr of @dk-ciphron.

![Rastergrafik](https://user-images.githubusercontent.com/48322755/117809971-1cd09100-b25f-11eb-9143-3fd44337786e.png)

An idea here was, to have a possibility to perform simple actions, like "accept" something in a single click, without the detour of CustomerTicketProcess.

---

**Open Questions**
1. Is it necessary to have an explicit "Create new process ticket" for the customer user? A process can easily be initiated by the generic interface out of customer tickets with a certain set of parameters, and we don't see a real benefit of having this separation apparent for the customer user.
2. Would it be useful to integrate the action links into the TicketLists? (E.g. behind the three dots which at the moment have no function.)

**Comment by svenoe** [comment]
We received a pr of dk-ciphron (https://github.com/RotherOSS/otobo/pull/990 - thanks, here, too :), which, for now, I merged into the branch [issue-#1002-customerprocess_01](https://github.com/RotherOSS/otobo/tree/issue-%231002-customerprocess_01) to maybe use it as a foundation for further development.

Our biggest question would be, if it is necessary to have this separation between normal ticket creation and process-ticket creation. Some further improvements of the UI would also be needed, but it is functional, and probably a good starting point. I can get into more detail at another time, for now I would prefer to gather some opinions first.

**Comment by joserribeiro26** [comment]
Using two CustomerTicketMessage and CustomerTicketProcess Interface usually leaves the user confused about opening tickets. If it is centered on a single screen, I think it would be a great idea.
But due to the modularization of the process components, I think that the effort is much greater.

**Comment by acorderor** [comment]
I think since there could be many different processes and from different areas it would be a good idea to be able to see them as a tree, the same as the Service Catalog or the Queues where one can see the available proceses listed and expanded based on a prequalification for example Human Resources -> Process 1, Process 2, etc

**Comment by svenoe** [comment]
> But due to the modularization of the process components, I think that the effort is much greater.

@joserribeiro26 - With the hideshow-functionality the CustomerTicketMessage is already quite modular, we feel, and we already have a package which will be included in the standard, which allows to remove the subject, the main text box, and the attachments from the CustomerTicketMessage. The only real difference I'm aware of, is, that still always an article will be created (and those fields will contain standard values, or a summary of the filled in fields of the CustomerTicketMessage), and you will necessarily have a queue selected. But I'm not so sure, whether there are processes where this is absolutely unwanted (and if, we could also remove the necessity to create an article from CustomerTicketMessage - it seems a bit strange to me, though).

It is probably more effort, though, to prepare all of this via ACLs, I agree.

> I think since there could be many different processes and from different areas it would be a good idea to be able to see them as a tree...

@acorderor - Exactly this would be achieved by letting the customer user select a service, e.g., just in the standard way in the customer ticket message, and then having a generic agent start the process in the background if this specific service was selected, without the customer user having to bother with it.

---

In general it wouldn't be much more effort to support both ways, I guess. Actually in the pr of @dk-ciphron the old "create a new process ticket" is already implemented, anyways. But the question is maybe more, if there should be put effort into expanding this route, like the example of @acorderor, or not.

**Comment by acorderor** [comment]
In fact I have many several implementations where the customer itself requests the service via a process ticket, each of the process has its own set of fields to be completed. For that reason my idea of being able to let them choose a path as a tree to be able to fill the right form and avoid the need to having some one re-routing the ticket or asking for additional information. In fact as @joserribeiro26 it gets confusing to have multiple options, but usually my customers prefer to get ride of the standard option and go through the New Process Ticket option as standard, The key is the expandability and the possibility of form customization it offers. Usually customers are not satisfied with the simplicity of the standard new ticket form.
