### ISSUE TITLE
Issues with readme.md

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1016]
The file readme.md is prominently visible on the GitHub starting page for OTOBO: https://github.com/RotherOSS/otobo . There are some issues with that file:

- [ ] _OTOBO is one of the most flexible web-based ticketing systems used for Customer Service, Help Desk, and IT Service Management based on the ((OTRS)) Community Edition._ That sentence is IMHO too long.
- [ ] Maybe also reference Znuny LTS
- [ ]  _OTOBO offers always full OTOBO functionality._  That's a tautology.
- [ ]    _OTOBO offers always full OTOBO functionality._  Link is to the German site
- [ ] Link to OTOBO homepage points to German site
- [ ] _It is distributed_  What is distributed?
- [ ] Link COPYING is broken
- [ ] _is available on github_   The site is usually called GitHub
- [ ] Maybe move the content of "How to contribute" to the dedicated file CONTRIBUTING,md

**Comment by GritRother-OTOBO** [comment]
Hi Bernhard, 
I changed the file and commited the changes to rel-10_0. 
Please merge them to rel-10_1 and close this issue. Thanks!

**Comment by bschmalhofer** [comment]
The README was update in rel-10_0 and in rel-10_1. Closing this issue.
