### ISSUE TITLE
Wrong parse of customer mail adress in followups

### ISSUE THREAD

**Issue by Velcatt** [RotherOSS/otobo#1024]
Hello there,

I'm currently trying to setup Otobo mailing and I encountered a weird issue : when I try to reply to a ticket, it's supposed to autofill the "To" field with the name and mail address of the customer. However the address parses oddly and the first name of the customer is added within the "<>" that encapsulates email address (which is weird since the mai field is correctly set up on the customers). That means I have to manually write the customer's mail everytime if I want the mail to be delivered. Is there any way to change the way Otobo automatically fetches email for followup replies ?

here's a picture to make it clearer : <edit svenoe - picture removed>

Thanks

**Comment by svenoe** [comment]
Hi Velcatt,

usually there are no problems with this. I assume this customer is not defined as a customer user in the ticket system, so the email itself is interpreted in a strange way. (I saw the picture and removed it, to not have email addresses publicly flying around here. It was basically a '"name" <xxx@yyy.fr surname>'.)

Could you please download the email (either directly from your mail provider, or by enabling Ticket::Frontend::PlainView in the SysConfig, then going to the respective article, click on "Plain View", or the corresponding translation, and there "Download Email"), open the email in your favorite email client, click on "reply" there, and see, whether it behaves differently? If so, please send an email to hello@otobo.de, with the email attached, and we will have a look at it.

Best regards, Sven

**Comment by Velcatt** [comment]
Thanks for you answer,

I think the said user is defined as a customer, the customer base is linked with LDAP and this account is from the AD. I'll add that in the customer view the email addresses are displayed correctly (it doesn't include the surname, unlike the auto "reply to" field).

I can't seem to be able to download the original article or even open it in plain view, the one that opened the ticket, I'm not sure it's considered like a mail. But I'll send one of the replies that's acting odd at the mail you gave. 

Thanks again for your help

**Comment by svenoe** [comment]
Ah, yes, you won't be able to download it that way, if it was not a mail to begin with - I made wrong assumptions there. In the case you described, it would be important to see what exactly is provided as email address to OTOBO by your AD. Please make sure that everything is correct there, and that OTOBO is properly configured. In principle this definitely works, which doesn't mean that there cannot be a bug somewhere 100%, but to further investigate this, we would need a detailed description on how to reproduce this behaviour, basically...

For more general advice, please consider visiting our [forums](https://otobo.de/en/forums/otobo/otobo-forum/). (Also we received your mail, but the problem lies elsewhere, and this unfortunately doesn't provide more information here.)

**Comment by Velcatt** [comment]
I'll send you a screenshot by mail, but according to the email field in the customer view, the emails are given correctly by our AD. I don't think Otobo is misconfigured either, since the mails woks just fine if I manually type the address. I don't know how to reproduce these steps to be honest, the configuration is almost vanilla so I really don't know what's screwing with that field...

**Comment by Velcatt** [comment]
Well it's definitely a problem between Otobo and our AD but as I wasn't finding any solution (I still don't understand how mail are well stored in the Customers, the notifications works as expected but ticket answers adds first name after the mail address) I ended up editing the js to manually parse out the added first name. Problem solved, even if I don't like the way I solved it, no choice since our Otobo have to be ready by the end of the week. Still, thanks a lot for your help !
