### ISSUE TITLE
placeholder ckeditor customer interface

### ISSUE THREAD

**Issue by joserribeiro26** [RotherOSS/otobo#1035]
When we disable the Frontend::Rich Text setting, the customer portal appears to have a problem with the Class placeholder.
See the image below.

![image](https://user-images.githubusercontent.com/475022/119868631-aafe7580-bef5-11eb-8112-bf71a763b50a.png)

**Comment by joserribeiro26** [comment]
![image](https://user-images.githubusercontent.com/475022/119868877-fca70000-bef5-11eb-9c29-22d10491acdd.png)

**Comment by svenoe** [comment]
Thanks for letting us know. We will have to include this correctly to the css and possibly js.

**Comment by reneeb** [comment]
This seems to be fixed in the meantime. At least in 10.1 beta1 I could reproduce the error...

**Comment by svenoe** [comment]
> This seems to be fixed in the meantime. At least in 10.1 beta1 I could reproduce the error...

"could *not*" I guess. Yes, we introduced quite some changes for the dynamic field generation between 10.0 and 10.1. This came up somewhere in another issue and I forgot about this one. It is fixed at least in 10.1, I'm closing the issue.
