### ISSUE TITLE
Implemention of Process Actions in the CustomerTicketZoom

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#1060]
Customers can be part of a process, so we need the process actions in the CustomerTicketZoom

**Comment by svenoe** [comment]
Here the pr of @dk-ciphron can be used as base. See https://github.com/RotherOSS/otobo/pull/990.

**Comment by svenoe** [comment]
First implementation is merged.

**Comment by svenoe** [comment]
Need to adapt the test. Also have a look at the button lengths.

**Comment by svenoe** [comment]
Fix prefilled text fields. Autoclose other activities (see #1395).

**Comment by svenoe** [comment]
Prefilled text fields are a general bug of rel-10_1 and are dealt with in https://github.com/RotherOSS/otobo/issues/1132 - closing this issue for now.
