### ISSUE TITLE
Any way to get categories ?

### ISSUE THREAD

**Issue by Velcatt** [RotherOSS/otobo#1061]
Simple question : I saw that in future releases Otobo will include a ticket category system. As we're migrating from GLPI we're already used to categories so do you think there's any way to include these into Otobo (even poorly) until then ?

**Comment by svenoe** [comment]
Hi Velcatt,
sorry, but with general questions like this, please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) (or consider getting a support contract). Github atm is really only intended for bugs etc..
Best regards, Sven

**Comment by Velcatt** [comment]
Ok my bad, sorry.
