### ISSUE TITLE
Support for Unified Caching Interface CHI

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#107]
Currently there are two explicit caching interfaces: FileStorable and Redis.
However the usual approach for caching in the Perl world is to use [CHI](https://metacpan.org/pod/CHI). CHI than has different pluggable backends. So support for CHI would be nice.

**Comment by bschmalhofer** [comment]
See also #435 .

**Comment by svenoe** [comment]
Sounds good, would need quite some time to implement properly, though, I guess.

**Comment by bschmalhofer** [comment]
Implementation should be no problem. Just implement the driver module `Kernel::System::CHI`. A benchmark comparing `Kernel::Cache::FileStorable` and `Kernel::Cache::CHI` with the driver `File` would be interesting.

**Comment by svenoe** [comment]
Seems to be not too difficult to at least test it. Please have a look, but don't invest too much time before discussing again.

**Comment by bschmalhofer** [comment]
Closing this, as the suggestion is still on triage.
