### ISSUE TITLE
Docker: upgrade to Perl 5.34.0

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1081]
Currently the web Docker image is based on Perl 5.32.0. Let's upgrade to the new release 5.34.0, https://hub.docker.com/_/perl. The changelog https://perldoc.perl.org/5.34.0/perldelta shows nothing scary. Most interesting is the new experimental try/catch syntax. In older Perls this syntax is useable via https://metacpan.org/pod/Feature::Compat::Try.

The minimal supported version of Perl will stay at 5.24.

**Comment by svenoe** [comment]
What would be the reason? We have to stay compatible with non-docker installations, so new features will not be usable anyways.

**Comment by bschmalhofer** [comment]
OTOBO specifies Perl 5.24 as minimum Perl version, there is no max version specified. This means that Perl 5.34 is officially supported. A good way to guarantee that support is to use 5.34 in Docker based installation.

**Comment by bschmalhofer** [comment]
First test run looks mostly fine. There a 9 failing scripts. Most, if not all, of these failures are due to an encoding issue in Kernel::System::Log::Log(). See #1082.

**Comment by bschmalhofer** [comment]
Running the test suite with Perl 5.34.0 in the Docker images showed the same failures as in HEAD of rel-10_1. Looks good. PR is merged. Closing the issue.
