### ISSUE TITLE
Avatar overlays the logout / preference button in the dashboard

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#1094]
the avatar overlays the logout / preference button in the dashboard.
Version 10.0.10

**Comment by OlliW** [comment]
![otobo_dashboard](https://user-images.githubusercontent.com/80096822/122723048-c64d6e00-d272-11eb-85e8-13908bde2f54.PNG)

**Comment by OlliW** [comment]
![otobo_dashboard2](https://user-images.githubusercontent.com/80096822/122723403-36f48a80-d273-11eb-8624-89d94611cab5.PNG)

**Comment by OlliW** [comment]
![otobo_dashboard](https://user-images.githubusercontent.com/80096822/122723492-525f9580-d273-11eb-88ec-b9f81d496b9c.PNG)

**Comment by svenoe** [comment]
Hi Olli,
I cannot confirm this. My hunch would be, that you maybe have to clear your browser cache. Else please visit https://demo.otobo.org/otobo/customer.pl and login with
User: Felix
Password: Felix
where, upon mouse hover the avatar is blurred out a bit, and the logout and settings icons will be shown separately.
If this is not the case for you please let me know.
Best regards, Sven

**Comment by svenoe** [comment]
I will close this issue for now.
Please let me know, if you couldn't resolve the issue.
