### ISSUE TITLE
It is not easily possible to run OTOBO and OTRS in same mod_perl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#110]
I had the situation where I had both _zzz_otrs.conf_ and _zzz_otobo.conf_ in _/etc/apache2/sites-enabled_ . My guess was that this should work fine, as OTRS and OTOBO are in different databases and are available in different pathes. However http://localhost/otobo/installer.pl loaded the Perl modules for OTRS. This is apparently because die modules are in the same namespace and OTRS prepends to `@INC` after OTOBO. 

A possible fix would be to use a different namespace. E.g. rename Kernel to OTOBO. But this would be a major change with risks and downsides. So for now I would only add a warning in the installation instructions.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

that's not true, I think your config is wrong. It's possible without a problem. Only two systems with mod_perl is not so easy (1 OTRS and 1 OTOBO or 2 OTRS).

Please send me your config file, then I'll take a look at it.

Best wishes,

Stefan

**Comment by bschmalhofer** [comment]
The problem was that OTRS was already installed. When calling installer.pl for OTOBO I got the error that SecureMode is set. My assumption was that installer.pl for OTOBO loaded modules from the OTRS installation, but I did not investigate further. The error went away after I removed zzz_otrs.conf.  I send my configs via Telegram.
