### ISSUE TITLE
Agent email not saved when equal to username

### ISSUE THREAD

**Issue by niccord** [RotherOSS/otobo#1113]
Hi everyone,
as the title suggests, I found this bug: the agent's email is saved in the `user_preferences` table but only when it is different from the username.

This causes two issues:
1. when using `$UserObject->UserSearch(PostMasterSearch => $email)` no user is found;
2. if you change the agent's username, it also became the new agent's email.

---

You can solve this by:
1. removing the block at Kernel::System::User at row 269:
``` perl
# check compat stuff
if ( !$Preferences{UserEmail} ) {
    $Preferences{UserEmail} = $Data{UserLogin};
}
```
  (this method is used a lot in the codebase, so potential side-effects must be verified with care);

2. change the "no useless updates" part at row 1260:
``` perl
# no updated needed
return 1
    if defined $User{ $Param{Key} }
    && defined $Param{Value}
    && $User{ $Param{Key} } eq $Param{Value};
```
adding a condition to check if the Key is "UserEmail".

**Comment by svenoe** [comment]
Hi Nicola,

you are right. I was curious, and the three lines of code which add the UserEmail were added in July 2002, when the email address was not yet mandatory in UserAdd(). (In a nightly session...^^) I'm pretty sure that it doesn't make sense anymore. From my perspective if a method needs an email address from GetUserData() and a user has none, an error could be thrown. Just removing it, however, would lead to problems for all people who have exactly your setup...

Thanks for pointing it out - I will think about how this can be resolved...

(Actually, I think for now we should just call SetPreferences() within this condition and set the UserEmail in the Preferences. This would solve your problem, too, quite quickly. With OTOBO 10.1, or for safety maybe with OTOBO 11.0 we probably can remove this altogether.)

Edit a minute later: Ah^^ - of course this doesn't work. But it could be set directly...

**Comment by niccord** [comment]
Great news! Thank you!
