### ISSUE TITLE
AJAX error message when installing only with SMTP server

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1127]
During installation of OTOBO (via Docker), when only setting the SMTP Server in the installer.pl, an AJAX error message appears. When you additionally fill out the incoming mail server, everything is fine.

**Comment by svenoe** [comment]
The email setup in the installer in general needs some work. There is an older issue which was neglected quite a bit... I will close this issue and mention it in https://github.com/RotherOSS/otobo/issues/375.
