### ISSUE TITLE
"Title or salutation" field displayed in Customer User Name / From column

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1128]
When displaying the "Customer User Name" in e.g. a Dashboard Widget or in a ticket list (e.g. Queue view), always the "Title or salutation" from the customer user information is being displayed. This works out if you put the title there, but it doesn't work out if you put a salutation into that field. Especially when you only put parts of the salutation into there.

![Pasted Graphic](https://user-images.githubusercontent.com/87359203/125411600-5daf6800-e3be-11eb-9e07-50ab8ead33b0.png)

It also looks like that in the column "Name" in Action=AdminCustomerUser

I like the possibility to have a title displayed in those columns, but I would like to have it optional, e.g. a System Configuration setting like "Display title or salutation for customer user name".

**Comment by bschmalhofer** [comment]
Reopened because the issue is still at 'Needs triage'

**Comment by GritRother-OTOBO** [comment]
+1 !
