### ISSUE TITLE
Problem whit Apache2 an Template

### ISSUE THREAD

**Issue by wacorado** [RotherOSS/otobo#1131]
I try to use this solución in a company, have done everything indicated in the installation manual, use Centos 7 server whit all the Software requirements, when y try made this part of te installation 

Configure Apache without SSL support
Copy the template file /opt/otobo/scripts/apache2-httpd.include.conf to the apache sites-available directory. In most cases no further editing of the template is required. Then enable the new configuration.

# Debian/Ubuntu:
root> cp /opt/otobo/scripts/apache2-httpd.include.conf /etc/apache2/sites-available/zzz_otobo.conf
root> a2ensite zzz_otobo.conf
root> systemctl restart apache2

white the equivalent comands of Centos y have this problem 

/var/log/httpd/error_log:[Fri Jul 09 13:43:24.474258 2021] [perl:error] [pid 4742] Can't locate Template.pm in @INC (@INC contains: /opt/otobo/Custom /opt/otobo/Kernel/cpan-lib /opt/otobo/ /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /etc/httpd) at /opt/otobo/scripts/apache2-perl-startup.pl line 72.\nBEGIN failed--compilation aborted at /opt/otobo/scripts/apache2-perl-startup.pl line 72.\nCompilation failed in require at (eval 2) line 1.\n
/var/log/httpd/error_log:[Fri Jul 09 13:43:24.474275 2021] [perl:error] [pid 4742] Can't load Perl file: /opt/otobo/scripts/apache2-perl-startup.pl for server ............

them acces to the apache2-perl-startup.pl whit vi comand an coment or disable the line 72

# Preload dependencies that are always used.
#use Template ();
use Encode qw(:all);

and run the restar for apache2 and the problem is solved but when y try to acces for the installer.pl in ma browser dont run can you helmpe please.

**Comment by svenoe** [comment]
Hi wacorado,

with general questions and problems with regards to the installation, configuration and so on, please visit our forums and ask them there: https://otobo.de/en/forums/otobo/otobo-forum/
I will close this issue here. For the moment we use github just for bugs and development related topics, sorry.

Best regards, Sven
