### ISSUE TITLE
Think about dynamic field rendering

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1132]
The dynamic field HTML differs between the customer and agent interfaces. For standard fields this is only small stuff and taken care of via js atm, but at latest with more special fields arriving we should definitely include the interface which the field is rendered for directly in the backend methods, I think. Also we have to think about this with respect to process management, I imagine...

**Comment by stefanhaerter** [comment]
Related: Issue #625.

**Comment by svenoe** [comment]
Branch merged, the js still needs to be looked at, though, e.g. moving of the labels should not be necessary anymore.

**Comment by bschmalhofer** [comment]
@stefanhaerter Lately I got some unit test errors that might be related to dynamic field rendering. Could you check that?

> /opt/otobo/scripts/test/DynamicField/EditFieldRender.t                                                    (Wstat: 4096 Tests: 69 Failed: 16)
>   Failed tests:  6-21
>   Non-zero exit status: 16
>

**Comment by svenoe** [comment]
Please have a look at the normal text field, again, Stefan. I'm not 100% certain it came with the refactoring here, but it suddenly is a textarea instead of a normal input field, and here would be my first place to suspect... ;)

**Comment by stefanhaerter** [comment]
> Please have a look at the normal text field, again, Stefan. I'm not 100% certain it came with the refactoring here, but it suddenly is a textarea instead of a normal input field, and here would be my first place to suspect... ;)

My bad, commit https://github.com/RotherOSS/otobo/pull/1361/commits/46f9dc5a58bdf7aed3babbf1e9bd540d87c8c7f5 should fix this.

**Comment by stefanhaerter** [comment]
> @stefanhaerter Lately I got some unit test errors that might be related to dynamic field rendering. Could you check that?
> 
> > /opt/otobo/scripts/test/DynamicField/EditFieldRender.t                                                    (Wstat: 4096 Tests: 69 Failed: 16)
> > Failed tests:  6-21
> > Non-zero exit status: 16

This was due to some small mistakes by myself, commit https://github.com/RotherOSS/otobo/pull/1361/commits/46f9dc5a58bdf7aed3babbf1e9bd540d87c8c7f5 should fix this also.

**Comment by svenoe** [comment]
There are still some issues, text fields e.g. are filled with their label.

**Comment by stefanhaerter** [comment]
Reopening this for introducing Selenium tests for Dynamic Fields. First goal is to provide tests for Database fields since this is one of the most complex types.

**Comment by svenoe** [comment]
Closing it again, you can still use it as reference.

On second thought, maybe open another issue in the end, it will be more clear to people reading patch notes later...
