### ISSUE TITLE
Validation of Dynamic Field from type database not works correctly in the CustomerTicketMessage

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#1140]
when i define a Dynamic Field from type database and it is defined as a mandatory Field in the CustomerTicketMessage.
When i hide the Field with an ACL, the validation on the ACLs not working correctly
I can't create an Ticket from the CustomerTicketMessage, because the mandatory Field is not filled out (it's hidden).

**Comment by svenoe** [comment]
This should be solved with the above commits. We still have some open points for other dynamic field types, and actually the above probably has introduced a regression for those, but this only is that some mandatory fields which are initially hidden and then revealed might skip client side validation, and as all fields are checked on the server side again, and it only affects certain types, this is still an improvement. The rest will be dealt with in #1162.
