### ISSUE TITLE
Customer Frontend state selector jumps when ACL is active

### ISSUE THREAD

**Issue by manuelveith** [RotherOSS/otobo#1145]
Version: 10.0.11

ACL:
![image](https://user-images.githubusercontent.com/48509874/126660055-a77d3d78-93d9-4295-a8f6-d61026f323d5.png)

Problem: 
When ACL is active and the customer want to close an open ticket, the selector jumps always to the first entry in the list and can't be changed. Tested in Edge and Firefox.
When I disable the ACL he can select all entries again.
On closed tickets the behavious is as expected, the only option is to open the ticket. 
I implemented the ACL because customers always forget the change the ticket to open when they reply to a closed ticket.

**Comment by svenoe** [comment]
Hi Manuel,

sorry for the delay, at the moment we are quite busy. We will definitely have a look at this at some point, for now you will still have to have some patience, though.

Thanks for letting us know, Sven

**Comment by svenoe** [comment]
Should be fixed in 10.0.12. :)

Edit: Btw - I forgot to write this earlier. There is a new Setting CustomerTicketZoom###StatePreset which can be used for a similar purpose, but still let the Customer User have the option at least, of keeping the ticket closed.

Best regards, Sven
