### ISSUE TITLE
PSGI: Allow to omit the funny '.pl' in the URL

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#116]
`http://localhost/otobo/index` should be the same as `http://localhost/otobo/index.pl` The same for `customer.pl` and so on.

**Comment by bschmalhofer** [comment]
Stefan: Das solltest du entscheiden, da es nach außen sichtbar ist und vermutlich ein Unterschied zur mod_perl Variante ist.

**Comment by bschmalhofer** [comment]
For constistencies sake, the URLs without '.pl' should then work on Apache too.

**Comment by svenoe** [comment]
If done properly, there are no arguments against it. The improvement is a very minor one, however, in my eyes.
