### ISSUE TITLE
Out of memory errors during migration

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1170]
At least on customer has problems with out of memory during migration. This is most likely due to very large tables when articles and attachments are stored in the database. This is not surprising as per default DBD::mysql, and maybe DBD::Pg, store the complete result set in the RAM. For MySQL this behaviour can be changed by setting 'mysql_use_result' instead of the default 'mysql_store_result'. For PostgreSQL it is not clear whether the behaviour can be changed.

See https://docstore.mik.ua/orelly/weblinux2/modperl/ch20_02.htm.

Alternatively we could advise people to  switch to ArticleStorageFS before the migration, but I fear that the switch will have the same problem.

**Comment by OrionExplorer** [comment]
Hello @bschmalhofer !

I ran into this problem during my last OTRS to OTOBO migration as well. Unfortunately source DB was PostgreSQL and I had no other option than to increase the amount of RAM.

Also I'd like to notice that migration takes place with ElasticSearch already up and running. I had to temporarily stop the service to gain 1 or 2 GB of memory (as set in JVM config as heap size).

Now I am about to start next large migration, with MariaDB as source DB and brand new server for OTOBO. I'll try with ArticleStorageFS and come here with feedback.

Bernhard, if you have any more ideas to verify I'd be happy to test them out.

**Comment by OrionExplorer** [comment]
> For MySQL this behaviour can be changed by setting 'mysql_use_result' instead of the default 'mysql_store_result'.
> 
> See https://docstore.mik.ua/orelly/weblinux2/modperl/ch20_02.htm.
> 

@bschmalhofer One more question, if you don't mind.
Switch to `mysql_use_result` is available only by modifying source code? Am I understand that right?

**Comment by bschmalhofer** [comment]
Hi Marcin,
yes, currently there is no easy way for setting `mysql_use_result` for the migration. 

If your migration is from MySQL to MySQL I would recommend the streamlined data migration https://doc.otobo.org/manual/installation/stable/en/content/migration-from-otrs-6.html#optional-step-streamlined-migration-of-the-database.

Modifying the source is not really straightforward, as the DB-connections are encapsulated in Kernel::System::DB objects. But you could try to modify _Kernel/System/MigrateFromOTRS/CloneDB/Driver/Base.pm_ at line 831. But this is just a guess, as I havn't tried out that variant.

>             # Now fetch all the data and insert it to the target DB.
>             {
>                 # avoid out of memory
>                 local $SourceDBObject->{Backend}->{'DB::Attribute'}->{mysql_use_result} = 1;
>                 $SourceDBObject->Prepare(
>                     SQL   => $SelectSQL,
>                     Limit => 4_000_000_00,
>                 ) || return;
>             }

I hope that helps,
   Bernhard

**Comment by OrionExplorer** [comment]
Thank you Bernhard,

I'll definitely give it a try during the test migration. As for now my plan is to check two scenarios:
* standard migration (not streamlined) with `mysql_use_result` set
* standard migration (not streamlined and without `mysql_use_result` set) but with all the articles and attachments stored in the filesystem

Streamlined migrations would be my last resort as I have no access to our customer's OTRS and OTOBO...

Regards,
Marcin

**Comment by StefanRother-OTOBO** [comment]
Hi,

I think this bug is fixed. If this is not the case, please let me know again.

Thanks,

Stefan
Team OTOBO
