### ISSUE TITLE
Email-Ticket can´t be send

### ISSUE THREAD

**Issue by awegWEGeg** [RotherOSS/otobo#1172]
Backend ERROR: OTOBO-CGI-61 Perl: 5.28.1 OS: linux Time: Wed Aug 11 09:19:55 2021

 Message: Impossible to send message to: "Kunde Koenig" <*******@******.de> .

 RemoteAddress: 192.168.22.1
 RequestURI: /otobo/index.pl

 Traceback (9705): 
   Module: Kernel::System::Ticket::Article::Backend::Email::ArticleSend Line: 306
   Module: Kernel::Modules::AgentTicketEmail::Run Line: 2019
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1257
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otobo_bin_cgi_2dbin_index_2epl::handler Line: 37
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32

**Comment by svenoe** [comment]
Hi,

sorry, but we don't answer general support questions etc. on github. This is solely for development concerns. Please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) if you encounter general errors like the above or have trouble with configuration or installation.

Best regards, Sven

(P.S.: In your example the email address is obviously wrong, so if you didn't edit it...)
