### ISSUE TITLE
Missing Packages in otobo.CheckModules.pl in rel-10_1

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#1180]
Running bin/otobo.CheckModules.pl -list, Packages are listed as 'Not installed', which are not reflected in the Result of bin/otobo.CheckModules.pl -inst. In my use case, this are the following:

- CGI::PSGI
- DBIx::Connector
- Plack
- Plack::Middleware::ForceEnv
- Plack::Middleware::Header
- Plack::Middleware::Refresh
- Plack::Middleware::ReverseProxy
- Plack::Middleware::Rewrite
- SOAP::Transport::HTTP::Plack

Operating System: Kali Linux
Native Installation, not Docker

**Comment by bschmalhofer** [comment]
It looks like line 1432 in _bin/otobo.CheckModules.pl_ is the culprit.

`            next MODULE if !IsHashRefWithData( \%InstallCommand );
`
When there is no install command then no output is printed. We could print `cpanm $module` as a default install  command in these cases. On the other hand. Why should some modules be installed via `cpanm` and others via `apt-get `?

**Comment by kess-net** [comment]
Modules might not be available via `apt-get`

**Comment by bschmalhofer** [comment]
@stefanhaerter Could you take a look at the update otobo.CheckModules.pl script? Whether it works for you?

**Comment by stefanhaerter** [comment]
I ran bin/otobo.CheckModules.pl -list and it worked fine. Do you want to see the output?

**Comment by bschmalhofer** [comment]
Thanks for checking, no need to inspect the output in a detailed way.  Closing this issue.
