### ISSUE TITLE
unneeded entry in table gi_webservice_config_history

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#119]
In _scripts/database/otobo-initial_insert.xml_ there is an entry in gi_webservice_config_history which is essentially the same as the entry in gi_webservice_config. It looks like this entry can be removed.

**Comment by svenoe** [comment]
No. The webservice history always contains the recent webservice configuration, too. See e.g. the end of WebserviceAdd() in Kernel/System/GenericInterface/Webservice.pm.
