### ISSUE TITLE
Cannot configure QuickClose states, QuickClose button not visible in Queue / Tickets views

### ISSUE THREAD

**Issue by ngleb** [RotherOSS/otobo#1194]
Hello!

According to the description of Otobo, it has integrated QucikClose addon. However we cannot configure QuickClose actions as we could in the addon for OTRS, before migrating to Otobo.

So it seems to be a different addon and not the one that was available for OTRS/Znuny. Is this so?

For example, there's no quick close button in the queue view, we cannot set close state (closed successful, close unsuccessful). Were they removed?

**Comment by svenoe** [comment]
Hi ngleb,

sorry for the late reply - please use our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) for general support questions, though. Github atm is used exclusively for bugs and technical discussion.

Best regards, Sven
