### ISSUE TITLE
Support or switch to JavaScript::Minifier::XS

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1197]
To me it looks like this was related to CKEditor 4.15.1 and does not occur with 4.16.0. We should consider switching to the XS versions anyways, I guess. I will postpone it to 10.0.9 though.

_Originally posted by @svenoe in https://github.com/RotherOSS/otobo/issues/771#issuecomment-775852304_

**Comment by bschmalhofer** [comment]
I don't see the advantages from having the test and support both JavaScript::Minifier and JavaScript::Minifier::XS. I propose to switch to the XS in 10.1. Always happy to clean out _Kernel/cpan-lib_.

**Comment by svenoe** [comment]
Please have a look whether the XS library is available in the Debian/Ubuntu/etc. repos...

**Comment by bschmalhofer** [comment]
I checked whether the JavaScript::Minifier::XS is available in the relevant distributions. Yes, it is.

**Comment by bschmalhofer** [comment]
In the same vein, switch to CSS::Minifier::XS.

**Comment by bschmalhofer** [comment]
Tests look fine after adapting the expected output. Looks like JavaScript::Minifier::XS keeps the Copyright statements, which makes sense to me.
Closing this issue.
