### ISSUE TITLE
Please change Config Option DashboardBackend###0410-RSS

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1206]
Hi,

please change the following ConfigOption in Framework.xml to the following values:

    <Setting Name="DashboardBackend###0410-RSS" Required="0" Valid="1">
        <Description Translatable="1">Defines the parameters for the dashboard backend. "Limit" defines the number of entries displayed by default. "Group" is used to restrict access to the plugin (e. g. Group: admin;group1;group2;). "Default" indicates if the plugin is enabled by default or if the user needs to enable it manually. "CacheTTL" indicates the cache expiration period in minutes for the plugin. "Mandatory" determines if the plugin is always shown and can not be removed by agents.</Description>
        <Navigation>Frontend::Agent::View::Dashboard</Navigation>
        <Value>
            <Hash>
                <Item Key="Module">Kernel::Output::HTML::Dashboard::RSS</Item>
                <Item Key="Title" Translatable="1">Custom RSS Feed</Item>
                <Item Key="Description" Translatable="1">OTOBO News</Item>
                <Item Key="URL">https://otobo.de/en/feed/</Item>
                <Item Key="URL_de">https://otobo.de/de/feed/</Item>
                <Item Key="Block">ContentSmall</Item>
                <Item Key="Limit">6</Item>
                <Item Key="Group"></Item>
                <Item Key="Default">1</Item>
                <Item Key="CacheTTL">1440</Item>
                <Item Key="Mandatory">0</Item>
            </Hash>
        </Value>
    </Setting>

**Comment by bschmalhofer** [comment]
Merged the PR. Closing this issue when it has been checked that the RSS feed shows up in the Dashboard.

**Comment by bschmalhofer** [comment]
The RSS feed does show up in the Dashboard now.

@StefanRother-OTOBO : This content of the feed _DashboardBackend###0410-RSS_ seems to be the same as the content from _DashboardBackend###0405-News_.  Should both be enabled at the same time per default?

**Comment by bschmalhofer** [comment]
After this PR the panel 0410-RSS was no longer shown per default, but could be activated via the SysConfig. Looks good. Closing this issue.
