### ISSUE TITLE
Please change the OTOBO package verify logos

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1207]
Hi,

we have new verified logos. Please change the logo.

Thanks,

Stefan
[OTOBO verified 2.zip](https://github.com/RotherOSS/otobo/files/7081506/OTOBO.verified.2.zip)

**Comment by bschmalhofer** [comment]
Found two images with 'OTOBO verified'. Replaced them with the new images of the same size.

Before:

> bes:~/devel/OTOBO/otobo/var/httpd/htdocs/skins/Agent/default/img (issue-#1207-verified_logos)$ file otobo-verify.png
> otobo-verify.png: PNG image data, 200 x 45, 8-bit/color RGBA, non-interlaced
> bes:~/devel/OTOBO/otobo/var/httpd/htdocs/skins/Agent/default/img (issue-#1207-verified_logos)$ file otobo-verify-small.png 
> otobo-verify-small.png: PNG image data, 76 x 16, 8-bit/color RGBA, non-interlaced

Copy:

> bes:~/devel/OTOBO/OTOBO verified $ cp OTOBO_verified-45px.png  ~/devel/OTOBO/otobo/./var/httpd/htdocs/skins/Agent/default/img/otobo-verify.png
> bes:~/devel/OTOBO/OTOBO verified $ cp OTOBO_verified-16px.png ~/devel/OTOBO/otobo/./var/httpd/htdocs/skins/Agent/default/img/otobo-verify-small.png


After;

> bes:~/devel/OTOBO/otobo/var/httpd/htdocs/skins/Agent/default/img (issue-#1207-verified_logos)$ file otobo-verify.png
> otobo-verify.png: PNG image data, 200 x 45, 8-bit/color RGB, non-interlaced
> bes:~/devel/OTOBO/otobo/var/httpd/htdocs/skins/Agent/default/img (issue-#1207-verified_logos)$ file otobo-verify-small.png 
> otobo-verify-small.png: PNG image data, 76 x 16, 8-bit/color RGB, non-interlaced

**Comment by bschmalhofer** [comment]
After purging the browser cache the two new images were displayed in the AdminPackageManager frontend. PR is merged. Closing this issue.

**Comment by bschmalhofer** [comment]
The layout of the the logo is not nice in 10.0.13. This needs to tidied.
