### ISSUE TITLE
bin/otobo.Console.pl does not import customers if the -use-customer-batches flag is not set.

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1211]
Hi,

bin/otobo.Console.pl does not import customers if the -use-customer-batches flag is not set.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Looks like this is relvevant for the command `Maint::Elasticsearch::Migration`. A PR with a fix is provided but not tested yet.

**Comment by bschmalhofer** [comment]
Enhanced the output by stating how many items have been transferred. Did a simple test case with a single customer company and a single customer user. Looking good, Toni Tester was found when doing a customer user search.

**Comment by bschmalhofer** [comment]
PR is merged closing this issue.
