### ISSUE TITLE
Remove Kernel::System::Diff

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1229]
It looks like this module was never used in either OTRS or OTOBO. I propose to remove the module.

**Comment by bschmalhofer** [comment]
I confirmed this again:

> bernhard@bernhard-Aspire-A515-57:~/devel/OTOBO/otobo$ git branch --show-current
> rel-11_0
> bernhard@bernhard-Aspire-A515-57:~/devel/OTOBO/otobo$ grep -r Kernel::System::Diff
> Kernel/System/Diff.pm:package Kernel::System::Diff;
> Kernel/System/Diff.pm:Kernel::System::Diff - Compare two strings and display difference
> Kernel/System/Diff.pm:    my $DiffObject = $Kernel::OM->Get('Kernel::System::Diff');
> scripts/test/Diff.t:my $DiffObject = $Kernel::OM->Get('Kernel::System::Diff');

**Comment by stefanhaerter** [comment]
Would this be something for rel-11_1, like #226?

**Comment by bschmalhofer** [comment]
I second to remove `Kernel::System::Diff` in rel-11_1.  This means that `Text::Diff::FormattedHTML` can be removed from _Kernel/cpan-lib_ as well. Removing `Text::Diff::FormattedHTML` allows to remove `File::Slurp` as well.

If diff functionality is needed in future I suggest to use `Algorithm::Diff` instead of `Text::Diff`. This should cause no problems as `Text::Diff` is already based on `Algorithm::Diff`.

**Comment by stefanhaerter** [comment]
PR #3535 merged, issue closed

**Comment by bschmalhofer** [comment]
Reopen to also remove Text::Diff::FormattedHTML and File::Slurp.

**Comment by stefanhaerter** [comment]
I agree on removing these, but would you prefer to have it in this issue or in #2610?

**Comment by bschmalhofer** [comment]
Done.

@stefanhaerter : I read your comment only after the fact, so #1229 it is.

**Comment by stefanhaerter** [comment]
From [metacpan](https://metacpan.org/pod/Algorithm::Diff#SYNOPSIS):

```perl
require Algorithm::Diff;
 
# This example produces traditional 'diff' output:
 
my $diff = Algorithm::Diff->new( \@seq1, \@seq2 );
 
$diff->Base( 1 );   # Return line numbers, not indices
while(  $diff->Next()  ) {
    next   if  $diff->Same();
    my $sep = '';
    if(  ! $diff->Items(2)  ) {
        printf "%d,%dd%d\n",
            $diff->Get(qw( Min1 Max1 Max2 ));
    } elsif(  ! $diff->Items(1)  ) {
        printf "%da%d,%d\n",
            $diff->Get(qw( Max1 Min2 Max2 ));
    } else {
        $sep = "---\n";
        printf "%d,%dc%d,%d\n",
            $diff->Get(qw( Min1 Max1 Min2 Max2 ));
    }
    print "< $_"   for  $diff->Items(1);
    print $sep;
    print "> $_"   for  $diff->Items(2);
}
```

As far as I understand it, `Algorithm::Diff` needs way more code to produce a traditional diff, which is our only use case at the moment:

https://github.com/RotherOSS/otobo/blob/6140b4fe179146246a6d98ad48b659f53bc2c998/Kernel/Modules/AdminPackageManager.pm#L126-L136

**Comment by bschmalhofer** [comment]
I agree, [Text::Diff](https://metacpan.org/pod/Text::Diffl) stays.
