### ISSUE TITLE
Backup should follow symlinks

### ISSUE THREAD

**Issue by niccord** [RotherOSS/otobo#1236]
Hi everyone!
I encountered this issue while backing up a system for a client of ours:
when `scripts/backup.pl` is executed it backups and archives the files and the database but if you have a symbolic link to another location in the filesystem (i.e. articles or configurations) it collects the links and not the file it points to.

Update the `backup` script in order to follow the symlink and archive the right file.

**Comment by bschmalhofer** [comment]
Hi Nicola,

I'm not sure about the best approach here. I see the danger that existing installations break when the behaviour of backup.pl suddenly changes. Perhaps a safer fix would be to add an option '--follow-symlinks' . I have also found https://github.com/h4ck3rm1k3/otrs/blob/master/scripts/backup.pl which puts the linked data into an extra file.

@svenoe : I think this needs to be discussed among the core developers.
