### ISSUE TITLE
Docker: Kerberos problems

### ISSUE THREAD

**Issue by markus-gitdev** [RotherOSS/otobo#1239]
The kerberos section in the nginx config is commented out in "rotheross/otobo-nginx-kerberos-webproxy:latest".

Also the settings from the .env-file are not correctly transported into the nginx config in that container and have to be corrected manually, but the changes are overwritten on restart of the container.

**Comment by bschmalhofer** [comment]
Hi Markus, @markus-gitdev ,

these issues are handled in #1462 and #1465, and #1476. Fixes are planned for OTOBO 10.0.14. Closing this issue.

Best regards,
   Bernhard
