### ISSUE TITLE
Migration: Missing migration steps for process tickets

### ISSUE THREAD

**Issue by markus-gitdev** [RotherOSS/otobo#1240]
After the migration to OTOBO  process tickets are not fully functional since not all OTRS-tags are migrated to OTOBO-tags.
Especially for the transition action "Article create".

Would be great if that could be adopted in the migration script for further migrations.

**Comment by bschmalhofer** [comment]
This requires some understanding how process management works. Presumably one needs to replace OTRS_ with OTOBO_ in some YAML strings. The YAML is stored in database fields like _pm_process.config_.

**Comment by bschmalhofer** [comment]
Might be related to #882.

**Comment by markus-gitdev** [comment]
### Workaround

To work around this problem, just export the processes where you use ``OTRS`` in e.g. a transition action, open the ``.yml``-file in an editor of your choice and replace ``OTRS`` with ``OTOBO``.
Use the ``Confguration Import`` in the ``Process Management`` of OTOBO and make sure you have activated ``Overwrite existing entities``.
After that ``Deploy All Processes`` and it works again.

**Comment by bschmalhofer** [comment]
Moved this to the wishlist as it might be sensible to automate this.
