### ISSUE TITLE
Problem with umlaute and accents in CustomerUsers coming from LDAP

### ISSUE THREAD

**Issue by sunflowerbofh** [RotherOSS/otobo#1244]
We get our customer users from LDAP server.  Looking at the overview of the customer users the names with Umlaute (äöü) or Accents (éè) have strange characters, e.g.
AnitaMÃ¼ller
StefanSpÃ¶hel
StÃ©phaneFÃ©lix
I can't see anything in the config which is not utf-8. Maybe there is some 'endoding(utf-8, ...) missing at some place?
The LDAP server itself can handle utf8. When I do an ldapsearch I get correctly encoded names.
We use version 10.0.12.

**Comment by reneeb** [comment]
Did you check if the server sends the data utf-8 encoded or any other encoding?

**Comment by sunflowerbofh** [comment]
On Friday, 2022-01-07, 05:07:02 (GMT -0800), Renee wrote:
> Did you check if the server sends the data utf-8 encoded or any other encoding?

Usually we use ldap v3, there should be utf-8 included. As for Umlaute, the
strings are returned base64-encoded. With php or python based apps there was
never a problem about that.

> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/RotherOSS/otobo/issues/1244#issuecomment-1007392326
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Berner Fachhochschule / Bern University of Applied Sciences
IT-Services / Team Linux & Infrastructure Services
Katharina Drexel
IT System Engineer
___________________________________________________________
Dammweg 3, CH-3013 Bern
Telefon direkt +41 31 848 48 87
Telefon Servicedesk +41 31 848 48 48
***@***.***
https://bfh.ch
https://bfh.science

**Comment by bschmalhofer** [comment]
Closing this issue, as it seems to be specific to the specific setup.
