### ISSUE TITLE
Remove Kernel::Environment::OTOBOInfoGet()

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1249]
It looks like this method is not used. Should the cruft be removed?

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard, I think there is nothing against it.

Thanks Stefan

**Comment by bschmalhofer** [comment]
On second thought, the method  `OTOBOInfoGet()` fits in well with the other methods in `Kernel::System::Environment`. Let's keep it.
