### ISSUE TITLE
Deactivate the webservice ElasticSearch on new installations

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#125]
When running the testsuite on my local machine I get a lot of error messages like:

`Message: DebugLog error:  Summary: Error while performing REST 'POST' request to Controller '/customeruser/_doc/CustomerLogin%23test7787801219300002' on Host 'http://loca      lhost:9200'. Response code '500'.  Data   : Response content: 'Can't connect to localhost:9200Connection refused at /home/bernhard/devel/OTOBO/otobo/Kernel/cpan-lib/LWP/Pr      otocol/http.pm line 46.'.`

My hunch is that this is because the ElasticSearch webservice is activated per default for a new installation. I propose to change that default setting, as AFAIK ElasticSearch is not installed per default.

**Comment by StefanRother-OTOBO** [comment]
At the moment the Elasticsearch web service is not supposed to be valid right after the installation. Executing
bin/otobo.Console.pl Maint::Elasticsearch::Migration
automatically sets the web service to valid and sets up the indices on the Elasticsearch server. We could automate this within the installation process, however.

**Comment by bschmalhofer** [comment]
The webservice Elasticsearch has been disabled by default. Closing the issiue.
If the webservice should be active by default in the Docker, then a new issue should be open for that requirement.

**Comment by marcoteixeira** [comment]
Hello. I installed a fresh copy of the latest 10.1.x and I'm getting the error below, even after disabling Elasticsearch in System Configuration. Can you help fix this?
===
Jan 31 12:02:27 servicedesk OTOBO-CGI-69[97638]: [Error][Kernel::GenericInterface::ErrorHandling::HandleError][Line:115]: DebugLog error:  Summary: Error while performing REST 'POST' request to Controller '/ticket/_update/133535' on Host 'http://localhost:9200'. Response code '500'.  Data   : Error while performing REST 'POST' request to Controller '/ticket/_update/133535' on Host 'http://localhost:9200'. Response code '500'..
===

**Comment by svenoe** [comment]
Hey Marco,

if you are having general questions about OTOBO please either visit our [forums](https://otobo.de/de/forums/) to ask the community or write an email to hello@otobo.de for professional support. Github is reserved for development issues.

Thanks for your understanding, Sven

**Comment by marcoteixeira** [comment]
> Hey Marco,
> 
> if you are having general questions about OTOBO please either visit our [forums](https://otobo.de/de/forums/) to ask the community or write an email to [hello@otobo.de](mailto:hello@otobo.de) for professional support. Github is reserved for development issues.
> 
> Thanks for your understanding, Sven

I deleted my previous post. sorry about that. you can delete your reply as well just to keep it clean :) (i will delete this in an hour or so)

**Comment by svenoe** [comment]
> I deleted my previous post. sorry about that. you can delete your reply as well just to keep it clean :) (i will delete this in an hour or so)

Haha, that wouldn't have been necessary. We just don't have the time that our developers solve support issues, unfortunately, and I wanted to give you the link to the forum, though, instead of not answering. :)
