### ISSUE TITLE
404 returned from makalu.otobo.org

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1250]
Since about September 10th there are four failing test cases in _scripts/test/WebUserAgent.t_ . The cause seems to be that makalu.otobo.org no longer replies as expected.

> bes:~/devel/OTOBO/otobo (issue-#1247-otrs.com)$ wget --no-check-certificate https://makalu.otobo.org/unittest/HTTPBasicAuth/
> --2021-09-22 12:03:24--  https://makalu.otobo.org/unittest/HTTPBasicAuth/
> Auflösen des Hostnamens makalu.otobo.org (makalu.otobo.org) … 138.201.55.196
> Verbindungsaufbau zu makalu.otobo.org (makalu.otobo.org)|138.201.55.196|:443... verbunden.
> WARNUNG: Das Zertifikat von makalu.otobo.org kann nicht geprüft werden, ausgestellt von »CN=TRAEFIK DEFAULT CERT«:.
>   Die Autorität des Zertifikatausstellers kann lokal nicht geprüft werden.
> WARNUNG: Keiner der alternativen Namen des Zertifikats stimmt mit dem angefragten Maschinennamen »makalu.otobo.org« überein.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
> 2021-09-22 12:03:24 FEHLER 404: Not Found.
> 

It is not obvious whether this is related to the self signed certificate.

**Comment by svenoe** [comment]
This is likely due to the change from otrs to otobo, without such a server existing here. We could try changing it back to otrs.com... ;) Or we set up this stuff ourselves.

**Comment by bschmalhofer** [comment]
This is not required for 10.0.14.

**Comment by bschmalhofer** [comment]
I propose to not provide a service makalu.otobo.org. Instead spin up a small webserver running on localhost. The small webserver can use https://metacpan.org/pod/Plack::Middleware::Auth::Basic.
Unfortunately [Plack;;Test](https://advent.plackperl.org/2009/12/day-13-use-placktest-to-test-your-application.html) does not fit the bill as we want to test the user agent, not the application.

**Comment by bschmalhofer** [comment]
Let's take a different route here. Skip the failing tests that use makalu.otobo.org for rel-10_0. In lieu, convert these tests to a local webserver in rel-10_1. This should be easy in rel-10_1, as we already have a dependency on Plack in that branch.
