### ISSUE TITLE
Admin Documentation Link points to wrong URL

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1312]
In the Admin Area (Action=Admin) you find on the left hand side a link to the admin documentation.
Unfortunately it points to the wrong URL (https://doc.otobo.org/doc/manual/admin/10.0/en/html/index.html).
Correct would be https://doc.otobo.org/manual/admin/stable/en/content/index.html

Also I think the naming of the button (View the admin manual on Git**h**ub) is not correct, as it doesn't point to GitHub at all.

**Comment by bschmalhofer** [comment]
Looks like the French translators did check the link:

> Kernel/Language/fr.pm:        'View the admin manual on Github' => 'Voir le manuel administrateur sur le site officiel',

**Comment by bschmalhofer** [comment]
The link seems to have been repaired in commit bd0ba5ea20e203ad2ff96cc93fe5dc0271d403e1 for #1550.
TODO:

- [x] remove the "on Github"

**Comment by bschmalhofer** [comment]
A sanity check after recreating local Docker images and running _docker-compose/scripts/update.sh_ looks fine. The "on Github" is gone and the links still works.
Closing this issue.
