### ISSUE TITLE
No service in bulk action possible

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1319]
In the system configuration Ticket::Frontend::AgentTicketBulk it is not possible to enable the service field.
In my opinion that clearly is a bug.

**Comment by svenoe** [comment]
I think AgentTicketBulk in general doesn't give the option to change attributes, which have dependencies. Which services are shown depends on the CustomerUser of the ticket, as this could be different for the selected tickets, it is not clear which services should be listed as possible values. (Actually one could at least show the standard services, but I am pretty sure this is the reason. It is clearly not a bug, but a missing feature, though... ;)
