### ISSUE TITLE
Bug in AgentTicketZoom with DynamicFields, using DynamicFieldScreens

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1321]
Hi,

if I add ProcesswidgetDynamicField to "selected to disabled elements" for AgentTicketZoom in DynamicField Screens, the the dynamic field is never displayed, even if I activate it for AgentTicketZoom. I think it is at this location in AgentTicketZoom where the two config options are simply merged.

```
1664     # get dynamic field config for frontend module
1665     my $DynamicFieldFilter = {
1666         %{ $ConfigObject->Get("Ticket::Frontend::AgentTicketZoom")->{DynamicField} || {} },
1667         %{
1668             $ConfigObject->Get("Ticket::Frontend::AgentTicketZoom")
1669                 ->{ProcessWidgetDynamicField}
1670                 || {}
1671         },
1672     };
1673
1674     # get the dynamic fields for ticket object
1675     my $DynamicField = $Kernel::OM->Get('Kernel::System::DynamicField')->DynamicFieldListGet(
1676         Valid       => 1,
1677         ObjectType  => ['Ticket'],
1678         FieldFilter => $DynamicFieldFilter || {},
1679     );
```

Thanks!

Stefan

**Comment by svenoe** [comment]
Clarification: Deactivation happens for ProcessWidgetDynamicField, not AgentTicketZoom, as I understood. Thus the right course of action would probably be to swap the order of both hashes.
