### ISSUE TITLE
Translating ticket types does not work

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1333]
When creating a Custom Translation file and you enter your source language of your type names, they are not translated in the type dropdown, e.g. in AgentTicketPhone
<img width="468" alt="image" src="https://user-images.githubusercontent.com/87359203/137928796-c2d9103f-a7c8-465b-90a5-3892ee1efd11.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/87359203/137928879-18226bde-ba25-4e50-9144-174464659ee8.png">

![image](https://user-images.githubusercontent.com/87359203/137928923-997ed3d3-01c9-4b79-9e04-378c6c932ecb.png)

This also happens still after
bin/otobo.Console.pl Maint::Config::Rebuild
Rebuilding the system configuration...
Done.
bin/otobo.Console.pl Maint::Cache::Delete
Deleting cache...
Done.
bin/otobo.Console.pl Maint::Loader::CacheCleanup
Cleaning up the loader cache files...
Done.
bin/otobo.Console.pl Maint::WebUploadCache::Cleanup
Cleaning up the upload cache files...
Done.

Tested in OTOBO 10.0.13 (ov48)

**Comment by bschmalhofer** [comment]
This is more of a design decision. On the technical side, there is a declaration for each standard field type whether the entries should be translated or not. For example in _Kernel/Modules/AgentTicketPhone.pm_ around line 2298:

>             TypeID => {
>                 PossibleNone => 1,
>                 Translation  => **0**,
>                 Max          => 100,
>             }

Globally changing the declaration, for all relevant frontend modules, is probably a bad idea. This leaves us most likely with yet another config option.

**Comment by StefanAbel-OTOBO** [comment]
Hello,

with 10.1.5 this still is happening. In general this should work, as we discussed this multiple times. And afaik this should have already worked someday. So it would be great if it could work again.

Funny is that e.g. in system configuration setting "Ticket::Type::Default" the translation works, but where you actually need it, it doesn't:

Ticket::Type::Default:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/87359203/193260305-165ba52c-2b8d-48fe-8898-3b0c14ebd065.png">

AgentTicketPhone:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/87359203/193260362-c04e9d5c-fca8-477a-b89f-6298fcad9a6a.png">

**Comment by stefanhaerter** [comment]
Hi Stefan,

as far as I could see, this is caused by https://github.com/RotherOSS/otobo/blob/9f6f9a0fc10ba312866845e1a03f3c12daf5c955/Kernel/Modules/AgentTicketPhone.pm#L2973 , where the type string is configured as non-translatable, and git blame showed that this is the case since the initial commit. Can you confirm that the wanted behavior is that the Translation-Option is set to 1 or that there is a config option? If so, I could create a pull request.

**Comment by StefanAbel-OTOBO** [comment]
Hello,

As far as I'm concerned the types should be translated everywhere (e.g. also in AgentTicketZoom). Maybe there is a reason why this is not the case, but imho it should be. I'm not aware of any config option (if there would be in the system configuration e.g., that would be even better, but not really necessary I would say).

**Comment by stefanhaerter** [comment]
Ok, I will look after this =)

**Comment by svenoe** [comment]
We will do this for 11.0 not 10.1.

**Comment by stefanhaerter** [comment]
Closed with #3145
