### ISSUE TITLE
DynamicField MasterSlave missing in AgentTicketMasterSlave and AgentTicketBulk

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1334]
After installing the Feature MasterSlave, a new action is added: AgentTicketMasterSlave
But: here the new dynamic field MasterSlave is missing.
In my opinion it should be there by default - as the new action usually has no other purpose.

![image](https://user-images.githubusercontent.com/87359203/137931001-f291e47c-8271-4b34-800f-0ddc053a9eec.png)

Also in my opinion it also should be there in AgentTicketBulk

![image](https://user-images.githubusercontent.com/87359203/137930826-64c04af7-083b-4a76-baeb-726a8e83c163.png)

Tested with OTOBO 10.0.13 (ov48) with MasterSlave 10.0.1

**Comment by reneeb** [comment]
IMHO this should be reported at https://github.com/RotherOSS/MasterSlave as this should be handled in the packagesetup script there.

Relevant are the lines after https://github.com/RotherOSS/MasterSlave/blob/7a866ef87ab43b6baeafd4263baebc30193a72e0/var/packagesetup/MasterSlave.pm#L340

**Comment by svenoe** [comment]
Moved to https://github.com/RotherOSS/MasterSlave/issues/2
