### ISSUE TITLE
DF RegEx Error Message not visible in CustomerTicketMessage

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1337]
When defining a RegEx for a DynamicField in CustomerTicketMessage, you don't see the defined Error Message, when trying to create the ticket:
![image](https://user-images.githubusercontent.com/87359203/137935368-3ee01bda-caab-4181-b5a2-8716a136f1f9.png)

After clicking OK:
![image](https://user-images.githubusercontent.com/87359203/137935408-0f721a7b-b949-43b6-912d-7d090a97936c.png)

This is the defined Error Message in Action=AdminDynamicFieldText;Subaction=Change;:
![image](https://user-images.githubusercontent.com/87359203/137935691-798fa589-74b9-4f37-a086-4e76de4d9446.png)

Tested in OTOBO 10.0.13 (ov48)

**Comment by reneeb** [comment]
This seems to be related to https://github.com/RotherOSS/otobo/issues/625

**Comment by svenoe** [comment]
Yes, it is a duplicate. Stefan is working on it.
