### ISSUE TITLE
Changing a parent queue also changed Changed Date for sub-queue

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1339]
When changing something in a parent queue (), you see in Action=AdminQueue that the sub queue has also been updated - at least the Changed Date adjusts accordingly to the parent Changed Date.

Before you can see the Changed Date 17:00 for Misc::sub:
![image](https://user-images.githubusercontent.com/87359203/137937555-3d2e8287-06d5-4d24-88df-92b811e025ef.png)

After changing something in the parent queue Misc at 17:01 in Action=AdminQueue;Subaction=Change, you see the new Changed Date 17:01 also for Misc::sub:
![image](https://user-images.githubusercontent.com/87359203/137937906-4a3a7a77-35ff-4bbb-a9ef-14622efa9b1e.png)

Tested in 10.0.13 (ov48)

**Comment by reneeb** [comment]
The linked PR avoids updates when the name of the parent queue wasn't updated. There are pro and contra arguments whether a name update of the parent queue should change the "last update" timestamp of the subqueues as it indeed changes the entry in the database. 

The PR can be extended when it is decided that even a name change shouldn't change the "last update" timestamp.

**Comment by svenoe** [comment]
Ah, I should have read the issue before... ;)

Renees pr fixes that subqueues "change" when the name stays the same. Changing the timestamp of subqueues when their name changes is reasonable to me, regardless of whether an agent directly changed it via AdminQueue, or whether it was an automatic change.
