### ISSUE TITLE
"This feature is currently not available." when adding a calendar appointment.

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1341]
When adding a new appointment to any calendar, you still see the rest of an "advertisement" for the OTRS Feature AddOn "Calendar Resource Planning":

Resource
This feature is currently not available.

![image](https://user-images.githubusercontent.com/87359203/138069443-c9fb01d8-0168-458b-8ef3-f74ce3e28038.png)

Either we should implement a resource planning to fill that gap or we should remove that part.

Tested with OTOBO 10.0.13 (ov48).

**Comment by stefanhaerter** [comment]
Merged.
