### ISSUE TITLE
Kernel::System::Package: remove compatability to OTRS 2.2

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1364]
There is still some support for OTRS 2.2 style packages in _Kernel/System/Package.pm_. I think that this is no longer needed.

**Comment by svenoe** [comment]
Can be removed. We don't offer full compatibility to OTRS packages, even though some work out of the box, more or less. 2.2 is so old, that having a look at them is a good idea anyways, probably...

**Comment by bschmalhofer** [comment]
Can be done after the current changes for #1362 are merged.

**Comment by bschmalhofer** [comment]
Removed the workarounds for OTRS 2.2. Plus a bit of tidying.

Closing the issue only when the unit tests look fine.

**Comment by bschmalhofer** [comment]
Test suite looked fine. Closing this issue.
