### ISSUE TITLE
Remove deprecated script otobo.PostMaster.pl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1365]
The script is documented as:

> DEPRECATED. This console command is deprecated, please use 'Maint::PostMaster::Read' instead.

If the script should be kept, then the deprecation warning should be rephrased,

**Comment by svenoe** [comment]
Can be removed - have fun with your favorite activity... ;)
(Thanks :) )

**Comment by bschmalhofer** [comment]
Done, with a limited amount of -Ofun.
