### ISSUE TITLE
Are the special cases for Net::DNS still useful ?

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1370]
In the code there are several cases with special handling for Net::DNS. E.g. in bin/otobo.CheckModules.pl:

>         # Test if all module dependencies are installed by requiring the module.
>         #   Don't do this for Net::DNS as it seems to take very long (>20s) in a
>         #   mod_perl environment sometimes.
>         my %DontRequire = (
>             'Net::DNS'     => 1,
>             'Email::Valid' => 1,    # uses Net::DNS internally
>         );

Is this still necessary? I recall that tests can take a long time, but actual loading seems to be fast.

> bes:~/devel/OTOBO/otobo (issue-#27-remove_RPC_pm)$ time perl -MNet::DNS -E 'say $INC{"Net/DNS.pm"}'
> /usr/share/perl5/Net/DNS.pm
> 
> real    0m0,075s
> user    0m0,071s
> sys     0m0,004s

**Comment by svenoe** [comment]
Someone can have a look at this.

**Comment by bschmalhofer** [comment]
The workaround was added in 2014, see https://github.com/znuny/Znuny/commit/1ce2561fc3779bd3aa79eab677de73ae96ef7722 . OTOBO currently requires Perl 5.24 which was released in May 2016. So let's assume that this is no longer an issue in newer versionsions of Net::DNS. Let's required Net::DNS 1.05 which was released in March 2016.

**Comment by bschmalhofer** [comment]
Special handling of Net::DNS is gone. Closing this issue.
