### ISSUE TITLE
We have changed the default ticket unlock behaviour in OTOBO 10.1.

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1372]
We have changed the default ticket unlock behaviour in OTOBO 10.1. Now, the ticket is not only unlocked, but also handed over to the system user again. Thus, the behaviour is clearer, but it is no longer possible to read out who last edited the ticket. Please deactivate the config option Ticket::OwnerResetOnUnlock to restore the behaviour of the OTRS version 2-6 and OTOBO 10.

**Comment by StefanRother-OTOBO** [comment]
We need to execute bin/otobo.Console.pl to create new initial_insert scripts from scripts/database/otobo-initial_insert.xml. And perhaps we need to change the settings inside the OTOBO 10.1 upgrade script.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO : Do you mean scripts like _scripts/database/otobo-schema.mysql.sql_ ? Those were not used in rel-10_0 and have been removed in rel-10_1.

**Comment by StefanRother-OTOBO** [comment]
I have changed it to otobo-schema.xml, everything should be correct.
