### ISSUE TITLE
Add new GenericInterface Invoker TicketCreate and TicketUpdate

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1373]
This enhancement adds the functionality of two new invokers (TicketCreate, TicketUpdate) for
OTOBO web services. 

1. Invoker TicketCreate
This invoker returns the complete ticket and article data based on ticket ID, article ID of the
triggered event.

2. Invoker TicketUpdate
This invoker returns the complete ticket and article data based on ticket ID, article ID of the
triggered event.

3. Advanced filtering for outgoing data
For outgoing data, it is possible to define what kind of ticket fields, article fields or dynamic
fields the request should contain. Furthermore it is possible to filter by article type and article
sender type.

4. Set dynamic field values based on incoming response data
It is possible to automatically save certain data of incoming responses to local dynamic fields.

**Comment by StefanRother-OTOBO** [comment]
Sven, can you please look over it again before publication? I have also included the part of sternenseemann again from Issue #772. In the next step I create the documentation.
Thank you!

**Comment by StefanRother-OTOBO** [comment]
Bernhard, please can you prove the unit test files for me? I'm not sure what's new...
Thanks!

**Comment by bschmalhofer** [comment]
Does the commit a3724f5 actually work? I see renaming of methods from Content() to Run() and the use of `%ENV` . My impression is that the state of rel-10_0 was merged back in.

**Comment by bschmalhofer** [comment]
GenericInterface error summary from the test suite:

> /opt/otobo/scripts/test/GenericInterface/Invoker/Ticket/WebserviceTicketInvoker.t                         (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> /opt/otobo/scripts/test/GenericInterface/Operation/Session/SessionCreate.t                                (Wstat: 5120 Tests: 87 Failed: 20)
>   Failed tests:  11, 14, 19, 22, 27, 30, 35, 38, 43, 46
>                 51, 54, 59, 62, 67, 70, 75, 77, 83, 85
>   Non-zero exit status: 20
> /opt/otobo/scripts/test/GenericInterface/Operation/Session/SessionGet.t                                   (Wstat: 3584 Tests: 62 Failed: 14)
>   Failed tests:  14-15, 21-22, 28-29, 35-36, 42-43, 49-50
>                 56-57
>   Non-zero exit status: 14
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketCreate.t                                  (Wstat: 21760 Tests: 135 Failed: 85)
>   Failed tests:  34-118
>   Non-zero exit status: 85
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketCreateIncludeTicketData.t                 (Wstat: 2816 Tests: 70 Failed: 11)
>   Failed tests:  36, 41-43, 51-56, 58
>   Non-zero exit status: 11
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketGet.t                                     (Wstat: 65280 Tests: 14 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketHistoryGet.t                              (Wstat: 2560 Tests: 60 Failed: 10)
>   Failed tests:  13-14, 20-21, 27, 30, 36, 42, 48, 56
>   Non-zero exit status: 10
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketSearch.t                                  (Wstat: 65280 Tests: 17 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketUpdate.t                                  (Wstat: 9728 Tests: 136 Failed: 38)
>   Failed tests:  22-23, 29-31, 36-37, 43-44, 50-51, 57-59
>                 64-66, 71-73, 78-80, 85-87, 93-94, 102-103
>                 111-115, 123-125
>   Non-zero exit status: 38
> /opt/otobo/scripts/test/GenericInterface/Operation/Ticket/TicketUpdateIncludeTicketData.t                 (Wstat: 6144 Tests: 85 Failed: 24)
>   Failed tests:  23, 25-26, 28, 34, 36-37, 39-41, 53, 55-56
>                 58-61, 70, 72-73, 75-78
>   Non-zero exit status: 24
> /opt/otobo/scripts/test/GenericInterface/Provider/Provider.t                                              (Wstat: 1280 Tests: 7 Failed: 5)
>   Failed tests:  1-5
>   Non-zero exit status: 5
> /opt/otobo/scripts/test/GenericInterface/Transport/HTTP/REST.t                                            (Wstat: 7680 Tests: 103 Failed: 30)
>   Failed tests:  24-25, 28-29, 32-33, 36-37, 40-41, 44-45
>                 48-49, 52-53, 56-57, 60-61, 64-65, 68, 76-77
>                 85-86, 94-96
>   Non-zero exit status: 30
>   Parse errors: No plan found in TAP output
> /opt/otobo/scripts/test/GenericInterface/Transport/HTTP/SOAP.t                                            (Wstat: 22528 Tests: 235 Failed: 88)
>   Failed tests:  15-16, 19-20, 23-24, 27-28, 31-32, 35-36
>                 40, 44, 47-48, 52, 55-56, 60, 63-64, 68
>                 71-72, 76, 79-80, 83-84, 87-88, 92, 95-96
>                 100, 104, 108, 111-112, 116, 119-120, 124
>                 127-128, 132, 135-136, 139-140, 143-144
>                 148, 152, 156, 160, 163-164, 167-168, 172
>                 176, 180, 183-184, 187-188, 191-192, 195-196
>                 199-200, 208-209, 212-213, 217-218, 221-222
>                 226-228, 231-233
>   Non-zero exit status: 88
>   Parse errors: No plan found in TAP output
>

**Comment by bschmalhofer** [comment]
The commit a3724f51800b6 broke some things, notably in the generic interface. There are at least two options how to proceed.

- revert the commit and start from scratch
- go through the 24 changed files and do a proper merge with the parent commit of a3724f51800b6

Let's try the second option first.

**Comment by bschmalhofer** [comment]
TODO:

- [ ] import _Kernel/Language/{de|hu}_WebserviceTicketInvoker.pm_ into the regular translation frameworl
- [ ] clean up duplication between _Kernel/Modules/AdminGenericInterfaceInvoker{Default|Ticket|Event}.pm_
- [x] align the test scripts REST.t and SOAP.t

**Comment by bschmalhofer** [comment]
- [ ] Also still some test failures. Some because two scripts were not yet converted to the changed testing framework.

> /opt/otobo/scripts/test/GenericInterface/Invoker/Ticket/WebserviceTicketInvoker.t                         (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> /opt/otobo/scripts/test/GenericInterface/Transport/HTTP/REST.t                                            (Wstat: 5376 Tests: 73 Failed: 21)
>   Failed tests:  5, 8, 11, 14, 17, 20, 23, 27, 31, 35, 39
>                 43, 47, 51, 55, 59, 63, 69-72
>   Non-zero exit status: 21
> /opt/otobo/scripts/test/GenericInterface/Transport/HTTP/SOAP.t                                            (Wstat: 13824 Tests: 205 Failed: 54)
>   Failed tests:  5, 8, 11, 14, 18, 22, 26, 30, 34, 38, 42
>                 46, 50, 54, 58, 62, 66, 70, 74, 78, 82
>                 86, 90, 94, 98, 102, 106, 110, 114, 118
>                 122, 126, 130, 134, 138, 142, 146, 150
>                 154, 158, 162, 166, 170, 174, 178, 182
>                 186, 190, 194, 198, 201-204
>   Non-zero exit status: 54
> /opt/otobo/scripts/test/Selenium/Agent/Admin/AdminGenericInterfaceInvokerTicket.t                         (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output

**Comment by bschmalhofer** [comment]
After some fixes the test failures are down to 28:

> /opt/otobo/scripts/test/GenericInterface/Transport/HTTP/REST.t                                            (Wstat: 1024 Tests: 26 Failed: 4)
>   Failed tests:  22-25
>   Non-zero exit status: 4
> /opt/otobo/scripts/test/GenericInterface/Transport/HTTP/SOAP.t                                            (Wstat: 6144 Tests: 58 Failed: 24)
>   Failed tests:  13-14, 16, 18, 20, 22, 26, 28-30, 32, 34
>                 36, 40-43, 46-48, 54-57
>   Non-zero exit status: 24
>

**Comment by bschmalhofer** [comment]
Found another stumbling block. The transport modules are still relying on the environment:

>     # Check if we are in a real request environment (UnitTests may call this function directly).
>     if ( $ENV{HTTP_UNITTESTHEADERS} ) {
>         my %AllRequestHeaders;
>         ENVKEY:
>         for my $EnvKey ( sort keys %ENV ) {
>             next ENVKEY unless substr( $EnvKey, 0, 5 ) eq 'HTTP_';
> 
>             my $HeaderKey = substr( $EnvKey, 5 ) =~ s{_}{-}xmsgr;
>             $AllRequestHeaders{$HeaderKey} = $ENV{$EnvKey};
>         }
> 
>         # If we are in UnitTest header check mode, mirror request headers in response.
>         if ( my $MirrorHeaderPrefix = delete $AllRequestHeaders{UNITTESTHEADERS} ) {
>             my @HeaderBlacklist = split ':', delete $AllRequestHeaders{UNITTESTHEADERBLACKLIST};
> 
>             HEADER:
>             for my $Header ( sort keys %AllRequestHeaders ) {
> 
>                 # Attention: CGI uses all-uppercase names for headers.
>                 next HEADER if grep { uc($_) eq $Header } @HeaderBlacklist;
> 
>                 $Headers{ $MirrorHeaderPrefix . $Header } = $AllRequestHeaders{$Header};
>             }
>         }
>     }
> 

Actually there are two different usages. First, there is `$ENV{HTTP_UNITTESTHEADERS}` for activating the header mirroring feature of nph-genericinterface.  This can be replaced by a setting in the SysConfig. Then there is `$AllRequestHeaders{$HeaderKey} = $ENV{$EnvKey};` for actually getting the headers. This can be replaced by accessing the Kernel::System::Web::Request object.

**Comment by bschmalhofer** [comment]
While working on this I noticed that `Kernel::GenericInterface::Transport::ProviderGenerateResponse()` is not very consistent. An exception should be thrown when one of the two checks has something to complain about.

> sub ProviderGenerateResponse {
>     my ( $Self, %Param ) = @_;
> 
>     if ( !defined $Param{Success} ) {
> 
>         return $Self->{DebuggerObject}->Error(
>             Summary => 'Missing parameter Success.',
>         );
>     }
> 
>     if ( $Param{Data} && ref $Param{Data} ne 'HASH' ) {
> 
>         return $Self->{DebuggerObject}->Error(
>             Summary => 'Data is not a hash reference.',
>         );
>     }
> 
>     # throws an exception
>     return $Self->{BackendObject}->ProviderGenerateResponse(%Param);
> }
> 
>

**Comment by bschmalhofer** [comment]
Some more fixes, unit tests are now succeeding.

**Comment by bschmalhofer** [comment]
The changes for this issue introduced some _OTOBOTicketInvoker_ change markers. My understanding ist the code taken from addons and integrated into OTOBO core is not marked with change markers. Let's eliminate them.

**Comment by bschmalhofer** [comment]
The translation files _Kernel/Language/de_WebserviceTicketInvoker.pm_ and _Kernel/Language/hu_WebserviceTicketInvoker.pm_ turn out to be no longer needed. They will be removed for #5167 .
