### ISSUE TITLE
Nicer layout of the OTOBO verified logo

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1377]
The layout of the the logo is not nice in 10.0.13. This needs to tidied.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/1207#issuecomment-957342047_

**Comment by bschmalhofer** [comment]
Made a first stab at this, using the SVG versions of the icons. 
Leaving this issue open, in case the layout in case further adaptions are needed.

**Comment by StefanRother-OTOBO** [comment]
For the moment everything is fine, our new package manager is the future.
