### ISSUE TITLE
Implement OpenIDConnect

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1389]
Implement OpenIDConnect authentication for agents and customer users via the authorization code flow (recommended) or implicit code flow.

Added basic user creation and authorization via id_token information for agents.

**Comment by bschmalhofer** [comment]
See also #1398 which proposes to move authentication to a PSGI middleware.

**Comment by svenoe** [comment]
Works, need to add Crypt::JWT to docker images.
