### ISSUE TITLE
Multiple ActivityDialogs in Customer Interface open below each other

### ISSUE THREAD

**Issue by wetzf** [RotherOSS/otobo#1395]
Hello OTOBO Team,

I am currently testing OTOBO 10.1 and noticed a strange behavior when using multiple ActivityDialogs in the customer interface. 

I have a process with two Dialogs available in the customer interface. Now I open one of the dialogs. When I want to change the Dialog, it does not close the one previously selected. Instead, the second dialog is open above or below. If I submit one of them, only values from that dialog are saved.

Is this behavior wanted? I would expect that only one dialog can be open at any time. So the one previously selected closes when I open another one. 

![2021-11-10 09_38_46](https://user-images.githubusercontent.com/84456263/141078984-9011d77b-6b7a-40c6-869d-4894946da18c.png)

Kind regards.

**Comment by svenoe** [comment]
Hi wetzf,

I am aware of this behaviour and I just haven't yet decided on which behaviour is wanted here. In principle this way it would be easier to copy stuff from one dialog to the other. But maybe you are right, and we should automatically close all other dialogs. I will ask the others how they see it before deciding.

In general please add your comments on this directly to issue #1060, then other people won't get distracted by this.

Thank you for your feedback in any case! :)

**Comment by wetzf** [comment]
Hi Sven, 

thanks for the quick reply. I will close this issue and add further comments to #1060.
