### ISSUE TITLE
Always set the header Content-Length

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1430]
While implementing support for serving attachments as file handles, I found that only few OTOBO pages include the Content-Length header. The cases I found were:

- inline and non-inline Attachments in the customer and agent interface
- AJAX responses
- responses from the generic interface

The reason, that Content-Length is rarely set, might be that in OTOBO 10.0.x the the Output was printed in chunks and thus the final length could not easily be determined. In OTOBO 10.1.x we always have that information as either a string or a real file handle is served.
Assuming that setting Content-Length is best practice I propose to:
- remove the instances where Content-Lenght is currently set
- activate https://metacpan.org/pod/Plack::Middleware::ContentLength

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/1397#issuecomment-974639003_

**Comment by Getty** [comment]
Yeah, that sounds like the right direction, in general, if we know the content length it should be set, and that can be done automatically with the middleware. That way all parts of the PSGI-chain know how to handle the data and doesn't start guessing around.

**Comment by bschmalhofer** [comment]
@svenoe had no objections.

**Comment by bschmalhofer** [comment]
There is some potential for breakages in this issue. So let's keep it open for a while.

**Comment by bschmalhofer** [comment]
No bad consequences have been encountered so far. Closing this issue.
