### ISSUE TITLE
(Potential) Unused Parameter "FilesizeRaw"

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#1433]
Found in rel-10_0_12, Kernel/Modules/CustomerTicketArticleContent, L.151:

FilesizeRaw => bytes::length($Content)

The %Data variable including this line later is passed on to $LayoutObject->RichTextDocumentServe(). This function itself doesn't use the parameter, instead, it fetches the content length itself with bytes::length. A first test (outcommenting the line) indicated that it is unused, but someone with deeper knowledge should have a look at this topic.

**Comment by bschmalhofer** [comment]
Put the milestone to 10.1.1 as in 10.0.x only important bugs should be fixed. Also the module _Kernel/Modules/AgentTicketArticleContent,pm_ should be checked too.

**Comment by bschmalhofer** [comment]
Yes, FilesizeRaw was not used in the two frontend modules. Removed it. Closing this issue.
