### ISSUE TITLE
ACL "NewOwner", "OldOwner" and "Owner" is not looking for the user name / login

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1453]
In the ACL, "NewOwner", "OldOwner" and "Owner" trigger for the user's name (firstname + lastname). But should be the user name / login, e.g. for the (not too rare) case that two people share the same name.

Here the extract from the documentation (which should be adjusted accordingly:

        NewOwner:
        # For ticket action screens, where the Owner is already set.
        - some owner
        OldOwner:
        # For ticket action screens, where the Owner is already set.
        - some owner
        Owner:
        # For ticket create screens, because Owner is not set yet.
        - some owner
        # more ticket attributes

**Comment by stefanhaerter** [comment]
Closing in favor of #2200
