### ISSUE TITLE
Add nested group support for LDAP user/group sync

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1454]
@fraenki submitted a pull request for nested group support: https://github.com/RotherOSS/otobo/pull/1291

**Comment by reneeb** [comment]
As the original PR was merged this issue should be closed, shouldn't it?

**Comment by svenoe** [comment]
Yes, overlooked it, thanks.

**Comment by bschmalhofer** [comment]
See also #1573 .
