### ISSUE TITLE
Password sanity check in installer.pl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#146]
In installer.pl there is a JavaScript check that the repeated DB password for 'otobo' is the same as the password,

1. Password is entered
2. Start typing the repeated password => Password is marked in red
3. Really typing the identical password => Password is still marked in red

**Comment by bschmalhofer** [comment]
Also: maybe only activate the 'Continue' button when the passwords match

**Comment by svenoe** [comment]
Password check moved to the "repeat"-field. The validate plugin does not instantly run, but this is the same at other locations. In any case, no false negatives anymore, if filled in the correct order.

The unclickable continue button is not so important, imo.
