### ISSUE TITLE
Provide a better way to show and edit information as CustomerAccept, an About, etc.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1467]
Provide a better way to show and edit information as CustomerAccept, an About, etc.

**Comment by svenoe** [comment]
Working

**Comment by svenoe** [comment]
(The above commit belongs to #1476 - typo in the commit message...)

**Comment by bschmalhofer** [comment]
See also #739.

**Comment by bschmalhofer** [comment]
In the AdminAbout page the headline is "Privacy Policy" which is likely left over from the AdminCustomerAccept frontend.
