### ISSUE TITLE
Rendering fails in CustomerTicketZoom if dynamic fields of type 'Title' are too long

### ISSUE THREAD

**Issue by RGronau** [RotherOSS/otobo#1473]
Hello all, 

If you show dynamic fields of the type 'Title' that are too large, the layout is destroyed. (See screenshot)

![grafik](https://user-images.githubusercontent.com/95427123/144442803-864e76a0-ca72-44e0-853c-6eaa037d857f.png)

Best regards

Ralf

**Comment by svenoe** [comment]
Thanks for letting us know.

Somewhere an overflow: hidden has to be included to the form or fieldset most likely. (Probably present in 10.0.)

**Comment by RGronau** [comment]
...one more hint. This also happens if you have placed a dynamic text field and then resize it in the customer portal at runtime.
