### ISSUE TITLE
Tickets get locked on FollowUp even if the owner is root@localhost

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1475]
Behavior in 10.0: 
After activating "Ticket::EventModulePost###2700-ForceOwnerResetOnMove" the owner of the Ticket changes to root@localhost on queue change. If a FollowUp happens, the ticket gets locked for root@localhost, so nobody gets the notification on the FollowUp.

Behavior in 10.1:
On unlock of a ticket, the owner changes to root@localhost, so the same problem happens, where nobody get notification if a FollowUp happens.

Fix is comming.

**Comment by reneeb** [comment]
As the fix was applied, this issue should be closed, shouldn't it?

**Comment by StefanRother-OTOBO** [comment]
Yes, thanks. Closed.
