### ISSUE TITLE
Provide a configurable default krb5.conf file

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1476]
Another related issue concerns the file _/etc/krb5.conf_ in the nginx-kerberos image. Currently this is expected to be created by the user and mounted  from a file on the Docker host. 
But there already is a sample file _scripts/nginx/kerberos/krb5.conf_ which contains placeholder variable for variables from the _.env_ file. The plan is that the sample _krb5.conf_ is included in the image and that the placeholder will be replaced autmatically.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/1462#issuecomment-985562378_

**Comment by bschmalhofer** [comment]
The replacement of the placeholders for the environment can't be done in the image itself. This means that the replacement should be done when starting up. This can be done with the same approach as taken in _/docker-entrypoint.d/20-envsubst-on-templates.sh_  .

Note that _/etc/krb5.keytab_ then still needs to be mounted from the host. 

TODO:

- [ ] What is the best approach when further adaptions of /etc/krb5.conf are required ?

**Comment by wornet-aer** [comment]
Unfortunately it seems like we introduced a syntax error in 12a9d7e from #1465. There should be a semikolon in the keytab line.
```
        auth_gss on;
        auth_gss_keytab /etc/krb5.keytab
        auth_gss_service_name ${OTOBO_NGINX_KERBEROS_SERVICE_NAME};
```

**Comment by svenoe** [comment]
The above pr was merged manually: https://github.com/RotherOSS/otobo/commit/524db1869ffd8f93058817505f4cb06bfb056094

**Comment by bschmalhofer** [comment]
A related issue is https://github.com/RotherOSS/otobo-docker/issues/81.

**Comment by bschmalhofer** [comment]
The current state of affairs has beed integrated into the sources for OTOBO 10.1.1. This is low risk as the changes are very specific for Kerberos support. However the changes havn't really been tested.

**Comment by bschmalhofer** [comment]
Besides testing, the documentation is also lacking. The documentation should be added as an advanced topic in https://doc.otobo.org/manual/installation/10.1/en/content/installation-docker.html. Here is a first take:

For enabling authentication with Kerberos please base you .env file on the sample file .docker_compose_env_https_kerberos. This activates  the _docker-compose/otobo-override-https-kerberos.yml_  configuration. This Docker compose config file activates a Nginx image that supports Kerberos. It also passes some Kerberos specific setting as environment values to the running Nginx container. These settings are:
      OTOBO_NGINX_KERBEROS_SERVICE_NAME
      OTOBO_NGINX_KERBEROS_REALM
      OTOBO_NGINX_KERBEROS_KDC
      OTOBO_NGINX_KERBEROS_ADMIN_SERVER
      OTOBO_NGINX_KERBEROS_DEFAULT_DOMAIN

The values for these setting can be specified in the .env file. These setting will be used as replacement values for the template https://github.com/RotherOSS/otobo/blob/rel-10_1/scripts/nginx/kerberos/templates/krb5.conf.template . In the running container the adapted config will be available in /etc/krb5.conf.

Providing an user specific krb5.conf file is still possible. This can be done by mounting a volume that overrides /etc/krb5.conf in the container. This can be done by setting  OTOBO_NGINX_KERBEROS_CONFIG in the .env file and by activation the /etc/krb5.conf mount in _docker-compose/otobo-override-https-kerberos.yml

_/etc/krb5.keytab_ must always be mounted from the host system.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO , @StefanAbel-OTOBO
Or there still issues with Kerberos-Konfiguration? Can this issue be closed?

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I have published a first version of the Kerberos documentation at: https://doc.otobo.org/manual/installation/10.1/en/content/sso-kerberos.html

Kerberos works for me perfekt, beta status is removed. I close that issue.
