### ISSUE TITLE
The following configuration changes are implemented in OTOBO 10.1 to make the system easier to handle.

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1484]
The following configuration changes are implemented in OTOBO 10.1 to make the system easier to handle.

 Ticket::ZoomTimeDisplay activated
Ticket::Frontend::TicketArticleFilter activated
Ticket::Frontend::PlainView activated -> Administrators can now view all articles in AgentTicketZoom in plain mode.
Ticket::Frontend::AgentTicketNote###InformAgent activated -> In AgentTicketNote, communication between agents is now possible by default.
Ticket::Frontend::AgentTicketPhoneOutbound###State -> Default status changed to "open".
PreferencesGroups###DynamicFieldsOverviewPageShown -> 100, 250, or 500 dynamic fields are now displayed in AdminDynamicField.
Ticket::Frontend::DynamicFieldsZoomMaxSizeSidebar -> increased to 40 characters
Ticket::Frontend::CustomerInfoZoomMaxSize -> increased to 40 characters
SystemMaintenance::TimeNotifyUpcomingMaintenance -> increased to two hours
LinkObject::ViewMode -> Changed to "Complex". Links are now displayed below the article by default.
Ticket::ViewableStateType -> Removed type "pending auto".
First name of system user root@localhost changed to - -.

**Comment by bschmalhofer** [comment]
Adapted the test script _scripts/test/Selenium/Agent/Admin/AdminSystemMaintenance.t_ to the changed default for TimeNotifyUpcomingMaintenance. The setting changed from 30 to 120.
