### ISSUE TITLE
If there is a default value in a dynamic field, then this value is overlaid in the customer portal by the field designation.

### ISSUE THREAD

**Issue by RGronau** [RotherOSS/otobo#1485]
Hello all,

If you store a standard text in a dynamic variable, then the field heading should not appear in the field when it is displayed in the customer portal. This is because both overlap in a strange way and neither can be read correctly. You then have to click in the field to be able to read the content completely.

<img width="389" alt="Otobo_Issue_1" src="https://user-images.githubusercontent.com/95427123/144824759-1f20f8fb-67f2-44e7-9d75-0b7665a06f7e.PNG">
<img width="238" alt="Otobo_Issue_2" src="https://user-images.githubusercontent.com/95427123/144824775-e318a2a1-0c92-4a39-b2b0-380e60b94b86.PNG">
.

**Comment by svenoe** [comment]
Which OTOBO version are you running? This is already fixed in any case, but maybe not yet released. In the latter case it will come with the next update.

Thanks, Sven
