### ISSUE TITLE
OTOBO Statistics Enhancement

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1486]
OTOBO Statistics Enhancement

With OTOBO 10.1 it will now be possible to generate reports as well as statistics. 
Several statistics can now be summarised and formatted attractively, combined into one report and sent automatically if required.

**Comment by bschmalhofer** [comment]
TODO:

- [x] test scripts need to initialize $Kernel::OM. `use Kernel::System::UnitTest::RegisterDriver;`

**Comment by bschmalhofer** [comment]
Adapted the test scripts related statistics reports.
Fixed two more test scripts that turned out to be related to changes in the default settings.

Closing the issue again.

**Comment by bschmalhofer** [comment]
The commit https://github.com/RotherOSS/otobo/commit/6e610f46687ba6c98933a17b2703db6e08684fc7 added the file _Kernel/Language/de_OTOBOCommunity.pm_ . This file is not needed as the translatable strings are also part of _Kernel/Language/de.pm_ . Thus _de_OTOBOCommunity.pm_ can be removed. This will be done in #5167 .
