### ISSUE TITLE
Docker: Show whether OTOBO is running under Docker 

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1503]
Usually the environment varialbe OTOBO_RUNS_UNDER_DOCKER can be used for that.

There is also the file _/.dockerenv_ which should be present in the Docker case. Not sure how reliably that is. See https://github.com/testcontainers/testcontainers-java/issues/3681 .

**Comment by reneeb** [comment]
I would recommend to not use DOCKER specific strings/files. Under RHEL 8, _podman_ is a drop-in replacement of docker, so _.dockerenv_ **might** not be there. I would recommend an env variable like _OTOBO\_RUNS\_IN\_A\_CONTAINER_ (or something like that).
