### ISSUE TITLE
Docker Hub: implement policy concerning the 'latest' tag

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1504]
Current every new release, regardless whether in 10.0 or on 10.1, sets the lag 'latest'. This does not make sense at all when there is more than on maintained branch.

TODO:

- [x] define a policy which labels should be set
- [x] implement it, propable in _hooks/post_push_

**Comment by bschmalhofer** [comment]
This was discussed between @StefanRother-OTOBO , @svenoe , and @bschmalhofer . The conclusion was:

- the tag 'latest' is deprecated, but will continue to point to the latest patch release of the 10.0 series
- releases that do not match rel-<major>_<minor>_<patch> will get no extra tag, e.g. rel-10_1_Beta2
- patch level releases will get a latest-<major>_<minor> tag

These rules can be implemented in _hooks/post_push_ .

TODO after implementation:

- [x]  sample .env files need to be adapted in docker-compose,  trying to keep rel-10_0 and rel-10_1 with having few differences
- [x] doc-otobo-install might need to be updated
- [x] create a new tag latest-10_0  pointing to the current latest
- [x] backport to rel-10_0

**Comment by bschmalhofer** [comment]
Tested this by setting `DOCKER_TAG` directly in the scripts. Let's see whether a latest-tag will be created after pushing rel-10_1_beta2.

**Comment by svenoe** [comment]
I will close this. If there is a problem, we will see only with the release anyways.
