### ISSUE TITLE
OTOBO Dashboard Spalten hinzufügen

### ISSUE THREAD

**Issue by dominikfuller** [RotherOSS/otobo#1507]
Wenn man auf dem Agent-Dashboard auf eines der Zahnrädchen für die Einstellungen klickt und dort Spalten hinzufügen oder verändern will und dieses anspeichert, werden die Änderungen nicht übernommen.

**Comment by svenoe** [comment]
Hi Dominik,

ich kann das leider nicht nachvollziehen (= bei mir funktioniert ein kurzer Test). Könntest du bitte die Version schreiben, die du nutzt, ein, zwei Bilder machen, die veranschaulichen, was du genau machst, und am besten mal die logs angucken, ob es irgendwelche Fehlermeldungen gibt? Gerade falls letzteres der Fall ist, wäre es uns auch lieb, wenn du erstmal in den [Foren](https://otobo.de/en/forums/otobo/otobo-forum/) Hilfe suchen würdest, weil wir github eigentlich nur für Entwicklungsthemen und keinen Support nutzen. (Ich sehe ein, dass hier nicht ganz klar ist, wie es einzuordnen ist.)

Viele Grüße, Sven

**Comment by dominikfuller** [comment]
hi, ich habs auch im Demo versucht.... https://demo.otobo.org/otobo/index.pl
![01](https://user-images.githubusercontent.com/96129962/146024362-5908afb6-67a4-49b2-a626-48b1e66e0aa8.JPG)
![02](https://user-images.githubusercontent.com/96129962/146024369-0e70d7c2-ffe2-41f6-840f-b0249005874a.JPG)

**Comment by dominikfuller** [comment]
im syslog steht:
Dec 14 16:29:57 dedb-linapp04 OTOBO-CGI-22[5631]: [Error][Kernel::System::User::UserLookup][Line:1036]: No UserLogin found for '2'!
Dec 14 16:29:57 dedb-linapp04 OTOBO-CGI-22[5631]: [Error][Kernel::System::User::Preferences::DB::SetPreferences][Line:94]: Cannot add or update a child row: a foreign key constraint fails (`otobo`.`user_preferences`, CONSTRAINT `FK_user_preferences_user_id_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)), SQL: '#012            INSERT INTO user_preferences#012            (user_id, preferences_key, preferences_value)#012            VALUES (?, ?, ?)'
Dec 14 16:29:57 dedb-linapp04 OTOBO-CGI-22[5631]: [Error][Kernel::System::User::UserLookup][Line:1036]: No UserLogin found for '2'!
Dec 14 16:29:57 dedb-linapp04 OTOBO-CGI-22[5631]: [Error][Kernel::System::User::Preferences::DB::SetPreferences][Line:94]: Cannot add or update a child row: a foreign key constraint fails (`otobo`.`user_preferences`, CONSTRAINT `FK_user_preferences_user_id_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)), SQL: '#012            INSERT INTO user_preferences#012            (user_id, preferences_key, preferences_value)#012            VALUES (?, ?, ?)'
