### ISSUE TITLE
DashboardBackend###0000-ProductNotify can't connect (Product News)

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1532]
When activating DashboardBackend###0000-ProductNotify, it shows an error message:
Can't load cloud-service operation backend: PublicFeeds::ProductFeed!

<img width="566" alt="image" src="https://user-images.githubusercontent.com/87359203/148401842-1528dd76-2637-417b-94ba-c020487aad42.png">

@svenoe  proposed to de-active the System Configuration setting for now.

Can be tested on ov71

**Comment by bschmalhofer** [comment]
I can confirm that the ProductNotify dashboard tile does not work.

**Comment by svenoe** [comment]
We should bring this feature back. (It is mostly work on our infrastructure, not on OTOBO itself.) Until then we disable it.

**Comment by bschmalhofer** [comment]
Deactivating DashboardBackend###0000-ProductNotify cause failures in the test suite.

> /opt/otobo/scripts/test/Selenium/Output/Dashboard/ProductNotify.t                                         (Wstat: 768 Tests: 10 Failed: 3)
>   Failed tests:  5, 7, 9
>   Non-zero exit status: 3

_ProductNotify.t_ needs to be skipped.

**Comment by bschmalhofer** [comment]
Test is skipped now. Closing again.

**Comment by bschmalhofer** [comment]
The test _[scripts/test/Selenium/Output/Dashboard/ProductNotify.t](https://github.com/RotherOSS/otobo/commit/394b56754be3d650fb6ab762dcdf83cc658f3052#diff-3e65af2ce085e396ce1e582eab03bed90203db49d49297a145d2fd486cea468e)_ should be skipped in rel-10_0 as well.

**Comment by bschmalhofer** [comment]
Use the script from rel-10_1. A test execution of the scripts looked fine. Closing this issue again.
