### ISSUE TITLE
Bug in OTOBO 10.1 with HttpType

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1541]
In OTOBO 10.1 (Docker and none docker) the error_log is overflowing with messages like:
HttpType https is set, but http is used!
The problem is that in Kernel/System/Web/InterfaceAgent.pm and Kernel/System/Web/InterfaceCustomer.pm 
the following query always returns "HTTP *":

 203     # Restrict Cookie to HTTPS if it is used.
 204     my $CookieSecureAttribute = $ConfigObject->Get('HttpType') eq 'https' ? 1 : undef;
 205 
 206     # check whether we are using the right scheme
 207     my ($RequestScheme) = split '/', $ParamObject->ServerProtocol(), 2;
 208     $RequestScheme = lc $RequestScheme;
 210     if ( $RequestScheme ne $ConfigObject->Get('HttpType') ) {
 211         $Kernel::OM->Get('Kernel::System::Log')->Log(
 212             Priority => 'notice',
 213             Message  => sprintf(
 214                 'HttpType %s is set, but %s is used!',
 215                 $ConfigObject->Get('HttpType'),
 216                 $RequestScheme
 217             ),
 218         );
 219     }

**Comment by bschmalhofer** [comment]
See also #142, #184, and #477.

**Comment by bschmalhofer** [comment]
I recommend to simply remove this check. The config setting _HttpType_ is solely used for things like notification that provide links back to OTOBO. The setting is not used in the internal workings of the web application. The use case of a TLS terminating proxy sitting in front of an HTTP only webserver is nothing unusual and deserves no entries in the logfile.

@StefanRother-OTOBO , @svenoe : Are there any objections?

**Comment by svenoe** [comment]
I included it as an information above anything. With incorrect settings the cookies, at least with 10.0 and the non docker apache install, were not working. In the worst case (which admittedly didn't occur often, mostly after migrations sometimes) this could shut the user out, if the session was stored in the wrong cookie from a previous OTOBO instance were this setting differed. A more common error though is, that without the cookies the article view in the customer interface, and probably other places where content is shown as iframe only shows the login screen. So I thought this is a good hint, that something is not configured correctly. I don't know however, how the current behaviour is in all of that.

**Comment by bschmalhofer** [comment]
One idea for alleviating the "HttpType has changed" problem is to incorporate the HttpType into the cookie name. This would force a new session for the agents when HttpType changes. On the other hand, I can image other kinds of confusion when there are multiple cookies.

**Comment by svenoe** [comment]
Also it would not give any hints in case of the more common iframe problem. In the end it shouldn't be hard to find out the protocol we use and compare, I guess... I can have a look at it, later.

**Comment by bschmalhofer** [comment]
@svenoe confirmed that this check can be removed.

**Comment by bschmalhofer** [comment]
The check has been removed. Closing this issue.
