### ISSUE TITLE
EffectiveValue is not optional in SettingsSet

### ISSUE THREAD

**Issue by sternenseemann** [RotherOSS/otobo#1546]
Contrary to documentation `EffectiveValue` can't be omitted in the list supplied to `SettingsSet` via the `Settings` parameter. Regardless of whether it's given or not, its type and structure will be checked and consequently fail as it turns out to be `undef` instead a hash etc.

E.g.:

```
ERROR: OTOBO-otobo.UnitTest-08 Perl: 5.32.1 OS: linux Time: Wed Jan 19 16:46:43 2022

 Message: EffectiveValue is invalid! Its not a hash!

 Traceback (180): 
   Module: Kernel::System::SysConfig::SettingUpdate Line: 519
   Module: Kernel::System::SysConfig::SettingsSet Line: 4748
   Module: /opt/otobo/scripts/test/otobo-rocketchat.t Line: 405
```

**Comment by svenoe** [comment]
Hi Sterni,

for the moment adding a comment to the "(optional)" in the pod, that at least type and structure have to fit (like https://github.com/RotherOSS/otobo/blob/c1ff3e68740f876712eb1e6c5eb1180952f2e903/Kernel/System/SysConfig.pm#L505-L506) for I assume other than strings, would probably be the easiest solution. Maybe the code can be changed to always accepting `undef`, too, but someone should investigate first. I am not sure if we would gain much of it, either, though. The first should be done for now, the latter is more optional, I guess.

Thanks for the note, Sven :)

**Comment by sternenseemann** [comment]
I think it would also be fine to just update the documentation and make the field mandatory. My use case was to change the validity but leave the settings unchanged, but didn't check if there was an alternative way.

**Comment by bschmalhofer** [comment]
The POD of Kernel::System::SysConfig is indeed a bit lacking. My understanding is that EffectiveValue is marked as optional because it can be omitted when a setting is invalidated. I updated the POD accordingly.

Closing this issue.
