### ISSUE TITLE
INSTALL.md points to a document that is 404

### ISSUE THREAD

**Issue by ernstki** [RotherOSS/otobo#1550]
Hi all, hope you're well.

An issue of very little importance, but FYI: the link within [`INSTALL.md`](../blob/master/INSTALL.md) is currently a 404 Not Found.

```markdown
Please see [the installation instructions](https://doc.otobo.org/manual/installation/stable/en/content/index.html)
in the online documentation.
```

On the basis of the `stable` there in the URL, I _assume_ this happened when documentation was moved from Read the Docs to being self-hosted. The correct URL is (currently) <https://doc.otobo.org/manual/installation/10.1/en/content/index.html>, but of course that version number will change; <https://doc.otobo.org/manual/installation> would work nicely if it redirected, but it's 403 Forbidden.

Some options:

*  I searched the web for "sphinx +latest +stable version" and came up with [sphinx-contrib/sphinxcontrib-versioning](https://github.com/sphinx-contrib/sphinxcontrib-versioning)
    * I don't know Sphinx well enough to tell if this is viable, or just an over-engineered solution to a simple problem
* creating a symlink, _e.g._ `stable` → `10.1`, when you deploy your documentation
* a redirect in `.htaccess`, but [that's an Apache thing](https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/)
* just point to doc.otobo.org
* remove `INSTALL.md` from the repository and rely on the README instead

**Comment by ernstki** [comment]
A cursory search for other files that are affected:

```console
$ ag --markdown stable/en
UPDATING.md
1:Please see [the updating instructions](https://doc.otobo.org/manual/installation/stable/en/content/updating.html)

INSTALL.md
1:Please see [the installation instructions](https://doc.otobo.org/manual/installation/stable/en/content/index.html)

README.md
42:The software and hardware requirements [can be found in our documentation.](https://doc.otobo.org/manual/installation/stable/en/content/requirements.html)
```

**Comment by svenoe** [comment]
Hi Kevin,

thanks for the hint - we changed the paths with 10.1, I will adapt the file.

Sven

**Comment by svenoe** [comment]
(good morning...)
