### ISSUE TITLE
Fix unit test failures before OTOBO 10.1.1 final release

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1553]
Here are the current test failures:

```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1787 Failed: 0)
  TODO passed:   1012, 1037
/opt/otobo/scripts/test/DynamicField/EditFieldRender.t                                                    (Wstat: 2048 Tests: 69 Failed: 8)
  Failed tests:  14-21
  Non-zero exit status: 8
/opt/otobo/scripts/test/Selenium/Output/Dashboard/TicketGenericFilter.t                                   (Wstat: 256 Tests: 25 Failed: 1)
  Failed test:  20
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
  Failed tests:  76-77, 89, 101
  Non-zero exit status: 4
Files=961, Tests=82084, 6835 wallclock secs (32.22 usr  3.41 sys + 1758.55 cusr 221.89 csys = 2016.07 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host d9bf5f435b43 .

```

**Comment by bschmalhofer** [comment]
The four failures in _scripts/test/WebUserAgent.t_  are handled in #1250.

**Comment by bschmalhofer** [comment]
The failures in Selenium/Output/Dashboard/TicketGenericFilter.t were due to the new widget showing the last changed tickets. There were some checks that specific tickets should not be shown in the Dashboard after some action in the NewTickets widgets. However the test scripts saw those tickets in the lastchange widget, and was led astray. The fix is to switch to strikter XPath and Jquery selectors that look only at the relevant div.

**Comment by bschmalhofer** [comment]
@stefanhaerter , could you take a look at _scripts/test/DynamicField/EditFieldRender.t_ ? These failures seem to be related to changed HTML in the rendered dynamic fields. See #1132.

**Comment by stefanhaerter** [comment]
Forgot to respond: Should be fixed with PR https://github.com/RotherOSS/otobo/pull/1563

**Comment by bschmalhofer** [comment]
Thanks to @stefanhaerter  the failures in _scripts/test/Selenium/Output/Dashboard/TicketGenericFilter.t_ are fixed now.
But new failures cropped up in _scripts/test/Selenium/Agent/Znuny4OTOBOShowPendingTimeIfNeeded.t_

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1010, 1035
> /opt/otobo/scripts/test/Selenium/Agent/Znuny4OTOBOShowPendingTimeIfNeeded.t                               (Wstat: 512 Tests: 82 Failed: 2)
>   Failed tests:  79, 82
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82088, 7188 wallclock secs (33.60 usr  3.30 sys + 1946.55 cusr 242.81 csys = 2226.26 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host d32a845d69d7 .
>

**Comment by bschmalhofer** [comment]
Result of the latest run. _Znuny4OTOBOShowPendingTimeIfNeeded.t _ is fine again, but two new failing test scripts.

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1010, 1035
> /opt/otobo/scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t                                         (Wstat: 512 Tests: 38 Failed: 2)
>   Failed tests:  37-38
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82003, 6796 wallclock secs (32.76 usr  3.11 sys + 1864.78 cusr 226.86 csys = 2127.51 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host d5d74f294a00 .
>

**Comment by bschmalhofer** [comment]
Here are the current test results. The failure in _AdminPackageManager.t_ might be sporadic or might depend on  the package repository. The test failed reproducibly for some hours but seems to work now. The recent changes in the test script are no fixes, just tidying.

> 
> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1010, 1035
> /opt/otobo/scripts/test/Selenium/Agent/Admin/AdminPackageMana> 
> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1010, 1035
> /opt/otobo/scripts/test/Selenium/Agent/Admin/AdminPackageManager.t                                        (Wstat: 256 Tests: 66 Failed: 1)
>   Failed test:  66
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82021, 6625 wallclock secs (32.09 usr  3.28 sys + 1679.32 cusr 204.94 csys = 1919.63 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host a095de872c1b .
> ger.t                                        (Wstat: 256 Tests: 66 Failed: 1)
>   Failed test:  66
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82021, 6625 wallclock secs (32.09 usr  3.28 sys + 1679.32 cusr 204.94 csys = 1919.63 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host a095de872c1b .
>

**Comment by bschmalhofer** [comment]
Latest run of the test suite. Failure in _AdminCustomerGroup.t_ is new.
 
> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 256 Tests: 1788 Failed: 1)
>   Failed test:  863
>   TODO passed:   1013, 1038
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t                                         (Wstat: 512 Tests: 38 Failed: 2)
>   Failed tests:  37-38
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82013, 6635 wallclock secs (31.46 usr  3.27 sys + 1689.87 cusr 206.30 csys = 1930.90 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host e93ae1aef60c .
>

**Comment by bschmalhofer** [comment]
The failure in _scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t_ might have been sporadic.
But then something is still strange with _scripts/test/Selenium/Agent/Admin/AdminPackageManager.t_

  (in cleanup) Can't use an undefined value as a HASH reference at Kernel/System/DB.pm line 261 during global destruction.

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 256 Tests: 1788 Failed: 1)
>   Failed test:  863
>   TODO passed:   1013, 1038
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82062, 6342 wallclock secs (31.11 usr  2.93 sys + 1633.55 cusr 199.29 csys = 1866.88 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host 1eccd6e3bf7c .
>

**Comment by bschmalhofer** [comment]
It turned out that the override of `Kernel::System::WebUserAgent::Request()` is needed after all. Mainly because other test scripts did the same, so we got unexpected content from that method. No idea how that could have worked before with the broken code. Maybe it wasn't broken after all.

**Comment by bschmalhofer** [comment]
Looks better now:

> 
> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 256 Tests: 1788 Failed: 1)
>   Failed test:  863
>   TODO passed:   1013, 1038
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82061, 6464 wallclock secs (31.43 usr  2.98 sys + 1660.01 cusr 203.50 csys = 1897.92 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host def81b671d6e .
>

**Comment by bschmalhofer** [comment]
A test run with a local Apache and _scripts/apache2-httpd.include.conf_ looks fine. The _Archive.t_ failures fine, are some files have changes since ARCHIVE was generated.

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Archive.t                                                                         (Wstat: 768 Tests: 4 Failed: 3)
>   Failed tests:  2-4
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1801 Failed: 0)
>   TODO passed:   1010, 1035
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=81752, 6620 wallclock secs (25.90 usr  2.95 sys + 1384.04 cusr 169.19 csys = 1582.08 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host bernhard-HP-250-G6-Notebook-PC .
>

**Comment by bschmalhofer** [comment]
See also #1054

**Comment by bschmalhofer** [comment]
_scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t_ are now again the only failures.

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1010, 1035
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82059, 6509 wallclock secs (31.46 usr  3.00 sys + 1678.36 cusr 207.21 csys = 1920.03 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host f55be759bf43 .
>

**Comment by bschmalhofer** [comment]
Latest run under Docker looks fine:

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1786 Failed: 0)
>   TODO passed:   1011, 1036
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=82059, 6988 wallclock secs (32.52 usr  3.36 sys + 1747.15 cusr 215.31 csys = 1998.34 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host 061df86647c0 .
>

**Comment by bschmalhofer** [comment]
Advanced tip for when running installer.pl manually and then the test suite: Choose English as the default language

**Comment by bschmalhofer** [comment]
Unit test for Apache with _apache2-httpd-cgi.include.conf_ looks fine, ignoring the failures in _ErrorHandling.t_.

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1802 Failed: 0)
>   TODO passed:   1011, 1036
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/Customer/Ajax/ErrorHandling.t                                            (Wstat: 512 Tests: 19 Failed: 2)
>   Failed tests:  16, 19
>   TODO passed:   5-12
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=81724, 8403 wallclock secs (26.68 usr  3.12 sys + 1444.59 cusr 182.37 csys = 1656.76 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host bernhard-HP-250-G6-Notebook-PC .
>

**Comment by bschmalhofer** [comment]
Running the test suite with Apache and _apache2-httpd.include.conf_ looks fine too:

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Archive.t                                                                         (Wstat: 512 Tests: 3 Failed: 2)
>   Failed tests:  2-3
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1802 Failed: 0)
>   TODO passed:   1011, 1036
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=960, Tests=81741, 7083 wallclock secs (24.80 usr  2.97 sys + 1404.67 cusr 170.48 csys = 1602.92 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host bernhard-HP-250-G6-Notebook-PC .
>

**Comment by bschmalhofer** [comment]
Latest run of the test suite under Docker showed no new failures.

**Comment by bschmalhofer** [comment]
The only real failures in the rel-10_1 unit tests are now the failures in AdminProcessManagementTransitionAction.t .
@reneeb : Did you make changes in that area?

**Comment by svenoe** [comment]
Yes: https://github.com/RotherOSS/otobo/pull/1565 - this has been manually tested by several people now, and I'm pretty certain we will have to adapt the test, without having had a look at it, though.

**Comment by reneeb** [comment]
I have some issues with my selenium setup. Do you have a short checklist how to setup the selenium tests? The easiest change would be to change the selected transition action in that test and set the values. I can prepare a pull request for that but can't actually run the test at the moment.

**Comment by bschmalhofer** [comment]
No new failures:


```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1786 Failed: 0)
  TODO passed:   1011, 1036
/opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
  Failed tests:  81, 84, 87
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
  Failed tests:  76-77, 89, 101
  Non-zero exit status: 4
Files=960, Tests=82062, 6994 wallclock secs (32.70 usr  3.46 sys + 1924.94 cusr 234.43 csys = 2195.53 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host 987eb525cea6 .

```

**Comment by bschmalhofer** [comment]
Another test run. _scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t_ seems to be sporadic, as it works when called explicitly.

```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1786 Failed: 0)
  TODO passed:   1011, 1036
/opt/otobo/scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t                                         (Wstat: 512 Tests: 38 Failed: 2)
  Failed tests:  37-38
  Non-zero exit status: 2
/opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
  Failed tests:  81, 84, 87
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
  Failed tests:  76-77, 89, 101
  Non-zero exit status: 4
Files=960, Tests=82014, 6510 wallclock secs (30.91 usr  3.14 sys + 1687.42 cusr 201.44 csys = 1922.91 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host d9e1b078243e .

```

**Comment by bschmalhofer** [comment]
I ran the test suite and got many failures. Very unscientifically I tried it again and it looked better on the second attempt:


> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1011, 1036
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/Output/Dashboard/ProductNotify.t                                         (Wstat: 768 Tests: 10 Failed: 3)
>   Failed tests:  5, 7, 9
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=961, Tests=82075, 6617 wallclock secs (31.29 usr  2.90 sys + 1715.92 cusr 209.00 csys = 1959.11 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host a3770cfd2a23 .
> 

The failure of _Selenium/Output/Dashboard/ProductNotify.t_ is due to #1532 and has been fixed by skipping that test script.

**Comment by bschmalhofer** [comment]
Still looking fine:

> 
> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
>   TODO passed:   1011, 1036
> /opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 Tests: 87 Failed: 3)
>   Failed tests:  81, 84, 87
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> /opt/otobo/scripts/test/WebUserAgent.t                                                                    (Wstat: 1024 Tests: 121 Failed: 4)
>   Failed tests:  76-77, 89, 101
>   Non-zero exit status: 4
> Files=961, Tests=82064, 6638 wallclock secs (30.75 usr  3.06 sys + 1702.07 cusr 204.71 csys = 1940.59 CPU)
> Result: FAIL
> ran tests for product OTOBO 10.1.x on host 7fa0b4a9b883 .
>

**Comment by svenoe** [comment]
I have no "unknown" problems without docker (and without selenium, though), so I will close this issue. The remaining ones are tests which should be adapted, but not necessarily for 10.1.1.
