### ISSUE TITLE
Database Fields reinitialization leads to error message.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1559]
Having a DB field in AgentTicketFreeText filled, will lead to a "Duplicated entry" error upon expanding the article box when AgentTicketFreeText###Note is set but not AgentTicketFreeText###NoteMandatory.

This comes from https://github.com/RotherOSS/otobo/blob/524db1869ffd8f93058817505f4cb06bfb056094/var/httpd/htdocs/js/Core.Agent.DynamicFieldDBSearch.js#L396 being called (tested), which likely comes from https://github.com/RotherOSS/otobo/blob/524db1869ffd8f93058817505f4cb06bfb056094/var/httpd/htdocs/js/Core.Agent.DynamicFieldDBSearch.js#L135-L137

Probably a good fix would be to restrict the initialization to fields within the opened widget.

**Comment by stefanhaerter** [comment]
Note: Entry is added not only when expanding box but also when collapsing.
