### ISSUE TITLE
Tidying of Kernel::System::Auth::Sync::LDAP

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1573]
No special reason, but it is good to be consistent. `_ConvertFrom()` is also a method.

Maybe also check whether the `$FindMember` as an anonymous sub is really the best solution.

**Comment by bschmalhofer** [comment]
See also #1291 and https://github.com/OTRS/otrs/pull/1344.

**Comment by bschmalhofer** [comment]
It also would be very nice to have better test coverage of LDAP related features. AFAIK, in OTOBO there is not even a mock LDAP server that could be used for running tests against.

**Comment by bschmalhofer** [comment]
Merged the easy parts of the open patch.

**Comment by bschmalhofer** [comment]
Provided an updated version of the patch as a PR.

**Comment by bschmalhofer** [comment]
Hi Frank, @fraenki ,

when working on a simplified PR I noticed the call to `Net::LDAP::search()` in https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/System/Auth/Sync/LDAP.pm#L937. Do you know whether the parameter `Attributes`is correct? In the [documentation](https://metacpan.org/dist/perl-ldap/view/lib/Net/LDAP.pod#search-(-OPTIONS-)) I have only seen the parameter `attrs`.

Best regards,
    Bernhard

**Comment by fraenki** [comment]
> Do you know whether the parameter Attributes is correct? In the [documentation](https://metacpan.org/dist/perl-ldap/view/lib/Net/LDAP.pod#search-(-OPTIONS-)) I have only seen the parameter attrs.

It's been so long since I've touched this code, so I don't know. :(
But after reading the documentation I agree with your assessment, it should most likely be `attrs`.

**Comment by bschmalhofer** [comment]
Hi Frank, @fraenki, 
after looking at the code of [Net::LDAP](https://metacpan.org/dist/perl-ldap/view/lib/Net/LDAP.pm) I concluded that the parameter `Attributes` is silently ignored. That is, only the parameter `attrs` would be part of the message sent to the LDAP server.  as I don't want to change the current behavior I went for simply removing `Attributes`, 

The current behaviour is that the default attributes of the found LDAP entries are returned. In principle it would make sense to request that only the needed attributes, even if they are not declared as default, are included. But that would be a different issue.

Could you give the newest version,
https://github.com/RotherOSS/otobo/blob/issue-%231573-ldap_tidying_take4/Kernel/System/Auth/Sync/LDAP.pm, a try? I still don't have the possibility to really test on my development machine.

Best regards,
    Bernhard

**Comment by fraenki** [comment]
Hi @bschmalhofer, I've tested the newest version and it seems to work fine. I've made some manual changes to the group memberships, but after a new logon the LDAP sync fixed the group memberships as expected. LGTM.

**Comment by bschmalhofer** [comment]
Hi Frank,
thanks for testing. I have merged the PR, so that the changed code will be included in OTOBO 10.1.7.

Best regards, einen guten Rutsch,
   Bernhard
