### ISSUE TITLE
Autologout after Deployment 

### ISSUE THREAD

**Issue by Taiserisa** [RotherOSS/otobo#1574]
OTOBO 10.0.15 with ITSM 10 Bundle Package, testserver, intern, no internet connection

The problem - after configuring the system settings and then deploying them in admin area, I am automatically logged out every time. Is it desired or an error?

**Comment by reneeb** [comment]
Do you use SSL? What's the value of the system configuration setting "HttpType"? Does that match?

**Comment by svenoe** [comment]
Hey Taiserisa,

this is most likely the setting Renee mentioned. For general questions however please use our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) and not github, which is intended for development issues.

I will close this issue here, best regards, Sven
