### ISSUE TITLE
installer.pl does not check for changed file Kernel/Config.pm

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1575]
During testing for OTOBO 10.1.1 Beta2 @svenoe noticed database connection failures while running _installer.pl_ . This was almost certainly caused by the web server process having still loaded an unchanged version of Kernel::Config. This is relevant as _Kernel/Modules/Installer.pm_ writes the new database credentials into that file.

The big mystery is why this behavior was noticed only now. Doing a test installation with OTOBO 10.1.1 Beta2 showed the same error.

A possible solution is to check for every request whether Kernel/Config.pm has changed. This is basically the same check as done in `Kernel::Config::Defaults:;new()` for possibly changed _ZZZ*.pm_ files.

While we are at it, we should also check for explicit `use Kernel::Config;` statements. These statements should be avoided unless they are really necessary. But they are not really the culprit as the object manager calls under the hood also `require Kernel::Config`.

**Comment by bschmalhofer** [comment]
No new insights turned up, why this wasn't an issue before. 

For fixing the bug I added the refresh of _Kernel/Config.pm_ in _otobo.psgi_ . Care had to be taken that Kernel/Config.pm is in the refresh cache before the first check. Otherwise the following situation could arise:

1. Kernel::Config.pm is loaded in process A, but not in refresh cache
2. Kernel/Config.pm is modified in process B
3. Kernel/Config.pm is checked in process A, but not reloaded is this is the first check

**Comment by bschmalhofer** [comment]
I tested installer.pl with a local Apache and the _apache2-httpd-cgi.include.conf_ configuration. Installing was without hassle. But there were errors after the installation was completed. Looks like we need a bit more testing and maybe fixing.

**Comment by bschmalhofer** [comment]
Looked again what `Module::Refresh::refresh_module_if_modified()` is actually doing. There is no refreshing when the module has been loaded and changed after the last time it has been encountered by Module::Refresh. So the current approach is;

1. `require $PMFile;`   load when it wasn't already loaded
2. ` Module::Refresh->refresh_module_if_modified('Kernel/Config.pm');` either remember the timestamp, do nothing, or reload

Made the changes and did quick tests of _installer.pl_.

- Apache2 with apache2-httpd.include.conf
- Apache2 with apache2-httpd-cgi.include.conf
- Gazelle running in Docker

The quick tests looked fine and the test suite looked fine too. Except #1587.
Thus I merged the changes into rel-10_1.

**Comment by svenoe** [comment]
Can this be closed? We are already one step further anyways, I guess, aren't we?

**Comment by bschmalhofer** [comment]
The reloading of _Kernel/Config.pm_ appears to be more sane now. Note that there was yet another iteration handled in issue #1594. Closing this issue.
