### ISSUE TITLE
Remove height in order to see more data than just one line in AgentTicketZoom Processview

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1592]
Remove height in order to see more data than just one line in AgentTicketZoom Processview

**Comment by svenoe** [comment]
This needs another look. If we want to keep it that way, at least the class name "CutValue" should be changed if nothing is cut anymore. Maybe though the whole css block as well as the class in the template file can be removed completely as currently only 'display: block' is meaningful.
