### ISSUE TITLE
Import of Dynamic Fields doesn't respect FieldOrder

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1596]
When you try importing a partial list of Dynamic Fields, the FieldOrder-Property does not affect the import at all. The imported items are ordered alphabetically.

Expected Result:
Imported items are in exact order of their FieldOrder-Property or the items are in relative order to existing DynamicField items.

Example:
Import List:
- FieldOrder = 8
- FieldOrder = 13
- FieldOrder = 28
- FieldOrder = 33

Already existing DF-Entries:
- FieldOrder = 1 .. 12

After the import it should look like this:

- FieldOrder = 1 .. 12
- FieldOrder = 13 (original 8)
- FieldOrder = 14 (original 13)
- FieldOrder = 15 (original 28)
- FieldOrder = 16 (original 33)

**Comment by stefanhaerter** [comment]
The code in question is the following:

https://github.com/RotherOSS/otobo/blob/6d6cd0ba9c1734b06796d41558bd242bf49b735c/Kernel/System/ZnunyHelper.pm#L1609-L1618

I suppose that, in order to fix the issue, the reordering from the AdminDynamicField... modules would have to be replicated there.

**Comment by stefanhaerter** [comment]
DF ImportExport seems to depend on the sorting of the fields in Kernel/Modules/AdminDynamicFiedImportExport.pm, thus, in a first step, I sorted the fields accordingly in PR #3579.

However, the ZnunyHelper has a mechanism in place relying on DF config parameter 'FieldOrderAfterField', which I couldn't get to work properly. The mechanism should be reviewed and a decision should be made if we want to keep it.

**Comment by stefanhaerter** [comment]
Original issue solved with merging #3579. However, I still didn't get to grip with the FieldOrderAfterField mechanism, but I think this should be a different issue if needed.

Closing the issue.
