### ISSUE TITLE
Check the email addresses given in the source code

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1601]
When checking the usage of otobo.de vs. otobo.org  it was recognised that the email addresses should be standardized too.

> I think we also need to have a look at the email addresses given. 

_Originally posted by @GritRother-OTOBO in https://github.com/RotherOSS/otobo/issues/604#issuecomment-721642512_

**Comment by stefanhaerter** [comment]
Mail addresses should be standardized to 'otobo.io' with #3425 - suggest to remove this issue from the wishlist.

**Comment by bschmalhofer** [comment]
Reopening, as the issue was moved out of the wishlist.

**Comment by stefanhaerter** [comment]
I think it can be closed again as mail addresses should be done with the URL changes in #3425
