### ISSUE TITLE
Update the copyright year in the Migration tool

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1605]
When running `bin/otobo.Console.pl Dev::Tools::Migrate::OTRSToOTOBO` for migrating an OTRS package I still get 2021 as the latest year. This should be changed to the current year.

**Comment by bschmalhofer** [comment]
@svenoe Is this resolved by the commit https://github.com/RotherOSS/otobo/commit/4ac6f66e77932e81a0c16d69feb76ed6a4fea4f3 ?

**Comment by svenoe** [comment]
Ah, I did not see this issue. I would say yes with a relatively high confidence. For me I noticed this during package migration, which uses the OTOBO migration backend modules though.

**Comment by bschmalhofer** [comment]
Closing this issue as it was implicitly tested.
