### ISSUE TITLE
Console commands for linking and unlinking package files

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1612]
During development of OTOBO packages there is commonly the need to link the to be installed files into an existing installation. Traditionally this was done with https://github.com/OTRS/module-tools . But there is no apparent reason for not including this functionality into core OTOBO. So I propose to add:

- Dev::Package::LinkFiles  (with an option --force for backing up existing files)
- Dev::Package::UnlinkFiles

Common functionality with Dev::Package::Build should be factored out into a base module.

The devel manual should be updated accordingly.

**Comment by svenoe** [comment]
For package building, though, this is only one of the functionalities you would want, and aside from package building it has no use at all. Let us talk about this today, briefly. In any case I would not try to incorporate it into 10.1.1.

**Comment by bschmalhofer** [comment]
See also https://metacpan.org/pod/OPM::Maker

**Comment by bschmalhofer** [comment]
See also the discussion in #1614.
