### ISSUE TITLE
Missing table stats_report

### ISSUE THREAD

**Issue by joserribeiro26** [RotherOSS/otobo#1613]
After installing otobo 10.1 beta 2, at first, no update was made.
The error below has been appearing in the log /opt/otobo/var/log/otobo.log

I checked the database tables with "show tables" I didn't find either.

 Message: Table 'otobo.stats_report' doesn't exist, SQL: 'SELECT id, name FROM stats_report WHERE valid_id IN (1)'

<img width="787" alt="image" src="https://user-images.githubusercontent.com/475022/153782263-8ac97360-fb64-4880-92ea-44bce93105a7.png">

I verified that its creation is in the /opt/otobo/scripts/database/otobo-schema.xml file but it does not appear in the /opt/otobo/scripts/database/otobo-schema.mysql.sql file

**Comment by joserribeiro26** [comment]
https://user-images.githubusercontent.com/475022/153782624-41f9525b-54c3-4d00-9383-82ce0632da1f.mov

**Comment by svenoe** [comment]
Hi José,

with my test installation this works and the table is present in scripts/database/otobo-schema.xml. For the moment I would almost exclude the possibility that there is an error with its creation (I at least never had something like this occur with any other table).

Is it possible, that you for some reason (a wrong docker container or so), are using a 10.0 database? And I did understand you correctly that you did a completely new installation and not an update? Was the system clean?

Best regards, Sven

**Comment by bschmalhofer** [comment]
I also think that some mixing up of versions must have occurred. AFAIK there is no _/opt/otobo/scripts/database/otobo-schema.mysql.sql_ file in OTOBO 10.1. _installer.pl_ only uses the XML-file for table creation.

**Comment by joserribeiro26** [comment]
I don't know exactly where I went wrong, but since it's a staging environment, I reinstalled and everything worked as it should.

I'll close the bug, it was my mistake.
