### ISSUE TITLE
Log level for communication_log_object_entry

### ISSUE THREAD

**Issue by TorstenEhrhardt** [RotherOSS/otobo#1616]
The communication_log_entry table is filled up with many unnecessary entries in case you have many postmaster filters. Each filter will create a new debug entry if it did not fit. This will also slow down the receiving process.
Having a new config variable for the log level in this log, will help to reduce the entries if you do not need them, especially for debug entries.

**Comment by svenoe** [comment]
Hi Torsten,

I agree that this certainly would be nice at times. On the other hand, the object log is at least neatly stored away and real errors should also be visible in the normal log, so aside from debugging (where this then is helpful), I don't know whether it is necessary to look in there, too often...

Thanks for the suggestion, I will add it to our list of wanted enhancements, Sven

(P.S.: If anyone is up for it, this would certainly be an easy topic for a pull request. ;)

**Comment by svenoe** [comment]
I will close this until someone starts to work on it, to not clutter the issues too much, it is visible in the Enhancements project.
