### ISSUE TITLE
Preview StopAfterMatch in AdminPostMasterFilter Overview

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1618]
For Debugging purposes it would be very helpful seeing the value of "StopAfterMatch" in the overview of "Action=AdminPostMasterFilter

![grafik](https://user-images.githubusercontent.com/89428719/154225781-eb69ea18-3d94-449e-921e-76a82ed6b629.png)
"

**Comment by svenoe** [comment]
Agreed - same for the ACLs, where I recently had the pleasure... ;)

**Comment by stefanhaerter** [comment]
PR merged. Moving the milestone and closing the issue.
