### ISSUE TITLE
Enter in Textinput (e.g. subject) cancels reply in CustomerTicketZoom.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1619]
The above. Please fix for 10.0 and merge.

**Comment by stefanhaerter** [comment]
Side Note: Core.Form.js contains a functionality to submit forms with Strg+Enter

https://github.com/RotherOSS/otobo/blob/4ac6f66e77932e81a0c16d69feb76ed6a4fea4f3/var/httpd/htdocs/js/Core.Form.js#L383
