### ISSUE TITLE
No error message if date is set to invalid date

### ISSUE THREAD

**Issue by Marios007** [RotherOSS/otobo#1632]
1. choosing a date like 31.2.2022 in CustomerTicketMessage (dynamic field type Date)
2. submit ticket
3. Submit failed and no error message is shown 

Please show a error message that date is invalid.

**Comment by svenoe** [comment]
This works as expected in 10.1 which we are about to release in its stable form. As there were quite some changes to how dynamic fields are rendered, it will not be backported to 10.0 though.

Best regards, Sven
