### ISSUE TITLE
Offer more configuration options in installer.pl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1633]
There are several SysConfig settings that need to be set after the installation. It would be convenient to set those directly in _installer.pl_. These extra setting would constitute an extra SysConfig deployment, not setup that is saved in _Kernel/Config.pm_ .

An example for such settings has been identified in #1217 :
> additionally it would be nice to have the choice of default redirect in the installer. But only if it is a selection, and this only if we can change the ValueType of the SysConfig to "Select" (and still use the OTOBO_CONFIG tag)

Therefore it would be nice to be able to set the following setting during installation:

- Frontend::DefaultInterface
- CustomerFrontend::Active
- PublicFrontend::Active

**Comment by svenoe** [comment]
This will be handled in a bigger overhaul of the installer.
