### ISSUE TITLE
Are the po-files needed in the Docker image?

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1635]
I was wondering about the _i18n_ files in the Docker image? Are they really useful? They constitute a significant part of the image size.

```
otobo@d50bf84ba735:/opt/otobo_install/otobo_next$ du -hs .
194M    .
otobo@d50bf84ba735:/opt/otobo_install/otobo_next$ du -hs i18n/
40M     i18n/
otobo@d50bf84ba735:/opt/otobo_install/otobo_next$ du -hs Kernel/Language
32M     Kernel/Language
```

**Comment by svenoe** [comment]
You are right, the directory i18n is not needed for running otobo (and thus for docker installations) at all. It is just used to store translations and generate the Kernel/Language files on our servers (without docker being involved).

**Comment by bschmalhofer** [comment]
Skip the directory _i18n_ in the _.dockerignore_ file. A bit of tidying in the ignore file. A quick check of a newly generated image showed that the web app is still working and that i18n is gone. Closing this issue.
