### ISSUE TITLE
Ticket from STDIN - problem

### ISSUE THREAD

**Issue by ebasse-prog** [RotherOSS/otobo#1642]
I have Sendmail selected in the reporting system. I should not be receiving messages from STDIN, and yet such a system has automatically sent out some messages that it does not want to receive.
How do I turn it off?
I have imap accounts set up in my system, from which I should only receive messages. 

![obraz](https://user-images.githubusercontent.com/65177524/156155455-d37a3e5d-c2d4-415a-9051-44a7eb995eb6.png)

![obraz](https://user-images.githubusercontent.com/65177524/156156121-dd0d9d65-7ded-4aaf-99eb-2af9ce57ffb8.png)

**Comment by svenoe** [comment]
Hi ebasse-prog,

for general questions around the usage of OTOBO please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/). Github is used only for development topics.
I will close this issue here, thanks for your understanding.

Best regards, Sven
