### ISSUE TITLE
Tile_FeaturedLink: open link in separate Browser tab

### ISSUE THREAD

**Issue by GritRother-OTOBO** [RotherOSS/otobo#1643]
It would be great if the Featured Link in the customer portal (and other links as well) would point to a new Browser tab by default instead of being opened in the same tab as it is now.

**Comment by svenoe** [comment]
I don't think having this behaviour in general is wanted. For the Featured Link I would suggest adding an option to the SysConfig, which will set whether we add `target="_blank"` (open it in a new tab) or not.

**Comment by svenoe** [comment]
Was done in 10.1.1.
