### ISSUE TITLE
ITSM-CIAttributeCollection Functionalities should be part of OTOBO

### ISSUE THREAD

**Issue by acorderor** [RotherOSS/otobo#1647]
There is a package to extend the use of the CMDB in OTRS and was widely use by our users, although I have not been able to see something similar in OTOBO, I was able to migrate the package and install it in my first installation of OTOBO 10.0.x. Is it posible to make that package part of OTOBO 10.x or OTOBO 11.x

**Comment by bschmalhofer** [comment]
Improving the CMBD is one of the goals for OTOBO 11. The functionality covered in https://opar.perl-services.de/package/C/CA/CAPEIT/ITSM-CIAttributeCollection is on our radar. But it might be that not the complete functionality will be covered or some things will be different.
