### ISSUE TITLE
Notify last Owner who is not "- -", if followUp happens on free ticket.

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1653]
With the new changes on how tickets are handled when they are freed and assgined to "- -" a problem occurs that no notification is send to relevant agents if a followUp happens. 

Nice would be to notify the last actual owner about events on the ticket, so no requests are missed.

**Comment by StefanRother-OTOBO** [comment]
Hi,
Currently, this function is not available and is actually not intended. Either the owner is still stored, in which case a follow-up notification can be sent to unlocked tickets, or the ticket no longer belongs to anyone, in which case there can be no notification. My recommendation would be to simply remove the "Ticket follow-up notification (unlocked)" notification under Admin -> Ticket Notifications.
