### ISSUE TITLE
GenericInterface: PATCH and PUT requests fail

### ISSUE THREAD

**Issue by reneeb** [RotherOSS/otobo#1657]
The transport class HTTP::REST tries to get the value for the POSTDATA param. But for PATCH and PUT requests that param does not exist. The body is stored in PATCHDATA/PUTDATA.

See PR #1656

**Comment by bschmalhofer** [comment]
This bug seems to have been introduced in rel-10_1. In rel-10_0 the content was read from STDIN which seems to have worked fine for PUT and PATCH too.

@reneeb : please go ahead and merge the PR

**Comment by bschmalhofer** [comment]
TODO:

- [x] add tests for PATCH and PUT

**Comment by bschmalhofer** [comment]
Tests were added. Closing this issue again.
