### ISSUE TITLE
Wrong Link in navigation bar for reports

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1666]
When you create a new report and try to go back to the report overview, the link doesnt work and you receive an error:

<img width="685" alt="Bildschirmfoto 2022-03-11 um 12 57 29" src="https://user-images.githubusercontent.com/89428719/157863096-652d5563-2887-4b41-8623-f1c41b76ab6f.png">

Backend ERROR: OTOBO-CGI-82 Perl: 5.34.0 OS: linux Time: Fri Mar 11 11:58:56 2022

 Message: Keine Subaction erhalten!

 RemoteAddress: XXX
 RequestURI: /otobo/index.pl?Action=AgentStatisticsReports

 Traceback (21): 
   Module: Kernel::Modules::AgentStatisticsReports::new Line: 38
   Module: Kernel::System::Web::InterfaceAgent::Content Line: 1227
   Module: Kernel::System::Web::InterfaceAgent::Response Line: 1321
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 200
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 170
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 156
   Module: Plack::Middleware::HTTPExceptions::try {...}  Line: 20

**Comment by bschmalhofer** [comment]
This should be implemented analogous to AgentStatistics frontend. For that frontend the breadcrumb path is set up in the template files.
```
      [% BreadcrumbPath = [
            {
                Name => Translate('Report Management'),
                Link => Env("Action"),
            },
        ]
    %]

```
However there seems to be obsolete setup for `Breadcrumbpath` in _Kernel/Modules/AgentStatistics.pm_ . This should be cleaned up.

**Comment by bschmalhofer** [comment]
Fixed the breadcrumb path in the AgentStatisticsReports templates. The outcome looks good. Closing this issue.
