### ISSUE TITLE
rename reject auto response title

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1714]
In Action=AdminAutoResponse there is some grammatically eye-catching wording:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/87359203/162765631-1ed51133-6ab7-47ca-b420-5ee82370454f.png">

Action=AdminAutoResponse;Subaction=Change;ID=2 => default reject (after follow-up and rejected of a closed ticket) => "rejection" should be better

**Comment by stefanhaerter** [comment]
Closed with merging #3566
