### ISSUE TITLE
"Untitled!" Ticket

### ISSUE THREAD

**Issue by Manschk3rl** [RotherOSS/otobo#1723]
Hi,
If your create a ticket with only a dynamic field the ticket shows up as "Untitled!" in the CustomerDashboard. If you open up the ticket, it shows the correct title from the GenericAgent.
![3](https://user-images.githubusercontent.com/4741314/164240142-f48d3adc-74bb-4f90-b1ac-ff2b80284d83.png)
![4](https://user-images.githubusercontent.com/4741314/164240364-8df3ec95-b869-4bd1-96f4-e67b3716d55e.png)

Setup:
- OTOBO 10.1.2
- A Queue with only a Dynamic Field.
_(Subject, Body and Attachments are hidden. ACL: "PossibleNot" > "FormStd" > "Article" | "PossibleAdd" > "Form" > "AnyDynField")_
![1](https://user-images.githubusercontent.com/4741314/164238963-96f681a1-8aeb-4738-ae4b-8fd7d3657152.png)

- A GenericAgent which updates the title of the ticket to something
![2](https://user-images.githubusercontent.com/4741314/164239861-8162ebf7-a4bd-4f65-852a-4b915d08151a.png)

So i think its a bug because in OTOBO 10.1 you added the abillity to hide the Subject, Body and Attachments but you can't change the title from this ticket.

I found a interesting thing... If you create an ID in the "article"-Table in the DB with values like:
`INSERT INTO article
	(
		ticket_id,
		article_sender_type_id,
		communication_channel_id,
		is_visible_for_customer,
		search_index_needs_rebuild,
		create_time,
		create_by,
		change_time,
		change_by
	) VALUES (
		"339",
		"3",
		"3",
		"1",
		"0",
		"2000-01-01 08:00:0",
		"1",
		"2000-01-01 08:0:0",
		"1"
	);`
the ticket will show up correctly. But you cant open it anymore.
`Error creating DateTime object ( 'String' => undef ).`
`Missing parameter Year.`
`No such article (TicketID=339, ArticleID=1811)!`

**Comment by Manschk3rl** [comment]
If a agent adds a note, the ticket in the customerdashboard shows up correctly

**Comment by svenoe** [comment]
Hey Manschk3rl,

sorry for the long delay, we are quite busy as most of the time...

Without looking at it in the code, I would guess, that the ticket list shows the subject of the last article, not the title of the ticket (which makes some sense). If I'm not totally wrong, this should not have changed from OTRS times (where it should be reproducible via a process ticket which the agent starts). Anyhow, I agree that for this case, it would be nice, to have a "if no subject, try the title" there. Should be a small change.

Best, Sven

**Comment by svenoe** [comment]
Hi Manschk3rl,

we discussed this a bit and decided to leave it like that for now. The background here is, that the title can hold information which the CustomerUser should not see. (If a ticket is opened with an article not visible to the customer, the title is still set, thus OTOBO checks whether there are articles visible to him or her, and shows their subject, usually.)

Even though I agree that for most cases where the ticket title is set explicitely in cases like yours, the customer will be allowed to see it and it would be nicer, this is just not certain. By changing this behaviour within some patch, maybe some systems would be affected.

We might think on a solution for this again, though - I will add it to our project list for now.
Best regards, Sven

**Comment by Manschk3rl** [comment]
Hi,

OK, thank you for the information. I will try to build a kind of trigger for our system to solve the "problem" for us.

**Comment by stefanhaerter** [comment]
If I understand it correctly, this should be solved with #2015 for 11.0. Removing the issue from the wishlist.

**Comment by bschmalhofer** [comment]
Reopening, as the issue was moved out of the wishlist.

**Comment by stefanhaerter** [comment]
Are there any objections against the fix for #2015?
