### ISSUE TITLE
upgrade fullcalendar.js to 5.11.3, remove moments.js

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1725]
There is a recommendation to move away from moments.js, https://momentjs.com/docs/#/-project-status/. Consider doing so.

**Comment by bschmalhofer** [comment]
See also #1722

**Comment by daxim** [comment]
Replacement is <https://fullcalendar.io/docs/luxon2>, but that requires upgrading Fullcalendar to v5 first, which doesn't have the dependent `fullcalendar-scheduler` as a single package any more: https://fullcalendar.io/docs/v4/upgrading-from-v3#scheduler

**Comment by bschmalhofer** [comment]
@daxim : Are fullcalender and luxon2 the JS libraries that you would use for new projects? If so, than I would second to upgrade to the current versions. If you would use other libraries, then I would evaluate first whether OTOBO can migrate to alternative libraries.

**Comment by daxim** [comment]
Luxon definitely, cursory survey about calendaring is inconclusive, looks all the same to me without getting into the weeds. I think in order to minimise disruption it makes sense to stick with Fullcalender.

**Comment by bschmalhofer** [comment]
Browsing the [fullcalendar](https://fullcalendar.io) website I found that support for time line views and resource views are premium features. They can be used in OTOBO as OTBOBO is under GPL v3. See https://fullcalendar.io/license. 
The plugin structure has changed a bit, see https://fullcalendar.io/docs/plugin-index. But that just means that different libraries have to be selected. There is support for https://fullcalendar.io/docs/luxon2, which can replace moments.js.

**Comment by bschmalhofer** [comment]
Closing, as the convention is that issues in the wishlist should be closed.
