### ISSUE TITLE
Improve CustomerTicketCategories.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1738]
We will change the ticket categories slightly and make some improvements:

- Add Service and State also to CustomerTicketZoom
- Make translations a SysConfig-Option rather than translating just Service and State hardcoded (**Attention!** This means if you are using this feature since 10.1.3 you will have to add this to your SysConfig!)
- Add a "Link"-feature, similar to the DynamicField Links
- Add a feature to edit the text shown
- Add Type (requested below)

**Comment by otoKreutz** [comment]
Is it possible to add the Type to the CustomerTicketCategories as well?

**Comment by svenoe** [comment]
Yes, we can include this.
