### ISSUE TITLE
Fix SMIME for newer openssl versions.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1739]
We have to adjust some code for newer openssl versions (3.0.2 which is shipped with Ubuntu 22.04):

- [x] The Fingerprint is not parsed correctly
- [x] scripts/test/SMIME/ConvertCertFormat.t fails which is at least partly due to openssl being able to directly use the der-format. We have to check whether this makes the test obsolete, or we have to change the check.

The latter can be found here https://github.com/RotherOSS/otobo/blob/1a8f405b3750198ebd818e6ea35f33217ee60a0e/Kernel/System/Crypt/SMIME.pm#L874-L876 where the newer openssl just does not return any error with the "wrong" format, and thus the method returns.

**Comment by bschmalhofer** [comment]
A migration guide of openssl 1.1.x  to opensssl 3.0.x is available at https://www.openssl.org/docs/man3.0/man7/migration_guide.html

The relevant part seems to be:

> The openssl commands that read keys, certificates, and CRLs now automatically detect the PEM or DER format of the input files so it is not necessary to explicitly specify the input format anymore. However if the input format option is used the specified format will be required.

**Comment by bschmalhofer** [comment]
Getting a test system up an running was way harder than expected:

- Ubuntu 22.04 in VirtualBox failed because of disk space ran out
- Installing openssl 3.0.3 from source failed because the web container did not start up
- Finally created a Perl base image with Debian sid, which has openssl 3.0.3 included

@svenoe: Is there a virtual otobo installation that runs under Ubuntu 22.04 ? This would have been an easier approach.

**Comment by bschmalhofer** [comment]
With openssl 3 we could propably get by with storing DER formatted certificates in the store. But let's stay consistent and convert all certificates to PEM. 
The first fix is to require `-inform pem` when checking for PEM formats.

There is another changed behavier when checking whether a pfx file is a der file. openssl 1 immediately gave an error in that case. openssl 3 ask for a password first, which halts the whole test script, as it waits for console input.

OpenSSL 1:

bes:~/devel/OTOBO/otobo (issue-#1739-openssl_3)$ openssl version                                                                                                       OpenSSL 1.1.1f  31 Mar 2020                                                                                                                                                 bes:~/devel/OTOBO/otobo (issue-#1739-openssl_3)$ openssl x509 -inform der -in scripts/test/sample/SMIME/SMIMECertificate-1.pfx -noout                                       unable to load certificate                                                                                                                                                  139832142112064:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1149:                                                             139832142112064:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:309:Type=X509_CINF                                    139832142112064:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=cert_info, Type=X509                    bes:~/devel/OTOBO/otobo (issue-#1739-openssl_3)$ openssl x509 -inform der -in scripts/test/sample/SMIME/SMIMECertificate-1.pfx -noout --passin pass:'a passphrase'          unable to load certificate                                                                                                                                                  139838789682496:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1149:                                                             139838789682496:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:309:Type=X509_CINF                                    139838789682496:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=cert_info, Type=X509                    bes:~/devel/OTOBO/otobo (issue-#1739-openssl_3)$            
                                                                                                                

OpenSSL 3:

otobo@8238ae993b3d:~$ openssl version                                                                                                                                       OpenSSL 3.0.3 3 May 2022 (Library: OpenSSL 3.0.3 3 May 2022)                                                                                                                otobo@8238ae993b3d:~$ openssl x509 -inform der -in scripts/test/sample/SMIME/SMIMECertificate-1.pfx -noout                                                                  **Enter pass phrase for PKCS12** import pass phrase:                                                                                                                            Could not read certificate from scripts/test/sample/SMIME/SMIMECertificate-1.pfx                                                                                            C0128307437F0000:error:16000071:STORE routines:try_pkcs12:error verifying pkcs12 mac:../crypto/store/store_result.c:564:empty password                                      Unable to load certificate                                                                                                                                                  otobo@8238ae993b3d:~$ openssl x509 -inform der -in scripts/test/sample/SMIME/SMIMECertificate-1.pfx -noout --passin pass:'a passphrase'                                     Could not read certificate from scripts/test/sample/SMIME/SMIMECertificate-1.pfx                                                                                            C012BB4E5A7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()                                                                                                                                                   Unable to load certificate                                                                                                                                                  otobo@8238ae993b3d:~$

**Comment by bschmalhofer** [comment]
And another divergence. It looks like the sample pfx files were created by obsolete algorithms, e.g. RC2-40-CBC . These algorithms are still support, but they must be enabled with the option `-legacy`. See https://www.openssl.org/docs/manmaster/man7/migration_guide.html#Legacy-Algorithms . My gut feeling is that these algorithms are deprecated for a reason and should not be enabled by default, if ever. Let's clarify this in a dedicated issue.

```

otobo@8238ae993b3d:~$ openssl pkcs12 -in scripts/test/sample/SMIME/SMIMECertificate-1.pfx -noout -nomacver -passin file:scripts/test/sample/SMIME/SMIMEPrivateKeyPass-1.asc Error outputting keys and certificates
C082B234A57F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

```

**Comment by bschmalhofer** [comment]
The test suite passed with both, openssl 1 and openssl 3. Closing this issue.
