### ISSUE TITLE
Don't try to upgrade packages that are not listed in any online respository

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1743]
On Upgrading, OTOBO tries to upgrade all packages as well. Packages that are not listed in any online respository will also tried to be upgraded, but run in a long timeout. It would be nice to lower the timeout duration or check if the packages are available online and only then upgrade the package.

**Comment by bschmalhofer** [comment]
Did not encounter this when running the update process for OTOBO 11.0.x which does not have any packages in the online repositories. Assuming that this has been fixed in the mean time. Closing this issue.
