### ISSUE TITLE
UnitTests: Reactivate Selenium tests

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#175]
Looks like testing with Selenium is deactivated.

**Comment by wollmers** [comment]
If Mojolicious is installed, `Mojo::UserAgent` can be used for many tests under perlish test infrastructure.

**Comment by bschmalhofer** [comment]
Yes, we could also create a Mojolicious wrapper for otobo.psgi and use https://metacpan.org/pod/Test::Mojo.

**Comment by svenoe** [comment]
There are quite a number of Selenium tests present however, which should be used again, at some point!
(If there are reasons to swap to Mojolicious for newer tests I'm not against it. It would just be a waste if we didn't use what's there already, I figure...)

**Comment by bschmalhofer** [comment]
Selenium testing is activated by pasting Selenium configuration into Config.pm

    # ---------------------------------------------------- #
    # setting for running Selenium tests under Docker      #
    # ---------------------------------------------------- #
    $Self->{'SeleniumTestsConfig'} = {
        remote_server_addr  => 'localhost',
        port                => '5555',
        platform            => 'ANY',
        browser_name        => 'firefox',
        extra_capabilities => {
            marionette     => \0,   # Required to run FF 47 or older on Selenium 3+.
        },
    };

Current the setup is such that a Selenium or PhantomJS server is required. On first sight it looks like "Without Standalone Server" variant would be more convenient. Trying that variant looks like a worthwhile experiment. The prerequisite is that `geckodriver` is installed. Gecko provodis the protocol Marionette for remote controlling the Browser.

**Comment by wollmers** [comment]
@bschmalhofer Where are the Selenium tests running in the above case? In the docker host? I guess, because it needs the binary of FireFox.

Tried yesterday to get a Selenium client running via Perl on Mac OS. Specifying `firefox` doesn't work on Mac OS even with full path (wich starts FF from the command line). The modules for Selenium on Cpan do not look well maintained. 

Using PhantomJS (without FireFox) is very slow for me even with a local website reacting in under 0.1 secs.  Seems to start PhantomJS for each request or has a builtin delay.

```
#!perl

use strict;
use warnings;

use Selenium::PhantomJS;

my $driver = Selenium::PhantomJS->new(
	'binary' => '/usr/local/bin/phantomjs',
);

$driver->get('http://127.0.0.1:3000/line/ONB_aze_19110701_001.jpg_tl_43.gt.txt');
print $driver->get_title(),"\n";
$driver->quit();
```

```
$ time perl selenium_phantonjs.t

Killing Driver PID 16714 listening on port 58650...

real	0m2.956s
user	0m0.214s
sys	0m0.088s

$ time wget http://127.0.0.1:3000/line/ONB_aze_19110701_001.jpg_tl_43.gt.txt
--2020-09-10 14:47:34--  http://127.0.0.1:3000/line/ONB_aze_19110701_001.jpg_tl_43.gt.txt
Verbindungsaufbau zu 127.0.0.1:3000 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 7408 (7,2K) [text/html]
Wird in »ONB_aze_19110701_001.jpg_tl_43.gt.txt« gespeichert.

ONB_aze_19110701_001.jpg_tl_ 100%[===========================================>]   7,23K  --.-KB/s    in 0s      

2020-09-10 14:47:34 (442 MB/s) - »ONB_aze_19110701_001.jpg_tl_43.gt.txt« gespeichert [7408/7408]


real	0m0.114s
user	0m0.004s
sys	0m0.009s

```

3 seconds for a simple request are not acceptable. Will try the Linux/Docker variant.

**Comment by bschmalhofer** [comment]
@wollmers, I just started looking into Selenium testing for OTOBO. It is not clear to me how well these tests were maintained in OTRS. 
My preference is that the tests are running in the otobo_web_1 container, just like the other tests. Preferably without having to use another container.

**Comment by svenoe** [comment]
Starting with https://github.com/OTRS/otrs/commit/8c6ae2b02ce29be4e38232e443e733345e2b3a38 there have been a number of commits around Selenium which I have not implemented in otobo yet. If we are at a point were we actively use Selenium testing, we should have a look at them at least. (Can be done by me.)

**Comment by bschmalhofer** [comment]
@svenoe I have cherry-picked @mgruner changes to _Kernel/System/UnitTest/Selenium_ .
Selenium::Remote::Driver is loaded only when running the unit tests. Therefore removed _Kernel/cpan-lib/Selenium_ and added Selenium::Remote::Driver as an optional dependency, just like Test2::Suite. Clone is now an implicit dependency.

**Comment by svenoe** [comment]
> @svenoe I have cherry-picked @mgruner changes to _Kernel/System/UnitTest/Selenium_ .
> Selenium::Remote::Driver is loaded only when running the unit tests. Therefore removed _Kernel/cpan-lib/Selenium_ and added Selenium::Remote::Driver as an optional dependency, just like Test2::Suite. Clone is now an implicit dependency.

Seems reasonable. Having smaller standard installations is generally a good thing, I guess. :)

**Comment by bschmalhofer** [comment]
Next step: try to find a setup that does not use an extra server and works in the OTOBO Docker image.

**Comment by bschmalhofer** [comment]
Here are some notes what could work. Mostly deduced from reading https://github.com/SeleniumHQ/docker-selenium .

- add an override file that add a selenium server running on port 4444 to the docker internal network
- use the image selenium/standalone-firefox:latest
- expose the VNC port 5900 so that we can watch the automated browser
- share the volume /dev/shm because Firefox wants it 
- TestHTTPHostname should already be fine in otobo_web_1
- figure out whether    extra_capabilities  =>  { marionette => 1 } is required or useful
- enhance update.sh to enable the Selenium container on the command line

**Comment by bschmalhofer** [comment]
Testing with Selenium kind of works. Crome is starting up as visible with Remmina using the location localhost:5900 and the VNC password 'secret'. But simple commands like 'delete_all_cookies()' and 'get_page_source()'  run into a timeout. Executing JavaScript looks fine too.

TODO:

- [x] investigate why the timeouts happen

Using the Docker image for Selenium 3 fixed the problem.

**Comment by bschmalhofer** [comment]
For some reason sometimes the error '-' is emitted.

TODO:

- [ ] fix false failure like e.g. in scripts/test/Selenium/Agent/Admin/Admin.t

**Comment by bschmalhofer** [comment]
Selenium tests can be run on Chrome in the Docker image. Remaining failures are handled on #682. Closing this issue.

**Comment by bschmalhofer** [comment]
Just for the record, regarding #2387, phantomjs is no longer, or maybe has never been, used for running tests in OTOBO.
