### ISSUE TITLE
Translation for AcceptGDPR

### ISSUE THREAD

**Issue by reaperfromhell** [RotherOSS/otobo#1754]
Hello,

All translation files seem to have the wrong translation for the GDPR message, as it shows up in German:
"Mit einem Klick erkläre ich meine Zustimmung".
I did a quick grep for the string and it pretty much shows up on all the files.

**Comment by svenoe** [comment]
Hi reaper,

you are right, a German string snuck into the source code. We will fix that.

Best regards

**Comment by svenoe** [comment]
Done, thanks for letting us know. We will update the language files for weblate within this day.
