### ISSUE TITLE
AgentTicketZoom: Keep Pending Time in Ticket categorization dialogue

### ISSUE THREAD

**Issue by GritRother-OTOBO** [RotherOSS/otobo#1756]
At the moment, a set ticket pending time is lost / set back to the system standard when opening the ticket categorization dialogue. It would be great if the existing setting could be maintained :)

**Comment by stefanhaerter** [comment]
Current state: #1832 is ready, but there is also a package which has this functionality. It has to be decided if the package is to be used or the PR should be merged.

**Comment by stefanhaerter** [comment]
Closed with merging #1832
