### ISSUE TITLE
IMAPClient->get doesn't exist

### ISSUE THREAD

**Issue by niccord** [RotherOSS/otobo#1787]
Hi everyone,
if you have an error in the PostMaster object creation while downloading an email via the `Kernel::System::MailAccount::IMAPTLS` package, then a not supported call in the Mail::IMAPClient API is called since there is no method `get` in the client:
``` perl
412            my $Lines = $IMAPOperation->( 'get', $Messageno, );
```

You can check the API here: https://metacpan.org/pod/Mail::IMAPClient

The variable `$Lines` is not used but in the `Kernel::System::MailAccount::IMAP` class, it uses the `Net::IMAP::Simple` library which, in the `get` method, causes a possible side-effect in fetching the email, check here: https://metacpan.org/pod/Net::IMAP::Simple#get

In my opinion, the line itself can be removed, but it's your call, obviously 😄

**Comment by bschmalhofer** [comment]
Hi Nicola,
thanks for your report, even if it took some time for us to react.
I removed the incorrect call for OTOBO 11.0, just in case there are side effects that I did not see.

Closing this issue.
