### ISSUE TITLE
Calendar Appointments not visible when SessionUseCookie not activated

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1813]
When the System Configuration setting "SessionUseCookie" is not activated, you can not see any appointments in any of your calendars.
If you create them, they are created properly (e.g. when you export the calendar you see them in the text file), but they are not shown.
When activating SessionUseCookie, the appointments can be seen.

Tested in 10.1.4

**Comment by svenoe** [comment]
Doesn't have a high prio in my eyes. We will have to have a look if there are technical reasons for this, maybe.

**Comment by StefanAbel-OTOBO** [comment]
I disagree, as you can't use the whole calendar module in case you have this option activated - or even worse, you rely on the calendar and don't see an appointment you should be attending.

**Comment by stefanhaerter** [comment]
Reason seems to be in https://github.com/RotherOSS/otobo/blob/rel-10_1/var/httpd/htdocs/js/Core.Agent.AppointmentCalendar.js#L523. In my oppinion, https://github.com/RotherOSS/otobo/blob/rel-10_1/var/httpd/htdocs/js/Core.AJAX.js#L201 (function GetAdditionalDefaultData) should be used here, but currently, it is a private function (meaning it is only available within Core.AJAX.js).

**Comment by stefanhaerter** [comment]
Merged.
