### ISSUE TITLE
Add indication for inherited Services

### ISSUE THREAD

**Issue by ExecuteGK** [RotherOSS/otobo#1816]
When working with default customer user services, the following situation can arise and cause confusion:

Services in default customer user services:
SERVER::NEW SERVER
SERVER::REMOVE SERVER
SERVER::MODIFY SERVER

Services for a specific Customer User:
SERVER::NEW SERVER

The resulting active services for the Customer User are the explicitly set services ONLY. No additional services from the default services are added.

I recommend to add either an option to activate / deactivate inheritance of the default services, or to add a warning that by selecting explicit services, ALL default services will be overwritten for that Customer user.

This will help troubleshooting visibility issues and clarify the consequences of setting explicit services for customer users.

Thank you

Sebastian Dietz

**Comment by svenoe** [comment]
Hi Sebastian,

thanks for your suggestion. I see that counting customer user specific services as additive could be a better version for some systems. In bigger environments probably you would want to have the possibility to set services based on CustomerUserGroups even. I will put in in the list of suggestions, as we are quite booked, atm, and I don't see this having a really high priority, it probably will need some time, until we really start working on those things.

Best regards, Sven
