### ISSUE TITLE
Add debug capability for ACLs

### ISSUE THREAD

**Issue by ExecuteGK** [RotherOSS/otobo#1817]
Add a debug capability for ACLs.

Troubleshooting ACLs is quite difficult. A feature that can be activated for specific user (customers or agents) and specific modules would be very helpful in solving ACL issues.

Details to be displayed should be the ACLs triggered and the values evaluated.

Regards,

Sebastian Dietz

**Comment by svenoe** [comment]
Hi Sebastian,

please search for TicketACL::Debug in the SysConfig. You will get more details logged if you enable it (note that the MinimumLoglevel has to be low enough for the TicketACL-Loglevel).

I hope that helps, best regards, Sven
