### ISSUE TITLE
code policy - prohibit unused variables

### ISSUE THREAD

**Issue by daxim** [RotherOSS/otobo#1818]
https://github.com/RotherOSS/CodePolicy/issues/74 exposed a number of policy violations.

**Comment by bschmalhofer** [comment]
The output of
`../CodePolicy/bin/otobo.CodePolicy.pl --plugins +TidyAll::Plugin::OTOBO::Perl::PerlCritic -a --processes 1 1>critic.out`
looks good now. Closing this issue.
