### ISSUE TITLE
Permission for AgentTicketZoom falsely revoked after setting up ACLs for Agent Ticket Print

### ISSUE THREAD

**Issue by doorbird-tech** [RotherOSS/otobo#1824]
I have set up the following ACLs:

**060 - Hide Print Button for all:**
Match:
 - User
  -- Role → regex → .+
  
Possible Not:
- Action
 -- exact match → AgentTicketPrint

**061 - Show Print Button for stats and admin:**
Match:
 - User
  -- Role → regex → admin|stats
  
Possible:
- Action
 -- exact match → AgentTicketPrint
 
As soon as I set the 61 to valid. I can no longer get Zoom on any Tickets ("This ticket does not exist, or you do not have permission" etc.). 

Having only 060 activated works as intended, though, and hides "Print" from both Misc and the Compose section. Only when I also activate 061...

Otobo Version 10.1.1

**Comment by svenoe** [comment]
Possible excludes any other Actions. For what you want please use PossibleAdd.

Also please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) with questions, though, github should stay reserved for the development...

Thanks, and best regards, Sven

Edit:
User: [NotRegex]admin|stats
PossibleNot: AgentTicketPrint

Is an all in one solution ;)
