### ISSUE TITLE
Filter valid and unvalid Agents in Action=AdminUser

### ISSUE THREAD

**Issue by geralwo** [RotherOSS/otobo#1828]
For organisations with many agents, it would be really helpful to have the ability to hide valid/unvalid agents from the overview.

Maybe with a checked checkbox to only show valid agents as default.
Unchecking the checkbox shows all agents independed of their valid state.

**Comment by stefanhaerter** [comment]
I would suggest to think about including filters here, like the ones that are already present in the ticket overview screens. @svenoe what do you think?
