### ISSUE TITLE
Order of libs in Kernel/System/UnitTest.pm is incorrect

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#1829]
In Kernel/System/UnitTest.pm, L.232, the libs in TAP::Harness-new() are in the following order:

lib => [ $Home, "$Home/Kernel/cpan-lib", "$Home\Custom" ],

This prevents loading files located in Custom, so the order should be corrected.

**Comment by bschmalhofer** [comment]
@stefanhaerter : Yes, please fix this.

**Comment by stefanhaerter** [comment]
Fix merged (https://github.com/RotherOSS/otobo/pull/1830)
