### ISSUE TITLE
UnitTests: Failure for AdminLog in scripts/tests/Frontend/Basic.t

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#183]
Seems to occur under PSGI and under Apache.

`not ok 322 - Module AdminLog status code (http://localhost:5000/otobo/index.pl?Action=AdminLog) (is '500' should be '200')`

**Comment by svenoe** [comment]
Due to an erroneous interaction with missing time stamps in log entries. Fixed by reverting DateTime changes: bef967ac8c7be7597ca6428ba42ce341cabe0c09
