### ISSUE TITLE
GenericAgent CMD missing

### ISSUE THREAD

**Issue by Manschk3rl** [RotherOSS/otobo#1834]
Hi,
i updated from otobo 10.1.2 to 10.1.4. Now my scripts don't work anymore. After looking around a bit I found out that under "genericagent" > "execute ticket commands" the menu item "cmd" is missing. I didn't find anything in the changelog or an alternative so I guess it's a bug.
https://doc.otobo.org/manual/admin/10.1/en/content/processes-automation/generic-agent.html#execute-ticket-commands

**Comment by Manschk3rl** [comment]
![image](https://user-images.githubusercontent.com/4741314/177322636-b3cdf627-42ce-413a-b4a0-aea07b4bdee2.png)

Now:
![image](https://user-images.githubusercontent.com/4741314/177322553-6071473f-c44c-4cd6-8132-c840d4b441b1.png)

**Comment by svenoe** [comment]
Hi Manschk3rl,

it is intended and can be activated again: https://otobo.de/en/otobo-10-1-3/#Admin-Schwachstelle

The whole topic is not completely settled yet, OTRS had a lot of places like this - in hindsight it might have been better to just change all of it with the release of the version 11, on the other hand this way people are at least aware...

Best regards
