### ISSUE TITLE
DynamicField Database - Type MSSQL ODBC 

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#1838]
i get the error, when i will type some inputs in the DynamicField:
`malformed or illegal unicode character in string [\xfchle PM6 al], cannot convert to JSON at /opt/otobo/Kernel/System/JSON.pm line 105.
`
OTOBO 10.0.16

**Comment by StefanRother-OTOBO** [comment]
Hi Olli,

I think you need to configure the right charset (utf-8) inside freetds.conf or odbc.conf.
Did you try this?

Untested:

1.) Open freetds.conf.
2.) add client charset = UTF-8 in your connection settings.

Thanks,

Stefan
