### ISSUE TITLE
Calendar feature - Add an appointment to multiple calendars

### ISSUE THREAD

**Issue by mbagnus** [RotherOSS/otobo#1839]
Currently,
when you create a new appointment on OTOBO calendar (either from a ticket view or directly in calendar),
you can put the appointment only in one calendar, even if the selection box seems to be able to accept multiple selection.

Is it possible to enable the multiple selection in the calendar box, and add the appointment to all selected calendars?

Thank you

**Comment by bschmalhofer** [comment]
Hi @mbagnus,
I have looked at the code and the intent is clear. Only creation in a specific calendar is supported. I agree that the appearance is a bis misleading, with the star that can be used to remove the single selection. But that same layout is used in various parts of OTOBO, so it is a consistent interface.
For consolation, there is an easy way to copy an appointment to another calendar.

1.  Open the Edit-View of the appointment
2. Choose another calendar
3. Save the changed  calendar with "Copy". In this way the appointment will still be in two calendars

![Screenshot 2022-10-31 at 16-33-35 Overview - Calendar - OTOBO 10](https://user-images.githubusercontent.com/46019/199048678-e6285865-4cda-4cfa-a302-256140084b9d.png)

**Comment by bschmalhofer** [comment]
Closing this issue. Note that questions and suggestions on how to work with OTOBO can also be posted in the [OTOBO Forum](https://otobo.de/en/forums/otobo/otobo-forum/).
