### ISSUE TITLE
UnitTests: Make test work with HttpType = https

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#184]
If that is not easily done, then set HttpType = http for the UnitTest scripts.

**Comment by stefanhaerter** [comment]
Is this issue a candidate for the wishlist or is this an active topic?

**Comment by bschmalhofer** [comment]
Hi @stefanhaerter,

this is just a nice to have feature. The intent was to make the unit test more realistic, as in production OTOBO is usually accessed via HTTPS. From my side, this issue can be moved to the wishlist.

**Comment by stefanhaerter** [comment]
Then I will do so - if the decision is to implement it somewhen, it can easily be brought back.

**Comment by bschmalhofer** [comment]
See also #1815
