### ISSUE TITLE
Docker Versions for ARM64

### ISSUE THREAD

**Issue by cchance27** [RotherOSS/otobo#1851]
I wanted to run otobo on a Arm64 but it seems theirs no copy of the current images built for arm?

**Comment by bschmalhofer** [comment]
Hi Chris,
yes, there are no images prepared for Arm64. I also haven't looked into what would be needed to create them.
But, I suppose that roll your own images. The Docker files are located in https://github.com/RotherOSS/otobo. I also use the script _bin/docker/build_docker_images.sh_ for building locally.

Please keep us posted on your progress. Out of curiosity, what is the use case for running on Arm64?

Best regards,
    Bernhard

**Comment by bschmalhofer** [comment]
Closing, as the convention is that issues in the wishlist should be closed.

**Comment by flozano** [comment]
https://github.com/RotherOSS/otobo/pull/5472 proposed a PR for consideration, it's really convenient to have arm images when working with macs and for deploying on AWS graviton for example.
