### ISSUE TITLE
Docker + OIDC doesn't work behind a Proxy

### ISSUE THREAD

**Issue by astapelfeld** [RotherOSS/otobo#1852]
I'm getting this error message when I try to use OIDC Auth (AzureAD) behind a proxy:

`[Error][Kernel::System::OpenIDConnect::_ProviderDataGet][599] Error in retrieving OpenIDConfiguration: 500 Can't connect to login.microsoftonline.com:443`

I created a file .docker/config.json with the proxy config in the home directory of the user that deploys the containers. These settings are passed to the containers as environment variables, but Perl doesn't seem to be picking these settings up.

Not really good at Perl here, but I checked the file otobo/Kernel/System/OpenIDConnect.pm and found this line twice:

`my $UserAgent = LWP::UserAgent->new();`

If I add my proxy directly after the creation of the variable $UserAgent, it works fine:

`$UserAgent->proxy(https => 'http://<myproxy>');`

This may be a better fix: https://metacpan.org/pod/LWP::UserAgent#env_proxy  or maybe I just have to add the settings somewhere else? In that case I would appreciate your help :)

**Comment by svenoe** [comment]
Hi astapelfeld,

spontaneously I would say it is probably a good idea to have a configurable proxy specific to the OIDC server anyways. We have not implemented this, and it would be the right place. We will add an option for this to the Config, I think.

Best regards, Sven

**Comment by bschmalhofer** [comment]
Yes, I would second to activate the proxy specific for the openid connect. Using the `https_proxy` environment variable might have unintended consequences.

**Comment by g0g11** [comment]
@astapelfeld Did your OAuth implementation worked? We are currently struggling to implement OAuth (Azure AD) in Otobo. I couldn‘t find any documentation how to do the config in Otobo. So it would be great if you can share some insights.

**Comment by astapelfeld** [comment]
> @astapelfeld Did your OAuth implementation worked? We are currently struggling to implement OAuth (Azure AD) in Otobo. I couldn‘t find any documentation how to do the config in Otobo. So it would be great if you can share some insights.

There are some comments in otobo/Kernel/System/Config/Defaults.pm. Just search for "OpenIDConnect".

My  config looks like this:

```
root@server01:/opt/otobo/Kernel/System# cat ../Config/Files/ZZZOpenID.pm
package Kernel::Config::Files::ZZZOpenID;
use strict;
use warnings;
no warnings 'redefine'; ## no critic qw(TestingAndDebugging::ProhibitNoWarnings)
use utf8;
sub Load {
    my ($File, $Self) = @_;
$Self->{AuthModule1} = 'Kernel::System::Auth::DB';
$Self->{AuthModule} = 'Kernel::System::Auth::OpenIDConnect';
$Self->{'AuthModule::OpenIDConnect::AuthRequest'}->{ResponseType} = [ 'code' ];
$Self->{'AuthModule::OpenIDConnect::AuthRequest'}->{AdditionalScope} = [
        qw/profile email/
    ];
$Self->{'AuthModule::OpenIDConnect::Config'}{ClientSettings} = {
        ClientID    => '<client_id>',
        RedirectURI => 'https://<hostname>/otobo/index.pl?Action=Login',
    };
$Self->{'AuthModule::OpenIDConnect::Config'}{ClientSettings}{ClientSecret} = '<secret>';
$Self->{'AuthModule::OpenIDConnect::Config'}{ProviderSettings} = {
        OpenIDConfiguration => 'https://login.microsoftonline.com/<tenant-id>/v2.0/.well-known/openid-configuration',
    };
$Self->{'AuthModule::OpenIDConnect::UID'} = 'sub';  };
    # Optionally enable user authorization via the id token - hashes can be used for complex claims
    $Self->{'AuthModule::OpenIDConnect::RoleMap'} = {
    'roles' => {
    '<AzureAD ObjectID of the Group>' => '<Role in Otobo'
    }
    };
    # Optionally enable user creation - this currently does not support complex claims; email is mandatory
    $Self->{'AuthModule::OpenIDConnect::UserMap'} = {
        email       => 'UserEmail',
        given_name  => 'UserFirstname',
        family_name => 'UserLastname',
    };
$Self->{'AuthModule::OpenIDConnect::Debug'}->{'LogIDToken'} = 1;
    return;
}
1;
```

If you are behind a http proxy, you have to add 2 lines in otobo/Kernel/System/OpenIDConnect.pm:

```
202-    }
203-
204-    my $UserAgent = LWP::UserAgent->new();
**205:    $UserAgent->proxy(https => 'http://<Proxy IP>:<Proxy Port>');**
206-    if ( $Param{ProviderSettings}{SSLOptions} ) {
207-        OPTION:
208-        for my $Key ( keys $Param{ProviderSettings}{SSLOptions}->%* ) {
--
594-            );
595-        }
596-    }
**597:    $UserAgent->proxy(https => 'http://<Proxy IP>:<Proxy Port>');**
598-
599-    my $Response = $UserAgent->get( $Param{ProviderSettings}{OpenIDConfiguration} );
600-    my $Content  = $Response->content;
```

**Comment by svenoe** [comment]
Probably when implementing, it would be good to also give the opportunity to add a proxy authorization, just as it is done in the generic interface. https://github.com/RotherOSS/otobo/blob/751c65ac86be2401774b59cac2a6e4fb9a3121a0/Kernel/GenericInterface/Transport/HTTP/REST.pm#L645-L664

We don't have special headers included to the request right now, so I would do this when the need arises for more people. For now I will add it to our enhancements project.
