### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by FusionCreations** [RotherOSS/otobo#1853]
I am not able to use email services of otobo. which is really bothering me and restricting the capabilities of otobo.
is there any help available ?

**Comment by svenoe** [comment]
Hi FusionCreations,

please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) for general questions. Github is for the development only.

In any case you will have to provide a more detailed description of what you are doing and where it fails.

Thanks for your understanding and best regards, Sven

**Comment by FusionCreations** [comment]
Thanks [svenoe](https://github.com/svenoe) 
will visit the forums
