### ISSUE TITLE
Hide the "Change password" box in CustomerPreferences when using OIDC

### ISSUE THREAD

**Issue by jambondeparme** [RotherOSS/otobo#1854]
When using OIDC to authenticate Customer users, the "Change password" box still appears in CustomerPreferences. 

Adding _OpenIDConnect_ to line 62 of Kernel/Output/HTML/Preferences/Password.pm seems to fix the issue:

```perl
61    # return on no pw reset backends
62    return if $Module =~ /(LDAP|HTTPBasicAuth|Radius|OpenIDConnect)/i;
```

**Comment by svenoe** [comment]
We won't include this right now at least. It is possible to just remove the password selection via disabling the sysconfig CustomerPreferencesGroups###Password and at least in principle we support having OIDC as well as standard authentication via password, if we use more than one AuthModule. Even though this is currently not really nice, for the moment I'd rather put effort into making this better than.
