### ISSUE TITLE
Fehlende Tabellen stats_report & data_storage nach Migration auf OTOBO >= 10.1

### ISSUE THREAD

**Issue by markus-gitdev** [RotherOSS/otobo#1863]
Hallo,

Wir haben heute ein OTRS 6, das auf einer Oracle-DB läuft auf eine aktuelle OTOBO 10.1.4 (weiterhin mit einer Oracle-DB) migriert und da ist uns unter anderem aufgefallen, dass die Tabellen ``stats_report`` und ``data_storage`` fehlen und daher das System Log mit Fehlermeldungen gefüllt wird.

Nach einer Recherche haben wir herausgefunden, dass diese beiden Tabellen mit 10.1 neu dazu gekommen sind, diese Änderungen bei Migrationen aber scheinbar nicht berücksichtigt wird.
Es wäre daher sinnvoll, dass entweder in der Dokumentation mitaufzunehmen (z.B.: "After successful migration to OTOBO versions greater or equal 10.1 the script ``/opt/otobo/scripts/DBUpdate-to-10.1.pl`` has to be executed." in ["Step 6: After Successful Migration!"](https://doc.otobo.de/manual/installation/10.1/en/content/migration-from-otrs-6.html#step-6-after-successful-migration)), oder das in die Migration automatisch mit aufzunehmen.

Für alle, die ebenfalls Fehlermeldungen wie ...
````
There was an error executing Execute() in Kernel::System::Console::Command::Maint::Stats::Reports::GenerateCron: DBD::Oracle::db prepare failed: ORA-00942: Tabelle oder View nicht vorhanden (DBD ERROR: error possibly near <*> indicator at char 21 in 'SELECT id, name FROM <*>stats_report WHERE valid_id IN (1)') [for Statement "SELECT id, name FROM stats_report WHERE valid_id IN (1)"] at /opt/otobo-10.1.4/Kernel/System/DB.pm line 770.
````
... bekommen, einfach als Workaround das Script ``/opt/otobo/scripts/DBUpdate-to-10.1.pl`` ausführen und das Problem ist behoben.

**Comment by bschmalhofer** [comment]
Hallo Markus,

ich vermute das die fehlenden Tabellen ein Effekt der wenig getesteten Migration von Oracle nach Oracle ist. Die neuen Tabellen `stats_report` und `data_storage`sind in _scripts/database/otobo-schema.xml_ enthalten.  Bei einer "normalen" Migration werden die zwei Tabellen also in Schritt 1 der Migration, https://doc.otobo.org/manual/installation/10.1/de/content/migration-from-otrs-6.html#step-1-install-the-new-otobo-system, angelegt.
Somit ist die Dokumentation der Migration von Oracle nach Oracle, https://doc.otobo.org/manual/installation/10.1/de/content/migration-from-otrs-6.html#migration-from-oracle-to-oracle, nicht vollständig. Am einfachsten ist dann wohl den Aufruf des Skriptes in diesem Kapitel einzufügen.

Zu Prüfen ist auch ob dieser Effekt auch in https://doc.otobo.org/manual/installation/10.1/de/content/migration-from-otrs-6.html#optional-step-streamlined-migration-of-the-database auftritt.

Viele Grüße,
    Bernhard

**Comment by markus-gitdev** [comment]
Hallo Bernhard,

Danke für die Rückmeldung, dann könnte man den Hinweis vielleicht am Ende von ["Migration from Oracle to Oracle"](https://doc.otobo.de/manual/installation/10.1/en/content/migration-from-otrs-6.html?highlight=oracle#migration-from-oracle-to-oracle) hinzufügen?

Liebe Grüße,
Markus
