### ISSUE TITLE
Otobo 10.1.4 - Elasticsearch Migration

### ISSUE THREAD

**Issue by forgeOneHQ** [RotherOSS/otobo#1873]
Hello together,

when I try to run the elasticsearch migration on otobo 10.1.4 I get the following error:
otobo@otobo01:~/bin$ ./otobo.Console.pl Maint::Elasticsearch::Migration
Use of uninitialized value in numeric ne (!=) at /opt/otobo/Kernel/System/Console/Command/Maint/Elasticsearch/Migration.pm line 98.
Elasticsearch webservice is now activated. If you don't want to keep it enabled, please disable it manually in the admin interface, after the migration is complete.
ERROR: OTOBO-otobo.Console.pl-Maint::Elasticsearch::Migration-01 Perl: 5.30.0 OS: linux Time: Tue Aug 16 10:54:04 2022

 Message: Need ID!

 Traceback (195867): 
   Module: Kernel::System::GenericInterface::Webservice::WebserviceUpdate Line: 324
   Module: Kernel::System::Console::Command::Maint::Elasticsearch::Migration::PreRun Line: 103
   Module: (eval) Line: 465
   Module: Kernel::System::Console::BaseCommand::Execute Line: 465
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 88
   Module: ./otobo.Console.pl Line: 35

Elasticsearch webservice could not be activated! Unable to continue.
Error: Died at /opt/otobo/Kernel/System/Console/Command/Maint/Elasticsearch/Migration.pm line 110.

Does anyone else has the same error and solved it?

**Comment by svenoe** [comment]
Hi Mathias,

something is wrong with your Elasticsearch webservice here, it gets returned to the migration routine in a broken state. You could have a look at it in the Admin->Webservices screen, I would assume that you get errors there, too. In general I would assume that something didn't work properly during installation, or you maybe installed some packages which altered something.

In general, unless you are very certain that there is a bug in OTOBO and you can tell us a way how to reproduce it on a clean system, please rather visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) for questions and help. Github is exclusively for developement, atm. I will close this for now.

Best regards, Sven
