### ISSUE TITLE
Fix Wikipedia Icon in sample Link of ToolBox tile in customer dashboard

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1884]
The hotlinked icon https://cdn3.iconfinder.com/data/icons/inficons-round-brand-set-2/512/wikipedia-512.png does no longer work. It should be replaced with a working version. I'm also not sure whether hotlinking to the iconfinder CDN is still recommended.

![Bildschirmfoto vom 2022-08-23 13-56-22](https://user-images.githubusercontent.com/46019/186151921-45ee0a89-a962-47f2-9ed7-3855a7351cd4.png)

**Comment by stefanhaerter** [comment]
Is this done? In rel-11_0 it looks like the icon is working again.

**Comment by bschmalhofer** [comment]
An icon recognizable as an icon for Wikipedia is shown. The image is ctually a nice example for a data-url. That's good enough, closing this issue.
