### ISSUE TITLE
Broken links to bugs.otobo.org

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#19]
In the code there are comments like `http://bugs.otobo.org/show_bug.cgi?id=2230`. These links are broken as bugs.otobo.org is empty. IMHO these links could be reverted back to e.g. `http://bugs.otrs.org/show_bug.cgi?id=2230` .

**Comment by svenoe** [comment]
I agree. (This is an unwanted side effect of the migration.)

**Comment by svenoe** [comment]
Solved, thanks Bernhard.
