### ISSUE TITLE
Are recursive translations officially allowed?

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1915]
The code in _Kernel/Language.pm_ , https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/Language.pm#L277, allows for recursive translation.

```
    # Expecting that the replacements do not contain a '%'.
    # That the substitutions stop at the first undefined replacement can be considered a bug.
    for my $Replacement (@Replacements) {
        return $Text unless defined $Replacement;

        $Text =~ s/\%(?:s|d)/$Replacement/;
    }

```
Is this an official feature? If so, a test case should be added to _scripts/test/Language.t_

```
diff --git a/scripts/test/Language/Translate.t b/scripts/test/Language/Translate.t
index ad46ff9112..41cb787323 100644
--- a/scripts/test/Language/Translate.t
+++ b/scripts/test/Language/Translate.t
@@ -80,6 +80,12 @@ my @Tests = (
         TranslationResult => 'Test7 [% test %] {" special characters test"}',
         Parameters        => ['test'],
     },
+    {
+        OriginalString    => 'OTOBOLanguageUnitTest::Test8 recursive %s',
+        TranslationString => 'recursive replacement %s',
+        TranslationResult => 'recursive replacement level 1 level 2 level 3 level 4',
+        Parameters        => ['level 1 %s', 'level 2 %s', 'level 3 %s', 'level 4'],
+    },
 );
 
 for my $Test (@Tests) {

```
If not the loop could be enhanced so that substitutions are done only after the last substituted text.

See also #534.

**Comment by svenoe** [comment]
It's the substitution rather than the translation - I don't see any use in calling it like your test exemplifies in any occasion, so I wouldn't count it as official feature, at the same time you can not really break stuff using it, and the comment suggests to not do it, so, I don't see a big necessity for any action here...

**Comment by bschmalhofer** [comment]
Let's leave it like this.
