### ISSUE TITLE
Generic Agent persistently sets SendNoNotification for all following Events.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#1918]
If a generic agent is configured with SendNoNotification (Ticket Command -> Send Notification "No"), this sets the corresponding attribute in the ticket object itself to prevent notifications being sent for additional triggered actions, but it also affects all independent, but later executed things. This could be a standard notification on the "NotificationNewTicket" event, which is preceeded by a generic agent triggered on the "TicketCreate" event, but even go so far that on multiple incoming mails, notifications for one ticket are not sent, if for the preceeding ticket/mail the generic agent was executed.

I was thinking about using `$Kernel::OM->Create()` instead of `Get()` in https://github.com/RotherOSS/otobo/blob/c8d91ec027b3c66c41a23b41cf50c6c3f88ed4d2/Kernel/System/GenericAgent.pm#L948 which works for the above, but I think the nicer solution is to delete the attribute from the TicketObject instead, after the routine, to ensure no notifications will be sent for stuff triggered by the generic agent.

**Comment by bschmalhofer** [comment]
It might suffice to simply localize the attribute:
`local $TicketObject->{SendNoNotification} = $Param{Config}->{New}->{SendNoNotification} ? 1 : 0;`

**Comment by stefanhaerter** [comment]
This seems to work in manual tests. Trying it now in the unit tests.
