### ISSUE TITLE
Docker: The article storage should be in a separate volume

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#193]
It feel right to separate code and content.
This is one of the steps for making the Docker installation easily upgradeable.

**Comment by bschmalhofer** [comment]
Moved to wishlist as it is not sure that it will be implemented.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I think we can close this issue, cause the S3 interface exists now?

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO not really, the S3 backend is with regard to articles analogous to the DB articles. But maybe we should expand the question into how to achieve cleaner seperation between code and data.

**Comment by bschmalhofer** [comment]
The current strategy is to close wishlist issues.
