### ISSUE TITLE
Support for package names that differ only in case

### ISSUE THREAD

**Issue by niccord** [RotherOSS/otobo#1931]
Hi all,
when upgrading a package, if it has changed the case of some letters in its name, then the upgrading process will be stuck in a loop.

For example:
upgrading my package from `OpmTest v.10.0.0` to `opmtest v.10.0.1`
this is the output in the console:
``` bash
$ bin/otobo.Console.pl Admin::Package::Install opmtest-10.0.1.opm
Installing package...
Deep recursion on subroutine "Kernel::System::Package::PackageInstall" at /opt/otobo/Kernel/System/Package.pm line 834.
Deep recursion on subroutine "Kernel::System::Package::PackageUpgrade" at /opt/otobo/Kernel/System/Package.pm line 519.
```

Since I think the uniqueness of a package name should not be based on the case of its letters, I think you should change the check on `Kernel::System::Package`.

Cheers!

**Comment by niccord** [comment]
I paste here the comment of @svenoe in the linked PR:

> Package name changes are not allowed, automatically. You can use
> `<PackageMerge Name="OldPackageName" TargetVersion="10.1.x"></PackageMerge>`
> within the sopm to replace packages with different name(s) with the new one during installation.

**Comment by svenoe** [comment]
Ah, hi Nicola, again,

I somehow overlooked the issue to the pr, sorry. I wasn't aware that you seemingly run into a loop. From the pr I thought it is only about the ability to change names.

We will have a look at this, I'll reopen the issue. Whoever looks into it, please also have a look at the above pr.

Best regards, Sven

**Comment by niccord** [comment]
I thought `<PackageMerge>` could solve the issue but I confirm this is not the case, the issue is still there.

**Comment by bschmalhofer** [comment]
Hi Nicola,

I will look into this sometimes in the next days. At least I can confirm the problem in a simple test case, see https://github.com/RotherOSS/otobo/blob/issue-%231931-upper_lower/scripts/test/Package.t#L1161.

Best regards,
   Bernhard

**Comment by bschmalhofer** [comment]
The infinite loop works like that:

1. The package "DUMMY" is installed without problems
2. The package "dummy" should be installed
3. PackageInstalled() is called. The select is by package name, case insensitive in MySQL
4. The package DUMMY is found
5. PackageUpgrade() is called
6. RepositoryList() is called
7. Case sensitive lookup in the result of RepositoryList() gives that "dummy" is not installer
8. Back to 3.

The fix is to make PackageInstalled() case sensitive.

**Comment by niccord** [comment]
But if you make PackageInstalled() case sensitive, then you can have "DUMMY" and "dummy" packages installed at the same time. I think this is not what you want.

I think the fix to make is changing the sensitive lookup in the RepositoryList(), giving "dummy" is installed since "DUMMY" is found.

In my PR I did exactly that: https://github.com/RotherOSS/otobo/pull/1935

**Comment by bschmalhofer** [comment]
Hi Nicola,
I discussed this with @svenoe  and the conclusion is that package names should be case sensitive. The packages "DUMMY" and "dummy" can be installed at the same time.
I adapted PackageIsInstalled() accordingly and it looks like installation now proceeds the way it should. But during testing I found that there is only one entry in the table "package_repository". This still needs to be fixed.

TODO:

- [ ] verify that packages are installed, and listed correctly, when their names differ only in case
- [x] enhance the test suite with calling PackageIsInstalled() in that special case
- [ ] enhance the test suite with calling RepositoryList() in that special case
- [ ] also the check the case of combined vs. precomposed unicode characters

**Comment by bschmalhofer** [comment]
There are some more instances in `Kernel::System::Package` where package names are treated as case insensitive. At least under MariaDB or MySQL. PostgreSQL and Oracle are fine.

Note that the caching layer is case sensitive, so there is some potential for confusion.

- [ ]  RepositoryGet:


```
    # get repository
    $DBObject->Prepare(
        SQL   => 'SELECT content FROM package_repository WHERE name = ? AND version = ?',
        Bind  => [ \$Param{Name}, \$Param{Version} ],
        Limit => 1,
    );

```

- [ ] RepositoryAdd:

```
        $DBObject->Do(
            SQL  => 'DELETE FROM package_repository WHERE name = ? AND version = ?',
            Bind => [ \$Structure{Name}->{Content}, \$Structure{Version}->{Content} ],
        );

```

- [ ] RepositoryRemove:

```
    # create sql
    my @Bind = ( \$Param{Name} );
    my $SQL  = 'DELETE FROM package_repository WHERE name = ?';
    if ( $Param{Version} ) {
        $SQL .= ' AND version = ?';
        push @Bind, \$Param{Version};
    }

```

- [ ] PackageInstall:

```
    # update package status
    return if !$Kernel::OM->Get('Kernel::System::DB')->Do(
        SQL => 'UPDATE package_repository SET install_status = \''
            . Translatable('installed') . '\''
            . ' WHERE name = ? AND version = ?',
        Bind => [
            \$Structure{Name}->{Content},
            \$Structure{Version}->{Content},
        ],
    );
```

- [ ] PackageUpgrade:

```
    return if !$Kernel::OM->Get('Kernel::System::DB')->Do(
        SQL => 'UPDATE package_repository SET install_status = \''
            . Translatable('installed') . '\''
            . ' WHERE name = ? AND version = ?',
        Bind => [
            \$Structure{Name}->{Content}, \$Structure{Version}->{Content},
        ],
    );
```

**Comment by bschmalhofer** [comment]
I starting adapting the code, so that it checks the case on the client side. But there are is a downsides to that approach. The code
becomes more complex. E.g. for deletion one must first fetch the name and the id, check the case of the name, and then delete by id. This has the disadvantage that an atomic operation becomes a non-atomic operation. This opens a can of worms.

So let's go for overriding the collation utf8mb4_unicode_ci using the BINARY declaration. See https://dev.mysql.com/doc/refman/5.7/en/case-sensitivity.html and https://stackoverflow.com/questions/5629111/how-can-i-make-sql-case-sensitive-string-comparison-on-mysql.

**Comment by stefanhaerter** [comment]
In today's discussion, it was decided to not allowing the installation of packages which differ only in case. One reason is that this is increases the potential for mistakes.

**Comment by stefanhaerter** [comment]
Note for development: Think about RepositoryGet, e.g. at https://github.com/RotherOSS/otobo/blob/5610750b81bce919edc1ec328b1e5c7e1ce8c4ef/Kernel/System/Package.pm#L385-L391

**Comment by svenoe** [comment]
I'm setting this on hold. It would be good to resolve this, but the prio is too low, currently.

**Comment by stefanhaerter** [comment]
While browsing through perldoc, I came across [fc](https://perldoc.perl.org/functions/fc) and was reminded of this issue. Perhaps this function might be useful here.

**Comment by bschmalhofer** [comment]
I rebased the branch to the current HEAD of rel-10_1, just to make it easier to pick up again in the future,
