### ISSUE TITLE
Print company ticket in CustomerTicketOverview shows wrong "printed by" information

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1938]
Hi,

When I print a ticket in the OTOBO Customer Area -> Company Tickets, the customer who created the company ticket is displayed at the top under "printed by", not the customer who is printing the ticket.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Merged the recent changes in rel-10_1 mainly because the CodePolicy action failed. I suppose this was because the branch was still using an old version of _cpanfile.docker_. Thus an outdated set of CPAN libraries was used, where LibUtil.c could not be linked any more.

**Comment by stefanhaerter** [comment]
Fix merged and looking good. Closing the issue.
