### ISSUE TITLE
Docker: separate git repos for otobo-nginx-webproxy and otobo-elasticsearch

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#194]
Separate things should be separate. _otobo.web.dockerfile_ could then be renamed to _Dockerfile_.

**Comment by bschmalhofer** [comment]
@svenoe Could you create the Git repositories? As this is a kind of official action and I don't want to decide on the naming.
I'll then think about the directory structure and copy the files.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

do you have a name suggestion or

otobo-docker-nginx
otobo-docker-elasticsearch

fits for you too?

Thanks,

Stefan

**Comment by StefanRother-OTOBO** [comment]
Hi,

I'll create the new repos. 

Best wishes,

Stefan

**Comment by bschmalhofer** [comment]
I think that this should be discussed, maybe in the OTOBO devel-meeting.

**Comment by bschmalhofer** [comment]
Frankly, I got used to it. Let's keep it the way it currently is.
