### ISSUE TITLE
Kernel::System::Calendar::Appointment uses uninitialized Log object

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1942]
In _Kernel/System/LinkObject/Appointment.pm_ the attribute `LogObject` is used but never initiialized.

TODO:

- [ ] enhance the test script such that the relevant code is called
- [x] Get the Log object from `$Kernel::OM`

**Comment by stefanhaerter** [comment]
Would it be good practice to replace the two occurrences of $Self->{LogObject} with $Kernel::OM->Get... ? Or would you just add $Self->{LogObject} = $Kernel::OM->Get... ?

**Comment by bschmalhofer** [comment]
@stefanhaerter  In this case I would opt for consistency and use `$Kernel::OM->Get('Kernel::System::Log')->Log(...);`. The same way it is done in the other methods.

**Comment by bschmalhofer** [comment]
Merged the PR. Closing this issue.
