### ISSUE TITLE
Error message in Log when changing data for a customer user with no password

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#1946]
It is possible to create a customer user without setting a password. If the user data is altered later, the following error message appears in the log:
Use of uninitialized value $CurrentUserData{"UserPassword"} in string ne at /opt/otobo/bin/psgi-bin/../../Kernel/Modules/AdminCustomerUser.pm line 374.

**Comment by bschmalhofer** [comment]
@stefanhaerter Why is this labelled as invalid? That a warning is emitted with in a valid use case is IMHO a bug.

**Comment by stefanhaerter** [comment]
You're right. I wasn't sure about how to label this. Since the process works, I thought the description "Something isn't right" would fit best.

**Comment by bschmalhofer** [comment]
Yes, the description of the label was confusing. I changed it to "The report was either incorrect, or it describes the correct behavior."

**Comment by stefanhaerter** [comment]
Slightly related to #779

**Comment by stefanhaerter** [comment]
Closed with merging #2556
