### ISSUE TITLE
Script to solve utf8 / utf8mb3 problems

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1956]
I have developed a script that changes the charset of MySQL and MariaDB columns to utf8mb4 for incorrectly installed or migrated OTOBO systems (with utf8 or utf8mb3 columns). 

A forum entry for this is here: https://otobo.de/de/forums/topic/emojis-in-e-mails-zerstoeren-ticket

**Comment by bschmalhofer** [comment]
Siehe auch #1881 und #1879.
