### ISSUE TITLE
ACL Form (Hide/Show Dynamic Field) does not work in AgentTicketCompose

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1960]
When having an ACL which hides a DynamicField, it doesn't hide it in Agent Ticket Compose.
I could reproduce the issue with OTOBO 10.1.5:

Steps to reproduce:

- Create DynamicField called "test"
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/87359203/193286246-56d26bc2-c4dd-46e5-b9a0-0be6703699cd.png">
- Display the DynamicField in AgentTicketCompose and e.g. AgentTicketPhone
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/87359203/193286448-5b477f26-ed8a-4ac4-85a5-f2690ee45e16.png">
- See that the DF is displayed in both:
1. AgentTicketPhone:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/87359203/193286725-07baca9f-03e2-4dbb-9472-b77319017b8f.png">
2. AgentTicketCompose:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/87359203/193286812-169d8cd6-007c-4069-a92c-7532175c52f3.png">
- Now create a new ACL, set it to valid and deploy it: Possible Not > Form > test
<img width="341" alt="image" src="https://user-images.githubusercontent.com/87359203/193288046-8b0be4ea-d4ab-4dd6-a141-eceff79b430d.png">
- See that the ACL works in AgentTicketPhone
<img width="258" alt="image" src="https://user-images.githubusercontent.com/87359203/193287687-ff1480e2-31ba-4f34-9608-7efb675d87c2.png">
- See that the ACL doesn't work in AgentTicketCompose
<img width="467" alt="image" src="https://user-images.githubusercontent.com/87359203/193287950-7eb93c16-9c7c-46fb-88e8-acb9e8cfcfb2.png">

**Comment by svenoe** [comment]
I would guess this is one of the masks where the functionality is not yet implemented at all.

**Comment by stefanhaerter** [comment]
I looked into the Code in Kernel/Modules/AgentTicketCompose.pm. As far as I understand it, the values can be restricted via ACL in this mask, but not the visibility of the fields themselves.

**Comment by stefanhaerter** [comment]
See #3537

**Comment by stefanhaerter** [comment]
There is a package present providing the functionality up to 11.0, and the PR is merged into 11.1.
Closing the issue.
