### ISSUE TITLE
UnitTest: 1 failure in scripts/test/TemplateGenerator/Replace.t 

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#197]
A new failure from a test run under Docker.
Seen in commit  012cc9150b90cccba5ebaf74c1a9e7804f2afc8c

```
ok 28 - OTOBO customer subject 3 letters - _Replace()
not ok 29 - OTOBO customer subject 20 letters + garbarge - _Replace() (is 'Test RE: otobo' should be 'Test otobo')
ok 30 - OTOBO responsible firstname - _Replace()

```

**Comment by bschmalhofer** [comment]
This is because in the Docker-Installation the setting is `$Self->{'Ticket::SubjectRe'} =  'RE###';`  No Idea where that value comes from.

**Comment by svenoe** [comment]
No errors in standard installation, commit: 2d61f7716999e717fee9e9a4f48ae7653cdc2481

**Comment by bschmalhofer** [comment]
Works in fresh OTOBO image. No idea where  ` $Self->{'Ticket::SubjectRe'} = 'RE###'; ` came from. Closing,

**Comment by bschmalhofer** [comment]
Reopening as the failure happened again when running under Docker.
`$Self->{'Ticket::SubjectRe'} = 'RE###'; seems to be the cause again.

**Comment by bschmalhofer** [comment]
The impression is that Ticket::SubjectRe gets changed by one of the test scripts from 'Re' to 'RE###'. 
Looks like the culprit is _scripts/test/SysConfig/SettingSet.t_ . as it does not restore the old setting. Wondering why I did not find that immediately.

**Comment by bschmalhofer** [comment]
Tests look fine. Also checked ZZZAAuto.sh by running `watch -n 1 ./watch.sh` while running the testsuite. Where watch.sh greps for SubjectRe in ZZZAAuto.pm. Closing again.
