### ISSUE TITLE
Assigning multiple tickets to one owner by collective action does not work in OTOBO 10.1.5 and 10.1.4

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#1970]
Assigning multiple tickets to a new owner via bulk action does not work any more. Tested in OTOBO 10.1.4 and 10.1.5. 
Did work in older systems.

**Comment by GritRother-OTOBO** [comment]
Das Verhalten hängt mit einer Umstellung in der Systemkonfiguration zusammen.

Mit OTOBO 10.1 wurde das Standardverhalten bei der Freigabe von Tickets geändert => freigegebene Tickets werden an root@localhost zurückgegeben, der im Standard mit „–“ benannt ist. So ist offensichtlich, dass das Ticket gerade keinen Besitzer hat.Früher blieb der letzte Besitzer als Besitzer aufgeführt, auch wenn das Ticket eigentlich schon wieder freigegeben war. Das hat bei ungeschulten Benutzern immer wieder zu Verwirrung geführt.

Lösung:
- Entweder in der Systemkonfiguration die Einstellung „Ticket::OwnerResetOnUnlock“ deaktivieren und das komplette System auf das von früher gewohnte Verhalten umstellen oder 
- in der Sammelaktion eine weitere Einstellung vornehmen und ganz unten bei „Ticket Entsperren“ „Nein“ auswählen. Dann funktioniert es auch mit aktivierten Ticket::OwnerResetOnUnlock.

**Comment by bschmalhofer** [comment]
Closing, as it works as designed.
