### ISSUE TITLE
Frontend::MenuDragDropEnabled without any function

### ISSUE THREAD

**Issue by ghost** [RotherOSS/otobo#1973]
Enabling the Setting Frontend::MenuDragDropEnabled has no function. Drag and Drop in Menu is not possible, it does not matter if Setting is enabled/disabled.

**Comment by bschmalhofer** [comment]
I did a quick search for Frontend::MenuDragDropEnabled  and found that there is some support in the code for that feature. So the config setting can't simply be removed. One interesting comment was in _scripts/test/Selenium/Agent/AgentNavigationBar.t_:
```
        # TODO: remove limitation to firefox.
        if ( $Selenium->{browser_name} eq 'firefox' ) {
            $Self->True(
                1,
                "TODO: DragAndDrop is currently disabled in Firefox",
            );
        }

```
Which browser are you using? If it is only Firefox where drag&drop is not working, then we should investigated whether this limitation can be removed nowadays.

**Comment by ghost** [comment]
I am using Google Chrome, there it is not working.

**Comment by bschmalhofer** [comment]
Hi Markus,

thanks for the feedback. We will think about whether to fix or to remove this feature. But this will take some time, as it is not high up in the agenda. For now,  I filed the issue as planned for the 11.0 release.

Best regards,
   Bernhard

**Comment by ghost** [comment]
Hi Bernhard, i found out that its working with a fresh install. I did a migrate from Znuny LTS to Otobo. Are there some other settings i need to check?

**Comment by ghost** [comment]
Really interesting, since i started a rebuild of the sysconf its working (migrated and fresh installation)

**Comment by bschmalhofer** [comment]
Hi @OTECMarkus,

I'm closing this issue now. When there are problems again with drag and drop, a new issue can be opened. See also #2006, for reactivating tests for firefox.
