### ISSUE TITLE
Process Management CSS Border wrong (not round)

### ISSUE THREAD

**Issue by ghost** [RotherOSS/otobo#1974]
The Border is outline not round:
![image](https://user-images.githubusercontent.com/84412466/196009380-343f9515-cb3e-43a5-913e-212c2d2aeac1.png)

**Comment by stefanhaerter** [comment]
Hi Markus,

thank you for the feedback. As far as I understand the relevant code, this problem affects WidgetNotice, which is only used within the process management, so I can fix this by adding a border radius setting. However, I found that there is at least one other place where the border radius setting of an outer div overwrites the border of the inner div. I will leave this as a note here for potential further investigation.

Best regards,
Stefan

**Comment by svenoe** [comment]
Please also change the color to #fffccc.

**Comment by stefanhaerter** [comment]
Closed by merging #1979
