### ISSUE TITLE
Dynamic Field Database search backend produces undefined data due to off by one error

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#1984]
Code line:
https://github.com/RotherOSS/otobo/blob/d89a619725a6450d18a317f3df2dad70931d4d42/Kernel/System/DynamicFieldDB.pm#L560

Because $RowCount is initialized with scalar @Row, which gives the number of elements in the array, instead of $#Row, which gives the highest index, the returned data contains '{ Data => undef, Label => undef },'.

The same initialization is used in the function DatabaseSearchDetails, but there a prevention against empty items is included. I would opt for fixing this at both locations nonetheless.

**Comment by bschmalhofer** [comment]
At least in the first case you could also write something like  `for my $Item ( @Row ) { .. `.

**Comment by stefanhaerter** [comment]
Good suggestion, I will check this. Maybe I was tempted by doing as few changes as possible ;)

**Comment by stefanhaerter** [comment]
PR merged.

**Comment by bschmalhofer** [comment]
Reopen because there was a failure in _scripts/test/DynamicField/DynamicFieldDB.t_

**Comment by stefanhaerter** [comment]
Test looking fine so far. @bschmalhofer can you confirm?

**Comment by bschmalhofer** [comment]
Running the test suite with Docker looks fine. Closing this issue again.
