### ISSUE TITLE
Ticket Owner is reset to root@localhost when closing and setting explicit a owner

### ISSUE THREAD

**Issue by ghost** [RotherOSS/otobo#1988]
When I close a Ticket and set explicit a new Owner, the Owner is always reset to root@localhost. Same behaviour when i dont set a new Owner.
![image](https://user-images.githubusercontent.com/84412466/196994924-6a09a510-0b9c-43fd-a0ae-e451ae726b40.png)

In Znuny LTS this behaviour did not exist and I could not find any configuration differences between our old Znuny LTS and the new OTOBO installation.

**Comment by svenoe** [comment]
Hi Markus,

we use github solely for development issues, not for general help questions. Please visit [our forums](https://otobo.de/en/forums/otobo/otobo-forum/) for help from the community or write an email to hello@otobo.de for professional support. One of use will have a look at your other issues, too, but especially when migrating a system, depending on its customization, installed addons etc. some side effects which have to be handled manually can always occur and although automating as much as possible is our goal, it doesn't have the highest priority.

To solve this issue, please look at the SysConfig setting "Ticket::OwnerResetOnUnlock" (I'm bot a huge fan, either, but for absolute newcomers we deemed it helpful).

Depending on the complexity of answers we might just close the other issues, thanks for your understanding and best regards,

Sven

**Comment by bschmalhofer** [comment]
See also #1372, which unfortunately does not give a reason for this change.

**Comment by stefanhaerter** [comment]
I would assume that this is the explanation: https://github.com/RotherOSS/otobo/issues/1653#issuecomment-1228228069
