### ISSUE TITLE
PSGI: Shorten the Traceback

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#199]
In case of error a Stacktrace is printed. This stacktrace contains with otobo.psgi the call stack with all of the middlewares. This appears to be overkill.

Example:

```
  Module: Kernel::System::Ticket::Article::Backend::Email::ArticleSend Line: 306
   Module: Kernel::Modules::AgentTicketCompose::Run Line: 1035
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1211
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 581
   Module: CGI::Emulate::PSGI::__ANON__ (v0.23) Line: 30
   Module: Plack::Middleware::Refresh::call Line: 23
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 314
   Module: Plack::Middleware::ForceEnv::call (v0.02) Line: 18
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Middleware::ReverseProxy::call (v0.16) Line: 68
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Middleware::Conditional::call Line: 16
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Middleware::ErrorDocument::call Line: 15
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Middleware::Lint::call Line: 24
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Middleware::StackTrace::try {...}  Line: 38
   Module: (eval) (v0.30) Line: 100
   Module: Try::Tiny::try (v0.30) Line: 93
   Module: Plack::Middleware::StackTrace::call Line: 42
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Middleware::AccessLog::call Line: 27
   Module: Plack::Component::__ANON__ Line: 50
   Module: (eval) Line: 145
   Module: Plack::Util::run_app Line: 145
   Module: Plack::Handler::Gazelle::__ANON__ (v0.49) Line: 220
```

**Comment by svenoe** [comment]
If it is easily doable, this would be very nice for debugging situations.

**Comment by bschmalhofer** [comment]
This is not urgent, back to Milestone 10.1,

**Comment by svenoe** [comment]
It's not super urgent, I agree, but it seems to me, that the implementation is not likely to cause any hardly foreseeable bugs or anything, as it is probably quite encapsulated from the rest. So if it is done somewhen, in my opinion nothing is speaking against doing it directly on the rel-10_0 branch - we already have some systems running on psgi, and I guess  all would be happy about spending less time searching for the important info. I would be for keeping it in 10.0, as long as the implementation doesn't involve some big changes.

**Comment by bschmalhofer** [comment]
Since 620a61fb4 (bernhard 2020-07-24 19:20:51 +0200  99) the environment variable PLACK_ENV is set per default to 'deployment' in _bin/docker/entrypoint.sh_ . This means that per default the middleware `Plack::Middleware::StackTrace` is not loaded. This  means that for exceptions no stacktrace is printed at all. When setting PLACK_ENV to 'development' explicitly, then a complete Stacktrace is IMHO fine.

Closing this issue as it no longer applies.
