### ISSUE TITLE
Allow creation of DateTime objects from CPAN DateTime objects 

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1993]
In OTOBO 10.1 there is a kind of secret possibility to create instances of `Kernel::System::DateTime`by passing a `DateTime`object via the parameter `_CPANDateTimeObject`. This approach should be made official for OTOBO 11.0.

**Comment by svenoe** [comment]
Is permitted.

**Comment by svenoe** [comment]
Please add a comment that it is allowed for K::S::DT

**Comment by bschmalhofer** [comment]
See also https://github.com/RotherOSS/otobo/issues/1993

**Comment by bschmalhofer** [comment]
Renamed the secret parameter `_CPANDateTimeObject` to `CPANDateTimeObject`, updated the POD and added a test. Closing this issue.

**Comment by bschmalhofer** [comment]
Reopening. Currently the passed in CPANDateTime is simple stored as the internal object. But this allows action at a distance, which is usually not expected. 

TODO:

- [x] add a test that there is no action at a distance
- [x] fix the failing test

**Comment by bschmalhofer** [comment]
Cloned the passed in CPANDateTime object and did some cleanup. Tests look fine. Closing this issue again.
