### ISSUE TITLE
 Frontend::ToolBarModule###210-Ticket::TicketSearchProfile Dropdown too much on the left

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#1996]
When adding the ToolbarModule for TicketSearch, the list with the search templates is too much on the left. Here you can see two examples from two different systems.

![image](https://user-images.githubusercontent.com/87359203/198062738-74bc29a1-7c30-4f36-ae94-e044dfc5f8d2.png)

![image](https://user-images.githubusercontent.com/87359203/198062775-c980b902-8d17-4c4d-a3e0-ff9e107e3e2d.png)

I reproduced it on a 10.1.5, you can try it out on OV125.

This might be related to [Issue#1205](https://github.com/RotherOSS/otobo/issues/1205)

**Comment by stefanhaerter** [comment]
For confirmation: I encountered the case that the elasticsearch input field enlargens on focus (from 135.5px to 143.5px, which seems to be due to padding changes). @svenoe @StefanAbel-OTOBO Can you tell if this is wanted behaviour? The relevant css code stems from the initial otobo commit.

**Comment by stefanhaerter** [comment]
Notes for development:
Grep for form names from ElasticSearch and TicketSearchProfile
Remove margin from input, potentially add to form
Check when and why margin changes were committed
Prefix new css with Toolbar (#Toolbar .Extended form ElasticSearch TicketSearchProfile)
Remove #Toolbar .Extended.SearchProfile padding-left and margin-right

**Comment by stefanhaerter** [comment]
Adapted CSS code, looking fine so far. Closing the issue.
