### ISSUE TITLE
Ticket::Frontend::CustomerTicketCategories translation by key

### ISSUE THREAD

**Issue by mario-minati** [RotherOSS/otobo#1999]
Currently the color of Ticket::Frontend::CustomerTicketCategories is based on the value of dynamic fields, not the key. Please check, whether translation happens before or after, as in the former case colors have to be added for each language individually. (Also have a quick look whether there are reasons, like the possible transformations of the value, for that behavior. Changing it as a patch level would invalidate the current configuration of some systems.)

**Comment by mario-minati** [comment]
The Issue is related to support request #2022103110000443.

**Comment by mario-minati** [comment]
First notes from analysing the source by Sven:

Kernel/Modules/CustomerTicketZoom.pm +2011 # my $Color...

uses the value, but we have to check if translation happens before or after that line.

**Comment by stefanhaerter** [comment]
MultiValue changes introduced with rel-11_0 increase complexity here, and priority is not high. Moving the issue to the wishlist.
