### ISSUE TITLE
Bump required Perl version to 5.24

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2]
https://doc.otobo.org/manual/installation/stable/en/content/requirements.html states that OTOBO requires Perl 5.16.0 . This version of Perl is from 2012 and supporting old Perl versions brings no benefit to OTOBO. Can we bump up the minimum version to Perl 5.24.   5.24 is because I'm a fan of posfix dereferencing.

**Comment by svenoe** [comment]
Changed to 5.24.

**Comment by bschmalhofer** [comment]
Cool. See https://perldoc.perl.org/feature.html for the new features available in 5.24
