### ISSUE TITLE
Non-existent method Kernel::System::Article::ArticleGet() is called in dead code

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2009]
In _Kernel/Modules/AgentTicketZoom.pm_ there is support for the subaction **ShowHTMLeMail** which calls `Kernel::System::Article::ArticleGet()` . But that method does not exist. This was not noticed because the subaction is only set in `Kernel::Output::HTML::Layout::CheckMIMEType()` which is unused.
```
bes:~/devel/OTOBO/otobo (rel-10_1)$ grep -r CheckMimeType Kernel/
Kernel/Output/HTML/Layout.pm:sub CheckMimeType {
bes:~/devel/OTOBO/otobo (rel-10_1)$ 
```
TODO:
- [x] remove CheckMIMEType
- [x] remove support for Subaction ShowHTMLeMAil
- [x] check for other uses of  Kernel::System::Article::ArticleGet()

**Comment by stefanhaerter** [comment]
In at least one occation, this requires to be cautious. In _scripts/test/GenericInterface/Invoker/Ticket/WebserviceTicketInvoker.t, L179_, `$ArticleObject->ArticleGet` is called, however `$ArticleObject` at this point refers to _Kernel/System/Ticket/Article/Backend/Internal.pm_, where the method `ArticleGet` indeed exists.

**Comment by bschmalhofer** [comment]
In _./Kernel/Modules/CustomerTicketZoom.pm_ there also is support for a subaction ShowHTMLeMail. Let's leave that in for now, as it is not obviously broken code.

**Comment by bschmalhofer** [comment]
Using to following seach for finding potentially problematic usages of ArticleGet():
`grep -r ArticleGet . | grep -v ArticleBackend | grep -v ArticleInternalObject | grep -v _MetaArticleGet | grep -v BackendForArticle `
Actually did not find any more problematic cases, which is a good thing.

**Comment by bschmalhofer** [comment]
Clean up completed. PR is merged. Closing this issue.

**Comment by svenoe** [comment]
`ShowHTMLeMail` seems still present in CustomerTicketZoom, can it be removed there, too?

**Comment by bschmalhofer** [comment]
`showHTMLeMail` in CustomerTicketZoom was without function. Looks like some leftover that was added in 2005.
Got rid of it. Closing this issue again,
