### ISSUE TITLE
Consider OTOBO modules in Kernel/cpan-lib in command Dev::Code::CPANUpdate

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2013]
There are some OTOBO modules in _Kernel/cpan-lib_. This is for supporting the namespace conventions of some CPAN modules. The command Dev::Code::CPANUpdate already makes provisions for the file _Kernel/cpan-lib/Devel/REPL/Plugin/OTOBO.pm_ . However _./Kernel/cpan-lib/Plack/Loader/SyncWithS3.pm_ and _Kernel/cpan-lib/Plack/Middleware/OTOBO/SecureModeAccessFilter.pm_ are not considered yet.

**Comment by svenoe** [comment]
We will work on Kernel/cpan-lib anyways - closed.
