### ISSUE TITLE
Prozess Transition Action - TicketCreate and Dyn. Feld vom Type MultiSelect Does Not Work

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#2014]
We have a process where a child ticket is created through a transition action. Many Dynamic Fields are passed in, and this works. Only Dyn. Feld vom Type MultiSelect will not work.
(Because when performing the transition action when copying fields of type MultiSelect instead of the selected values, only a string with the values is adopted.)

**Comment by stefanhaerter** [comment]
@svenoe For which branches is this relevant? For rel-11_0, this should be fixed with the adaptions made for #2656.

**Comment by svenoe** [comment]
We decided not to fix the behavior of the old tags (to not change too many systems, and also because stringification is what you usually would expect from this tag).

We could backport the new functionality as package, if needed, though.
