### ISSUE TITLE
Ticket has no title in the View CustomerTicketOverview

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#2015]
If a ticket does not have an item in the ticket, it does not have a title in the CustomerTicketOverview. 

![Bildschirm­foto 2022-11-14 um 17 17 21](https://user-images.githubusercontent.com/108396552/201710893-38027a90-75e2-48b3-9556-6f24336e7a28.png)

In the CustomerTicketZoom, the title is there.

![image](https://user-images.githubusercontent.com/108396552/201711503-aeea03e4-1868-4dc7-9821-fa9de2c3e33c.png)

**Comment by stefanhaerter** [comment]
Just to make sure that I understand the case correctly: A ticket title is set, but no item is there in the title?

**Comment by OlliW** [comment]
Yes, when the ticket has no article (visible for the customer)

**Comment by svenoe** [comment]
Our decision here is to, starting with OTOBO 11, always show the ticket title in the ticket lists (if the customer can see the ticket). This potentially shows information of articles not visible to the customer, if no articles visible to the customer exist and the ticket title is derived by one of those, which currently at least for ticket lists would be rendered as "Untitled!", but:
1. The cases where this happens are neglegibly low, especially compared to the rising amount of cases where in process tickets e.g. no articles exist, but the customer should be able to see the subject.
2. This was not completely fool proof before, as the ticket title could come from an invisible article, even if articles visible to the customer exist.
3. If you have a system where this matters, changing Ticket::Frontend::CustomerTicketOverview#ColumnHeader to LastCustomerSubject reliably solves this problem.
