### ISSUE TITLE
UnitTest Failure in AdminProcessManagementTransitionAction.t

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2029]
The test `scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t` fails, at least when running the whole directory of tests (`bin/otobo.Console.pl Dev::UnitTest::Run --directory Agent/Admin/ProcessManagement`). It seems that this is due to the test relying on behaviour prior to https://github.com/RotherOSS/otobo/pull/1565. The test should be adjusted accordingly.

**Comment by bschmalhofer** [comment]
@stefanhaerter, @svenoe  Can this be included with OTOBO 10.18 ?   It would be nice to have a test suite without failures.

**Comment by stefanhaerter** [comment]
I have already worked on that test, but I'm unsure whether my solution is a good way to address this. Maybe we could find some time to look at it together?

**Comment by stefanhaerter** [comment]
I pushed a fix which relies on a certain order of values. However, after some discussing @bschmalhofer and I consider the alphabetical sorting of keys in an existing transition action, which diverges from the original sorting in a new transition action, a bug which should be fixed. The fixed test is expected to fail when the bug is fixed, so it has to be adjusted again.

**Comment by bschmalhofer** [comment]
PR is merged. The test suite looks fine. Closing this issue.


```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1785 Failed: 0)
  TODO passed:   1147, 1244
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
Files=964, Tests=81147, 5987 wallclock secs (27.96 usr  3.50 sys + 1613.13 cusr 229.22 csys = 1873.81 CPU)
Result: PASS
ran tests for product OTOBO 10.1.x on host ffda6b56f95f .

```
