### ISSUE TITLE
Create Sysconfig Option to disable Timezone

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#2031]
Hi,

at the moment, the time zone is mostly displayed everywhere in the system, even if it is not actually used. Please verify when the time zone is displayed and when it is not.

For OTOBO 11 we have to create a possibility to deactivate the display of the time zone and to display it only in a central place.

Question: Are there users who need the time zone?

Thanks,

Stefan

**Comment by stefanhaerter** [comment]
Hi Stefan,

is this possibly a duplicate of https://github.com/RotherOSS/otobo/issues/2027?

**Comment by StefanRother-OTOBO** [comment]
Jepp, thanks!

Duplicate of #2027.
