### ISSUE TITLE
Issue with CommunicationLog

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#2037]
In certain situations it may happen that either a CommunicationLog of an outgoing mail already exists or the CommunicationLog has already been deleted. This often occurs when the mail server has been unavailable for a while.

Both currently ensure that no more e-mails are sent until manual intervention is made and either the corresponding messages are deleted or --force is used.

bin/otobo.Console.pl Maint::Email::MailQueue --help

shows the options. This cannot be, as manual intervention is always required.

Error Message (another one exist, if Log already deleted)

 Message: Object already has an open Log for this type.

 Traceback (151547): 
   Module: Kernel::System::CommunicationLog::_LogError Line: 546
   Module: Kernel::System::CommunicationLog::ObjectLogStart Line: 206
   Module: Kernel::System::Email::SMTP::Check Line: 56
   Module: Kernel::System::Email::SMTP::Send Line: 232
   Module: Kernel::System::Email::SendExecute Line: 763
   Module: Kernel::System::MailQueue::Send Line: 687
   Module: Kernel::System::Console::Command::Maint::Email::MailQueue::Send Line: 206
   Module: Kernel::System::Console::Command::Maint::Email::MailQueue::Run Line: 155
   Module: (eval) Line: 480
   Module: Kernel::System::Console::BaseCommand::Execute Line: 474
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 88
   Module: bin/otobo.Console.pl Line: 35

**Comment by svenoe** [comment]
I saw one occurence of this now, where the connection to the mysql server was interrupted for some time. This of course can create the state where a communication log type is not closed properly.
Thus we definitely have to handle it in a way which doesn't make the system hang.

**Comment by StefanRother-OTOBO** [comment]
More Error Messages:

otobo@rother-oss3:~$ bin/otobo.Console.pl Maint::Email::MailQueue —delete —filter=Recipient::test@test.de
ERROR: OTOBO-otobo.Console.pl-Maint::Email::MailQueue-99 Perl: 5.30.0 OS: linux Time: Thu Dec 15 11:27:39 2022

 Message: The communication ‚584446‘ is already closed, can’t be used.

 Traceback (654005): 
   Module: Kernel::System::CommunicationLog::_LogError Line: 546
   Module: Kernel::System::CommunicationLog::_RecoverCommunicationObject Line: 511
   Module: Kernel::System::CommunicationLog::new Line: 75
   Module: Kernel::System::ObjectManager::_ObjectBuild Line: 322
   Module: Kernel::System::ObjectManager::Create Line: 253
   Module: Kernel::System::MailQueue::_GetCommunicationLog Line: 1660
   Module: Kernel::System::MailQueue::Delete Line: 571
   Module: Kernel::System::Console::Command::Maint::Email::MailQueue::Delete Line: 326
   Module: Kernel::System::Console::Command::Maint::Email::MailQueue::Run Line: 165
   Module: (eval) Line: 480
   Module: Kernel::System::Console::BaseCommand::Execute Line: 474
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 88
   Module: bin/otobo.Console.pl Line: 35

Error: Can’t call method „ObjectLog“ on an undefined value at /opt/otobo/Kernel/System/MailQueue.pm line 573.

otobo@rother-oss3:~$ bin/otobo.Console.pl Maint::Email::MailQueue —send
ERROR: OTOBO-otobo.Console.pl-Maint::Email::MailQueue-99 Perl: 5.30.0 OS: linux Time: Thu Dec 15 11:28:24 2022

 Message: The communication ‚584653‘ is already closed, can’t be used.

 Traceback (654015): 
   Module: Kernel::System::CommunicationLog::_LogError Line: 546
   Module: Kernel::System::CommunicationLog::_RecoverCommunicationObject Line: 511
   Module: Kernel::System::CommunicationLog::new Line: 75
   Module: Kernel::System::ObjectManager::_ObjectBuild Line: 322
   Module: Kernel::System::ObjectManager::Create Line: 253
   Module: Kernel::System::MailQueue::_GetCommunicationLog Line: 1660
   Module: Kernel::System::MailQueue::Send Line: 646
   Module: Kernel::System::Console::Command::Maint::Email::MailQueue::Send Line: 206
   Module: Kernel::System::Console::Command::Maint::Email::MailQueue::Run Line: 155
   Module: (eval) Line: 480
   Module: Kernel::System::Console::BaseCommand::Execute Line: 474
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 88
   Module: bin/otobo.Console.pl Line: 35

Error: Can’t call method „CommunicationIDGet“ on an undefined value at /opt/otobo/Kernel/System/MailQueue.pm line 647.

**Comment by fraenki** [comment]
We're also affected by this bug. Removing the affected mail from the queue, as demonstrated in the previous comment, solved this issue for the time being.

**Comment by bschmalhofer** [comment]
PR is merged into rel-10_0,   The changes have been propagated to rel-10_1 and rel-11_0. Closing this issue.
