### ISSUE TITLE
Display of Internationalised Resource Identifiers

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#204]
I added the URL https://ca.wikipedia.org/wiki/Regi%C3%B3_ant%C3%A0rtica as the URL of an Customer. When opening the Link in Firefox it looks nice with all the diacritic characters properly displayed. But in the Customer Information Center all the ugly URL Escape codes are shown. It would be nicer to show the accented characters.

See https://www.ietf.org/rfc/rfc3987.txt

**Comment by svenoe** [comment]
Would be a nice feature, and the amount of work should be reasonable.
