### ISSUE TITLE
S3: fix failure of GlobalEffectiveValueGet.t

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2040]
This is a bit involved. First I fiddled until I could find a reproducible behavior. The identified case is:

- Tests are run in the same container where the web server is running
- First _./scripts/test/Package/ConfigurationCleanup.t_
- optionally sleep for 10 s
- Then run _./scripts/test/SysConfig/GlobalEffectiveValueGet.t_
- Actually I used modified version of these test scripts, in order to pinpoint the problem

The test _/ConfigurationCleanup.t_ installs an OTOBO package. The test _GlobalEffectiveValueGet.t_ verifies that a modified setting is actually modified when the config is reloaded. Without sleeping the latter test fails in most cases. With a sleep of 10 s the latter always succeeds. This behavior indicates that there is a connection with installing packages.

In the general case OTOBO can be served by different web servers that have independent _/opt/otobo_ directories. Changed config and newly installed packages are synchronized via the shared S3 backend and via the shared database.  Changed config is synchronised by writing the master copy to S3 first. Information about new packages is distributed by writing the file _event_package.json_ into S3. An updated timestamp on the S3 object indicates that the webserver should reinstall packages and 
restart the webserver. When installing a package, there often are new or changed files and new or changed configuration. Updating the configuration but not the files could create havoc. Therefore there is check in Kernel::Config::SyncWithS3 that config is only synced when the packages are up to date. The webserver has an event loop that checks every 10 s for new packages. This explains the time dependency. When running the two tests without sleep, then the config is not synced from S3 as the webserver hasn't reinstalled the packages yet.

There are several possibilities for redeeming this situation;

- add a sleep to the tests that are installing packages
- Add yet another parameter to Kernel::Config->new() that skips the check of event_package.json.
- write _event_package.json_ to the local file system after a package was installed

The last option might be the least fragile.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/1777#issuecomment-1351497848_

**Comment by bschmalhofer** [comment]
Created a dedicated ticket for the changed behavior of _event_package.json_.

**Comment by bschmalhofer** [comment]
While we are at it. TODO:

- [ ] eliminate the hard coded '/opt/otobo', based the LoadDefault() subroutine

**Comment by bschmalhofer** [comment]
A first testrun gave the following result:

```
Test Summary Report
-------------------
/opt/otobo/scripts/test/DynamicField/DynamicFieldDB.t                                                     (Wstat: 768 (exited 3) Tests: 23 Failed: 3)
  Failed tests:  9-11
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 (exited 3) Tests: 87 Failed: 3)
  Failed tests:  81, 84, 87
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Agent/MultiAttachmentUpload/CreateScreens.t                              (Wstat: 256 (exited 1) Tests: 128 Failed: 1)
  Failed test:  128
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t                                               (Wstat: 256 (exited 1) Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=964, Tests=80577, 6144 wallclock secs (27.36 usr  3.55 sys + 1809.24 cusr 245.32 csys = 2085.47 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host 717d69780028 .

```
The failure in _GlobalEffectiveValueGet.t_ is because of `ConfigLevel`, not `Ticket::Hook`.

**Comment by bschmalhofer** [comment]
Another test run, other failures:
```
Test Summary Report
-------------------
/opt/otobo/scripts/test/DynamicField/DynamicFieldDB.t                                                     (Wstat: 768 (exited 3) Tests: 23 Failed: 3)
  Failed tests:  9-11
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 (exited 3) Tests: 87 Failed: 3)
  Failed tests:  81, 84, 87
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketFreeText.t                      (Wstat: 2304 (exited 9) Tests: 64 Failed: 9)
  Failed tests:  40-41, 43, 46, 48, 50, 52, 54, 56
  Non-zero exit status: 9
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t                                               (Wstat: 256 (exited 1) Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=964, Tests=80646, 13998 wallclock secs (28.61 usr  3.64 sys + 1874.39 cusr 248.39 csys = 2155.03 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host 5aea2ad5e14f .

```

**Comment by bschmalhofer** [comment]
Another test run, where the screensaver did not kick in:

```
Test Summary Report
/opt/otobo/scripts/test/DynamicField/DynamicFieldDB.t                                                     (Wstat: 768 (exited 3) Tests: 23 Failed: 3)
  Failed tests:  9-11
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 (exited 3) Tests: 87 Failed: 3)
  Failed tests:  81, 84, 87
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t                                               (Wstat: 256 (exited 1) Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=964, Tests=80644, 6138 wallclock secs (27.30 usr  3.28 sys + 1837.01 cusr 244.75 csys = 2112.34 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host ea53725dfe45 .

```

**Comment by stefanhaerter** [comment]
I wonder about the DynamicFieldDB test... do you have an assumption about that?

**Comment by bschmalhofer** [comment]
I haven't really looked at this test as for now I'm concentrating on _GlobalEffectiveValueGet.t_ . Edit: that failure was fixed in the mean time, not related to S3.

**Comment by bschmalhofer** [comment]
The fixes so far are concerned about the effects of late handling of _event_package.json_ . But after the fix the test concerning ConfigLevel still seems to fail. 
Furthermore, the issues #2056 and #2058 have cropped up. So for this issue let's reenable S3 support in _otobo.psgi_ and maybe improve it a bit.

**Comment by bschmalhofer** [comment]
New test run with S3 after S3 has been reenabled in otobo.psgi:

```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransitionAction.t   (Wstat: 768 (exited 3) Tests: 87 Failed: 3)
  Failed tests:  81, 84, 87
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Agent/MultiAttachmentUpload/CreateScreens.t                              (Wstat: 256 (exited 1) Tests: 38 Failed: 1)
  Failed test:  38
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
/opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t                                               (Wstat: 256 (exited 1) Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=964, Tests=80487, 6404 wallclock secs (28.74 usr  3.61 sys + 1894.14 cusr 258.93 csys = 2185.42 CPU)
Result: FAIL
ran tests for product OTOBO 10.1.x on host 871c0487f4a6 .

```

**Comment by bschmalhofer** [comment]
I tried reproduce this but got contradictory results. Again, there are 4 web containers without a shared _/opt/otobo_. 

The last complete run gave:
```

ERROR: OTOBO-otobo.UnitTest-10 Perl: 5.36.0 OS: linux Time: Thu Apr  6 18:02:32 2023

 Message: Need SettingName!

 Traceback (12991): 
   Module: Kernel::System::SysConfig::GlobalEffectiveValueGet Line: 4956
   Module: /opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t Line: 76


# Failed test 'Setting with default EffectiveValue (defined in XML). - check expected result.'
# at /opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t line 78.
# +---------+-------+
# | GOT     | CHECK |
# +---------+-------+
# | <UNDEF> | 100   |
# +---------+-------+
[18:02:32] /opt/otobo/scripts/test/SysConfig/GlobalEffectiveValueGet.t ................................................. 
# Seeded srand with seed '20230406' from local date.
ok 1 - Missing SettingName - check expected result.
not ok 2 - Setting with default EffectiveValue (defined in XML). - check expected result.
ok 3 - Setting with EffectiveValue modified in the pm file. - check expected result.
1..3
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 

```

But I could not reproduce this with running prove in a web container. For example, running `prove -v -I . -I Kernel/cpan-lib/  ./scripts/test/Package/ConfigurationCleanup.t ./scripts/test/SysConfig/GlobalEffectiveValueGet.t` consistently returned:

```
ERROR: OTOBO-otobo.UnitTest-10 Perl: 5.36.0 OS: linux Time: Mon Apr 10 12:29:22 2023

 Message: Need SettingName!

 Traceback (862): 
   Module: Kernel::System::SysConfig::GlobalEffectiveValueGet Line: 4956
   Module: ./scripts/test/SysConfig/GlobalEffectiveValueGet.t Line: 76

./scripts/test/SysConfig/GlobalEffectiveValueGet.t ..  
# Seeded srand with seed '20230410' from local date.
ok 1 - Missing SettingName - check expected result.
ok 2 - Setting with default EffectiveValue (defined in XML). - check expected result.
ok 3 - Setting with EffectiveValue modified in the pm file. - check expected result.
1..3
ok
All tests successful.
```

**Comment by bschmalhofer** [comment]
I tried to reproduce this error reliably  and found that it consistently occurs when _scripts/test/SysConfig/GlobalEffectiveValueGet.t_ runs right after _scripts/test/SysConfig/DB/DeploymentModifiedVersionList.t_ . Further boiling down the code in the test scripts showed the probable cause. _DeploymentModifiedVersionList.t_ messes with _ZZZAAuto.pm_ but kindly restores the original version at the end of the script. But the _ZZZAAuto,pm_ in S3 is not restored. When the version in S3 is synced to the file system, then _GlobalEffectiveValueGet.t_ ends up with a broken file _ZZZAAuto.pm_. The fix is to do the same as in the commit https://github.com/RotherOSS/otobo/commit/7a45c437da493ee7efd7a8c2c1cdcec3e3797027.

**Comment by bschmalhofer** [comment]
Looks like the merged PR solved the problem with _GlobalEffectiveValueGet.t_ . Closing this issue.
