### ISSUE TITLE
Translation of country names using Locale::CLDR

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#205]
Most Country names are not translated. This means that when adding a customer in a non-english frontend, the country names are still mostly English.

TODO:

- [ ] maybe show two versions, like in Personal Settings, but what about multiligual countries ?
- [ ] maybe add missing Translations

My guess is that these translations can be taken from a publicly available resource.

**Comment by StefanRother-OTOBO** [comment]
If you look at the country names in the OTOBO -> Personal settings, you can see how it is supposed to be. First the name is displayed in the language of the country (so that the user who speaks the language can recognize it. Behind the minus is then the translation in the currently active language. 

Edit: this seems to be about language names, not the country names

**Comment by bschmalhofer** [comment]
The relevant resources for countries in multiple languages seem to be https://cldr.unicode.org/, https://icu.unicode.org/, and https://metacpan.org/pod/Locale::Country::Multilingual.

**Comment by bschmalhofer** [comment]
As far as I see in rel-11_0 the only place where a country list is used is the AdminCustomerCompany frontend. There there is either a selection of English country names from `Locale::Country` or from the SysConfig setting `
ReferenceData::OwnCountryList`. The country code isn't used anywhere. However there might be OTOBO packages that enhance the handling of countries.

**Comment by bschmalhofer** [comment]
Finally found the module that has the information from the latest release of CLDR: [Locale::CLDR](https://metacpan.org/dist/Locale-CLDR). Looks like it also has everything than anybody ever wanted for localisation.

**Comment by bschmalhofer** [comment]
I verified with OTOBO 10.0.x that the SysConfig setting `ReferenceData::OwnCountryList` has indeed a strange behavior. The keys of the mapping  are simply ignored. Only the values are shown in the GUI and stored in the database.

For the sake of this issue I propose the following:

- [x] Add new SysConfig setting like `ReferenceData::TranslatedCountryNames`
- [x] the new option will be implemented with Locale::CLDR
- [x] Locale::CLDR will be added to _Kernel/cpan-lib_
- [x] The CLDR country code will be stored in the database 
- [x] The country names in AdminCustomerCompany will be in the language of the current user
- [x] Additionally the Flag, or the Language Code, will be showh
- [ ] In the customer information widgets, the country will be in the language of the current user
- [x] There is no such concept as selection in the language of the country, because Belgium

**Comment by bschmalhofer** [comment]
Decided against added Locale::CLDR to _Kernel/cpan-lib_. This is because then the new dependencies of Locale::CLDR would also have to be added to _Kernel/cpan-lib_. And these modules might interfere with already installed versions of thess modules. 

So I declared Locale::CLDR as an optional dependency in the feature div:cldr.
It happens that Locale::CLDR is not available in Linux distro packages. So it has to be installed from CPAN. For convenience div:cldr will be included in the Docker image. This means that the availability of Locale::CLDR has to be checked at runtime. Maybe fall back to Locale::Country.

**Comment by bschmalhofer** [comment]
Worked on the implementation. Found that for each supported language the needed language pack must be installed.

**Comment by bschmalhofer** [comment]
During test I set my language to french. After reloading the page I had in the language selection entries like "Nederlandse - Dutch". The first part is fine, that is Dutch in Dutch. But the second part should be néerlandais,  that is Dutch in French. Looks like a translation is missing.

I propose to use Locale::CLDR for the complete matrix.

**Comment by bschmalhofer** [comment]
Implemented the translation of country names using Locale::CLDR. But my confidence that this is a good solution is waning a bit, as there are some problems:

- Loading of the customer information widget is slow
- Trying to get the Norwegian Bokmal  translation of BV (Bouvet Island) causes a deep recursion, see https://github.com/ThePilgrim/perlcldr/issues/41
- Country names for Serbian latin are shown in cyrillic, but that is fine as transliteration is a special case

**Comment by bschmalhofer** [comment]
Translations work fine with Locale::CLDR 0.34.4. PR is merged. Closing this issue.

**Comment by bschmalhofer** [comment]
Some missing pieces were encountered:

- previous country names should still be available, even if they are full country names instead of the two letter codes
- The special region names Pseudo-Accents and Pseudo-Bidi should not be in the selection
- The AdminCustomerUser frontend should also show the selection list

**Comment by bschmalhofer** [comment]
Closing again after the fixes.
