### ISSUE TITLE
Improvement suggestion/wish: notification method = web push notification and automaticly Dashboard refresh

### ISSUE THREAD

**Issue by ohobby** [RotherOSS/otobo#2074]
Hello,
As it looks, there is currently only email notification for the agents.
Would it be possible to add the web push notification to Otobo and then the agent receives a notification in the browser if the portal is not currently in the foreground?
Because in the browser you don't get to know when something new has come in, because the portal doesn't update itself automatically (that would also be a wish, that the portal dashboard updates itself regularly).

Regards,
Oliver

**Comment by svenoe** [comment]
Hi Oliver,

both is possible in principle, if we find something who sponsors the development of push notifications, those certainly will come at one point.

To keep things tidy, I'm adding this to a list of feature wishes, though the push notifications especially are a topic for us anyways.

Best regards, Sven
