### ISSUE TITLE
Sorry, can't install package, because package ImportExport v10.1.2 is required!

### ISSUE THREAD

**Issue by MirkoPlachta** [RotherOSS/otobo#2076]
Hello,

When trying to install ImportExportTicket-10.1.2.opm
This error appears, but I can't see, where to get ImportExport v10.1.2.

`Backend ERROR: OTOBO-CGI-20 Perl: 5.32.1 OS: linux Time: Wed Jan 4 08:42:04 2023

 Message: Sorry, can't install package, because package ImportExport v10.1.2 is required!

 RemoteAddress: 
 RequestURI: /otobo/index.pl?Action=AdminPackageManager;Subaction=InstallRemote;Source=https%3A%2F%2Fftp.otobo.org%2Fpub%2Fotobo%2Fpackages%2F;File=ImportExportTicket-10.1.2.opm;Name=ImportExportTicket;Version=10.1.2;

 Traceback (64006): 
   Module: Kernel::System::Package::_CheckPackageRequired Line: 3832
   Module: Kernel::System::Package::PackageInstall Line: 544
   Module: Kernel::Modules::AdminPackageManager::_InstallHandling Line: 2209
   Module: Kernel::Modules::AdminPackageManager::Run Line: 859
   Module: Kernel::System::Web::InterfaceAgent::Content Line: 1239
   Module: Kernel::System::Web::InterfaceAgent::Response Line: 1321
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 202
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 172
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 158
   Module: Plack::Middleware::HTTPExceptions::try {...}  Line: 20`

**Comment by svenoe** [comment]
Hi Mirko,

with general questions please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/). Github is reserved for development issues.

Thanks for your understanding and best regards, Sven

(You should be able to find it in the ITSM Bundle repository in the package manager, on the left.)

**Comment by MirkoPlachta** [comment]
Thanks for the Information, but then the link for sending an error report should be adjusted.
It leads to: `https://github.com/RotherOSS/otobo/issues?product=OTOBO+Helpdesk&comment=Message%3A%0D%0ASorry%2C+can%27t+install+package%2C+because+package+ImportExport+v10.1.2+is+required%21%0D%0A%0D%0AComment%3A%0D%0A%0D%0A%0D%0ATraceback%3A%0D%0AERROR%3A+OTOBO-CGI-20+Perl%3A+5.32.1+OS%3A+linux+Time%3A+Wed+Jan+4+09%3A28%3A29+2023%0D%0A%0D%0A+Message%3A+Sorry%2C+can%27t+install+package%2C+because+package+ImportExport+v10.1.2+is+required%21%0D%0A%0D%0A+RemoteAddress%3A+192.168.0.252%0D%0A+RequestURI%3A+%2Fotobo%2Findex.pl%3FAction%3DAdminPackageManager%3BSubaction%3DInstallRemote%3BSource%3Dhttps%253A%252F%252Fftp.otobo.org%252Fpub%252Fotobo%252Fpackages%252F%3BFile%3DImportExportTicket-10.1.2.opm%3BName%3DImportExportTicket%3BVersion%3D10.1.2%3B%0D%0A%0D%0A+Traceback+%2875832%29%3A+%0D%0A+++Module%3A+Kernel%3A%3ASystem%3A%3APackage%3A%3A_CheckPackageRequired+Line%3A+3832%0D%0A+++Module%3A+Kernel%3A%3ASystem%3A%3APackage%3A%3APackageInstall+Line%3A+544%0D%0A+++Module%3A+Kernel%3A%3AModules%3A%3AAdminPackageManager%3A%3A_InstallHandling+Line%3A+2209%0D%0A+++Module%3A+Kernel%3A%3AModules%3A%3AAdminPackageManager%3A%3ARun+Line%3A+859%0D%0A+++Module%3A+Kernel%3A%3ASystem%3A%3AWeb%3A%3AInterfaceAgent%3A%3AContent+Line%3A+1239%0D%0A+++Module%3A+Kernel%3A%3ASystem%3A%3AWeb%3A%3AInterfaceAgent%3A%3AResponse+Line%3A+1321%0D%0A+++Module%3A+Kernel%3A%3ASystem%3A%3AWeb%3A%3AApp%3A%3Acall+Line%3A+86%0D%0A+++Module%3A+Plack%3A%3AComponent%3A%3A__ANON__+Line%3A+50%0D%0A+++Module%3A+Plack%3A%3AApp%3A%3AURLMap%3A%3Acall+Line%3A+71%0D%0A+++Module%3A+Plack%3A%3AComponent%3A%3A__ANON__+Line%3A+50%0D%0A+++Module%3A+Plack%3A%3ASandbox%3A%3A_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi%3A%3A__ANON__+Line%3A+202%0D%0A+++Module%3A+Plack%3A%3ASandbox%3A%3A_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi%3A%3A__ANON__+Line%3A+172%0D%0A+++Module%3A+Plack%3A%3ASandbox%3A%3A_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi%3A%3A__ANON__+Line%3A+158%0D%0A+++Module%3A+Plack%3A%3AMiddleware%3A%3AHTTPExceptions%3A%3Atry+%7B...%7D++Line%3A+20%0D%0A%0D%0A%0D%0A++++++++++++++++++++&bug_file_loc=ewsupport.dyndns.org%2Fotobo%2Findex.pl%3FAction%3DAdminPackageManager%3BSubaction%3DInstallRemote%3BSource%3Dhttps%253A%252F%252Fftp.otobo.org%252Fpub%252Fotobo%252Fpackages%252F%3BFile%3DImportExportTicket-10.1.2.opm%3BName%3DImportExportTicket%3BVersion%3D10.1.2%3B`
