### ISSUE TITLE
Update Copyright year to 2023

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2077]
Copyright notes in the files need to be updated to 2023.

**Comment by svenoe** [comment]
Please also look for footer infos etc.

**Comment by bschmalhofer** [comment]
The command ../CodePolicy/bin/otobo.CodePolicy.pl -a --plugins +TidyAll::Plugin::OTOBO::Legal::ReplaceCopyright -a 1>critic.out is your friend.
See also #1570.

**Comment by bschmalhofer** [comment]
### Updated set of commands for rel-10_0

-  ../CodePolicy/bin/otobo.CodePolicy.pl -a --plugins +TidyAll::Plugin::OTOBO::Legal::ReplaceCopyright -a 1>critic.out
-  git add -u                         # only updated files
- git diff --cached -U0 > diff.out   # as a manual control
- git commit --no-verify      # ignored violations from updated CodePolicy
- rm diff.out
- grep -r 2022 | grep -v CHANGES | grep -v '\.git' | grep -v 'var/article/' | grep -v 'Kernel/cpan-lib' | grep -v 'var/log' | grep -v 'var/httpd/htdocs/js/thirdparty/' > ../grep.out  # manual control

Update the templates in _Kernel/System/MigrateFromOTRS/Base.pm_.

Create a PR and merge the changes into rel-10_0. Ignore potential complaints from CodePolicy.

### The other branches

Merge rel-10_0 into rel-10_1 and run `OTOBO::Legal::ReplaceCopyright` again. Same for rel-10_1 to rel-11_0.

**Comment by bschmalhofer** [comment]
Things look fine, closing this issue.
