### ISSUE TITLE
Cannot Access PendingTime attribute for communication

### ISSUE THREAD

**Issue by ikubetoomuzik** [RotherOSS/otobo#2088]
# Description of Issue
Trying to send communication to users that includes the PendingTime on their ticket. The attribute <OTOBO_TICKET_UntilTime> should provide the value required,

# Issue
Nothing is found when using <OTOBO_TICKET_UntilTime> in emails, it just leaves a '-'.

# Question
Am I missing another attribute that will give me this time formatted as a date? I've tried different names like 'PendingDate' and such with no luck.

**Comment by svenoe** [comment]
Hi Curtis,

with general questions please visit our [community forums](https://otobo.de/en/forums/otobo/otobo-forum/). Github is reserved for development issues.

Thanks for your understanding and best regards, Sven
