### ISSUE TITLE
Rename the namespace Kernel to OTOBO

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#209]
This is just a point for discussion, Just like RequestTracker has the namespace RT, OTOBO could have the namespace OTOBO. Kernel is not very descriptive.

**Comment by svenoe** [comment]
True, but the necessary amount of work, especially considering all external scripts which exist, etc., is ridiculously high, I believe. As it is a topic close to your heart, I will leave it in "very low priority"... ;)

**Comment by bschmalhofer** [comment]
Accepting that this won't be implemented in the foreseeable future.
