### ISSUE TITLE
Update documentation of Kernel/System/Main::FilenameCleanUp

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2090]
The POD for Kernel/System/Main::FilenameCleanUp seems to be a bit outdated. The following points have been identified:

- Attachment is not described
- The regex described near parameter NoReplace is no longer correct
- Enclosed alphanumerics missing
- It is not described that the case of parameter Type is insignificant

**Comment by bschmalhofer** [comment]
The documentation has been at least improved a bit. Closing this issue.
