### ISSUE TITLE
Can't match complete mail body in post master filter with regular expressions

### ISSUE THREAD

**Issue by dennis-dko** [RotherOSS/otobo#2092]
If you try to read the complete content of the e-mail with the regular expressions, only the first line is returned.

**Comment by bschmalhofer** [comment]
One suggestion is to use dynamic regex modifiers, https://perldoc.perl.org/perlre#Extended-Patterns . Here is an example:

```
bes:~/devel/OTOBO/docker-otodev (rel-10_1)$ cat t.pl 
use v5.24;
use warnings;

my $text = <<'END_TEXT';
Line1 asdf
Line2 asdf
END_TEXT

my $multi_re = '1.*2';
say 'multi mode matches' if $text =~ m/$multi_re/;

my $single_re = '(?s)1.*2';
say 'single mode matches' if $text =~ m/$single_re/;
bes:~/devel/OTOBO/docker-otodev (rel-10_1)$ perl t.pl 
single mode matches
bes:~/devel/OTOBO/docker-otodev (rel-10_1)$ 

```

**Comment by bschmalhofer** [comment]
See also #2063.

**Comment by dennis-dko** [comment]
> One suggestion is to use dynamic regex modifiers, https://perldoc.perl.org/perlre#Extended-Patterns . Here is an example:
> 
> ```
> bes:~/devel/OTOBO/docker-otodev (rel-10_1)$ cat t.pl 
> use v5.24;
> use warnings;
> 
> my $text = <<'END_TEXT';
> Line1 asdf
> Line2 asdf
> END_TEXT
> 
> my $multi_re = '1.*2';
> say 'multi mode matches' if $text =~ m/$multi_re/;
> 
> my $single_re = '(?s)1.*2';
> say 'single mode matches' if $text =~ m/$single_re/;
> bes:~/devel/OTOBO/docker-otodev (rel-10_1)$ perl t.pl 
> single mode matches
> bes:~/devel/OTOBO/docker-otodev (rel-10_1)$ 
> ```

Yes you're right. I can fix the problem by using this regex in Filter Condition: `((?s).+)`
