### ISSUE TITLE
Agent to role partially not working

### ISSUE THREAD

**Issue by MikeW83** [RotherOSS/otobo#2114]
Hello,

I have migrated from OTRS 6 to OTOBO 10.1 and now I have some users where the role assignmet is resettet when logging in? There is no error or something else. Role assignmet is controlled by groups in Active Directory. In the Log the systems says, that the role is assigned, but it's not.

This is happening actually with two users. Does anybody know about this or something similar.

Thank you!
Best regards, Michael

**Comment by svenoe** [comment]
Hi Mike,

there was a bug in the role assignment in the versions 10.1.3 and 10.1.4, but if you set up a new installation and are using 10.1.5 or 6, this is fixed. As for your other issue, though, please visit our forums if you are looking for community support.

Best regards, Sven

**Comment by MikeW83** [comment]
I think this issue is closed too fast... I had a fresh installation with 10.1.6 and migrated to it. Actually I have two users where this happens. In OTRS it was working. If this also happens with new users I have to check later.

**Comment by svenoe** [comment]
Hi Mike,

I'm sorry, but we are not providing OTOBO support on github.

If you are certain that you are encountering a bug, please at least provide a detailed description on how to reproduce it on a clean system (not a migration and without packages installed).

Especially if you are curious whether other people experienced similar issues or are uncertain whether everything is configured correctly, please also visit our forums, first.

OTOBO is open source and free to use, we have to finance ourselves, too, though, in the end, so if you need professional help with migration, setting up your system and/or support, please contact us via hello@otobo.de.

Best regards, Sven
