### ISSUE TITLE
File System permissions swapping

### ISSUE THREAD

**Issue by MikeW83** [RotherOSS/otobo#2115]
Hello. I have already raised a thread in the german forum, but I want to post it here too: https://otobo.de/de/forums/topic/bilder-werden-nicht-mehr-angezeigt/

I'm writing all mails to the file system and the permissions of the new created mails aren't always the same.

![image](https://user-images.githubusercontent.com/35097389/212658857-05f71760-4645-480f-a355-130a89f80d35.png)

I have to correct the permissions every few minutes with:  chown -R otobo:www-data
to see the full mail an all attachments.
best regards, Michael

**Comment by svenoe** [comment]
Hi Mike,

with general issues and questions please either stick to our forums or write an email to hello@otobo.de for professional support. Github is used for development issues only. Especially in your case, where you migrated an old system, it would be impossible for us to reproduce an error like this. Here files seem to be written by more than one process, it's difficult to say more.

Thanks for your understanding,
Sven
