### ISSUE TITLE
Kernel/System/SysConfig/Migration.pm does not compile

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#213]
Fix this module if it is still needed.

`# Can't locate scripts/MigrateFromOTRS/Base.pm in @INC (you may need to install the scripts::MigrateFromOTRS::Base module) (@INC contains: blib/lib /home/bernhard/devel/OTOBO/otobo /home/bernhard/devel/OTOBO/otobo/Kernel/cpan-lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0/x86_64-linux-gnu-thread-multi /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base /home/bernhard/devel/OTOBO/otobo /home/bernhard/devel/OTOBO/otobo/Kernel/cpan-lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/bernhard/devel/OTOBO/otobo/Kernel/cpan-lib/parent.pm line 16.
`

**Comment by bschmalhofer** [comment]
This is related to #190.
Sven, could you take a look at it? As I never looked into the migration procedures. Is migration from OTRS 5 actually supported? Also there seems to be some mixup 'OTRS' vs. 'OTOBO'. There is no such thing as OTOBO 5 or OTOBO 6.

**Comment by bschmalhofer** [comment]
Set the milestone to 10.1 because this should be an easy fix.

**Comment by bschmalhofer** [comment]
Base.pm is in _Kernel/System/MigrateFromOTRS_ not in _scripts/MigrateFromOTRS_. The package name was adapted. Closing.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I think you can remove this UnitTest, cause I think it's used for upgrading from 5 to 6. 

Best wishes,

Stefan

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO  
_Kernel/System/SysConfig/Migration.pm_ is compiling again, but I can't judge whether the module is still needed. If its no longer needed then please remove it. See also the other migration related failures at #190 ,

**Comment by rkarlsba** [comment]
Is this fixed in 10.1? I just got this error
[Mon Mar  1 16:58:12 2021][Error][Kernel::System::MigrateFromOTRS::CloneDB::Driver::Base::DataTransfer][792] Duplicate entry '328-Seen-25' for key 'ticket_flag_per_user', SQL: 'INSERT INTO ticket_flag (ticket_id, ticket_key, ticket_value, create_time, create_by) VALUES (?, ?, ?, ?, ?)'
Migrating from OTRS 6
