### ISSUE TITLE
After activating the Config parameter "CloseParentAfterClosedChilds" only the button "Close" is hidden.

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#2131]
After activating the Config parameter "CloseParentAfterClosedChilds" only the button "Close" is hidden. And the button "Quick Close" is not hidden! 

https://portal.rother-oss.com/otobo/index.pl?Action=AgentTicketZoom;TicketID=49729

**Comment by stefanhaerter** [comment]
Taking a quick look, I would assume that this is due to the following line not including AgentTicketQuickClose: https://github.com/RotherOSS/otobo/blob/99a57cf3a6938d5ce90457b9db6c9f5d41e4355e/Kernel/System/Ticket/Acl/CloseParentAfterClosedChilds.pm#L110

**Comment by bschmalhofer** [comment]
I suspect that this change broke the unit test script _scripts/test/Ticket/TicketACL/CloseParentAfterCloseChilds.t_:

```
ok 65 - Open Child - Action: 'AgentTicketProcess' should not be undefined in the ACL
ok 66 - Open Child - Action: 'AgentTicketQueue' should not be undefined in the ACL
not ok 67 - Open Child - Action: 'AgentTicketQuickClose' should not be undefined in the ACL (is 'undef')
ok 68 - Open Child - Action: 'AgentTicketResponsible' should not be undefined in the ACL
ok 69 - Open Child - Action: 'AgentTicketResponsibleView' should not be undefined in the ACL

```
My guess is that the test script must be updated to reflect the changed behavior.

@stefanhaerter, could you investigate this?

**Comment by stefanhaerter** [comment]
It looks like you're right. I made a PR and added AgentTicketQuickClose to the blacklisted actions in the unit test, which should fix the test.

**Comment by bschmalhofer** [comment]
PR is applied. Closing this issue after the next successful run of the test suite.

**Comment by bschmalhofer** [comment]
The test suite looks fine again. Closing this issue again.
