### ISSUE TITLE
Ticket hook "Nr." instead of "No." in English (US) TileTicketList and CustomerTicketOverview

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#2134]
Despite the fact that you see a "No." as kind of a hook in **CustomerTicketZoom** (English language setting), you see "Nr." as the same hook in the Dashboard Tile **TileTicketList** and in **CustomerTicketOverview**:

CustomerTicketZoom:
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/87359203/213688986-e67aff1b-e208-442f-820c-960ff608a97e.png">

TileTicketList:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/87359203/213689049-62bff0c9-6dee-42ab-9daa-3a6c1042b4f9.png">

CustomerTicketOverview:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/87359203/213688895-6164e0b5-48a3-4dd3-9605-1655cfb94680.png">

**Comment by bschmalhofer** [comment]
I was a bit confused because in the text of this issue I see the glyph for the numero sign, № - U+02116 - NUMERO SIGN, but in the screenshots I see three consecutive letters 'N', 'r', and '.'. When copying from the issue text and pasting to vim I also get the three letters. According to https://unix.stackexchange.com/questions/610690/firefox-converts-nr-to-how-to-fix this is an effect of the font that is active in Firefox. The font Nimbus Sans displays the three letters "Nr."  look just like the numero sign "№".

**Comment by bschmalhofer** [comment]
Contrary to expectations the SysConfig settings `Ticket::Hook`and `Ticket::HookDivider are not used in these views. Instead, the strings 'No.' and 'Nr.'. are hard coded in the templates.

```
bes:~/devel/OTOBO/otobo (rel-10_1)$ grep TicketNumber Kernel/Output/HTML/Templates/Standard/CustomerTicketZoom.tt 
            <p class="ooo12g" title="[% Translate('No.') | html %] #[% Data.TicketNumber | html %]">[% Translate('No.') | html %] #[% Data.TicketNumber | html %]</p>
bes:~/devel/OTOBO/otobo (rel-10_1)$ grep TicketNumber Kernel/Output/HTML/Templates/Standard/CustomerTicketList.tt 
    <a href="[% Env("Baselink") %]Action=CustomerTicketZoom;TicketNumber=[% Data.TicketNumber | uri %]" class="oooTicketListItem">
            <p class="oooTIDNumber ooo12g">[% Translate("Nr.") | html %] #[% Data.TicketNumber | html %]</p>
bes:~/devel/OTOBO/otobo (rel-10_1)$ 
```
In English the correct abbreviation for Number is 'No.' or the numero sign №. The translation files in _Kernel/Language_ are in that regards consistent, such that "No." is much more often translated than "Nr.". But then, in most cases in the customer interface the SysConfig setting `Ticket::Hook` is used. Therefore I propose to **standardize on `Ticket::Hook`**.  This is not a big change.

```
bes:~/devel/OTOBO/otobo (rel-10_1)$ grep -r -l 'N[or]\.' Kernel/ | grep -v Kernel/Language
Kernel/Output/HTML/Templates/Standard/CustomerTicketList.tt
Kernel/Output/HTML/Templates/Standard/CustomerTicketZoom.tt
Kernel/Output/HTML/Templates/Standard/AgentTicketZoom.tt

```

**Comment by bschmalhofer** [comment]
@svenoe aggreed to consistently use Ticket::Hook. Also made some smaller related fixes:

- [x] consistently HTML quote the ticket numbr
- [x] consistently use &mdash; for separating ticket number and title
- [x] in one instance added a space between HTML tag attributes

Checked the three views mentioned by @StefanAbel-OTOBO , merged PR, closing this issue.
