### ISSUE TITLE
Limited Unicode-Support when printing wide character

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2140]
I created a ticket with the following content in the first article:

📢 - U+1F4E2 - PUBLIC ADDRESS LOUDSPEAKER 
Ⅺ - U+0216A - ROMAN NUMERAL ELEVEN

When printing, choosing PDF file as target, the 📢 and the Ⅺ , were displayed as the placeholder box.

I also tried printing a configuration item. There the Ⅺ  was fine, but the 📢 got the placeholder.

[OTOBO Küchentisch - configitem_1024000001_2023-01-24_10-54.pdf](https://github.com/RotherOSS/otobo/files/10488886/OTOBO.Kuchentisch.-.configitem_1024000001_2023-01-24_10-54.pdf)
[OTOBO Ticket#2023012410000016 _ Test PDF Generation - Ticket_2023012410000016_2023-01-24_11 00.pdf](https://github.com/RotherOSS/otobo/files/10488887/OTOBO.Ticket.2023012410000016._.Test.PDF.Generation.-.Ticket_2023012410000016_2023-01-24_11.00.pdf)

**Comment by bschmalhofer** [comment]
This was with OTOBO 10.1.6 running in a Docker container.

**Comment by svenoe** [comment]
Check whether it's a PDF::API2 problem, and if, probably just ignore.

**Comment by bschmalhofer** [comment]
This seems to be a duplicate with #1848.
