### ISSUE TITLE
Adapt var/httpd/htdocs/index.html during migration

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2141]
@nm583 reported that in index.html /otrs/index.pl was not changed to /otobo. Thus the setting Frontend::DefaultInterface is not honored.

This this seems to an artefact of the migration from OTRS. An existing file _var/httpd/htdocs/index.html_ is copied from OTRS to OTOBO. This makes sense, as _var/httpd/htdocs/index.html_ might have been customized in OTRS. The original OTOBO file is still available in _/opt/otobo_install/otobo_next/var/httpd/htdocs/index.html_ .   Apparently the migration did some rewriting, changing "otrs/index.html" to "otobo/index.html" and "OTRS Redirect" to "OTOBO Redirect". 

I'm not sure whether the migration should generally  change the "/otrs/index.html" to "/otobo". I'll file it as an separate issue.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/1279#issuecomment-1403695803_

**Comment by svenoe** [comment]
After quick discussion, we would leave it as is, as long as "/otrs" or "/otrs/customer.pl" are not rewritten to "/otobo/index.pl". (I.e. as long as it is just an otrs to otobo substitution.)

This way the old OTRS behaviour is not changed, and people using OTRS should know that this file has (or had) to be configured.

**Comment by bschmalhofer** [comment]
Sounds good to me, closing this issue.
