### ISSUE TITLE
Error with Dynamic Fields dropdown while filtering

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#2143]
If you are in the overview by queues and set a filter on the column with the Dynamic Fields dropdown and select one that contains a space, the list of tickets is empty.

Ask me for further info.

**Comment by stefanhaerter** [comment]
Having a quick look, it appears to be the case that the query value arrives html-encoded in TicketSearch.pm, like so:

`'Equals' => 'ab%20cd'`

This does not match the correct value `'ab cd'`. At some point along the road, there seems to be a decode missing.

**Comment by stefanhaerter** [comment]
I think the core problem is that the search parameter is passed within the URL, but not decoded later on. I would suggest to implement `URI::ESCAPE::uri_unescape` for the corresponding field parameters, since `URI::Escape` is already included in `Kernel/cpan-lib`.
