### ISSUE TITLE
Mailserver timeout might prevent events from being executed.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#2148]
Please check, whether fetching multiple mails in one run uses the same ticket object, and thus the kill in the timeout in MailAccountFetch will prevent the execution of events triggered by the destruction of the ticket object.

https://github.com/RotherOSS/otobo/blob/9a6e290ad2a3137576d9940b16026358d8fd9292/Kernel/System/Console/Command/Maint/PostMaster/MailAccountFetch.pm#L119-L126

If so, please think about how to solve it. Probably discarding the ticket object somewhere within the run would be a possible solution.

**Comment by stefanhaerter** [comment]
So far, I think the assumption that the same ticket object is used seems reasonable to me. I did two test cases, one with two mails, the other with three mails to fetch. For the first test, two ticket objects where created. To confirm that the ticket object creation does not depend on the number of emails, I did the second test with three emails, and also two ticket objects where created.
