### ISSUE TITLE
Old OTRS Orange on pop up search close button

### ISSUE THREAD

**Issue by DasMetaphysischeparadoxon** [RotherOSS/otobo#2150]
Hi, 

every pop up search in OTOBO has the close button in the OTRS orange. i would like to see this replaced once by the OTOBO blue. The topic is perhaps not so important and would also be a matter of taste.

Current OTOBO:
![orange_hover](https://user-images.githubusercontent.com/50116610/216363892-5a159422-9041-4d14-b57d-b0b96515214b.png)

My suggestion:
![blue_hover](https://user-images.githubusercontent.com/50116610/216363873-6222b803-ad81-4a46-bf4a-4ca5fb8a2f54.png)

I found the OTRS color here:

https://github.com/RotherOSS/otobo/blob/a077e914380d1a13d5aa31472ea687353b614622/var/httpd/htdocs/skins/Agent/default/css/Core.Dialog.css#L82-L84

and for my screenshot i used #0000fc

best regards,
~ DMP

**Comment by svenoe** [comment]
Please compare other dialogs, I woud assume, that our font color (the almost black) would be more fitting here.

**Comment by DasMetaphysischeparadoxon** [comment]
The color that fades more into black is already set (#00023c). On my screenshots the close button is also shown when hovering over it. When hovering I would then use a lighter color again, hence my suggestion with the blue (#0000fc).

**Comment by svenoe** [comment]
After some discussion, the hover color was completely removed.
