### ISSUE TITLE
Attachment with Unicode filename and Umlaut crashes editor window

### ISSUE THREAD

**Issue by tnafele** [RotherOSS/otobo#2151]
- OTOBO 10.1.6
- Article::Backend::MIMEBase:: ArticleStorageFS

When creating a ticket or writing an answer: Attaching a file with German file name i.e. "Audw**ä**nde.ods" from an Unicode file system (Ubuntu en_US.UTF-8) makes the browser window crash:
 
> Can't open this page
> Try the following tips:
>  [...[
> Error code: RESULT_CODE_KILLED_BAD_MESSAGE

**Comment by svenoe** [comment]
Hi tnafele,

I'm certain that this works on vanilla installations of OTOBO. We are based in Germany and we have a lot of customers from German speaking countries. Please check your Ubuntu installation, maybe try a new installation of OTOBO on a clean Ubuntu installation to compare,...

In any case, when opening an issue, please add the OTOBO logs, relevant syslog entries etc., and if you are using a non-standard fs, e.g., also more specifics would be necessary.

Best regards, Sven

**Comment by tnafele** [comment]
Hi Sven,

hard to tell for me from which point it's considered to no being vanilla anymore... I didn't modify any of the files, only set it up using the web GUI.
It's a Debian 10.13, not Ubuntu.
File system is ext4,
Locales is en_US.UTF-8 as default but also de_CH.UTF-8 is installed on the server.
Unfortunately I set OTOBO to log to a file but could never find the logfile so far. Shouldn't it be in /tmp?
I will switch this back to the default (syslog) and report back.

Best regards
t

**Comment by bschmalhofer** [comment]
Closing this issue as problems with non-Ascii file names have not surfaced again.
