### ISSUE TITLE
Remove San Miguel from the footer.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#2156]
Our partner San Miguel seemingly sold their domain they gave us as a link two years ago, and we are now linking to some sort of Casino. Please, for the moment, remove the link from the footer on the customer frontend.

**Comment by stefanhaerter** [comment]
#2191 and #2192 merged, closing issue.

**Comment by bschmalhofer** [comment]
Reopening because this change broke at least two test scripts.
Not sure whether the svg can be removed too.
Maybe update the URL in AUTHORS.md as well.

```
bes:~/devel/OTOBO/otobo (rel-10_0)$ grep -r sanmiguel
ARCHIVE:8ad80f8cfb0a10d60db6e954aff3ca4d::var/httpd/htdocs/skins/Customer/default/img/sanmiguel_g.svg
grep: .git/index: Übereinstimmungen in Binärdatei
AUTHORS.md:* San Miguel Team https://www.sanmiguel-brand-partner.com
scripts/test/Selenium/Customer/FooterLinks.t:            q{https://www.sanmiguel-brand-partner.com},
scripts/test/Selenium/Customer/Login.t:            DesignedBy => qr{designed by.{5,30}https://www\.sanmiguel-brand-partner\.com}s,
var/httpd/htdocs/skins/Customer/default/img/sanmiguel_g.svg:   sodipodi:docname="sanmiguel_g.svg"
bes:~/devel/OTOBO/otobo (rel-10_0)$ 

```

**Comment by stefanhaerter** [comment]
Regarding AUTHORS.md: I just googled, whould the link [https://www.sanmiguel.io/de/ux-ui-branding-agentur-muenchen ](https://www.sanmiguel.io/de/ux-ui-branding-agentur-muenchen )be appropriate?

**Comment by bschmalhofer** [comment]
I would simply go with https://www.sanmiguel.io/. The deep link is prone to change in the future.

**Comment by stefanhaerter** [comment]
Removing the SanMiguel lines from the unit tests seems to fix the problem, but running the FooterLinks test in docker with selenium results in two errors anyways, complaining that Unicode::GCString is not installed, if I interpret this correctly.

**Comment by bschmalhofer** [comment]
Ran the test suite for rel-10_0 and found no errors related to this change. Closing this issue.
