### ISSUE TITLE
No total sum of tickets in "Ticket Queue Overview" on Agent Dashboard

### ISSUE THREAD

**Issue by DasMetaphysischeparadoxon** [RotherOSS/otobo#2161]
Hi, 

it seems that the "Ticket Queue Overview" widget on the dashboard does not show a total sum of all tickets.

For example:

![Screenshot_2023-02-10_11-05-29](https://user-images.githubusercontent.com/50116610/218064533-dfa34e30-843c-484b-bac5-fb156b7335c7.png)

best regards,
~ DMP

**Comment by svenoe** [comment]
Low prio
