### ISSUE TITLE
Update CPANAudit

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2196]
Running UnitTests under docker and native with Perl 5.36, _./scripts/test/Console/Command/Dev/Code/CPANAudit.t_ does not issue any warnings, but does so when being run under Ubuntu 18 with Perl 5.26. A suspicion @bschmalhofer has is that the CPANAudit module does not work correctly.

**Comment by bschmalhofer** [comment]
I think that CPAN::Audit should be updated to the most current version. How the findings are handled in the unit tests is another question. It is to be expected that different environments will produce different findings.

**Comment by bschmalhofer** [comment]
I updated my local branch to CPAN::Audit 20230826.001 and switched to JSON output. In the Docker image 9 violations are reported. Some of those refer to old versions in _Kernel/cpan-lib_ . I propose to fix those low hanging fruits before discussing which advisories should be exempted.

**Comment by bschmalhofer** [comment]
Updated `File::Slurp`and `YAML` which triggered three advisories. Adapted the test script to check only the sanity of the printed JSON. It can't be expected that there are no advisories, therefore it is fine when the exit code is one.

The test suite looks fine. PR is merged. Closing this issue.

**Comment by bschmalhofer** [comment]
CPAN::Audit has had new releasese since August 2023, https://metacpan.org/dist/CPAN-Audit/changes. Let's update the module.
