### ISSUE TITLE
Layout glitch in calendar event popup when a notification is set

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2219]
In an installation of OTOBO 10.1.x HEAD I created a calendar entry with a notification '5 m before'. This worked fine. However, there is a glitch when viewing the details in the calendar overview. The values start all on new lines. My browser is Firefox 110.0.1, the current version in Ubuntu 12.04.
![Bildschirmfoto vom 2023-03-09 12-51-06](https://user-images.githubusercontent.com/46019/224016413-f6f51a4e-3878-41c6-9a29-5f176abafdbd.png)

**Comment by svenoe** [comment]
This is likely introduced with some of the changes made to css recently. Please check and see whether it also affects 10.0 or not.

**Comment by bschmalhofer** [comment]
Changed the milestone to 10.0.18 as the same glitch occurs in OTOBO 10.0.x

**Comment by stefanhaerter** [comment]
I went back till a commit from April 2nd, 2022 on rel-10_1, and it looks identically (rebuilt config, deleted cache via command line and in browser, restarted apache2) - can we tell how the desired layout of the tooltip would be?

**Comment by stefanhaerter** [comment]
Investigation and hints by @bschmalhofer showed that the bug is related to the notification icons, which are supposedly not closed correctly, thus the browser closes them itself, including the fieldset into the icon and so invalidating the relevant CSS for the fieldset. Fix will consist of closing the i-tags correctly.

**Comment by stefanhaerter** [comment]
Somehow, the recurring flag isn't set when rendering the icons, even at a recurring parent or child appointment. Also, I couldn't trigger ticket appointment types to be set.

**Comment by stefanhaerter** [comment]
Fixed with #2225
