### ISSUE TITLE
Bug with Appointment Tooltip Icons

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2223]
Somehow, the recurring flag isn't set when rendering the icons, even at a recurring parent or child appointment. Also, I couldn't trigger ticket appointment types to be set.

_Originally posted by @stefanhaerter in https://github.com/RotherOSS/otobo/issues/2219#issuecomment-1462254679_

**Comment by stefanhaerter** [comment]
At least the recurring icon seems to be a cache error.

**Comment by bschmalhofer** [comment]
I have set the milestone to 10.0 as the original issue #2219  was also resolved in 10.0.

**Comment by stefanhaerter** [comment]
The ticket appointment type seems to be related to Kernel/Modules/AgentAppointmentList.pm. Dynamic fields TicketCalendarStartTime and TicketCalendarEndTime are also related. They are used within the example process var/processes/examples/Conference_Room_Reservation.yml.

As #2219 is already solved, I think about closing this one, too.

**Comment by stefanhaerter** [comment]
Didn't observe the behavior again, closing the issue.
