### ISSUE TITLE
PDF files get corrupted when forwarding

### ISSUE THREAD

**Issue by escix** [RotherOSS/otobo#2231]
When I forwarded an email with PDF the file getting corrupted.

Comparing the original and forwarded files it looks like the some of the last lines of the file is removed.

 Not sure if this is the same for any binary files.

Article Storage is in FS.

**Comment by svenoe** [comment]
Hi escix,

could you please tell us your version of OTOBO, whether you have any packages installed, and/or custom modifications in the system, and then optimally export a test email, which contains a PDF which shows this behaviour and attach it here (you can edit the file and strip out all email addresses and other information in the headers), or send the eml to us directly (hello@otobo.de)? Then we could try to reproduce this behavior.

Best regards, Sven

**Comment by escix** [comment]
Hi Sven,

I couldn't replicate it, but it happened more than once.

I will do some tests and let you know under what circumstances this is happening. But happy for you to close it for now.

**Comment by svenoe** [comment]
Ok, as soon as you have an email, which can help us reproduce this behaviour, please send it to us in some way.

Best regards
