### ISSUE TITLE
Customer Portal: "Reply"-button shown but not working for closed tickets

### ISSUE THREAD

**Issue by markus-gitdev** [RotherOSS/otobo#2240]
In the customer portal the button "Reply" is shown for closed tickets, but nothing happens when clicked.

It would be better if it wasn't shown or brings up a pop-up which information like "The ticket is already closed and replies aren't allowed" or (and in my opinion this would be the best option) if it was replaced with something like "Create new linked ticket", which automatically creates a new ticket and the new ticket gets automatically linked to the previous closed ticket.

_P.S.: The "Reply"-button works perfectly fine for tickets, which aren't already closed._

**Comment by svenoe** [comment]
Hi Markus,

thanks, this is a bug. The button doesn't respect the queue setting "followup possible" properly. We will fix this.

Best regards, Sven

**Comment by stefanhaerter** [comment]
Closed with merging #2526
