### ISSUE TITLE
Customer Portal: Bad UI/UX for "Your last tickets"

### ISSUE THREAD

**Issue by markus-gitdev** [RotherOSS/otobo#2242]
@svenoe:
Since I can't reply in the previous issue #2241:

Maybe it would then be better if you rename the tile to something like "Your last X tickets", but show all the amount instead of cutting the last on off.
As of now, it just looks like this is a bug ...

And maybe you could even consider this further and make it configurable in the user profile to show for e.g. 5, 10, 15, ... tickets in this main dashboard and update the title accordingly.

If that's also no option, I'm OK with it. I just wanted to give feedback on how to maybe improve this (since one of our customers pointed this out to us and told us about this "bug").

**Comment by svenoe** [comment]
Hi Markus,

strange, people should be able to answer in closed issues, too, I thought.

Anyhow - I would argue that this is something subjective, and as I said before, if we will get more feedback in this direction, we are certainly willing to change this. (Even then there are a lot of things to work on, though.) If this is something important to you, in the meantime you are free to contact us via hello@otobo.de, we also offer paid customizations of otobo.

Best regards, Sven

(I will leave this open now for a day or so, and then close it...)

**Comment by markus-gitdev** [comment]
I'm sorry, if my initial reply caused confusion.
This is an answer about the cut off tickets (issue #2241) in the main dashboard of the customer portal, not about replying to closed tickets (that is issue #2240).

It's not urgent, my intention is to provide feedback/suggestions on how to improve the UI/UX in this regard, since the agents normally aren't that aware of issues in the customer portal, and we also only noticed this because a customer provided feedback about it.

And you are right: It is subjective, but I have to admit that our customer is also right and a cut off ticket (marked red in the screenshot of the previous issue, where you can only see the top of an avatar and the ticket is even clickable, without seeing the title and ticket number) just doesn't look/feels right.

**Comment by svenoe** [comment]
I understood, and the feedback was received. Still, as I said, this is subjective, so it would need a couple more people wanting this at the moment, for us to change it, especially since there is enough work with relatively high priority to be done, too.

I will close this issue, too, to try to keep things here tidy.
Sven
