### ISSUE TITLE
Fix CodePolicy violations for Kernel/System/Stats.pm

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2249]
Output of the CodePolicy:

```
[checked] Kernel/System/Stats.pm
[33mTidyAll::Plugin::OTOBO::Perl::PerlCritic[0m
[31mInputOutput::ProhibitBarewordDirHandles violated at Kernel/System/Stats.pm 995 column 11 (Severity: 5)
  Bareword dir handle opened
See pages 202,204 of PBP
 InputOutput::ProhibitBarewordDirHandles violated at Kernel/System/Stats.pm 3875 column 11 (Severity: 5)
  Bareword dir handle opened
See pages 202,204 of PBP[0m

```

**Comment by bschmalhofer** [comment]
CodePolicy is satisfied, PR is merged, closing this issue.

**Comment by stefanhaerter** [comment]
As far as I managed to track down, the change regarding the directory handles breaks Kernel/System/Stats.pm, at least in my fresh installation of rel-11_0. I keep getting this message:

`Can't use an undefined value as a symbol reference at /opt/otobo/bin/psgi-bin/../../Kernel/System/Stats.pm line 3888.\n`

Reopening the issue.

**Comment by bschmalhofer** [comment]
CodePolicy is still happy after applying the PR. Closing again.
