### ISSUE TITLE
Suggestion: remove support for Basic Auth

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#225]
Basic Auth is so 1990s. Let's discuss it.

**Comment by bschmalhofer** [comment]
Set milestone to 11.0, as this is a significant change.

**Comment by svenoe** [comment]
At the moment this, in my eyes, is definitely needed for web services. For now I don't see this happening.

**Comment by bschmalhofer** [comment]
There is another reason for keeping _Kernel/System/Auth/HTTPBasicAuth.pm_ and _Kernel/System/CustomerAuth/HTTPBasicAuth.pm_. These modules are basically checking the PSGI parameter REMOTE_USER. This parameter does not necessarily come from classic basic authentication. It might also come from an proxy webserver or from a Plack middleware.
