### ISSUE TITLE
Implement some leeway when checking OpenIDConnect auth data

### ISSUE THREAD

**Issue by ict** [RotherOSS/otobo#2266]
OTOBO currently checks the "issued at" timestamp from the logon server when validating a session:

https://github.com/RotherOSS/otobo/blob/be31115202e70f46975d4287de3f3fe8d94639f3/Kernel/System/OpenIDConnect.pm#L370

This leads to false logon fails when the system time of either OTOBO or the Auth server differs in just a single second (and since the `iat` is only measured in seconds without fractions, even a much smaller discrepancy in hardware clocks will cause it).
My proposal would be to implement a leeway of a few seconds to combat this. This applies to all timestamps in the token (`iat`, `exp`), with different directions of the leeway that should be applied.

An example library doing this is pyjwt:
https://github.com/jpadilla/pyjwt/blob/777efa2f51249f63b0f95804230117723eca5d09/jwt/api_jwt.py#L272

Best regards
Demian

**Comment by svenoe** [comment]
Hi Demian,

thanks for letting us know. Your suggestion makes sense, we will implement a small, configurable leeway at the respective places.

Best regards, Sven
