### ISSUE TITLE
Redis error: Could not connect to Redis server at redis:6379 at /opt/otobo_install/local/lib/perl5/x86_64-linux-gnu/Redis/Fast.pm line 246. !

### ISSUE THREAD

**Issue by mojstav** [RotherOSS/otobo#2271]
Hello,

Cann you please help me.
![Screenshot from 2023-04-12 07-08-41](https://user-images.githubusercontent.com/74152892/231380019-a2a548a3-0ca6-4cbb-9868-c70927f53d21.png)

I m new in Otobo. I have install Linux, Gui and otobo at my computer, and its all work fine. And I m move computer in another Hause with another connection, and now when i open link http://localhost/otobo/index.pl in web browser I have this problem:

Ein Fehler ist aufgetreten
Redis error: Could not connect to Redis server at redis:6379 at /opt/otobo_install/local/lib/perl5/x86_64-linux-gnu/Redis/Fast.pm line 246. !

Bitte kontaktieren Sie den Administrator.

Einen Fehlerbericht senden  oder  [Zurück zur vorhergehenden Seite](http://localhost/otobo/index.pl#)

Fehlerdetails
Backend ERROR: OTOBO-CGI-91 Perl: 5.36.0 OS: linux Time: Tue Apr 11 14:18:28 2023

 Message: Redis error: Could not connect to Redis server at redis:6379 at /opt/otobo_install/local/lib/perl5/x86_64-linux-gnu/Redis/Fast.pm line 246.
!

 RemoteAddress: 192.168.227.94
 RequestURI: /otobo/index.pl

 Traceback (19): 
   Module: Kernel::System::Cache::Redis::_Connect Line: 253
   Module: Kernel::System::Cache::Redis::Set Line: 65
   Module: Kernel::System::Cache::Set Line: 253
   Module: Kernel::Output::Template::Provider::_compile Line: 263
   Module: Kernel::Output::Template::Provider::_fetch Line: 167
   Module: Template::Provider::_fetch_path (v3.100) Line: 527
   Module: Template::Provider::fetch (v3.100) Line: 146
   Module: Template::Context::template (v3.100) Line: 141
   Module: Template::Context::process (v3.100) Line: 312
   Module: Template::Context::include (v3.100) Line: 416
   Module: (eval) (v3.100) Line: 87
   Module: Template::Document::__ANON__ (v3.100) Line: 7
   Module: (eval) (v3.100) Line: 166
   Module: Template::Document::process (v3.100) Line: 164
   Module: Kernel::Output::Template::Document::process Line: 48
   Module: (eval) (v3.100) Line: 354
   Module: Template::Context::process (v3.100) Line: 324
   Module: (eval) (v3.100) Line: 96
   Module: Template::Service::process (v3.100) Line: 93
   Module: Template::process (v3.101) Line: 66
   Module: Kernel::Output::HTML::Layout::Template::Output Line: 211
   Module: Kernel::Output::HTML::Layout::Header Line: 1614
   Module: Kernel::Output::HTML::Layout::FatalError Line: 965
   Module: Kernel::System::Web::InterfaceAgent::Content Line: 211
   Module: Kernel::System::Web::InterfaceAgent::Response Line: 1321
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: `217```

**Comment by svenoe** [comment]
Hi mojstav,

I'm sorry, but github is only for development issues, so I will close this issue. For community support please visit our [forums](https://otobo.de/de/forums/). We also offer professional support. For more information on that, please write an email to hello@otobo.de.

Best regards, Sven
