### ISSUE TITLE
Rebuild_Config

### ISSUE THREAD

**Issue by mscoppettuolo** [RotherOSS/otobo#2272]
Hi when i execute 
otobo@cp-otobo-s2:~$ ./bin/otobo.Console.pl Maint::Config::Rebuild
Rebuilding the system configuration...
Use of uninitialized value $InitValue in hash element at /opt/otobo/Kernel/System/SysConfig.pm line 2532.
Use of uninitialized value $InitValue in concatenation (.) or string at /opt/otobo/Kernel/System/SysConfig.pm line 2533.
ERROR: OTOBO-otobo.Console.pl-Maint::Config::Rebuild-61 Perl: 5.34.0 OS: linux Time: Wed Apr 12 09:09:46 2023

 Message: Invalid otobo_config Init value ()! Allowed values: Framework, Application, Config, Changes.

 Traceback (2864):
   Module: Kernel::System::SysConfig::ConfigurationXML2DB Line: 2533
   Module: Kernel::System::Console::Command::Maint::Config::Rebuild::Run Line: 135
   Module: (eval) Line: 480
   Module: Kernel::System::Console::BaseCommand::Execute Line: 474
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 88
   Module: ./bin/otobo.Console.pl Line: 35

Done.
otobo@cp-otobo-s2:~$

i am trying to install a new skin for agent, but it happens also with default skin

Someone can help me?
Besta regards

**Comment by svenoe** [comment]
Hi mscoppettuolo,

please ask questions around OTOBO in our [forums](https://otobo.de/de/forums/), github is reserved for our own development issues and bugs (if they are reproducable on a standard installation of OTOBO).

As a hint, though, have a look at your xml files, which you probably added, and compare the first lines with e.g. Ticket.xml.

Best regards, Sven
