### ISSUE TITLE
New dynamic field types: Reference and Lens

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2298]
Two new field types are deemed to be useful for OTOBO 11.0.x:

**Reference**
A dynamic field that references another entity, like Ticket, FAQ, or Configitem. Only entities supporting dynamic fields can be linked. The config of an instance of ReferenceDF holds information about the type of the linked objects and optionally further restrictions, like the class of a config item. This is a bit more restrictive than linking via the link table. The reference entity can't be changed via the dynamic fields.

**Lens**
The name refers to https://en.wikipedia.org/wiki/Bidirectional_transformation. It allows to read and write a dynamic field of an entity that is available via the Reference DF. Not sure whether that really is bijective. The design explicitly allows for direct manipulation of the internals of another object. So care must be taken when defining a dynamic field of the type Lens. The config of Lens DFs hold dynamic field id of a Reference DF and the dynamic field id of a DF that is supported by the Reference DF.

**Comment by bschmalhofer** [comment]
This feature is based on the enhancements done for #2251.

**Comment by bschmalhofer** [comment]
I noticed that dynamic fields types are declared in different XML files. This makes sense for specialized dynamic fields types, like the types used by process management. But it makes no sense that generally usable dynamic fields like **Text** or **Multiselect** are declared in _Ticket.xml_.

**Comment by StefanAbel-OTOBO** [comment]
Please make sure that the objects are actually linked to each other (so that you can scroll down to the link objects and reach them).
(I'm just trying to make sure that I have the same understanding of "linked".)

**Comment by svenoe** [comment]
> Please make sure that the objects are actually linked to each other (so that you can scroll down to the link objects and reach them). (I'm just trying to make sure that I have the same understanding of "linked".)

No, they won't be linked via standard links. (We can think about an extension which does this later, but not currently.)

**Comment by svenoe** [comment]
> I noticed that dynamic fields types are declared in different XML files. This makes sense for specialized dynamic fields types, like the types used by process management. But it makes no sense that generally usable dynamic fields like **Text** or **Multiselect** are declared in _Ticket.xml_.

As written before, the dynamic fields in Ticket.xml are the OTRS standard dynamic fields. The config of special dynamic fields like Webservices etc., which were added with OTOBO were written to a separate file. This is not consistent and can be improved, but it has no high priority either.

**Comment by bschmalhofer** [comment]
Test suite looks mostly fine:

_DynamicFieldDatabase.t_ is sporadic. _OverviewSmall.t_ still needs to be investigated.


```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1798 Failed: 0)
  TODO passed:   686, 811
/opt/otobo/scripts/test/Selenium/Customer/DynamicFields/DynamicFieldDatabase.t                            (Wstat: 256 (exited 1) Tests: 137 Failed: 1)
  Failed test:  137
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/Output/Ticket/OverviewSmall.t                                            (Wstat: 256 (exited 1) Tests: 39 Failed: 1)
  Failed test:  39
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
Files=961, Tests=80653, 3619 wallclock secs (15.62 usr  1.92 sys + 740.10 cusr 105.71 csys = 863.35 CPU)
Result: FAIL
ran tests for product OTOBO 11.0.x on host ba7bc17f47ec .

```

**Comment by bschmalhofer** [comment]
No failures in the latest run:

```
Test Summary Report
-------------------
/opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1798 Failed: 0)
  TODO passed:   686, 811
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
Files=961, Tests=80826, 4052 wallclock secs (15.70 usr  2.10 sys + 1123.96 cusr 101.29 csys = 1243.05 CPU)
Result: PASS
ran tests for product OTOBO 11.0.x on host 7ae7be5a35cc .

```

**Comment by bschmalhofer** [comment]
More developments took place in the mean time and new developments should have dedicated issues. So, closing this issue.
