### ISSUE TITLE
otobo/var/Logo-otobo-pdf.png not found error

### ISSUE THREAD

**Issue by escix** [RotherOSS/otobo#2312]
When trying to print PDF, this error getting logged.

Looks like this file is missing.

**Comment by svenoe** [comment]
Hi escix,

Logo-otobo-pdf.png is not part of the standard installation, and is also not used anywhere. Maybe you did a migration and it comes from an old config. In general if you encounter errors, please make sure that they are reproducible on a plain standard installation of OTOBO. If they are not, you can visit our [forums](https://otobo.de/de/forums/) to seek for help of the community. This github is only used for development issues and not support.

Thanks for your understanding, Sven
