### ISSUE TITLE
Clean up mentions of OTOBO 5 and OTOBO 6

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#232]
In these cases it can be presumed that either legacy version of OTRS or OTOBO 10 is meant.

**Comment by bschmalhofer** [comment]
In the migration modules and tests there are frequent mentions of OTOBO 5 and OTOBO 6. This is confusing as OTOBO starts with Version 10. 
I checked with the following commands:

- `grep -r -i 'otobo\s*[0123456789]' . | grep -v  -i 'otobo\s*10'`
- `find . -iname '*OTOBO[0123456789]*'`

I could do the renaming, but I would need some clarification concerning the migration pathes. OTRS 5 => OTOBO 10 vs, OTRS 6 => OTOBO 10.

**Comment by bschmalhofer** [comment]
Note that the only relevant migration is from OTRS 6 to OTOBO 10.

**Comment by bschmalhofer** [comment]
The UnitTests look fine. Closing.

**Comment by bschmalhofer** [comment]
Should this be backported to the rel-10_0 branch? Already for 10.0.4 ?

**Comment by StefanRother-OTOBO** [comment]
Hi,

I think this UnitTests are for migration OTRS 5 to 6, cause I do not create UnitTests for migrating to OTOBO yet. 
For me it's fine to remove the tests.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
I cherry-picked the commits for this branch into the rel-10_0 branch. Let's close this issue again when things look fine again. There might be some fallout from resolving the merge conflicts.

**Comment by bschmalhofer** [comment]
Did a final check on rel-10_0 and repaired info@otrs365.com.  Closing this issue again.
