### ISSUE TITLE
Not able to use dynamic fields with ElasticSearch

### ISSUE THREAD

**Issue by wetzf** [RotherOSS/otobo#2334]
Hello OTOBO Team, 

I want to search for dynamic field values via elastic search. To get there, I added a new dynamic field of type 'text' to 'Elasticsearch::TicketSearchFields'. I added the correspondig update event to 'TicketManagement' in the Webservice 'ElasticSearch'.
For newly created tickets I was not able to search for values in this dynamic field.

With the Webservice debugger I found out, that the value is initially set by the event 'TicketCreate' but is immediately reset to 'undef' by the DynamicFieldUpdate event.

TicketCreate:
``` 
$VAR1 = {
  'ArticlesExternal' => [],
  'ArticlesInternal' => [],
  'AttachmentsExternal' => [],
  'AttachmentsInternal' => [],
  'Created' => 1686148409,
  'CustomerID' => '123',
  'CustomerUserID' => 'wetzf',
  'DynamicField_Suchtest' => 'orbitaltotal',
  'GroupID' => 1,
  'QueueID' => 4,
  'TicketID' => 6,
  'TicketNumber' => '2023060710000058',
  'Title' => 'Blubber',
  'docapi' => '_doc',
  'id' => 6
}; 
```

TicketDynamicFieldUpdate_Suchtest:
```
$VAR1 = {
  'doc' => {
    'CustomerID' => '123',
    'CustomerUserID' => 'wetzf',
    'DynamicField_Suchtest' => undef,
    'GroupID' => 1,
    'QueueID' => 4,
    'TicketID' => 6,
    'Title' => 'Blubber'
  },
  'docapi' => '_update',
  'id' => 6
};
```

Turns out there is a typo in [Kernel/GenericInterface/Invoker/Elasticsearch/TicketManagement.pm](https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/GenericInterface/Invoker/Elasticsearch/TicketManagement.pm#LL647C13-L647C26). This should be 'DynamicFields', with 's'.
After I changed that, the search worked for me. I will create a pull request for this.

Kind regads

**Comment by svenoe** [comment]
Thanks, pr is merged. :)

**Comment by svenoe** [comment]
Added for rel-10_0; Tidied;
