### ISSUE TITLE
Set email for system

### ISSUE THREAD

**Issue by RicciLujan** [RotherOSS/otobo#2337]
i try to set the email account and when i try to reply a ticket this error happens:

Backend ERROR: OTOBO-CGI-87 Perl: 5.36.0 OS: linux Time: Fri Jun 9 10:44:25 2023

 Message: Impossible to send message to: "Luigi Nuñez" <riccilujanyt@outlook.es> .

 RemoteAddress: 88.20.186.10
 RequestURI: /otobo/index.pl

 Traceback (16): 
   Module: Kernel::System::Ticket::Article::Backend::Email::ArticleSend Line: 310
   Module: Kernel::Modules::AgentTicketCompose::Run Line: 1034
   Module: Kernel::System::Web::InterfaceAgent::Content Line: 1239
   Module: Kernel::System::Web::InterfaceAgent::Response Line: 1321
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 217
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 187
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 173
   Module: Plack::Middleware::HTTPExceptions::try {...}  Line: 20

**Comment by svenoe** [comment]
Hi RicciLujan,

sorry, but please visit our [forums](https://otobo.de/de/forums/) for general questions and community support. Github is for development topics only.

Thanks for your understanding, best regards, Sven
