### ISSUE TITLE
problem with customer portal

### ISSUE THREAD

**Issue by elmer303** [RotherOSS/otobo#2345]
Backend ERROR: OTOBO-CGI-60 Perl: 5.36.0 OS: linux Time: Sat Jun 10 11:35:11 2023

 Message: Registration for tile InfoTile-01 of CustomerDashboard is invalid! Order needs to be a unique number.

 RemoteAddress: 91.217.0.4
 RequestURI: /otobo/customer.pl

 Traceback (25): 
   Module: Kernel::Modules::CustomerDashboardCommon::Run Line: 106
   Module: Kernel::System::Web::InterfaceCustomer::Content Line: 1452
   Module: Kernel::System::Web::InterfaceCustomer::Response Line: 1534
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 500
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 217
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 187
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 173
   Module: Plack::Middleware::HTTPExceptions::try {...}  Line: 20

**Comment by svenoe** [comment]
Hi Elmer,

sorry, but please visit our [forums](https://otobo.de/de/forums/) for general questions and community support. Github is for development topics only.

Thanks for your understanding, best regards, Sven
