### ISSUE TITLE
Fix permissions

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2364]
On rel-10_1 and further on, the result of `sudo bin.otobo.SetPermissions` produces a diff regarding the two files:

- `Kernel/Modules/AgentTicketZoom.pm`
- `Kernel/Output/HTML/TicketZoom/TicketInformation.pm`

I would suggest to commit the files with the correct permissions.

**Comment by bschmalhofer** [comment]
PR is applied. Closing this issue.
