### ISSUE TITLE
Add support for data-attributes in BuildSelection()

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2372]
Sometimes, e.g. in the AdminDynamicFields frontend, selection lists are abused for navigation. This is fine. The code to achieve this is a bit convoluted. There is setup in Core.Config and a lot of JavaScript. Enriching the options with data-attributes  could be a way to simplify things. See https://www.w3schools.com/tags/att_data-.asp.

This means that `BuildSelection()` needs to be enhanced for the case where a ArrayHashRef is passed.

**Comment by stefanhaerter** [comment]
What do you think of the following diff as a proposal for this issue?

https://github.com/RotherOSS/otobo/compare/rel-11_0...issue-%232372-selection_data_attributes

To be honest, it is bit of quick and (perhaps) dirty, but I thought about this topic as I think I have another use case for data attributes in selects.

**Comment by bschmalhofer** [comment]
I think that this needs some kind of quoting or sanity checks. For example, passing the data attribute  
`{  qq[dummy="dummy" selected} => '1' } `
would produce HTML like
`data-dummy="dummy" selected="1"`
Thus the parameter  can be abused to set arbitrary attributes.

**Comment by stefanhaerter** [comment]
Good point. Perhaps this can be included with some kind of data structure handling, which I have still to think about in general. The similar lines above the change perform a json encoding, and I am undecided whether this makes sense for custom data attributes.

**Comment by bschmalhofer** [comment]
Closing, as the convention is that issues in the wishlist should be closed.
