### ISSUE TITLE
IMAPOAuth2 not working anymore for MS365 / Office365 / Azure accounts

### ISSUE THREAD

**Issue by bbqrob** [RotherOSS/otobo#2373]
Connections via IMAPOAuth2 do not work anymore with MS365 accounts, giving the following error after 600 seconds (which is the timeout for connecting there):

```
Something went wrong while trying to connect to 'IMAPOAuth2 => somemailbox@myhost.com/outlook.office365.com': Can't call method "authenticate" on an undefined value at /opt/otobo/bin/psgi-bin/../../Kernel/System/MailAccount/IMAPOAuth2.pm line 83.
```

That behaviour shows up in 3 different otobo instances (v10.1.5 and v10.1.6) using two different tenants from MS. Azure setup has been done according to the documentation here: https://doc.otobo.org/manual/admin/10.1/en/content/communication-notifications/postmaster-mail-accounts.html?highlight=mail#azure-configuration and worked already for almost 6 month.

**Comment by svenoe** [comment]
Hi Robert,

in general please visit [our forums](https://otobo.de/de/forums/topic/imap-verbindung-zu-m365-mit-oauth2-nicht-mehr-moeglich/#post-15317) for support questions. (Besides in this case looking in the [repo of the respective package](https://github.com/RotherOSS/MailAccount-OAuth2/pull/6) would also help.)

Best regards, Sven
