### ISSUE TITLE
new failure in AgentAppointmentCalendarOverview.t  

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2375]
Test failures are almost gone now, but there is a new failure:
```
/opt/otobo/ scripts/test/Selenium/Agent/AgentAppointmentCalendarOverview.t                                 (Wstat: 257 (exited 1) Tests: 165 Failed: 1)
  Failed test:  165
  Non-zero exit status: 1
```
Looks like some kind of Layout issue, likely not related to the JSON changes. Let's handle this in a new issue.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/2371#issuecomment-1613388799_

**Comment by stefanhaerter** [comment]
For me, it looks like the failing test is indicating that the timeline views in CalendarOverviews are broken.

**Comment by bschmalhofer** [comment]
This was needed because of the switch to Cpanel::JSON::XS, see #399 . When an empty string was added to Core.Config, then with the module `JSON`  it was serialized for JS as null. With the module `Cpanel::JSON::XS` the empty string is serialized as the empty string. This broke the `IsRTLLanguage` property used by the JS libraries datepicker and fullcalendar.

**Comment by bschmalhofer** [comment]
The test succeeds now again. A manual tests looked fine too. Closing this issue.

**Comment by bschmalhofer** [comment]
The expression

`( $TextDirection eq 'rtl' ) ? $Kernel::OM->Get('Kernel::System::JSON')->True() : $Kernel::OM->Get('Kernel::System::JSON')->False(),`

is a bit complicated. Let's add a method `Kernel::System::JSON::Bool` that takes a Perl value and turns it into `true` and `false`according to Perl rules. This means that the string `q{0}` will be converted to `false`.
