### ISSUE TITLE
Frontend::CommonParam###Action is declared twice

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2377]
That setting is declared in both Framework.xml and Ticket.xml. Ticket.xml wins.  AFAIK there is no scenario that works without Ticket.xml. So let's remove it in Framework.xml.

The question why these common parameters end up in the layout object is not part of this issue.

Kernel/Config/Files/XML/Framework.xml:
```
    <Setting Name="Frontend::CommonParam###Action" Required="0" Valid="1">
        <Description Translatable="1">Defines the default value for the action parameter.</Description>
        <Navigation>Frontend::Agent</Navigation>
        <Value>
            <Item ValueType="String" ValueRegex="">AdminInit</Item>
        </Value>
    </Setting>

```

_Kernel/Config/Files/XML/Ticket.xml_:
```
    <Setting Name="Frontend::CommonParam###Action" Required="1" Valid="1">
        <Description Translatable="1">Defines the default used Frontend-Module if no Action parameter given in the url on the agent interface.</Description>
        <Navigation>Frontend::Agent</Navigation>
        <Value>
            <Item ValueType="String" ValueRegex="">AgentDashboard</Item>
        </Value>
    </Setting>

```

**Comment by bschmalhofer** [comment]
A bit related, in the description url should be changed to URL. It is an acronym.

**Comment by bschmalhofer** [comment]
In _Framework.xml_ the default action is set up as AdminInit. As far as I see this frontend module is not used any more let's get rid of it.

**Comment by stefanhaerter** [comment]
Decision is to leave AdminInit and surroundings as fallback and if the ZZZAAuto file erroneously gets deleted.

Closing the issue.
