### ISSUE TITLE
Print styles missing in customer frontend

### ISSUE THREAD

**Issue by intebit-zorn** [RotherOSS/otobo#2380]
When printing the ticket overview in the customer frontend via browser menu -> print, the pages are almost empty. It seems some css is missing for the print media.

**Comment by svenoe** [comment]
Edit: confirmed; I didn't read correctly...

---

Hi Benedikt,

I cannot confirm this. Please check this on a freshly installed OTOBO, and if it happens there, too, please provide a step by step guide how to reproduce it, as well as a picture of what you are receiving.
If you are working on a customized OTOBO, please visit our [forums](https://otobo.de/de/forums/) for community help, or write an email to hello@otobo.de for professional support.

Best regards, Sven

**Comment by svenoe** [comment]
Ah, taking it back, I didn't read correctly.

There is basically no css for the media type print, too much of the current is only for screen. We should definitely check this at one point.

Thanks for the hint.

**Comment by svenoe** [comment]
After some internal discussion, this probably is a larger topic, if done right. I will keep it in the enhancement project, but it won't be done with a high priority, so I will for the moment close this issue.
