### ISSUE TITLE
Suggestion: Improve naming in AdminDynamicFieldScreen

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2394]
To me, it seems a bit irritating that `AgentTicketSearch` appears twice when editing dynamic field screens (`Action=AdminDynamicFieldScreen;Subaction=Edit;Type=DynamicField;`).

![grafik](https://github.com/RotherOSS/otobo/assets/46650328/8b7c1c32-ae8e-4151-8655-30d673af36b3)

I understand that this is due to the fact that AgentTicketSearch allows the configuration of DynamicFieldScreens and DefaultColumnsScreens, but maybe it is possible to prefix the two entries in some way or find another solution.

**Comment by bschmalhofer** [comment]
It is also irritatating that the frontend modules 

- AgentITSMConfigItemEdit
- AgentITSMConfigItemPrint
- AgentITSMConfigItemZoom

show up. My impression is that assigning DF to these screens has no effect.

**Comment by bschmalhofer** [comment]
Closing, as the convention is that issues in the wishlist should be closed.

**Comment by stefanhaerter** [comment]
Related: #1335
