### ISSUE TITLE
Error message while loading customer list in CustomerDashboard without Gravatar

### ISSUE THREAD

**Issue by Lucsaan** [RotherOSS/otobo#2425]
Use of uninitialized value in substr at /opt/otobo/bin/psgi-bin/../../Kernel/Output/HTML/TicketOverview/CustomerList.pm line 176.

If you are loading a list of tickets in customer dashboard, the above error is shown for every ticket

The problem is the usage of the wrong keys to get $UserInitials. 
Wrong: UserFirstName -> Correct: UserFirstname
Wrong: UserLastName -> Correct: UserLastname

`$UserInitials = substr( $CustomerUser{UserFirstName}, 0, 1 ) . substr( $CustomerUser{UserLastName}, 0, 1 );`

![image](https://github.com/RotherOSS/otobo/assets/11646726/68de872a-f31f-4bf1-9eb6-17ac68b42cb8)

**Comment by svenoe** [comment]
Hi Lucsaan,

a common mistake...thanks for noting and also the fix. :)

Sven
