### ISSUE TITLE
Console command Dev::Package::DocumentationGenerate handles PackageRequired statements erroneously

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2427]
I came across a (presumably) typo in https://github.com/RotherOSS/otobo/blob/152bb89910b1b09f97dd609eece157b991f19719/Kernel/System/Console/Command/Dev/Package/DocumentationGenerate.pm#L195-L202

Firstly, I got a warning in my log:

`Use of uninitialized value in concatenation (.) or string at /opt/otobo/Kernel/System/Console/Command/Dev/Package/DocumentationGenerate.pm line 198.`

According to debug prints, `$_` is undefined, and even if it would be defined, I would expect it to be a reference to a hash, not a hash itself. The loop variable `$Package` is a hash reference and contains the wanted data.

Personally, I would prefer to include the fix in rel-10_1 because the DocumentationGenerate command was firstly added to this version, but I would also understand if the decision would be to only fix it in rel-11_0.

**Comment by bschmalhofer** [comment]
I aggree that this should be included in rel-10_1.    
The PR is merged.

**Comment by stefanhaerter** [comment]
Thank you =)

Closed with merged #2428
