### ISSUE TITLE
Add some convenience methods to Kernel::System::DB

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2430]
There already is the convenience method `SelectAll()` that returns the complete data from the cursor, that is an executed statement handle, which is wrapped by `Kernel::System::DB`.
But it would be nice to have some more convenience methods:

- [x] add tests for `SelectAll()` 
- [x] SelectRowArray: select only a single row, could be based on Prepare() and FetchrowArray()
- [x] SelectColArray: select a single column, could be based on Prepare() and the DBI method selectcol_arrayref()
- [x] SelectMapping: select two columns and use the first as key for the second, could also be based on `Prepare()` and  `selectcol_arrayref()`

Migrating `SelectAll()` to the DBI method `selectall_arrayref` is beyond the scope of this issue

**Comment by bschmalhofer** [comment]
The three convenience methods have been added. Tests look fine. Closing this issue.

**Comment by stefanhaerter** [comment]
I'm not sure whether I found a bug or did some other mistake: With rel-11_0 and GeneralCatalog package installed, I wasn't able to view the general catalog classes in AdminGeneralCatalog, despite them being present in the database table. The patch attached to this comment fixed it for me, but I have no idea if this is the real origin or if anything else went wrong. @bschmalhofer could you please  have a look at this?

[selectcolarray.txt](https://github.com/RotherOSS/otobo/files/12619514/selectcolarray.txt)

**Comment by bschmalhofer** [comment]
Hi @stefanhaerter,

for testing I installed a local build of GeneraCatalog, from the master branch, into a fresh installation of OTOBO based on rel-11_0. In the AdminGeneralCatalob frontend I could add add classes and items without hassle.

It is purely a design choice whether `Kernel::System::DB::Prepare()` should return an array or an arrayref when `Execute => 0' is passed. Both approaches should work. I went with returning an array, as it was closer to the behavior in the default case.

My first suspicion was that you ran into some caching effect. But then I saw that the cache in `ClassList()`seems to be written but never read. How did you enter the items in `general_catalog`? Via the GUI or directly into the database? In the latter case it could be that you DB changes were not committed.

**Comment by stefanhaerter** [comment]
Hi @bschmalhofer,

thank you for your time and for testing - I had a fresh installation of rel-11_0 and used opm files generated via Dev::Package::Build, which I installed via Admin::Package::Install --force. First I installed ImportExport, then GeneralCatalog. When attempting to install ITSMCore, it complained not being able to find items of class ITSM::SLA, which was the starting point for my debugging.

I will try a fresh installation again, maybe a config rebuild, cache delete and apache2 restart between the package installations will help.

Thank you! 😊

**Comment by stefanhaerter** [comment]
I had a look at this again together with @svenoe and the conclusion was that the `return`-Statement in https://github.com/RotherOSS/otobo/blob/a8d0ea6ad2c860624f3600b50484036f916c5c8f/Kernel/System/DB.pm#L873 is behaving a bit odd, returning 0 when `$Execute` is 0.

A solution idea was to change it like this:

```
     # This is for internal use
-    return 1, @Array unless $Execute;
+    if ( !$Execute ) {
+        my @Return = (1, @Array);
+        return @Return;
+    }
```

@bschmalhofer, sorry to bother you again - could you have a look at this?

**Comment by bschmalhofer** [comment]
@stefanhaerter , under which circumstances does this effect occur? It could happen when Prepare() is called in scalar context when Execute => 0 is passed. But as far as I'm aware Prepare() is called in list context when the  "do not execute" behavior is wanted.

**Comment by svenoe** [comment]
It is called by SelectColArray() https://github.com/RotherOSS/otobo/blob/a8d0ea6ad2c860624f3600b50484036f916c5c8f/Kernel/System/DB.pm#L1133 and occurs when `@Array` is empty. I was quite surprised yesterday, too, but `$PrepareSuccess` was 0 in this situation.

**Comment by bschmalhofer** [comment]
@svenoe reported another case where the result of `my ($Flag, Binds) = $DBOBject->Prepare( Execute => 0, ... ) ` looked just like if the Prepare method was called in scalar context. That is, the `$Flag` contained the number of bind variables.

Using Perl 5.34.0 I ran a small test script in order to see if I could reproduce the behavior. But the output of the test script looks consistent.

- The scope is determined by the left side when the sample function is called.
- Postfix `if $Execute` seems to work
- result list is flattened when called in list context
- last element of unflattened result list is returned in scalar context
- when the last element is an array, then the array is valuated in scalar context, giving the length of the array

So the reason for the strange behavior is undetermined. It might depend on the Perl version, as @stefanhaerter suggested. So it would be good to rerun the test script with different versions of Perl.

Even if the real cause of the problems remain unclear, I'll do a bit of rewriting.

**Comment by stefanhaerter** [comment]
Can you send me the test? I'm really curious on seeing the result on my PC 👀

**Comment by bschmalhofer** [comment]
Ah, sorry, I meant to add the test script and the result I got. Here they are:

[return_with_postfix_if.pl.txt](https://github.com/RotherOSS/otobo/files/12701681/return_with_postfix_if.pl.txt)
[return_with_postfix_if.out.txt](https://github.com/RotherOSS/otobo/files/12701682/return_with_postfix_if.out.txt)

**Comment by stefanhaerter** [comment]
The script returned the exact same result on my machine (`nvim -d` showed no differences).
[return_with_postfix_if_sha.out.txt](https://github.com/RotherOSS/otobo/files/12711509/return_with_postfix_if_sha.out.txt)

**Comment by bschmalhofer** [comment]
Let's close this issue as the code in `Kernel::System::DB` has changed since the initial report and AFAIK no new problems have been encountered.
