### ISSUE TITLE
Test Failure in AgentTicketNote.t

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2450]
Currently there is a test failure in _AgentTicketNote.t_ .  The error is that the list of agents that may be informed does not correspond to the expected. The problem is that it is not obvious what should be expected.

The test script sets up four users and a queue. Then it presents an edit mask of a ticket and checks the list of agents that are eligable to be informed. Here is an example of the data from the table **group_user**. The four user IDs are 512,513,514,515. The ticket is in the queue with the ID 77. The data is consistent with the set up code in the test script.

```
512	77	note	2023-08-08 17:01:16.000
512	77	ro	2023-08-08 17:01:16.000
513	77	note	2023-08-08 17:01:16.000
514	2	rw	2023-08-08 17:01:16.000
514	1	rw	2023-08-08 17:01:16.000
514	77	rw	2023-08-08 17:01:16.000
515	2	rw	2023-08-08 17:01:16.000
515	1	rw	2023-08-08 17:01:16.000
515	77	note	2023-08-08 17:01:17.000

```
The failing assertion is that user 512 may be notified. 

The list of the agents that may be informed seems to be set up in _Kernel/Modules/AgentTicketActionCommon.pm_.

```
            my %InformAgentList = $GroupObject->PermissionGroupGet(
                GroupID => $GID,
                Type    => 'rw',
            );

```
The queried type is 'rw'. Therefore the user 512 may not be informed as she only has 'ro' and 'note'.

TODO:

- [x] convert AgentTicketNote.t to `Test2::V0`
- [x] find out whether the code or the test must be adapted
- [x] adapte the code or the test

**Comment by stefanhaerter** [comment]
The `ro` => `rw` change in Kernel/Modules/AgentTicketActionCommon.pm was introduced by me with commit  c976eb43d6. The commit's purpose was to initially transfer the development done in a customer package to the branch for issue #2251 to provide a base for dynamic field multivalue development. Most likely, the change to the permission check was an accidentally produced unwanted byproduct and can be revoked - just to be sure, I will check this and provide a PR.

**Comment by bschmalhofer** [comment]
The test failure in _scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketNote.t _ is gone now. Closing this issue.
