### ISSUE TITLE
ACL permission handling in AgentTicketEmailOutbound

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2470]
There are significant differences in the ACL permission checks between the frontend modules _Kernel/Modules/AgentTicketEmailOutbound.pm_ and e.g. _Kernel/Modules/AgentTicketForward.pm_ .
https://github.com/RotherOSS/otobo/blob/45b758b25f8ed847a76c2a23fdf1619b95f5ce29/Kernel/Modules/AgentTicketEmailOutbound.pm#L113
vs. 
https://github.com/RotherOSS/otobo/blob/45b758b25f8ed847a76c2a23fdf1619b95f5ce29/Kernel/Modules/AgentTicketForward.pm#L150

But the input to `TicketACL()` and the handling of the result is different. @stefanhaerter  tested in the WebGUI and found that `AgentTicketForward` works as expected and that `AgentTicketEmailOutbound` has flaws.

The problem can easily be fixed but it would be good to add code comments explaining what the results from `TicketAcl()` and `TicketAclActionData()` actually mean.

**Comment by stefanhaerter** [comment]
Closed with merging #2537
