### ISSUE TITLE
Standardize behavior of ValueGet for reference dynamic fields

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2475]
The value structure used within `sub ValueGet` should be maintained and not be altered by e.g. `sub ValueForLens`.

**Comment by stefanhaerter** [comment]
Closed with merging #2472

**Comment by bschmalhofer** [comment]
Reopen as I see some TODOs in that area.

**Comment by stefanhaerter** [comment]
Which TODOs are left here?

**Comment by bschmalhofer** [comment]
I think that this issue can be considered as being resolved, as there had been independent developments in the mean time. Closing now.
