### ISSUE TITLE
OIDC login functionality for agents and customers not working due to Redis caching issue

### ISSUE THREAD

**Issue by im-alfa** [RotherOSS/otobo#2483]
Hi all!

I'm having some trouble with the OIDC login functionality for both our agents and customers. It appears that the problem is with the way OTOBO is caching in Redis the `OpenIDConnect:ProviderData` value. This value is currently being used for both agent and customer logins, even though I'm using different providers (Google OIDC for agents and my own OIDC implementation for customers). I think each should have its own entry, one for Agents and one for Clients.

![image](https://github.com/RotherOSS/otobo/assets/25107205/d905d625-41ad-4010-8581-643b9e453ecd)

`$Self->{'AuthModule::OpenIDConnect::Config'}{ProviderSettings} = {
    OpenIDConfiguration => 'https://accounts.google.com/.well-known/openid-configuration',
}`

`$Self->{'Customer::AuthModule::OpenIDConnect::Config'}{ProviderSettings} = {
    OpenIDConfiguration => 'https://my.oidc/.well-known/openid-configuration',
};`

**Comment by svenoe** [comment]
Hi im-alfa,

in general please visit our [forums](https://otobo.de/de/forums/) with questions like this, or write us an email to hello@otobo.de for professional support. Github is only for development issues.

Thanks for your understanding, Sven

(In this case, please have a look at the Name attribute of the provider settings; see the Default.pm.)
