### ISSUE TITLE
Suggestion: Add "Send example notification to:" for ticket notifications

### ISSUE THREAD

**Issue by AlexanderOesterling-OTOBO** [RotherOSS/otobo#2492]
In the adminpanel under ticket notifications a button to send an example notification would help with the testing of such notifications.

![image](https://github.com/RotherOSS/otobo/assets/129976665/2cf013bb-3cd2-4551-9352-9c30dcfba50b)

**Comment by bschmalhofer** [comment]
The request makes perfect sense. Moving it to the wishlist though.

**Comment by stefanhaerter** [comment]
Moving it to "Likely never" following a brief discussion with @AlexanderOesterling-OTOBO.
