### ISSUE TITLE
Elastic Search for Dynamic Field

### ISSUE THREAD

**Issue by bahmed99** [RotherOSS/otobo#2496]
Hello,

I'm experiencing a problem. When adding a dynamic field linked to a ticket, the search in the elastic search bar does not find any tickets corresponding to the dynamic field.

Could you please help me find a solution or suggest steps to solve this problem?

**Installation : On Docker**

**Comment by svenoe** [comment]
Hi bahmed,

with general questions concerning configuration etc., please visit our [forums](https://otobo.de/de/forums/) for community support, or write an email to hello@otobo.de for professional support. Github is reserved for development issues.

Thanks for your understanding, Sven
