### ISSUE TITLE
Please open the links in the footer of the customer area in a new tab, not in the existing window.

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#2497]
Please open the links in the footer of the customer area in a new tab, not in the existing window.

**Comment by bschmalhofer** [comment]
Let's do this for rel-10_0 already, in order to be consistent. Ignore _Kernel/Output/HTML/Templates/Standard/CustomerFooterSmall.tt_ as this template seems to be unused.

**Comment by bschmalhofer** [comment]
The target of the otobo.de links have been set to '_blank'. Activated for rel-10_0, rel-10_1, and rel-11_0.
Tested manually, not sure whether the UnitTests will complain about the change. Closing this issue.
