### ISSUE TITLE
How to Send emails with SMTP Oauth?

### ISSUE THREAD

**Issue by sankethpb** [RotherOSS/otobo#2518]
Dear Team,

Could you please clarify how to send emails via SMTP Oauth? We could not find any document, only SendMail was available.

Thanks,
Sanketh

**Comment by svenoe** [comment]
Hi Sanketh,

for general support questions, please visit our [community forums](https://otobo.de/de/forums/). Github is for development issues only.

Thanks for your understanding, Sven
