### ISSUE TITLE
PSGI: is PSGI fully supported ?

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#252]
If so, let's remove the scary warning message in _otobo.psgi_.

**Comment by svenoe** [comment]
Just as a feeling I would say, we are not at a point to decide this. I would rather wait a couple of months and if we don't receive any complaints from other users, in addition to our installations working, then we can confidently take it out.

**Comment by bschmalhofer** [comment]
Let' decide that for 10.1

**Comment by bschmalhofer** [comment]
Docker, and therefore PSGI, is officially supported as of OTOBO 10.0.7. The scary warning can now be removed.

**Comment by bschmalhofer** [comment]
The scary warning is gone. Closing the issue.
