### ISSUE TITLE
I can't set up my Gmail account

### ISSUE THREAD

**Issue by MrSipping** [RotherOSS/otobo#2544]
Hi, I was trying to set up my gmail account during installation but the imap part wasn't working for me. What was I doing wrong? Can anyone advise me how to do it

**Comment by svenoe** [comment]
Hi MrSipping,

for general questions please either visit our [forums](https://otobo.de/de/forums/) for community help, or write an email to hello@otobo.de for professional support. Github is for development issues only.

Thanks for your understanding, Sven
