### ISSUE TITLE
Middle Mouse Button not working to open tickets in a new tab

### ISSUE THREAD

**Issue by Rainson12** [RotherOSS/otobo#2555]
When searching for a ticket and using middle mouse button to open a link in a new tab, this will not work with otobo. This also does not work in the overview. This is especially annoying when trying to compare tickets which often have the same title eg. "Backup report".

**Comment by stefanhaerter** [comment]
Hey @Rainson12 =)

Assuming that you are using OTOBO 10.1, I did a fresh installation to test this. Without changing anything on the configuration, it worked for me (I wanted to provide a screen recording, but GitHub doesn't seem to take either mpeg or avi). Could you please provide me with a more detailed description under which circumstances this doesn't work for you?

Kind regards,
Stefan

**Comment by Rainson12** [comment]
Dear @stefanhaerter,
thank you for the recording. I have tested it and it in fact works when i click on the ticket number. I find that confusing because the left click mouse event also works for all the other columns while the middle mouse button does not work and ctrl + click will actually open the ticket but not in a new window.

**Comment by stefanhaerter** [comment]
Dear @Rainson12,

Great that it works with the number and  thank you for the input regarding left- and right-clicking, this is interesting and I will give it a look when I have the time to.

Have a nice day!

**Comment by Rainson12** [comment]
> Dear @Rainson12,
> 
> Great that it works with the number and thank you for the input regarding left- and right-clicking, this is interesting and I will give it a look when I have the time to.
> 
> Have a nice day!

actually i just found out that the ctrl + click only works on the dashboard/ticket overview but not on the queue list.

**Comment by stefanhaerter** [comment]
> actually i just found out that the ctrl + click only works on the dashboard/ticket overview but not on the queue list.

This sounds a bit odd - are you sure that you clicked on the number? Maybe I'm missing something, but I am currently not aware of any behavior differences between mouse wheel / middle mouse button and Strg + left mouse button.

> I find that confusing because the left click mouse event also works for all the other columns while the middle mouse button does not work and ctrl + click will actually open the ticket but not in a new window.

I am with you that there is an inconsistency - it results from differences in the implementation which cause the number column to be an actual link (HTML anchor tag), while the other columns in the ticket overviews are handled via an onclick event in JavaScript. We will discuss internally how to solve this. I will provide updates on that here :)

**Comment by Rainson12** [comment]
> This sounds a bit odd - are you sure that you clicked on the number? Maybe I'm missing something, but I am currently not aware of any behavior differences between mouse wheel / middle mouse button and Strg + left mouse button.

this inconsistency only appears when you do not click on the number. This inconsistency exists between the dashboard/overview vs. ticket queue when clicking on any other column than the number

> I am with you that there is an inconsistency - it results from differences in the implementation which cause the number column to be an actual link (HTML anchor tag), while the other columns in the ticket overviews are handled via an onclick event in JavaScript. We will discuss internally how to solve this. I will provide updates on that here :)

appreciate it, thanks!

**Comment by stefanhaerter** [comment]
Nothing new so far - it looks like this won't be looked at in the forseeable future. Closing the issue.
