### ISSUE TITLE
Docker: add admin favourites for the user 'admin' created by quick_setup.pl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2563]
_bin/docker/quicksetup.pl_ has the option `--add-admin-user` which adds the user Andi Admin. It would be convenient when some of the most commonly used admin pages were automatically added  as favorites for that user:

- AdminSystemConfiguration 
- AdminPackageManager 
- AdminSupportDataCollector

**Comment by stefanhaerter** [comment]
I recently started to work on a console command to add user preferences. Whould this be helpful here?

**Comment by bschmalhofer** [comment]
I think that this is not necessary. As far as I had seen, the preferences can be passed via the call to `UserAdd() `.

**Comment by bschmalhofer** [comment]
A quick manual test looks find. PR is merged. Changes are merged into rel-10_1 and rel-11_0 as well. Closing this issue.
