### ISSUE TITLE
Custom Footer text for Agent PDF Statistics Reports

### ISSUE THREAD

**Issue by meinhart** [RotherOSS/otobo#2564]
Please implement the possibility to set a custom footer text in PDF reports by editing an report. In the output settings there should be a text field where i am able to set the shown text. In the report the text should be shown as centered in footer area one row before the page counter.

Nice to have when the font will be adjustable.

In my special case needed for document classification which is needed for ISO compliance. An example text would be "CLASSIFICATION: CONFIDENTIAL".

**Comment by svenoe** [comment]
Hi meinhart,

thanks for the suggestion, I will keep it in our enhancements project. To be honest, the likelihood that this will be implemented in the nearer future is low, though. If you are willing to pay for the feature, please write an email to hello@otobo.de, but else although I'm not saying it will never come, we are just more than booked with payed requests, so especially for things which won't be really useful for a majority of OTOBO users, the priority is just not high enough.

Best regards, Sven
