### ISSUE TITLE
The password recovery issue on the customer side

### ISSUE THREAD

**Issue by MrSipping** [RotherOSS/otobo#2566]
Hello, I have an issue with password recovery on the customer side because it works on the agent side, and I don't know why. On the agent side, I receive the email with the link containing the token, and then I get a second email with the temporary password. However, on the customer side, I only receive the first email and not the temporary password. The error I observed in the Docker is: 'Need User or UserId.' I have 10 customers, and I'm sure all the mandatory fields are filled out. I don't know what could be causing this

**Comment by svenoe** [comment]
As written now twice in your previous issues, we do not use github as a platform to provide general support for OTOBO. You are free to visit our [forums](https://otobo.de/de/forums/) to ask the community for help.
