### ISSUE TITLE
unable to activate Customer Service Catalogue on otobo 10.1 docker installation

### ISSUE THREAD

**Issue by laurentchap** [RotherOSS/otobo#2576]
Trying to test external Interface/ Customer Service Catalogue

after installing OTOB 01.1 + the service cataloge package 
unable to see/use external interface and Customer Service Catalog as found in doc : https://doc.otobo.org/manual/admin/10.1/en/content/external-interface.html

For extrene interface i mean this « External Interface » documented,which include customer Service Catalogue :

<img width="453" alt="ei" src="https://github.com/RotherOSS/otobo/assets/43187772/5c08252a-5b36-46ae-aa6b-e79313fc815c">

I installed  the service cataloge package. But I don’t have a admin menu to add Service Catalog access to the client page (customer.pl) like in the demo 

 <img width="889" alt="scp" src="https://github.com/RotherOSS/otobo/assets/43187772/26ff9b8a-7f80-4a49-8df1-bd0274b5bd6c">

 But I don’t have a admin menu to add Service Catalog access to the client page (customer.pl) like in the demo 

<img width="655" alt="dm" src="https://github.com/RotherOSS/otobo/assets/43187772/f8bf4714-7f1d-4185-ad80-bd52720b18d1">

For information my ui looks like this :

<img width="1126" alt="ui" src="https://github.com/RotherOSS/otobo/assets/43187772/edf2da95-b99f-4d08-b2ba-975d48be801e">

OTOBO is under docker install in redhat OS

**Comment by laurentchap** [comment]
I added some informations to the ticket

**Comment by svenoe** [comment]
Hi laurentchap,

sorry for writing just now. With general questions, however, please visit our [forums](https://otobo.de/de/forums/) for community help, or write an email to hello@otobo.de for professional support. Github is used for development issues only.

Thanks for your understanding, Sven
