### ISSUE TITLE
Support for "Selections" in "CustomerUserInformation"

### ISSUE THREAD

**Issue by meinhart** [RotherOSS/otobo#2582]
Please implement a support in module "Kernel::Output::HTML::Dashboard::CustomerUserInformation" showing custom CustomerUser selection values, which are defined in Config.

Example:
I have an int value defined in CustomerUser->Map config with "shown=1" value, and in CustomerUser->Selections i have created a custom selection where 1 = 'IT', 2 = 'Billing' etc.

When the CustomerUserInformation module get´s displayed on an customer entry of type "IT" it will show "1" at the moment.
It should display "IT" instead.

**Comment by svenoe** [comment]
As with your other request, I will add it to the enhancements project.
