### ISSUE TITLE
Docker: include more optional Perl modules

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#264]
There are some optional modules listed in bin/otobo.CheckModules.pl. 
TODO:

- [ ] analysed which modules can easily included in the Docker image

- [ ] include these modules

**Comment by bschmalhofer** [comment]
Authen::NTLM was added to the image for #295

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO   The question whether we can include DBD::Oracle in the image, depends on whether we can include Oracle instant client in the image. The technical side is no problem, but we need to consider licensing. Could you investigate?

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I think we do not need it for docker. If needed, we need to build a customer docker file.

Closed for me.

Thanks!

Stefan
