### ISSUE TITLE
Tagging support for Tickets

### ISSUE THREAD

**Issue by meinhart** [RotherOSS/otobo#2642]
Please implement an tagging system for tickets. As an support agent i want to tag specific tickets with multiple tags and later filter for tickets containing on or multiple tags. Also it should be possible to view the tags clearly in overview lists. It should be possible to color tags.

As an admin i want to set tags to tickets where incoming mails containing specified mail attributes (Postmaster-Filter).
I want to create reports for tickets containing specific tags.

**Comment by svenoe** [comment]
This can be done via dynamic fields already.
