### ISSUE TITLE
Create tickets without login

### ISSUE THREAD

**Issue by jonasbadstuebner** [RotherOSS/otobo#2693]
Hey there,
as the last reply was a long time ago, I wanted to also ask over here: Is it possible or planned at least to let customers create tickets without a login?
The original thread in the forum is here https://otobo.de/de/forums/topic/ticket-erstellen-ohne-login/
Thank you in advance for your reply!

**Comment by svenoe** [comment]
Hi Jonas,

we use github only for development issues. For general questions etc. please stick to the forums.

Thanks for you understanding,
Sven

**Comment by DrBu7cher** [comment]
Well then this is a feature request ticket: Please make it so I can send someone a link to a form and they can submit information, including an email address for example and upload some files and I can see a newly created ticket. Without them having to log in.
