### ISSUE TITLE
Remove support for bin/cgi-bin/rpc.pl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#27]
https://lists.otrs.org/pipermail/otrs/2013-July/040302.html states that rpc.pl is deprecated. IMHO this means that it can be removed in OTOBO. 
rpc.pl is already not supported in FastCGI and in PSGI.

**Comment by bschmalhofer** [comment]
Apparently rpc.pl is still used. Therefore add support for rpc.pl under PSGI.

**Comment by svenoe** [comment]
Merged, thanks Bernhard.

**Comment by svenoe** [comment]
We will completely remove the code from otobo.psgi.

**Comment by svenoe** [comment]
Removed in 566d8c42bafa9a66f7ec0166177712e44ad61ffc

**Comment by bschmalhofer** [comment]
Now also skip the unit tests that relied on rpc.pl.

**Comment by bschmalhofer** [comment]
Kernel::System::Web::RPC can be removed as well.

**Comment by bschmalhofer** [comment]
Removed Kernel::System::Web::RPC, closing again

**Comment by bschmalhofer** [comment]
Found more stuff that can be removed.

- scripts/rpc-example.pl
- SysConfig entries SOAP::User and SOAP::Password
- Kernel/System/SupportDataCollector/Plugin/OTOBO/DefaultSOAPUser.pm

**Comment by bschmalhofer** [comment]
Did the cleanup. Closing this issue again.
