### ISSUE TITLE
AgentTicketEmailResend - js error

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#2701]
I got an js error in agent ticket email resend. Please confirm. `To` and `Cc` where filled, `Bcc` was empty:
```
Uncaught TypeError: EmailAddressesBcc is undefined
    Init https://portal.rother-oss.com/otobo-web/js/Core.Agent.TicketEmailResend.js:66
```

**Comment by stefanhaerter** [comment]
Confirmed for rel-11_0.

**Comment by stefanhaerter** [comment]
Also confirmed for rel-10_0. Taking into account the relevant code line, I assume that the bug is based on  a simple typo.
