### ISSUE TITLE
Integrate ImportExport into OTOBO core

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2711]
Importing and exporting data is a basic feature. Therefore let's integrate the extension package ImportExport into the core.

TODO:

- [x] check CodePolicy in rel-10_1
- [x] Update the translations in _Kernel/Language/_ based on the changes in _i18n_
- [x] merge the updated rel-10_1 into master
- [x] merge the ImportExport files into OTOBO-core, skipping the translations and the package setup
- [x] keep _Kernel/Config/Files/XML/ImportExport.xml_ as a separate file
- [x] no need to integrate the files in _doc_, they just contain the database schema (still with OTRS 6 labels) 
- [x] Add the tables to _scripts/database/otobo-schema.xml_
- [x] integrate the package setup (actually no setup code is run, thus nothing to do)
- [x] Update the migration package
- [x] merge the translations ( concatenate to the existing files ??? )
- [ ] Update the dependency list of the ITSM bundle package. _Will be done later, as there is no rel-11_0 branch for that module yet_.
- [x] Move the ITSM specific Console Commands to ITSMConfigurationManagement, _Kernel/System/Console/Command/Admin/ITSM/_
- [x] move the tests and the test sample file for the console command to ITSMConfigurationManagement
- [ ] Decide whether ImportExportCustomerCompany and the other ImportExport modules should be integrated as well _Will be decided later_
- [x] Update the installation manual for OTOBO 11.  See https://github.com/RotherOSS/doc-otobo-installation/issues/123

**Comment by bschmalhofer** [comment]
Using msgadd from the gettext project for merging translations. Here is the script, just for future reference:
[integrate_importexport_po_files.sh.txt](https://github.com/RotherOSS/otobo/files/13488217/integrate_importexport_po_files.sh.txt)

The script does a slight reformatting when a translation contains newlines. This reformatting has been ignored when committing the changed .po files.

EDIT: this apparently belongs to some other issue

**Comment by bschmalhofer** [comment]
@svenoe  pointed out that ImportExport should not show up in the list of installed packages when upgrading from 10.1. This functionality has been added to _scripts/DBUpdate-to-11.0.pl_,

Note that this does not work well when ImportExport has been installed in a OTOBO 11 system and then _scripts/DBUpdate-to-11.0.pl_ is called. This is because the .save files are not copied to the overridden files. But this situation can only occur during development, as no version of ImportExport will be released for OTOBO 11.

**Comment by bschmalhofer** [comment]
ImportExport is now integrated. Closing this issue.

**Comment by bschmalhofer** [comment]
In https://github.com/RotherOSS/otobo/blob/6b4b3473696e5e98795f4f3178b82872cd9290c3/Kernel/System/SysConfig.pm#L2561 the precedence of the _Kernel/Config/Files/XML/*.pm_ is declared. `Framework`has there the lowest precedence. Currently only _Framework.xml_ and _ImportExport.xml_ are declared as `Framework`. This feels wrong, at least unexpected, as most other XML-Files are declared as `Application`.

```
$ grep init Kernel/Config/Files/XML/*.xml | grep '"Framework"'
Kernel/Config/Files/XML/Framework.xml:<otobo_config version="2.0" init="Framework">
Kernel/Config/Files/XML/ImportExport.xml:<otobo_config version="2.0" init="Framework">
```
and 
```
$ grep init Kernel/Config/Files/XML/*.xml | grep '"Application"'
Kernel/Config/Files/XML/Calendar.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/CloudServices.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/Daemon.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/DynamicFields.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/GenericInterface.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/OTOBOPasswordPolicy.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/ProcessManagement.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/Ticket.xml:<otobo_config version="2.0" init="Application">
Kernel/Config/Files/XML/Znuny4OTOBOShowPendingTimeIfNeeded.xml:<otobo_config version="2.0" init="Application">
```
TODO:

- [ ] change the init attribute in _ImportExport.xml_ to `Application`.

**Comment by bschmalhofer** [comment]
ImportExport.xml has been adapted. Testing was skipped. Closing this issue again.

**Comment by laiminhtrung1997** [comment]
Dear @bschmalhofer  @svenoe 
I can not input to the Class field. I deploy OTOBO 11.0.6. What is wrong with the ImportExport? Please help me.
![image](https://github.com/user-attachments/assets/21a8c911-ce82-42a8-9f52-93e9b0baf2a7)

**Comment by svenoe** [comment]
Firstly the CMDB for 11.0 is currently in beta, because we reimplemented parts and introduced large changes. ImportExport did work before, make sure, that in the general catalog there actually are classes defined. If everything seems alright, please open an issue in the ITSMConfigurationManagement repo with a step by step guide, how to reproduce this on a newly installed system.

(As a side note, we are currently finishing a first documentation for the new CMDB; probably it will be difficult to use it without. As a hint, look for the "Ready to import" classes in Admin->ConfigItems (on a test system!).

**Comment by laiminhtrung1997** [comment]
Dear @svenoe 
I just tried to import classes using the Ready2Import that you hinted at. I can choose the Class in ImportExport, but there is a difference in version 11.0.6. I can not find the class Computer that is present on version 10.1.8, and the classes are already installed. Could you confirm this, please?

**Comment by svenoe** [comment]
Hi [laiminhtrung1997](https://github.com/laiminhtrung1997),
yes, Computer is not part of those classes. If you want to use the old class, you have to migrate those via the console command "Admin::ITSM::Configitem::UpgradeTo11". But in the end, maybe wait for the next upgrade of the CMDB which will have some documentation in it, or please go to our forums in the meanwhile; we try to keep HowTo questions out of github, to keep it clean for the developers...

**Comment by laiminhtrung1997** [comment]
Hi @svenoe @bschmalhofer
I have some issues in [CMDB](https://github.com/RotherOSS/ITSMConfigurationManagement) that are [#24](https://github.com/RotherOSS/ITSMConfigurationManagement/issues/24) and [#26](https://github.com/RotherOSS/ITSMConfigurationManagement/issues/26). Please help me to check it. I very much appreciate it. Thank you a lot.
