### ISSUE TITLE
Useless use of 'local' in scripts

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2714]
In a lot of scripts the use of `local`is useless. For example, in _scripts/restore.pl_ there is code like:

```
# create common objects
local $Kernel::OM = Kernel::System::ObjectManager->new(
    'Kernel::System::Log' => {
        LogPrefix => 'OTOBO-restore.pl',
    },
);

```
The `local` localises the package variable `$Kernel::OM` to the current scope. But the current scope is the whole script and when the scripte ends, then `$Kernel::OM` is destroyed anyways. So I propose remove the `local` declaration in these cases. Note that this does not apply to `bin/psgi-bin/otobo.psgi`. In that case,  `$Kernel::OM` is localized in order to enforce that new objects are created for every HTTP request. 

The POD in _ObjectManager.pm_ should be updated as well.

The benefit of this change is to reduce cargo cult, reduce the impression that `$Kernel::OM` is something special.

**Comment by bschmalhofer** [comment]
Actually there are only eight relevant scripts:

```
bin/otobo.Console.pl:local $Kernel::OM = Kernel::System::ObjectManager->new(
bin/otobo.Daemon.pl:local $Kernel::OM = Kernel::System::ObjectManager->new(
bin/otobo.Daemon.pl:                local $Kernel::OM = Kernel::System::ObjectManager->new(
bin/docker/quick_setup.pl:    local $Kernel::OM = Kernel::System::ObjectManager->new(
scripts/restore.pl:local $Kernel::OM = Kernel::System::ObjectManager->new(
scripts/backup.pl:local $Kernel::OM = Kernel::System::ObjectManager->new(
scripts/contrib/otobo.SyncLDAP2DB.pl:local $Kernel::OM = Kernel::System::ObjectManager->new(
scripts/Migrate-From-OTRS.pl:local $Kernel::OM = Kernel::System::ObjectManager->new(

```

**Comment by bschmalhofer** [comment]
Let's refrain from doing this. It does indeed look strange to localise a namespace variable on the top of a script. Why temporarily override a variable that is assigned for the first time? But things seem to be working fine and there is always a chance of subtly breaking things with seemingly innocent changes.

**Comment by stefanhaerter** [comment]
Putting this into the 11.1.1 milestone as a commit has been done.
