### ISSUE TITLE
Parent-Services not greyed out, when translated

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#2717]
When you have a hidden (via ACL) or de-activated Service, it is usually greyed out. When you have a different translation, it is not greyed out, but can't be selected.

1. Activate the System Configuration settings Ticket::Service and Ticket::Service::KeepChildren Ticket.xml  
2. Activate translations for services in CustomerTicketMessage (Translation => 1 in (Custom/)Kernel/Modules/CustomerTicketMessage.pm for the two Service parts)
3. Create the following services: IT, IT::Software, IT::Hardware, IT::User management, IT::Network and IT::IT requirements and some Services below those
4. translate them, e.g. to this in German: IT, IT::Software, IT::Hardware, IT::Benutzerverwaltung, IT::Netzwerk and IT::IT-Anforderungen
5. see in CustomerTicketMessage that they are translated correctly
6. de-activate them or create an ACL Possible Not > Ticket > Service >  IT, IT::Software, IT::Hardware, IT::User management, IT::Network and IT::IT requirements
7. see the ones with target language != source language are not greyed out anymore, but the ones with target language = source language are still greyed out. Also see that the not greyed out ones can be selected but are removed right away (so can't really be selected - just like it is intended more or less)

Hint: it doesn't matter if you translate it in your Kernel/Language/xx_Custom.pm or via the package Ayte-CustomTranslations.

I found this out on my customer's system 10.1.8 (Docker)
I couldn't reproduce it on my OV, as I didn't manage to make the translations of the services work, but that shouldn't be a bigger problem.

**Comment by svenoe** [comment]
As in the standard services are not translated, this is irrelevant or not? It needs to be kept in mind if/when we change this behavior, however. I'll put a note down but close this issue.
