### ISSUE TITLE
Clean up remnants of MSWiin32 support

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2731]
I was running `grep -r -i Win32` and I found only two remnants of MSWin32 support. Let's clean them up nevertheless.

> Kernel/Modules/AdminDynamicFieldDB.pm:    if ( $^O ne 'MSWin32' ) {
> scripts/test/Package.t:  <OS>MSWin32</OS>
>

**Comment by bschmalhofer** [comment]
Also 

- _Kernel::System::Crypt::PGP.pm:  ` if ( $^O =~ m/Win/i ) {`

**Comment by stefanhaerter** [comment]
Recently, I ran about microsoft xml references (if I interpreted the code correctly) in these files:

- `Kernel/Output/HTML/Templates/Standard/AgentTicketSearchOpenSearchDescriptionFulltext.tt`
- `Kernel/Output/HTML/Templates/Standard/AgentTicketSearchOpenSearchDescriptionTicketNumber.tt`
- `Kernel/Output/HTML/Templates/Standard/CustomerTicketSearchOpenSearchDescription.tt`

Do these also belong to Win32 or something similar?

**Comment by bschmalhofer** [comment]
PR is applied, closing this issue.
