### ISSUE TITLE
Potential problem with ValueIsDifferent() and Set dynamic fields 

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2754]
There is a check whether old and new values are different when the value of a dynamic field is updated. This is sensible in order to avoid unnecessary updates and event. But this check might be broken when a dynamic field is part of a Set. For example ValueSet() and ValueGet() behave a bit differently when used within a Set. But in _Backend.pm_ there is the following code:

```
    my $OldValue = $Self->ValueGet(
        DynamicFieldConfig => $Param{DynamicFieldConfig},
        ObjectID           => $Param{ObjectID},
    );
    my $NewValue = $Param{Value};

    # do not proceed if there is nothing to update, each dynamic field requires special handling to
    #    determine if two values are different or not, this to prevent false update events,
    #    see bug #9828. Note: (do not send %Param, as $NewValue is a reference and then Value2 could
    #    have strange values).
    if (
        !$Self->ValueIsDifferent(
            DynamicFieldConfig => $Param{DynamicFieldConfig},
            Value1             => $OldValue,
            Value2             => $NewValue,
        )
        )
    {
        return 1;
    }
```
The new value is appropriate for usage in a Set. But the old value is fetched from the database without passing on the information that we are dealing with a Set. 

The fix is easy, but testing whether a dynamic field update event is fired, or not, is a bit more effort.

**Comment by stefanhaerter** [comment]
Within the changes made for #2804, `$Param{Set}` has been added to the call to `ValueGet()`. Did you think of anything specific for testing the dynamic field update event?

**Comment by bschmalhofer** [comment]
As things are still a bit in flux, I suggest to leave it at that.

**Comment by bschmalhofer** [comment]
Closing this issue after now.
