### ISSUE TITLE
Docker: Maintainer

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#276]
Currently the OTOBO docker images inherit the maintainer label from the parent images.

```
"Labels": {
                "maintainer": "Peter Martini <PeterCMartini@GMail.com>, Zak B. Elep <zakame@cpan.org>"
            }

```
@StefanRother-OTOBO   can I add you as maintainer? With which E-Mail address ?

**Comment by StefanRother-OTOBO** [comment]
Dear Bernhard,

If you don't like to be the maintainer, please add me: dev@otobo.org

Thanks very much!

Stefan

**Comment by bschmalhofer** [comment]
Set mysql as maintainer as the gut feeling is that the maintainer should be a real person.
