### ISSUE TITLE
Docker: Provide Open Containers Initiative annotations

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#277]
See: https://github.com/opencontainers/image-spec/blob/master/annotations.md .
Looks like this is a convention for labels on docker images.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO , @svenoe 

I have adapted the label in https://github.com/RotherOSS/otobo/tree/issue-277-open_containers_initiative. Could you take a look at these labels, whether the changes can be merged into rel-10_0:
```
                "maintainer": "Team OTOBO <dev@otobo.org>",
                "org.opencontainers.image.authors": "Team OTOBO <dev@otobo.org>",
                "org.opencontainers.image.created": "2020-08-31T07:49:32Z",
                "org.opencontainers.image.description": "OTOBO is the new open source ticket system with strong functionality AND a great look",
                "org.opencontainers.image.documentation": "https://otobo.org",
                "org.opencontainers.image.licenses": "GNU General Public License v3.0 or later",
                "org.opencontainers.image.revision": "cbb08a0f59a47a358fd07ed91484e45466e81ebd",
                "org.opencontainers.image.source": "git@github.com:RotherOSS/otobo.git",
                "org.opencontainers.image.title": "OTOBO",
                "org.opencontainers.image.url": "https://github.com/RotherOSS/otobo",
                "org.opencontainers.image.vendor": "Rother OSS GmbH",
                "org.opencontainers.image.version": "issue-277-open_containers_initiative"

```
The version is currently the Docker tag. For releases it probably is sensible to normalize _rel-10_1_0_ to _10.1.0_.

**Comment by bschmalhofer** [comment]
Changed   "org.opencontainers.image.url" to point to "https://github.com/RotherOSS/otobo".
On second thought I probably would leave "org.opencontainers.image.version" to contain the Docker hub tag, That is _rel-10_0_3_ instead of _10.0.3._ . Looks more consistent to me, as there are also tags for devel versions and maybe other cases.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

please implement it the way you think, it sounds perfekt for me.

Stefan

**Comment by bschmalhofer** [comment]
Labels look fine in local and in Docker hub builds. Closing the issue.

**Comment by bschmalhofer** [comment]
Let's backport this to 10.0.3 as the Docker version is starting to get used. TODO:

- [x] backport
- [x] check labels of local builds
- [x] check labels of Docker Hub builds

**Comment by bschmalhofer** [comment]
Labels look fine. Closing again.
