### ISSUE TITLE
DF default values do not work for article fields in masks based on ActionCommon.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#2785]
Add a multiselect field with default value to AgentTicketNote and see that it is rendered empty (if empty value is given).

**Comment by stefanhaerter** [comment]
This bug also affects article dynamic fields in the FollowUp of CustomerTicketZoom.

**Comment by stefanhaerter** [comment]
Maybe also relevant: In the comparable place for handling the dynamic field values, AgentTicketPhone makes use of default values stored in the user preferences:

https://github.com/RotherOSS/otobo/blob/8866f83fe2f2fe91153c8e59e0664c7c22d5c8ee/Kernel/Modules/AgentTicketPhone.pm#L705-L713

I didn't research this thoroughly, but at least AgentTicketActionCommon, CustomerTicketZoom and a few other masks do not use this UserPreference values. Perhaps this will be relevant if we re-introduce user-modifiable sysconfigs as referenced in https://github.com/RotherOSS/otobo/issues/2539#issuecomment-1772521158.

**Comment by stefanhaerter** [comment]
Closed with merging #2811
