### ISSUE TITLE
Improve sysconfig description for setting "DefaultLanguage"

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2788]
The description text for the setting says:

> Defines the default front-end language. All the possible values are determined by the available language files on the system (see the next setting).

However, it is not determined which setting is referred to by the term 'next setting'. I would suggest to replace this with the name of the referenced setting, if this can be determined. Interfering from the xml file, I assume that this is `DefaultUsedLanguage`.

https://github.com/RotherOSS/otobo/blob/8866f83fe2f2fe91153c8e59e0664c7c22d5c8ee/Kernel/Config/Files/XML/Framework.xml#L122-L130

**Comment by bschmalhofer** [comment]
Yes, "next setting" is not helpful when shown in the SysConfig GUI.

In a way related to #2707.

**Comment by bschmalhofer** [comment]
Description of 'DefaultLanguage' is adapted. PR in rel-10_0 is applied. Closing this issue.
