### ISSUE TITLE
Alternatives to Elasticsearch

### ISSUE THREAD

**Issue by pat-s** [RotherOSS/otobo#2808]
Elasticsearch is a resource monster and not the most performant one either.
Alternatives such as 

- https://www.meilisearch.com/
- https://zincsearch-docs.zinc.dev/

provide low-resource and faster solutions. 

Have there been any tests in using such alternatives? 

Also, I couldn't find a config option to override the Elasticsearch connection string - is there one exposed or is this not possible at all at the moment?

**Comment by svenoe** [comment]
Hi Patrick,

no, the quick search hasn't been a huge topic recently, as the current Elasticsearch implementation works and we didn't have much requests for any changes or enhancements here.

The connection is handled via the Elasticsearch webservice and can be altered there. With general questions, though, please visit our [forums](https://otobo.de/de/forums/) for community help, or write us an email to hello@otobo.de for professional support. Github is used for development issues only.

Best regards, Sven
