### ISSUE TITLE
Fix dynamic field set value rendering

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2814]
There are a few known bugs when rendering a dynamic field set with stored values.

Also, using a dynamic field which is based on BasedEntity in a set causes problems.

**Comment by stefanhaerter** [comment]
Closed with https://github.com/RotherOSS/otobo/commit/4030748025f323e67321b057e2caf41ee50b5f63 and https://github.com/RotherOSS/otobo/commit/fea5c67cfd59fad914ccbea94b2114f26204502e

**Comment by bschmalhofer** [comment]
Reopening because there is a test failure in _scripts/test/DynamicField/ValueSetGet.t_ which might be related to this issue. Specifically https://github.com/RotherOSS/otobo/commit/4030748025f323e67321b057e2caf41ee50b5f63 .The case in question is the SetOfAgentsAndTexts, test number 85,  test case. My hunch is that the test script needs to be updated.

**Comment by stefanhaerter** [comment]
I'll have a look on monday - thank you for testing =)

**Comment by stefanhaerter** [comment]
I just encountered the test failure myself and this certainly has something to do with changed behavior of one of the field drivers:

```
bin/otobo.Console.pl Dev::UnitTest::Run --test ValueSetGet
[13:52:20] /opt/otobo/scripts/test/DynamicField/ValueSetGet.t .. # RandomID is test7946602794100002
[13:52:20] /opt/otobo/scripts/test/DynamicField/ValueSetGet.t .. 36/? 
# Failed test 'SetOfAgentsAndTexts'
# at /opt/otobo/scripts/test/DynamicField/ValueSetGet.t line 1223.
# Caught exception in subtest: Can't use string ("3") as an ARRAY ref while "strict refs" in use at /opt/otobo/Kernel/System/DynamicField/Driver/BaseEntity.pm line 129.
# Seeded srand with seed '20240122' from local date.
[13:52:20] /opt/otobo/scripts/test/DynamicField/ValueSetGet.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/101 subtests
```

At line 129 in `Kernel/System/DynamicField/Driver/BaseEntity.pm` is a special behavior for single-value entity fields in sets, which I had to include. Most likely, this needs to be adapted again.

**Comment by stefanhaerter** [comment]
I was wrong - unit test needed indeed to be adapted.

**Comment by stefanhaerter** [comment]
@bschmalhofer PR with fix is merged - can you run the tests again to verify that the fix is correct?

**Comment by bschmalhofer** [comment]
The failure in _ValueSetGet.t_ is gone now. Closing this issue again.
