### ISSUE TITLE
Turn the BaseArray parameter into a behaviour

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2845]
Currently there is a parameter `BaseArray` that is passed to the method `ValueStructureFromDB()`. This parameter determines wheter a single value field is returned as a plain scalar or as an arrayref with a single value. This parameter should be replaced by a behavior. The advantage is that the behavior can be inspected from the outside. This is useful e.g. for ImportExport.

**Comment by bschmalhofer** [comment]
This has been implemented with corresponding changes in GeneralCatalog and ITMSConfiguration. Let's keep the issue open in case of problems.

**Comment by bschmalhofer** [comment]
Closing now as no problems cropped up.

**Comment by stefanhaerter** [comment]
Note: Perhaps PR #2862 actually belonged to this issue - not entirely sure, but mentioning it nonetheless to have the link between PR and issue.

**Comment by svenoe** [comment]
I reverted this change after a short discussion, as the initial reason for it, ImportExport using this information, was changed.
