### ISSUE TITLE
Consider rewriting module import of Kernel/Output/HTML/Layout.pm with using File::Basename

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2864]
While using a regex is functionally fine, in my opinion readability and maintainability could be improved by using File::Basename instead.

https://github.com/RotherOSS/otobo/blob/357f4d3dd621c0321d773d41788297c727fdf2a3/Kernel/Output/HTML/Layout.pm#L436-L454

**Comment by bschmalhofer** [comment]
Did a bit of refactoring using `File:;Basename::fileparse()`. Also check whether _HTML/Layout_ is a directory. PR is applied. Closing this issue.

**Comment by stefanhaerter** [comment]
Removing wishlist milestone to distinct it from 'open' wishlist issues.
