### ISSUE TITLE
Fix unit test failures regarding dynamic fields

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2889]
Currently failing are:

- [x] scripts/test/DynamicField/Backend.t
- [x] scripts/test/DynamicField/EditFieldRender.t
- [x] scripts/test/DynamicField/EditFieldValueGet.t
- [x] scripts/test/Selenium/Customer/DynamicFields/DynamicFieldDatabase.t

**Comment by stefanhaerter** [comment]
Two UT failures fixed with merging #2890

**Comment by bschmalhofer** [comment]
Verified in latest run of the test suite:

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1741 Failed: 0)
>   TODO passed:   692, 819
> /opt/otobo/scripts/test/DynamicField/Backend.t                                                            (Wstat: 512 (exited 2) Tests: 131 Failed: 2)
>   Failed tests:  107-108
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/DynamicField/EditFieldValueGet.t                                                  (Wstat: 3072 (exited 12) Tests: 196 Failed: 12)
>   Failed tests:  115-116, 119-120, 123-124, 146-147, 150-151
>                 154-155
>   Non-zero exit status: 12
> /opt/otobo/scripts/test/Selenium/Customer/DynamicFields/DynamicFieldDatabase.t                            (Wstat: 256 (exited 1) Tests: 40 Failed: 1)
>   Failed test:  40
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> Files=966, Tests=81436, 4029 wallclock secs (15.70 usr  2.05 sys + 1089.19 cusr 99.74 csys = 1206.68 CPU)
>

**Comment by bschmalhofer** [comment]
Latest run of the test suite:

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1741 Failed: 0)
>   TODO passed:   692, 819
> /opt/otobo/scripts/test/DynamicField/EditFieldValueGet.t                                                  (Wstat: 3072 (exited 12) Tests: 196 Failed: 12)
>   Failed tests:  115-116, 119-120, 123-124, 146-147, 150-151
>                 154-155
>   Non-zero exit status: 12
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> Files=966, Tests=81578, 4560 wallclock secs (15.48 usr  1.91 sys + 1123.17 cusr 100.57 csys = 1241.13 CPU)
> Result: FAIL
>

**Comment by stefanhaerter** [comment]
Thank you very much for verifying the fixes 😊
I am happy that three of four are done so far, but the fourth is a bit tricky - it has to do with passing an unused value to dynamic fields date(time). I will need a bit of time to get on top of that.

**Comment by stefanhaerter** [comment]
The remaining test failure `scripts/test/DynamicField/EditFieldValueGet.t` should be fixed with merging PR #2947 - waiting for confirmation from @bschmalhofer =)

**Comment by bschmalhofer** [comment]
Looks good:

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1745 Failed: 0)
>   TODO passed:   694, 822
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
> Files=966, Tests=81596, 4333 wallclock secs (15.16 usr  2.12 sys + 1127.03 cusr 102.68 csys = 1246.99 CPU)
> Result: PASS
> ran tests for product OTOBO 11.0.x on host 078559ca0578 .
> 

Closing this issue.
