### ISSUE TITLE
Clarification: possible to customize customer dashboard?

### ISSUE THREAD

**Issue by rubjo** [RotherOSS/otobo#2891]
Hi!

I’ve searched in the docs, but cannot find any info on this.

I know it is possible to activate/deactivate and order widgets, but is it possible to customize/brand the appearance of this page other than this?

Pointers to relevant docs highly appreciated.

**Comment by svenoe** [comment]
Hi rubjo,

for general problems and questions, please visit our [forums](https://otobo.de/de/forums/) for community help, or write to hello@otobo.de for professional support. Github is for development issues only.

Best regards, Sven
