### ISSUE TITLE
Clean up not needed '# Rother OSS' comments in files.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#291]
Just some tidying: `grep '^# Rother' Kernel -r` und `grep '# EO' Kernel -r`

**Comment by bschmalhofer** [comment]
After the commit https://github.com/RotherOSS/otobo/commit/6819be76b4ddb086decf42ffd403ac71114ffb8d the only instances left are in the template toolkit files.

**Comment by bschmalhofer** [comment]
The TODO comment in _Kernel/Output/HTML/Templates/Standard/AgentPreferences.tt_ still seem relevant

# Rother OSS / TODO
#                                [% IF Data.Label == 'Language' %]
#                                    [% Translate("Did you know? You can help translating OTOBO at %s.") | html | ReplacePlaceholders('<a href="https://translate.otobo.org" target="_blank">translate.otobo.org</a>') %]
#                                [% END %]
# EO Rother OSS

**Comment by bschmalhofer** [comment]
The comment in _Kernel/Output/HTML/Templates/Standard/AdminRegistration.tt_ still looks relevant
> \# Rother OSS / TODO / Remove or edit content?

**Comment by bschmalhofer** [comment]
Created dedicated issues for the remaining TODO comments. Therefore closing this issue.
