### ISSUE TITLE
Feature Request: Implement ability to edit agent notes + provide edit history for a given article

### ISSUE THREAD

**Issue by prephen** [RotherOSS/otobo#2934]
### Situation:
An agent provides wrong or otherwise inaccurate information in a given note and adds it to a ticket. The agent now needs to leave a new note correcting their mistake. Other agents need to disregard the inaccurate note / avoid using the inaccurate information to work the ticket.

### Suggestion:
Provide functionality that allows agents to edit their notes. If an edit history can be provided, this can help prevent agents from using edits to completely eliminate or obscure information from other agents without leaving inaccurate information immediately visible in the ticket.

**Comment by svenoe** [comment]
This functionality is currently in development and will come directly or as a package with OTOBO 11.
