### ISSUE TITLE
Disable account creation upon new email received

### ISSUE THREAD

**Issue by mkaag** [RotherOSS/otobo#2942]
Hey there,

perhaps this has been cleared out already, however I haven't find it in the doc or in the repo. I do have a dedicated email address connected to OTOBO, and this address is spammed (of course), which leads to several buggy accounts being created in the OTOBO instance.

Is there a mechanism to disable the account creation when new email arrives? Or maybe dropping email from unknown address? Therefore limiting the access to existing accounts. Legit accounts on my instance have various domain names, so I cannot restrict to a given domain name.

Thank you for your help, best regards,
Maurice

**Comment by svenoe** [comment]
Hi Maurice,

with general questions and problems please either visit our [forums](https://otobo.de/de/forums/) for community help, or write us an email to hello@otobo.de for professional support. Gihub is for development issues only.

Best regards, Sven
