### ISSUE TITLE
Use localization for "Sum" in Stats

### ISSUE THREAD

**Issue by meinhart** [RotherOSS/otobo#2944]
package Kernel::System::Stats

When using dynamic stats elements the sum row and column should be able to be localized. F.e. row column is hardcoded "Sum" and i didn´t get it working that it uses the correct translation with correct culture.

**Comment by svenoe** [comment]
Please confirm whether there is a "Translate()" missing, and add it, if so.

**Comment by stefanhaerter** [comment]
Regarding the sum row, the `Translate()` is indeed missing. Regarding the sum column, `Translatable()` is used (and seemingly does not work), but it works with `Translate()`.

**Comment by stefanhaerter** [comment]
Closed with merging #3827
