### ISSUE TITLE
Include package for custom translations into rel-11_0

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2948]

**Comment by stefanhaerter** [comment]
Closed with merging #2949

**Comment by bschmalhofer** [comment]
Reopening: for consistencies sake the SysConfig settings for Import/Export of translations should be located in _Kernel/Config/Files/XML/ImportExport.xml_ .

**Comment by stefanhaerter** [comment]
Are you already on this? Else I would try to have a look at it in the upcoming week.

**Comment by bschmalhofer** [comment]
I'll leave that to you. But make the change only when it makes sense to you too. I simply figures that having all Import/Export related settings in one XML file is more intuitive.

**Comment by stefanhaerter** [comment]
I have no strong opinion on this. When weighing having all translation options grouped together against having all importexport options in a dedicated file, I can see that the latter one is a bit more attractive. Made a PR: https://github.com/RotherOSS/otobo/pull/3256.

**Comment by bschmalhofer** [comment]
The config has been cleaned up, thanks to @stefanhaerter . No problems were reported. Closing this issue again.
