### ISSUE TITLE
Fix process related unittests

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2951]
There are new test failures, mostly related to processes:

> Test Summary Report
> -------------------
> /opt/otobo/scripts/test/Compile.t                                                                         (Wstat: 0 Tests: 1745 Failed: 0)
>   TODO passed:   694, 822
> /opt/otobo/scripts/test/Selenium/Agent/AgentTicketProcess.t                                               (Wstat: 768 (exited 3) Tests: 106 Failed: 3)
>   Failed tests:  41, 105-106
>   Non-zero exit status: 3
> /opt/otobo/scripts/test/Selenium/Agent/AgentTicketProcessACL.t                                            (Wstat: 256 (exited 1) Tests: 29 Failed: 1)
>   Failed test:  29
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Customer/CustomerTicketOverview.t                                        (Wstat: 512 (exited 2) Tests: 26 Failed: 2)
>   Failed tests:  25-26
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Selenium/Customer/DynamicFields/DynamicFieldDatabase.t                            (Wstat: 256 (exited 1) Tests: 46 Failed: 1)
>   Failed test:  46
>   Non-zero exit status: 1
> /opt/otobo/scripts/test/Selenium/Output/TicketZoom/ProcessInformation.t                                   (Wstat: 512 (exited 2) Tests: 25 Failed: 2)
>   Failed tests:  24-25
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
>   TODO passed:   21, 24, 28
>

**Comment by stefanhaerter** [comment]
Fixes are merged with #2956 - waiting for confirmation to close the issue.

**Comment by bschmalhofer** [comment]
The latest run of the test suite looks fine. Closing this issue.
