### ISSUE TITLE
Question - Response structure for DynamicFields Type Webservice

### ISSUE THREAD

**Issue by jneyses** [RotherOSS/otobo#2959]
Hi all, I configured a dynamic field which should be populated by a value retrieved using a REST invoker. The webservice gets called and also the JSON returned, but the dynamic fields remains disabled with the following message: DynamicField/Agent/WebService.tt

In the web service debugger I can see the values coming back. System log shows no errors.

What is the right structure of the JSON response to fill a dynamic field. Also, is it possible to retrieve multiple values and show them in a drop down box?

Thanks for help. I did already search in the forum and other sources, as well as I reviewed the documentation. But I have not found a solution to my problem yet.

**Comment by stefanhaerter** [comment]
Hi @jneyses,

thank you for reporting this. For the purpose of further investigation, a bit more information will be needed: On which version of OTOBO did this occur? Which type of dynamic field did you use and for which object type? Can you provide the config of the webservice and the JSON you used, so that we can try to reproduce the issue?

Kind regards,
Stefan

**Comment by jneyses** [comment]
Otobo version: 10.1.8

Dynamic Field Information

![image](https://github.com/RotherOSS/otobo/assets/19947672/f807db39-46a0-476a-9979-e1d56698bda1)

![image](https://github.com/RotherOSS/otobo/assets/19947672/34a193d1-f808-435f-861c-a203cd6e3a88)


WebService
![image](https://github.com/RotherOSS/otobo/assets/19947672/b5e448a1-f5b1-4086-9762-a09920373226)

![image](https://github.com/RotherOSS/otobo/assets/19947672/fe9fa056-05d6-4688-bc9b-574870cd3ea4)

![image](https://github.com/RotherOSS/otobo/assets/19947672/8ad45bbd-c213-4b6a-8b6d-1f0a78d2c15a)

![image](https://github.com/RotherOSS/otobo/assets/19947672/80a74401-6294-4905-9193-57cd8aa79b5a)


Data Transferred

Return Data: {"id":"2000123456"}
Data after mapping: 
$VAR1 = {
  'Value' => '2000123456'
};

Thanks

**Comment by svenoe** [comment]
Hi Jürgen,

the webservice fields are clearly bugged, currently. They were added as part of a package in the beginning of OTOBO, but were not used at all, to my knowledge (and apparently). As they are included they should still run, of course, though, but as we are currently quite busy with finishing OTOBO 11, this will probably have to wait a bit.

Best regards, Sven

**Comment by jneyses** [comment]
OK, would we have another alternative to look up values from a webservice? and populate a number of dynamic fields in a ticket? What would your expectations be in terms of timing. Reading above message I would not assume OTOBO 11 to solve the issue.

Regards, Jürgen

**Comment by svenoe** [comment]
You could e.g. just set up a webservice with a ticket update operation, depending on your needs of course. For the timing it's difficult to give an answer without having looked into it further, it likely won't come with 11, yes.
