### ISSUE TITLE
Typographical error in the display of password criteria.

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#2977]
It should be changed from "lang sein" to "enthalten".
![Bildschirmfoto 2024-02-16 um 15 17 44](https://github.com/RotherOSS/otobo/assets/108396552/0814b0bd-2de6-4351-a7ca-2cf3597ceb71)

**Comment by bschmalhofer** [comment]
The appropriate check in _Kernel/Output/HTML/Preferences/Password.pm_ is:

```
    # check min 2 char password
    if ( $Config->{PasswordMin2Characters} && $Pw !~ /[A-z][A-z]/ ) {
        $Self->{Error} = $LanguageObject->Translate('Can\'t update password, it must contain at least 2 letter characters!');
        return;
    }

```
So even the English message is wrong. It should be " must contain at least 2 consecutive letter characters". Also the "2" should be written as "two". In German this would be "zwei aufeinanderfolgende Buchstaben enthalter".

But even that is incorrect as the check is  for `[A-z][A-z]`. That is two letters in the latin script. So any Arabic letter characters or German Umlaute or ß would not be considered.

**Comment by svenoe** [comment]
I would change the regex here, rather than the explanation, because really what we want is to check for "at least two letters".

(The German translation has to be changed in weblate though, and this does not belong here.)

**Comment by stefanhaerter** [comment]
PR ist merged, translation change is proposed in weblate. Closing the issue.
