### ISSUE TITLE
Maybe upgrade FontAwesome font

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#3027]
In the Firefox console there are messages like this:

> downloadable font: Glyph bbox was incorrect (glyph ids 33 55 62 81 82 83 84 87 88 89 90 112 119 120 123 139 159 162 164 166 178 184 185 217 218 272 273 274 275 279 281 284 290 291 292 309 310 319 321 323 326 329 330 331 332 333 334 339 341 347 349 351 352 353 354 357 358 361 366 367 370 371 414 431 436 444 445 458 460 464 465 483 505 508 511 514 516 517 518 520 521 538 539 546 568 574 579 580 585 586 594 596 599 602 603 616 618 622 627 629 630 633 634 638 643 645 651 654 665 675 685 686 688 691) (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1) source: https://localhost:1482/otobo-web/common/fonts/fontawesome-webfont.woff2?v=4.7.0

According to https://github.com/FortAwesome/Font-Awesome/issues/19925 this has been fixed in version 6.5 of FontAwesome. I suggest to investigate whether the font file can be updated.

**Comment by bschmalhofer** [comment]
Font awesome is included in just about the complete interface:

```
grep -r font-awesome.min.css .
./Kernel/Output/HTML/Templates/Standard/HTMLHead.tt:    <link rel="stylesheet" type="text/css" href="[% Config("Frontend::WebPath") %]common/css/font-awesome.min.css" />
./Kernel/Output/HTML/Templates/Standard/Login.tt:    <link rel="stylesheet" type="text/css" href="[% Config("Frontend::WebPath") %]common/css/font-awesome.min.css" />
./Kernel/Output/HTML/Templates/Standard/CustomerHTMLHead.tt:    <link rel="stylesheet" type="text/css" href="[% Config("Frontend::WebPath") %]common/css/font-awesome.min.css" />

```

**Comment by bschmalhofer** [comment]
Moved this to the wishlist, as this does not look important.

**Comment by stefanhaerter** [comment]
Just wanted to open the same issue referencing the same FontAwesome issue ^^

I support the update request.
