### ISSUE TITLE
Iterate over keys or values of hash, not hash itself

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3037]
At a few places, for loops are iterating over a hash, not keys or values. While this is functionaly fine because everywhere there is a check if the iterator is a valid key of the hash, I would consider it a bad coding practice and thus fix it nonetheless.

**Comment by stefanhaerter** [comment]
On rel-11_0, I already identified the relevant places (see below), but I also want to check rel-10_1 and rel-10_0, therefor PR has to wait a bit.

- `Kernel/Output/HTML/TicketOverview/Preview.pm`
  https://github.com/RotherOSS/otobo/blob/c0a2b2f169fd880c6ec25b9ace1b4ae53e101218/Kernel/Output/HTML/TicketOverview/Preview.pm#L276-L283
- `Kernel/System/Auth/OpenIDConnect.pm`
  https://github.com/RotherOSS/otobo/blob/c0a2b2f169fd880c6ec25b9ace1b4ae53e101218/Kernel/System/Auth/OpenIDConnect.pm#L447-L449
- `Kernel/System/Package.pm`
  https://github.com/RotherOSS/otobo/blob/c0a2b2f169fd880c6ec25b9ace1b4ae53e101218/Kernel/System/Package.pm#L2380-L2389
- `Kernel/System/ZnunyHelper.pm`
  https://github.com/RotherOSS/otobo/blob/c0a2b2f169fd880c6ec25b9ace1b4ae53e101218/Kernel/System/ZnunyHelper.pm#L678-L690
  https://github.com/RotherOSS/otobo/blob/c0a2b2f169fd880c6ec25b9ace1b4ae53e101218/Kernel/System/ZnunyHelper.pm#L826-L831

**Comment by bschmalhofer** [comment]
Yes, these loops are strange. @stefanhaerter, could you check whether there is a Perl::Critic policy that covers these cases?

**Comment by stefanhaerter** [comment]
Yes, I think this is a very good idea - I thought about writing a CodePolicy plugin by myself, but if Perl::Critic already covers this, this would be great.

**Comment by stefanhaerter** [comment]
@bschmalhofer At a quick glanze, I couldn't find anything that matches this need at https://metacpan.org/dist/Perl-Critic/view/lib/Perl/Critic/PolicySummary.pod. Perhaps a plugin is needed.

**Comment by stefanhaerter** [comment]
Closed with merging the PRs.
