### ISSUE TITLE
Znuny GmbH Copyright 

### ISSUE THREAD

**Issue by dennykorsukewitz** [RotherOSS/otobo#307]
Hi there,
could please check the Copyright of the following files. We think you might have missed something here:

- [Znuny4OTOBOPasswordPolicy.pm](https://github.com/RotherOSS/otobo/blob/rel-10_1/Kernel/Autoload/Znuny4OTOBOPasswordPolicy.pm) (missing)

greetings

**Comment by svenoe** [comment]
Hi Denny,

I fixed it (3aebc6e38893f75509bf7e69f0510e9ebde3c721), sorry for this. We had overwritten the Copyright of some files with a script in the beginning and evidently had not found every instance of it.

Have a nice evening, Sven
