### ISSUE TITLE
Develop mechanism to add data to sysconfig options to eliminate the need to overwrite them

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3123]
A quick thought I just had: Perhaps it is possible to use in package sysconfig xml a syntax like this

```
<Setting Name="[NameOfExistingSetting]" [...] Mode="Add">
[...]
</Setting>
```

so that the Kernel module handling the sysconfig is able to tell that it should fetch the existing config and add the new data instead of overwrite.

**Comment by svenoe** [comment]
Would be useful, but rather complex, as this would need to change the default for the setting, and cannot just update it in the DB. Thus I'll close this issue, as it probably never will have a high enough prio...
