### ISSUE TITLE
Link to docs seems outdated

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#313]
In https://github.com/RotherOSS/otobo/blob/rel-10_0/doc/README.md the link 

```
[the online documentation](https://doc.otobo.de/)
```

does not lead to documentation. Maybe this is the right one:

https://otobo.de/de/dokumentation/

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO : Should https://doc.otobo.de/ be working? If not then I'll change the links in README.md, doc/README.md, and  CONTRIBUTING.md .

**Comment by StefanRother-OTOBO** [comment]
Hi Helmut,
Hi Bernhard,

thanks very much for your help!

https://doc.otobo.org/ is the right link, cause it is a community part. https://doc.otobo.org/ is working.

I´ve changed it.

Thanks!

Stefan

**Comment by bschmalhofer** [comment]
Fixed two more links in README.md and in CONTRIBUTING.md. Closing again.
