### ISSUE TITLE
Update to PDF::API 2.045

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#3147]
Note that the new optional CPAN package Text::QRCode which is used to produce qrcodes uses libqrencode which is not automatically installed on many distros.

**Comment by bschmalhofer** [comment]
TODO;

- [x] Add the feature div:qrcode to `%IsDockerFeature` and add the required Debian package to _otobo.web.dockerfile_

**Comment by bschmalhofer** [comment]
`Text::QRCode` is now available in new Docker builds.

```
otobo@4dd5e2923296:~$ perldoc -l Text::QRCode
/opt/otobo_install/local/lib/perl5/x86_64-linux-gnu/Text/QRCode.pm
```
