### ISSUE TITLE
Article Edit and Delete feature.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#3157]
Article Edit and Delete feature.

**Comment by stefanhaerter** [comment]
Linking #3111

**Comment by svenoe** [comment]
See https://github.com/RotherOSS/otobo/pull/3188 and the commit e8443c4f3bc0269e42670e8649fc670b432dfef3

**Comment by bschmalhofer** [comment]
I'm wondering whether in that SQL an ORDER BY clause is missing, https://github.com/RotherOSS/otobo/blob/5de8569a76ab70a3ba842738eec67a766710e370/Kernel/System/Ticket/Article.pm#L1225-L1233
This could be related to some failures in the test suite.
