### ISSUE TITLE
Load ckeditor.js only when needed

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#3223]
CKEditor 5 is supported by loading JavaScript libraries in the footer of pages. See https://github.com/RotherOSS/otobo/blob/00268c05ca55726674de03be8c0ecae9df9f365c/Kernel/Output/HTML/Layout.pm#L1810 . Currently that library is loaded for every request. But it would be cleaner to load them only when needed. Another reason is that this would avoid the system call for determining whether the translation file exists.

This could be implemented with the same approach as it is done with the datepicker library. See https://github.com/RotherOSS/otobo/blob/00268c05ca55726674de03be8c0ecae9df9f365c/Kernel/Output/HTML/Layout.pm#L1743

**Comment by AjaySDwivedi1** [comment]
Can I work on this issue? Do I need to change all the if statements that call $ConfigObject->Get() to $HasDatepicker?

**Comment by bschmalhofer** [comment]
Hi @AjaySDwivedi1 ,

you are welcome to work at this and to provide a pull request.

 I suggest that you look at the OTOBO code and understand how the `HasDatePicker` is used. It is basically a flag where frontend modules can indicate that the datepicker JavaScript library is needed for the page. Then you create a similar attribute `HasRichTextEditor` that does the same thing for _ckeditor.js_, Then you have to find all frontends that include a rich text editor and make them raise that new flag.

**Comment by bschmalhofer** [comment]
Sorry @AjaySDwivedi1, I clicked in the wrong tab of my browser and had to revert the PR afterwards.

So your patch is not quite there yet. I fear that solving that issue requires some understanding of OTOBO. So for example see https://github.com/RotherOSS/otobo/blob/df444416feae7c63386f3febf814ca2edf9c4efb/Kernel/Modules/AgentTicketPhone.pm#L3293 . This is an indication that this page uses the rich text editor. So this frontenend module needs to indicate the the _ckeditor.js_ file needs to be loaded. So that at the time the HTML footer is generated, it is know that the library must be included.

So the task is something like this:

- [x] identify the places, that is the frontend modules, where CKEditor is used
- [x] set a flag `HasRichTextEditor`, analoguous to `HasDatepicker`
- [x] add _ckeditor.js_ to the footer only when  `HasRichTextEditor` has been set

But maybe the first step is to get a local development system up and running. See https://doc.otobo.de/manual/installation/11.0/en/content/index.html for inspiration.

**Comment by AjaySDwivedi1** [comment]
Was the code I added correct for setting the flag? Where are other cases where ckeditor.js is loaded? This is my first time coding in Perl so I'm not very familiar with what everything does or is suppose to look like. I'm judging everything I do off the code that already exists in the files.

**Comment by bschmalhofer** [comment]
I suggest that you look first at the code base and search for HasDatePicker. When you understand why and where the flag is set, then the task wiil become more clear.

**Comment by AjaySDwivedi1** [comment]
Hi, I really sorry I got super busy with school. I won't be able to work on this issue anymore. I should've mentioned it sooner, I'm really sorry.

**Comment by bschmalhofer** [comment]
I think that it suffices when setting the flag in `Kernel::Output::HTML::Layout::SetRichTextParameters()`. But this is a bit confusing. Where are config settings like `RichText.Height` used? I didn't find it in _var/httpd/htdocs/js/Core.UI.RichTextEditor.js_ .

**Comment by stefanhaerter** [comment]
`RichText.Height` is still present in the rel-10_1 version of `var/httpd/htdocs/js/Core.UI.RichTextEditor.js`. I suppose it hasn't been transferred or been entirely omitted with the changes the file has undergone when introducing CKEditor 5.

**Comment by bschmalhofer** [comment]
PR is merged. A quick test looked fine. Closing this issue.
