### ISSUE TITLE
Remove duplicate use statement on VariableCheck in Kernel/System/CustomerUser/DB.pm

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3264]
The file Kernel/System/CustomerUser/DB.pm holds a duplicate line importing the OTOBO module Kernel::System::VariableCheck twice. One line should be removed.

**Comment by bschmalhofer** [comment]
Changed the milestone to 10.1.10 as I forgot to check the branch in the PR #3266

**Comment by bschmalhofer** [comment]
Hi Triston, @tristonarmstrong ,

thanks for your first contribution to OTOBO. Your pull request #3266 is applied. Looking forward to hearing from you again with further input.

Best regards,
   Bernhard
