### ISSUE TITLE
Moo.pm and namespace::clean are not bundled, but are claimed to be bundled

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#33]
`Kernel::System::Environment` claims that the package Moo is a bundled module . However there is no bundled Kernel/cpan-lib/Moo.pm.  The same applies to `namespace::clean`and possibly other modules.

There are two possible fixes: 

1. Add Moo and namespace::clean to Kernel/cpan-lib
2. Remove Moo and namespace::clean from `Kernel::System::Environment`and add them to bin/otobo.CheckModules.pl as needed modules

I'm not sure what the preferred approach would be. One hunch is that adding the bundled modules to otobo.CheckModules is sensible in any case.

**Comment by svenoe** [comment]
Leaning towards 2; I will check this somewhen.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

Moo and namespace is not used from OTOBO itself. It's a dependency from selenium, perhaps from other modules too. I´m not sure what's the right way, but I have no good feeling by adding the modules to Kernel/cpan-lib and add they to bin/otobo.CheckModules.pl as needed modules.

For my opinion, bundled module do not say, it must bundled with OTOBO. It's possible that they bundled with other modules? Cause inside the list are a lot of modules not bundled with OTOBO, only with other modules.

What do you think guys?
  
Thanks very much for your help!

Stefan

**Comment by bschmalhofer** [comment]
Well  Math::Random::Secure requires Moo and is used in ./Kernel/System/Main.pm. So this is core dependency.

Which modules are listed in Kernel::System::Environment::PerlInfoGet() and are not available in Kernel/cpan-lib ?

**Comment by bschmalhofer** [comment]
PR submitted and applied.
