### ISSUE TITLE
New Templates and Services wont show in the ticket 

### ISSUE THREAD

**Issue by marcwbbstr** [RotherOSS/otobo#3316]
Hi,

today we created new services and templates for tickets but they wont show in the ticket itself. Is there a limit for the number of services? We have currently 68 Services but only 3 templates.

In hope to get rid of the error i updated Otobo from 10.1.7 to 10.1.9 (docker) but nothing changed.   

![121213](https://github.com/RotherOSS/otobo/assets/110590923/127a340a-7ba4-4cea-b131-89dc224bdb76)

![1212](https://github.com/RotherOSS/otobo/assets/110590923/7235a947-b6a7-4ed2-be18-1e27e0dea305)

![test](https://github.com/RotherOSS/otobo/assets/110590923/c93f413c-9114-413e-af75-f33050f0b76f)

Is this a missconfiguration which somehow i overlooked?

**Comment by svenoe** [comment]
Hi marcwbbstr,

with general questions and problems please visit our [forums](https://otobo.de/de/forums/) for community help, or write us a mail to hello@otobo.de for professional support. Github is used for development issues only.

Best regards, Sven
