### ISSUE TITLE
Feature Request: More comprehensive backup retention strategy

### ISSUE THREAD

**Issue by ict** [RotherOSS/otobo#3337]
We are using the `scripts/backup.pl` for regular backups. It would be very helpful to have a more sophisticated backup retention strategy implemented than just the last N days.

I am imagining something like `borgbackup`'s configuration: `--keep-daily X --keep-weekly Y --keep-monthly Z`, which would then keep the last X daily backups, the last Y weekly backups and the last Z monthly backups.

**Comment by bschmalhofer** [comment]
Filing this as a Wishlist Item.
