### ISSUE TITLE
Various css fixes and changes

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3342]
Using this issue as a collection for a few minor css fixes and changes.

**Comment by stefanhaerter** [comment]
Related to #3359, linking it for the purpose of overview and structure.

**Comment by stefanhaerter** [comment]
Actually, I would prefer to shifting the changes made in #3345 to the default skin, as we have a similar problem there which would be fixed by the same solution.

![default_skin_settingupdatebox](https://github.com/RotherOSS/otobo/assets/46650328/f29922c5-f163-4131-aa47-7adfef8f50e5)

**Comment by stefanhaerter** [comment]
All PRs were merged some time ago - closing the issue.

**Comment by bschmalhofer** [comment]
Looks like the changes made it into OTOBO 11.0.1. Setting the milestone accordingly.
