### ISSUE TITLE
Add possibility to migrate from OTRS 7 to OTOBO 10.1

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#3360]
Add possibility to migrate from OTRS 7 to OTOBO 10.1 using the default migration.pl script.

**Comment by bschmalhofer** [comment]
Reopening because the regex `m/^6|7\.0(.*)$/ `  would also match strings like `6⛄` or `99.997.0adsf`.

**Comment by bschmalhofer** [comment]
Regex has been adapted. PR is merged. Closing this issue again.
