### ISSUE TITLE
ImportExport: Add sorting to JSON export

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3366]
Currently, when exporting data (e.g. ConfigItems) as JSON, the data is unsorted, which leads to different order of hash key / values. This is no problem for most of the time, except when checking the result against a fixed string in unit tests.

However, since the change affects all JSON exports, this needs confirmation.

**Comment by bschmalhofer** [comment]
I second this suggestion. Sorting also makes subsequent exports more comparable.

**Comment by stefanhaerter** [comment]
Provided a PR with the change in question.

**Comment by bschmalhofer** [comment]
This was discussed in the developper meeting and confirmed. PR is merged. Closing this issue.
