### ISSUE TITLE
Translations do not apply to "BreadCrumb."

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#3399]
Translations do not apply to "BreadCrumb." For example, "FAQ" under View by Categories.

![Bildschirmfoto 2024-05-16 um 13 20 35](https://github.com/RotherOSS/otobo/assets/108396552/de614b9d-9beb-496d-b3e4-c628d90a744a)

**Comment by stefanhaerter** [comment]
Edit: Following comment is obsolete. The bug affects customized translations not being applied to the breadcrumb.

Can you please specify to which version this applies and if other circumstances are relevant? I had a quick look and at least with the latest 11.0, my breadcrumb got translated:

![Bildschirmfoto vom 2024-05-16 13-26-53](https://github.com/RotherOSS/otobo/assets/46650328/6f79da48-e1b6-4fa6-ad31-766b299626cd)

**Comment by stefanhaerter** [comment]
This is due to missing `Translate`-Statements in the FAQ package templates. I will fix this.

**Comment by stefanhaerter** [comment]
Fix is pushed and will be published with the next release - closing the issue in the meantime.
