### ISSUE TITLE
Qlik Sense Hub Problem

### ISSUE THREAD

**Issue by LuboPerunko** [RotherOSS/otobo#3401]
I'm trying to log into Qlik Sense Hub, but it won't accept any of my credentials. 

I'm connected to a VPN, I have a secure network set up, yet when I enter my login credentials - username and current password it just won't let me into the system.
![Screenshot 2024-05-16 155906](https://github.com/RotherOSS/otobo/assets/170012692/d40a1154-bdbf-4d6a-b05d-580008393b24)

**Comment by bschmalhofer** [comment]
This issue looks like it is not related to OTOBO. Closing this issue.
