### ISSUE TITLE
Disable PostMaster::PreFilterModule###000-DetectAttachment by default

### ISSUE THREAD

**Issue by MarkusHlinka-OTOBO** [RotherOSS/otobo#3419]
By default, the setting `PostMaster::PreFilterModule###000-DetectAttachment` is enabled, which could cause issues for the fetching of mails with large attachments.

For future releases, this setting should be disabled by default.

Error message received for mails with large attachments, if the setting is enabled:
`Error: Timeout of 600 seconds reached, killing child process!`

**Comment by StefanRother-OTOBO** [comment]
Disabled in OTOBO 11 Standard.
