### ISSUE TITLE
ticket type empty in "ticket change" event though one is defined

### ISSUE THREAD

**Issue by sweting** [RotherOSS/otobo#3447]
**Installed Version:** 11.0.2 (Upgrade from 10.1)

## Problem - Steps to reproduce
 1. Ticket is created
 2. Set type is set to `other` with function ***change ticket***
 3. In ***ticket information*** widget i can see the type os changed to `other` also in ticket history (screen 1)
 4. Open the ***change ticket*** the title is set correct but the type is empty (screen 2)
 
### screen 1
![image](https://github.com/RotherOSS/otobo/assets/17857051/61878c7b-1f9a-451a-ad1c-ec555825523a)

### screen 2 
![image](https://github.com/RotherOSS/otobo/assets/17857051/076b89f7-8aa8-4dcb-9272-bf515c859c86)

Do you need more information on that?
It would be great if this issue can be fixed

There is a post in forum too: https://otobo.io/forums/topic/update11-0-1-ticket-typ-feld-nach-auswahl-leer-typ-felder-werden-uebersetzt/#post-30598

**Comment by svenoe** [comment]
Hi sweting,

I was aware of this issue, already, we will definitely have a look at it,
thanks for reporting and best regards,

Sven

**Comment by stefanhaerter** [comment]
Issue should be fixed with merged PR #3458 - leaving it open until further confirmation.

**Comment by sweting** [comment]
Great. I took your fix into our testing system and i works. So I can confirm from my site. 
Thanks for the very fast fix.
