### ISSUE TITLE
Add Data::Peek to feature devel:test in bin/otobo.CheckModules.pm

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3461]
While testing on Ubuntu 24.04, I encountered a problem with the perl module `Data::Peek`. Installation via `cpanminus` failed because `gcc` was not installed. Also, in `bin/otobo.CheckModules.pm` the entry `Data::Peek` is registered only for the feature `devel:encoding` despite unit test `scripts/test/DB/UTF8Range.t` failed when it wasn't present.

I suggest the following:

- [x] Add `devel:test` to feature list of entry for `Data::Peek`
- [x] Add `aptget` package to same entry
- [x] Add package names for other package managers if available

Addendum: At the moment, I don't know if this only affects `rel-11_0` or `rel-10_1` and `rel-10_0` also, so I set the milestone *OTOBO 11.0.3*.

**Comment by bschmalhofer** [comment]
All of that sounds good to me. Please also add a sample command in the POD that shows the command line for installing the modules needed for running the test suite.

**Comment by stefanhaerter** [comment]
Closed with merging #3464

**Comment by bschmalhofer** [comment]
@stefanhaerter  Could you also update the cpanfiles?  See `bin/otobo.CheckModules.pl -h`.

**Comment by stefanhaerter** [comment]
Sure - PR is https://github.com/RotherOSS/otobo/pull/3468

However, I only got changes for cpanfile and cpanfile.docker - not for Kernel/cpan-lib/cpanfile. Is this supposed to be or does this indicate some kind of problem?

**Comment by bschmalhofer** [comment]
_Kernel/cpan-lib/cpanfile_ should not be changed as the modules in _Kernel/cpan-lib_ have not changed.

Closing again, after the cpanfiles have been updated.

**Comment by bschmalhofer** [comment]
Sometimes it is useful to turn warnings into warnings with stack trace. This can be done with [Devel::Confess](https://metacpan.org/release/HAARG/Devel-Confess-0.009004/view/lib/Devel/Confess.pm). The implementation would use  the same approach as with Devel::Peek. See also #4465 .
