### ISSUE TITLE
Fullscreen mode for CKEditor 5

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#3477]
CKEditor 5 does not seem to support full screen mode per default. But having a fullscreen mode would be nice to have. There are several plugins that might do the job.

See:

- https://github.com/indico/ckeditor5-full-screen?tab=readme-ov-file
- https://github.com/leknoppix/ckeditor5-fullscreen
- https://github.com/pikulinpw/ckeditor5-fullscreen

TODO:

- [ ] evaluate the plugins
- [ ] add the selected plugin, if it works well

**Comment by bschmalhofer** [comment]
Closing, as the convention is that issues in the wishlist should be closed.

**Comment by stefanhaerter** [comment]
Has been solved via package in the meantime, thus removing it from the Wishlist milestone.
