### ISSUE TITLE
Allow adjustment of Richtext settings in Otobo 11

### ISSUE THREAD

**Issue by clemens1423** [RotherOSS/otobo#3492]
Actually, it's not possible to adjust any richtext settings in the system configuration of Otobo 11.
The available options like Frontend::RichText::DefaultCSS are ignored.
For example, it's not possible to change the font size or settings like line width.

Based on this forum post https://otobo.io/forums/topic/richtext-zeilenabstaende-entfernen/, it's due to the fresh implementation of CKEditor 5.

**Comment by stefanhaerter** [comment]
Development note: According to https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html, custom styles whould have to be placed in a static file.

**Comment by chzauleck** [comment]
for clarification:
The Frontend::RichText::DefaultCSS setting should work, but it is important to note that the CSS is bound to the article at the time of creation, that means changing this setting will only apply to articles created after the setting has been changed and deployed. Any articles already in the system at that time will keep their original styles.

**Comment by svenoe** [comment]
But the changes are only reflected in the article itself, not in the editor, which was different in OTOBO 10 with CK4, and which would be somewhat desirable, to be able to see what you are producing.
