### ISSUE TITLE
Hardcode /root/.cpanm in cleanup command in Dockerfile

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#3494]
This issue was initially reported in the otobo-docker repository:

I now did some digging and found an old issue with a similar problem, see https://github.com/RotherOSS/otobo/issues/972 . The strange UIDs seem to stem from CPAN. This satisfies my concern that something very strange is going on.

The fix for the old  problem was the cleaning up of _$HOME/.cpanm_ . This solution still seems to be in place and seems to be working for most environments. In your environment however, the build context seems to be different. Maybe your `$USER` is _/_ instead of _/root_. 

I see no problems in hardcoding `/root/.cpanm` . I'll do that in a branch in the otobo repository.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo-docker/issues/136#issuecomment-2168145267_

**Comment by bschmalhofer** [comment]
Hi @tb-killa,

could you take a look at the branch https://github.com/RotherOSS/otobo/tree/issue-%233494-cleanup_of_dot_cpanm ? Does the build work for you with the hard coded _/root/.cpanm_ ?

Best regards,
   Bernhard

**Comment by bschmalhofer** [comment]
The same or a similar problem was reported in the OTOBO community forum; https://otobo.io/forums/topic/installation-von-otobo-otobolatest-11_0-failed-to-register-layer/

**Comment by tb-killa** [comment]
@bschmalhofer Kann bestätigen, läuft ohne Probleme durch :)

**Comment by bschmalhofer** [comment]
@tb-killa , I'm still confused about this issue. My current understanding is that your build of the Docker image worked because the build was done in the Docker LXC Container.

Anyways, I did another iteration on _otobo.web.dockefile_ where I'm removing _/root/.cpam_ in the RUN where `cpanm` is used.
Could you try running with  the devel Image rotheross/otobo:devel-rel-11_0 from Docker Hub?  The image can be specified in the _,env_ file. Make sure that you call   `docker pull rotheross/otobo:devel-rel-11_0` before starting, so that you get the most recent build.

**Comment by bschmalhofer** [comment]
The last fixes in _otobo.web.dockerfile_ are looking good. See https://otobo.io/forums/topic/installation-von-otobo-otobolatest-11_0-failed-to-register-layer/#post-31296 .

**Comment by bschmalhofer** [comment]
I checked whether the same problem is present in rel-10_0 and rel-10_1. These branches seem to be fine. The problem was introduced in #2278 for rel-11_0.

**Comment by bschmalhofer** [comment]
No problems were encountered regarding the hard coded _/root/.cpanm_ . Closing this issue.
