### ISSUE TITLE
Owner blanked when closing a ticket OTOBO 10.1.7

### ISSUE THREAD

**Issue by basher-72** [RotherOSS/otobo#3501]
When you close a ticket the ticket's owner is set to blank .
I tried also to set the Onwer as mandatory. The owner field is visibile in the agent's closure windows and it is correctly valued to a specific agent. But when the ticket is close the owner is saved as "--".

**Comment by svenoe** [comment]
Hi basher,
there is a SysConfig setting for this. With general questions however, please visit our [forums](https://otobo.io/de/forums/) for community help, or write us an email to hello@otobo.io for professional support. Github is for development issues only.
Best regards, Sven
