### ISSUE TITLE
Apache: no longer support Apache version less than 2.4

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#351]
https://httpd.apache.org/ said in January 2018:

```
As previously announced, the Apache HTTP Server Project has discontinued all development and patch review of the 2.2.x series of releases.

The Apache HTTP Server Project had long committed to provide maintenance releases of the 2.2.x flavor through June of 2017. The final release 2.2.34 was published in July 2017, and no further evaluation of bug reports or security risks will be considered or published for 2.2.x releases.

```
So I think that OTOBO has no need to support Apache 2.2 or earlier.

@StefanRother-OTOBO : Do you agree ?

**Comment by bschmalhofer** [comment]
See also #132

**Comment by svenoe** [comment]
Might be good, to use a higher version for TLS 1.3. (@wollmers)

**Comment by bschmalhofer** [comment]
Assigned the issue to @wollmers , because he is our Apache config expert.

**Comment by wollmers** [comment]
@svenoe 

For TLS v1.3 see https://unix.stackexchange.com/questions/443341/how-to-enable-tlsv1-3-in-apache2

```
TLSv1.3 is now supported in Apache2 version 2.4.36 with OpenSSL 1.1.1
```

On Debian current stable "Buster" 10.5:

```
apache2          2.4.38-3+deb10u4
openssl           1.1.1d-0+deb10u3
```

On Debian old-stable "Stretch" 9.12 only TLS v1.2 is available:

```
apache2              2.4.25-3+deb9u9
openssl              1.1.0l-1~deb9u1
```

In both cases needs to turn off TLS v1.0 and v1.1, adaption of Apache-conf and (if used) certbot/letsencrypt Apache-include.

Popular browsers will force you to support TLS v1.2 as a minimum, but v1.3 is recommended. IMHO it's worth a chapter in the docs.

For other Linux distros I can't tell exactly. It depends on the versions of Apache and OpenSSL.

**Comment by wollmers** [comment]
@bschmalhofer Partly needs coordination of release and matching documentation. See e. g. https://github.com/RotherOSS/doc-otobo-installation/issues/20

**Comment by StefanRother-OTOBO** [comment]
Yes, I agree. Support of Apache 2.4 is sufficient.

**Comment by bschmalhofer** [comment]
Removed all the version checks. Keep the config for Apache 2.4. Closing the issue.
