### ISSUE TITLE
Check removal of sub ShowTicketStatus from Kernel/Modules/CustomerTicketOverview.pm

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3540]
The `sub ShowTicketStatus` in `Kernel/Modules/CustomerTicketOverview.pm` is called once, which is in the module itself. However, the calling code block is outcommented since the very beginning of OTOBO:

https://github.com/RotherOSS/otobo/blob/f9966778cec3053be793c1eeec757f22b4265b3a/Kernel/Modules/CustomerTicketOverview.pm#L585-L611

A quick comparison with OTRS, where the code was still in place in rel-6_0_32, leads to the assumption that `ShowTicketStatus` has been replaced by the call to `$TicketListObject->Run()` below and the sub indeed is a leftover.

If so, it should be cleaned up.

**Comment by stefanhaerter** [comment]
Closed with merging #3601

**Comment by bschmalhofer** [comment]
I propose to actually remove `ShowTicketStatus()` in OTOBO 11.2
