### ISSUE TITLE
AgentTicketQuickClose doesn't lock a ticket

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#3559]
When I close a ticket with QuickClose (AgentTicketQuickClose), in my understanding the ticket should be locked (and therefore an owner should be set) because of the setting Ticket::Frontend::AgentTicketQuickClose###RequiredLock
But that doesn't happen.
This is necessary to save the person who closed the ticket as an owner to the ticket.

I reproduced this on OTOBO 10.1.10 (ov254)

**Comment by svenoe** [comment]
I think closing tickets always unlocks them. However "RequiredLock" should imply that the ticket has to be lockable by me (not locked by another person) and that I will be set as the owner, I would say.

**Comment by svenoe** [comment]
Do that for 10.0 or 10.1, whereever applicable, please.

**Comment by stefanhaerter** [comment]
Closed with merging #3839
