### ISSUE TITLE
Check where sysconfig values can be replaced with entities

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3561]
In `Kernel/System/SysConfig/ValueType/Entity/`, there are selections provided for several entity types. Perhaps it makes sense to check where plain text value items can be replaced with entities for convenience.

Putting this on milestone 11.1 for the time being, but perhaps this is something for the wishlist.

**Comment by bschmalhofer** [comment]
Good idea.

**Comment by stefanhaerter** [comment]
See also https://github.com/RotherOSS/otobo/issues/1336#issuecomment-1007382995

**Comment by stefanhaerter** [comment]
ToDos:

- [x] Identify and adapt occurrences where to insert entities
- [x] Check if code relying on these sysconfigs still works with entities

**Comment by stefanhaerter** [comment]
Closed with merging #3564
