### ISSUE TITLE
Otobo Dark skin broken after update

### ISSUE THREAD

**Issue by Rainson12** [RotherOSS/otobo#3562]
We have updated today to the Otobo 11.0.3 version and the Dark Skin looks kind of odd in the alternate row styling:
![image](https://github.com/RotherOSS/otobo/assets/13119203/90e3db2e-95ea-466a-89c9-877893582f97)
The light gray text on white alternate row is very hard to read and I would suggest to change it.

This is due to `--colBGElement` css attribute set to #fff. In the darkmode this should rather be set to something like `#1f1f1f`

**Comment by Rainson12** [comment]
seems like this is an issue of the dark skin which is no longer actively maintained. I have created a PR but it doesnt look like the owner of the repo will merge it:
https://github.com/relkai/otobo-dark-skin/pull/3

Until then the darkskin should be removed or pulled from my repo

**Comment by bschmalhofer** [comment]
@Rainson12 There is a highcontrast skin in OTOBO core, but I haven't actually tried that skin myself. You can also try asking in the OTOBO forum, https://otobo.io/en/forums-en/otobo/english-area/.

Closing this issue here, as it is about a third-party enhancement.
