### ISSUE TITLE
No token refresh for long taken answer writing

### ISSUE THREAD

**Issue by mosling** [RotherOSS/otobo#3567]
Start yesterday to answer a ticket, finished it today and got the following message after pressing send.

![image](https://github.com/RotherOSS/otobo/assets/3647440/ad93064a-14e9-4c9e-91a6-6e0fbdfe3c4d)

And my answer was removed. 

The suggested behavior should:
-  using a refresh token
- ask me for credentials
- but never remove my message and show this failure

Can this be changed using installation configuration?

Thanks
Steffen

**Comment by svenoe** [comment]
Hi Steffen,

yes, OTOBO does not have a feature for this. Although we agree that it would be nice, it was not yet requested by any paying customer and is not high enough on our priority list, else. You can either store the answer as draft, when finishing for a day, or you could change the SysConfig, which determines how long your session will be valid (which can have security implications however, of course).

I will close this issue, as we are aware of this topic, but at least currently won't implement further functionality here, just for priority reasons. If it is important to you, you can consider writing an email to hello@otobo.io, to hire us to develop it, and make it available for everyone.

Best regards, Sven
