### ISSUE TITLE
Splitting tickets with inline images looses images

### ISSUE THREAD

**Issue by escix** [RotherOSS/otobo#3569]
Hi,

An email with inline images comes as a follow up to a closed ticket.
As the new email is a different subject I tried to split it as email ticket and reply to it.
When I split the ticket as email ticket the inline images do show up in the reply dialog, but once email sent the image is not there.

The image source in dev tools looks like this 
image001.jpg%4001DAC89A.E2CE7170

**Comment by stefanhaerter** [comment]
Closing the issue, see https://github.com/RotherOSS/otobo/issues/3594#issuecomment-2230826775.
