### ISSUE TITLE
Allow wrapping in CKEditor5 inputs.

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3571]
> Heya,
>
> we are running OTOBO 11.0.1 and using the CMDB module.
>
> We have encountered a layouting issue with the new CKEditor 5 Component.
> When editing CMDB Formatted Text Fields the CKEditor component displays the whole paragraph in one line and shows > a horizontal scrollbar instead of line-wrapping as expected.
>
> A temporary solution was to add 
>
> ```
> .ck-content {
>     text-wrap: wrap;
>     white-space: pre-wrap;
> }
> ```
>
> to the Stylesheet.
>
> Possibly already adressed in #3359 with the CKEditor Resize fixes?

_Originally posted by @jennypaxian in https://github.com/RotherOSS/otobo/issues/3359#issuecomment-2208532740_

**Comment by stefanhaerter** [comment]
Reproduced in the following screenshots:

![agentitsmconfigitemedit_description](https://github.com/RotherOSS/otobo/assets/46650328/f1175bec-02a7-4681-b4dc-e1ab6b642feb)

Description field working normal

![agentitsmconfigitemedit_dfrichtext](https://github.com/RotherOSS/otobo/assets/46650328/cc8f53d2-b3ad-43b0-9439-e830019d6b5c)

DynamicField RichText with buggy behavior

**Comment by svenoe** [comment]
This also affects the CustomerInterface in general currently, which I will change with the next commit for 11.0.5. The whole thing should be reviewed, though. Wrapping should work everywhere in the editor.
