### ISSUE TITLE
Tidy boolean HTML attributes

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3583]
> I found some leftovers of `disabled="disabled"`. Is this supposed to be also changed to `disabled` or are there objections?

_Originally posted by @stefanhaerter in https://github.com/RotherOSS/otobo/issues/2333#issuecomment-2178419121_

**Comment by bschmalhofer** [comment]
No objection to tidying the `disabled` attributes. That attribute is specced as boolean, see https://html.spec.whatwg.org/multipage/indices.html#attributes-3 .

**Comment by stefanhaerter** [comment]
I found a list of boolean html attributes:

- [x] checked (input type=checkbox/radio)
- [x] selected (option)
- [x] disabled (input, textarea, button, select, option, optgroup)
- [x] readonly  (input type=text/password, textarea)
- [x] multiple (select,input)
- [x] ismap isMap (img, input type=image)

- [x] defer (script)
- [x] declare (object; never used)
- [x] noresize noResize (frame)
- [x] nowrap noWrap (td, th; deprecated)
- [x] noshade noShade (hr; deprecated)
- [x] compact (ul, ol, dl, menu, dir; deprecated)

Edit: Confirmed via grep that the ticked attributes are not falsely used ( `grep '[ATTRIBUTE]=' -Rl ./`, e.g. `grep 'defer=' -Rl ./` )

**Comment by bschmalhofer** [comment]
Fixed the HTML generated by `BuildSelection()`. The fix is in commits that were mistakenly linked to #3584 . After the fix the test suits looks fine again.
There is also a bit of refactoring. Boolean attribute can, and should, now be indicated by the variables provided by `Types::Serialiser`.

**Comment by stefanhaerter** [comment]
Attributes tidied, closing the issue.
