### ISSUE TITLE
ERROR:  function lower(bytea) does not exist

### ISSUE THREAD

**Issue by escix** [RotherOSS/otobo#3585]
Had another log error:
[Sat Jul  6 21:35:52 2024][Error][Kernel::System::User::Preferences::DB::SearchPreferences][180] ERROR:  function lower(bytea) does not exist

Not sure how it triggered but happened when I just logged in as admin.

**Comment by stefanhaerter** [comment]
Closing the issue, see https://github.com/RotherOSS/otobo/issues/3594#issuecomment-2230826775
