### ISSUE TITLE
CMDB Textarea Dynamic Field fails to render line breaks

### ISSUE THREAD

**Issue by jennypaxian** [RotherOSS/otobo#3591]
We have configured a Textarea field "Tätigkeitsfeld" for our CMDB Class and upon entering or editing the data of a CMDB Entry we can enter newlines into the text field.

However as soon as we look at the finished entry, the text is no longer rendered in multiple lines.
This seems to not be a CSS issue, the newlines are completely missing.

See attached screenshots.

OTOBO Version 11.0.1

![Tätigkeitsfeld](https://github.com/RotherOSS/otobo/assets/154561207/4ddf8f3f-0a3a-49be-8663-a899d38ee303)
![Editor](https://github.com/RotherOSS/otobo/assets/154561207/8c1c2c22-b0e7-4a5d-9750-04143459b4f5)
![Rendering](https://github.com/RotherOSS/otobo/assets/154561207/cdfa758f-30f9-4904-943b-91883969a7eb)
![HTML](https://github.com/RotherOSS/otobo/assets/154561207/ced453f9-7a81-479a-a648-3434b0d76964)

**Comment by stefanhaerter** [comment]
Hi Jenny,

this bug is fixed now with pull request #3599. It will be included in the next release. If you prefer to have it earlier, you can insert the change which was included in the PR into the code.

Thanks for reporting it :)

Kind regards,
Stefan
