### ISSUE TITLE
Align WebMaxFileUpload in Frontend and Backend

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#3602]
This has to be verified, but from one report and a quick look, WebMaxFileUpload in the backend is used (also historically) for single file sizes. The frontend however seems to also have a check for combined upload size, see e.g.: https://github.com/RotherOSS/otobo/blob/e92f9cef2343505d3b2fa88690116e72b28b4350/var/httpd/htdocs/js/Core.UI.js#L840-L845
Somewhere in the frontend this leads to the file not being shown as uploaded, when in the backend it actually is.

Optimally both restrictions should be available, but set by two individual variables. The existing WebMaxFileUpload should uniformly be used only for single file sizes, but we should introduce a second Config which restricts total upload size, which then, of course also has to be checked in the backend.

**Comment by stefanhaerter** [comment]
Closed with merging the PRs for rel-11_1.
