### ISSUE TITLE
General translations in the processes will only work on the agent side in version 10.1.

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#3624]
General translations in the processes will only work on the agent side in version 10.1.x :

![Bildschirmfoto 2024-07-18 um 10 59 58](https://github.com/user-attachments/assets/8a5fa986-e1c0-4331-80e0-0373890e2351)

![Bildschirmfoto 2024-07-18 um 11 00 56](https://github.com/user-attachments/assets/92dab09b-a902-4377-a48c-82c8950f60d6)

**Comment by stefanhaerter** [comment]
Related to #2958

**Comment by stefanhaerter** [comment]
#3625 merged, closing the issue.
