### ISSUE TITLE
Hiding deleted articles does not work.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#3636]
While fixing this, please have a look what "ArticleStatus=1" does, or rather the redirect link in AgentTicketZoom in general, after deleting. In my opinion it should not change at all, if not really necessary.

**Comment by svenoe** [comment]
This is some cache problem.

**Comment by bschmalhofer** [comment]
Testing the behavior related to deleting articles in the AgentTicketZoom frontend. The system is a newly set up Docker installation using a local build of rel-11_0. The single article view in AgentTicketZoom was activated in the cases below. When viewing all articles everything seems to be fine.



## Behavior where deleted articles are either listed or not

The button 'Show deleted articles' or 'Hide deleted articles' is not touched

### Deleted articles are listed:

- Not deleted article is deleted => article list is updated, deleted article still shown
- Deleted article is restored       => article list is updated, deleted article still shown

### Deleted articles are now listed

- Not deleted article is deleted => article list is updated, the initial article is shown
- Deleted article is restored       => does not apply

## Behavior when the listing behavior is changed

The button 'Show deleted articles' or 'Hide deleted articles' is pressed. A followup article is viewed.

### No deleted articles exist, thus the viewed article is not deleted

- Clicking 'Hide deleted articles' => The first article is shown       **BUG**
- Clicking 'Show deleted articles' => The first article is shown       **BUG**

### A deleted article is viewed 

- Clicking 'Hide deleted articles' => The first article is shown, this is sensible behavior
- Clicking 'Show deleted articles' => does not apply

### There is a deleted article, but a non-deleted article is viewed

- Clicking 'Hide deleted articles' => The first article is shown       **BUG**
- Clicking 'Show deleted articles' => The latest deleted article is shown, that can be considered sane behavior

**Comment by svenoe** [comment]
The problem here was a non updated TimeAccounting which messed with the cache. Sorry for the confusion. @bschmalhofer, if you think one of your other findings, the link to different articles warrants an issue, please open a separate one.
