### ISSUE TITLE
Error when storing namespaces a second time.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#3641]
I can store and deploy a DF namespace in the SysConfig, but if I go to the setting again, enter edit mode and directly press "ok" again, the SysConfig will complain that the Regex does not match. Deleting the Namespace via "-" and readding 1:1 it via "+" works again, but it is not nice when dealing with a lot of entries.

**Comment by stefanhaerter** [comment]
I did a quick research and it seems to be a js issue. The regex in question is (see ¹ for explanation)

```
^[a-zA-Z0-9]{,64}$
```
According to the [Perl Regex Documentation](https://perldoc.perl.org/perlre#Quantifiers), perl supports a pure maximum quantifier ( `{,n}        Match at most n times` ). But according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Quantifiers), JavaScript doesn't, and the validation which fails is the one in JavaScript.

So, a workaround coud be to adjust the regex like so:

```
^[a-zA-Z0-9]{1,64}$
```

¹ Matches every lowercase and uppercase character between A and Z and every digit from 0 to 9 at most 64 times

**Comment by stefanhaerter** [comment]
Closed with merging #3643
