### ISSUE TITLE
Ticket wrong displayed

### ISSUE THREAD

**Issue by dischenk** [RotherOSS/otobo#3648]
Some Ticket content is displayed erroneously.

**Comment by svenoe** [comment]
Ich bin mir nach einem kurzen Blick leider nicht sicher, wo das Problem ist. Könnten Sie bitte aber ersteinmal dieses Issue komplett löschen, die Historie ihres Posts ist immer noch einsehbar (öffentlich!). Danach ist auch eigentlich unser [Forum](https://otobo.io/forums/otobo/otobo-forum/) die erste Anlaufstelle für Fragen an die Community, oder schreiben Sie uns bitte an hello@otobo.io falls Sie gerne professionellen Support in Anspruch nehmen würden. Github wird bei uns rein für technische Dinge genutzt.

Mit freundlichen Grüßen
