### ISSUE TITLE
Refactoring using List::Util::pairs

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3660]
I assume that in at least a few places iterations over a hash are done where key and value are processed. In this places, [List::Util::pairs](https://metacpan.org/pod/List::Util#pairs) could be a viable refactoring option.

**Comment by stefanhaerter** [comment]
Putting this on the wishlist and closing it.

**Comment by stefanhaerter** [comment]
Provided a small example in #3671

**Comment by bschmalhofer** [comment]
I think that we won't do a full refactoring where all loops over hashes are changed. So I think that having an example is good enough for now. New code can then make use of `List::Util::pairs()`.

**Comment by stefanhaerter** [comment]
Agree, sounds like a good idea.
