### ISSUE TITLE
CKEditor layout broken in AgentTicketBulk and AgentTicketFreeText

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3672]
AgentTicketBulk:

![agentticketbulk](https://github.com/user-attachments/assets/03ee25f8-e7c7-4da4-ae8a-c31663ac53f1)

AgentTicketFreeText:

![agentticketfreetext](https://github.com/user-attachments/assets/a0363362-ad13-400a-90ed-5a43f6ff5c75)

My assumption would be that the CKEditor initialization is not performed because the Editors are only visible after unfolding the corresponding area.

**Comment by escix** [comment]
No problems in my instance with OTOBO 11.0.3 and Edge.

**Comment by stefanhaerter** [comment]
Most likely then the behavior is related to changes to CKEditor behavior between OTOBO versions 11.0.3 and 11.0.4 - thank you for testing it =)
