### ISSUE TITLE
Usage of ACL with DynamicFieldSets

### ISSUE THREAD

**Issue by maettyhawk** [RotherOSS/otobo#3675]
Two observations when applying ACL on DynamicFieldSets in CustomerTicketMessage view:

- a mixture of filter conditions and value changes within / outside of the DynamicFieldSet is not possible (f. e. I specify the value of a DynamicField outside a DynamicFieldSet as a filter condition and then want to suppress a DynamicField within the DynamicFieldSet)
- assuming I have three DynamicFieldSets using the same DynamicField only the last appearence can be addressed by ACL

Maybe I misunderstand the DynamicFieldSet concept, but currently the documentation is pretty poor on this feature. 😅

**Comment by svenoe** [comment]
Hi matteyhawk,

with general questions please either visit our [forums](https://otobo.io/de/forums/) for community help, or write a mail to hello@otobo.io for professional support. Github is for development issues only. (Though we are aware that our documentation needs improvement quite some places...)

Best regards, Sven
