### ISSUE TITLE
CKEditor broken in AgentTicketCompose since OTOBO 11.0.5: CKEDITOR is not defined

### ISSUE THREAD

**Issue by wornet-aer** [RotherOSS/otobo#3690]
We have upgraded our Docker based OTOBO from 10.1 to 11.0.5 using https://doc.otobo.org/manual/installation/11.0/en/content/updating-docker.html#update-otobo today. Unfortunately it seems like the upgrade has broken the CKEditor in AgentTicketCompose view.

The ticket body is only displayed as HTML, the browser (FF and Chrome tested) shows an alert box "An error occurred", the JS Console says "Uncaught ReferenceError: CKEDITOR is not defined". However the other pages with CKEditor e.g. for adding notes to a ticket are working fine.

Can anyone reproduce this behaviour?
Any ideas on how to fix this?

**Update**: 
Tried to clear server-side caches, but the error seem to persist.
`./bin/otobo.Console.pl Maint::Loader::CacheCleanup` and `./bin/otobo.Console.pl Maint::Cache::Delete` did not help.

<img width="691" alt="otobo_fehler" src="https://github.com/user-attachments/assets/938438c1-aed5-4520-82d4-4e147c2e765b">

**Update2**:
With ` Loader::Enabled::JS` set to 0 the error still persists, so the JS-minify is not the problem in this case.

**Workaround**:
`var/httpd/htdocs/js/Core.Agent.TextModule.js` needs two edits:

Line 55 -> 57
```
//    CKEDITOR.on('instanceReady', function(CKevent) {
//       TargetNS.DragAndDrop(CKevent);
//     });
```

Line 94 -> 98
```
//     CKEDITOR.on('instanceReady', function() {
//       const Width = $('#cke_RichText').css('width');
//       $('#cke_RichText').css('width', '');
//       $('#cke_RichText').css('max-width', Width);
//     });
```

We didn't notice any major side-effects yet. All Text-Edit views seem to be working fine now.

**Comment by svenoe** [comment]
Hi Andreas,

the js file `var/httpd/htdocs/js/Core.Agent.TextModule.js` is not part of the standard, but likely a custom package. Those have to be upgraded, too. You can find out via `bin/otobo.Console.pl Admin::Package::ListInstalledFiles` which package this file belongs to.

Best regards, Sven

**Comment by md-esw** [comment]
I have also after 11.0.5 upgrade to 11.0.6/11.0.7 no CKEDITOR visible.
With Cache Clean i have now visible again back.

But whats the problem?

**Comment by svenoe** [comment]
> I have also after 11.0.5 upgrade to 11.0.6/11.0.7 no CKEDITOR visible. With Cache Clean i have now visible again back.
> 
> But whats the problem?

You could stick to your own issue, where you claimed it was not a cache problem and read my first reply again, maybe it helps after all, maybe it is something else though - no promises. Else please visit the [forums](https://otobo.io/forums/otobo/otobo-forum/) for community help, or write an email to [hello@otobo.io](mailto:hello@otobo.io) for professional support. ;) We use github for our development and not for support, sorry.

This issue here was caused by something different in any case.

**Comment by md-esw** [comment]
Hey!
the forum doesn't work anymore. And from professional support i got no answer. But the errors are so big, i not buying a support for something crashed by update itself!

Also i do not know the password from "otobo" in the container itself, anybody know this?
Your workaround are not possible, i have no file with this name....

**Comment by stefanhaerter** [comment]
> Hey! the forum doesn't work anymore. And from professional support i got no answer. But the errors are so big, i not buying a support for something crashed by update itself!

Out of curiosity: What exactly do you mean by "doesn't work anymore"? For me, the URL works pretty fine.

**Comment by md-esw** [comment]
The forum page are 404 page not Found after login!

**Comment by stefanhaerter** [comment]
Well, the previously posted URL https://otobo.io/forums/otobo/otobo-forum/ does not at all give a 404 - which one did you try?

**Comment by md-esw** [comment]
I got with your link directly 404!
