### ISSUE TITLE
Support for MariaDB 10.5

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#37]
ManiaDB 10.5 does not spport the `CREATE USER ... IDENTIFIED WITH .. BY ...` syntax. An alternative might be to use `IDENTIFIED WITH .. AS PASSWORD(...)` . This should also work on MySQL 5.7 and MySQL 8.

**Comment by bschmalhofer** [comment]
It would be interesting to see what happens when using the simple statement:
`CREATE USER `$DB{OTOBODBUser}`\@`$Host` IDENTIFIED BY '$DB{OTOBODBPassword}',
`
I don't know why the authorisation backend needs to be specified. Simply use the default backend.

**Comment by bschmalhofer** [comment]
Testing under MySQL 5.7 resulted in an error.

**Comment by StefanRother-OTOBO** [comment]
CREATE USER $DB{OTOBODBUser}\@$HostIDENTIFIED BY '$DB{OTOBODBPassword}' works for MySQL 5.7 and MariaDB. 

Thanks Bernhard!

**Comment by StefanRother-OTOBO** [comment]
MySQL 8 works too. Changed and closed.

**Comment by bschmalhofer** [comment]
This is broken again for MaraDB as MariaDB chokes on the 'WITH mysql_native_password' . @StefanRother-OTOBO  please reopen the isssue.
See https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/
