### ISSUE TITLE
account creation for customer

### ISSUE THREAD

**Issue by xdubx** [RotherOSS/otobo#3702]
hey,
i currently test the software in my docker container and read the manual. Did you plan to create an user creation support for the customer side? Without having an LDAP Backend?

**Comment by stefanhaerter** [comment]
Hey @xdubx,

You can easily add users and customer users via the frontend. For further questions please either visit our [forums](https://otobo.io/de/forums/) for community help, or write a mail to [hello@otobo.io](mailto:hello@otobo.io) for professional support. Github is for development issues only.

Kind regards,
Stefan
