### ISSUE TITLE
Improve error message in AdminCustomerCompany

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3706]
Currently, when adding a customer company with an already existing name, the whole sql error gets dumped into the message box:

```
ERROR: duplicate key value violates unique constraint "customer_company_name"DETAIL: Key (name)=(TestCompany) already exists., SQL: 'INSERT INTO customer_company (customer_id, name, street, zip, city, country, url, comments, valid_id, create_time, create_by, change_time, change_by ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, '2024-08-13 10:00:23', ?, '2024-08-13 10:00:23', ? )'
```

![grafik](https://github.com/user-attachments/assets/5654c566-5453-4f56-9519-655b7a62f59e)

I'm not sure if this could also be a security topic. Setting the milestone to 11.0.6 because I observed this on the latest rel-11_0, but haven't tested yet if previous versions are also affected.

**Comment by svenoe** [comment]
Test on 10.0 (and 10.1) and fix in lowest affected branch.

**Comment by stefanhaerter** [comment]
10.0 is affected as well, so I think it's fair to assume that all branches are affected. I also managed to discover the exact cause of the error:

The CustomerID is the primary key and properly checked for uniqueness in the frontend module. But the name column in the database table is also unique at not checked at all, so it fails upon insertion. In my opinion, it is important to check if there are other occurrences where unique database attributes are not checked properly.

**Comment by svenoe** [comment]
In principle cleaning up error messages would be good, but as only the admin interface is affected, this is ok, since the admin would else have to go to the log (where the error could also be seen).
