### ISSUE TITLE
change_time field is not updated at the second consecutive update

### ISSUE THREAD

**Issue by charlietangocharlie** [RotherOSS/otobo#3713]
change_time value is not updated at the second consecutive followup of a customer.

let's assume this situation : 
customer creates a ticket
Agent locks the ticket, assignes a queue, and reply (ticket state is waiting_customer) : change_time is updated
Customer replies, ticket state is changed to waiting_provider :  change_time is updated

Customer updates again (with no event on the ticket in between) the ticket with a second reply : change_time is not updated, and if he updates again and again the ticket, change_time value is not updated.

![image](https://github.com/user-attachments/assets/1d7137db-4eb6-481b-9605-6ceceb2a145a)

we can see the the change_time corresponds to the first reply timestamps after the ticket state was changed.
![image](https://github.com/user-attachments/assets/e514a067-ad39-4629-a021-881323a4f690)

**Comment by svenoe** [comment]
Ticket change time refers to changes of ticket attributes, which articles are not. The last change there was your state update in the first follow up.

This is not really inuitive, I agree, but it has been this way for a long time. I brought this up myself some time ago, but the conclusion was, that currently the priority of this is not high enough, to warrant a larger change in the fundamental logic of this. I will close this issue for tidyness, feel free to add good arguments for a next discussion, still. ;)
