### ISSUE TITLE
AdminTranslations shows deactivated translation proposals

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#3729]
When you want to add a new translation via Action=AdminTranslations and use one of the proposals, e.g. Services, you always see the de-activated names.
This can make sense, e.g. if you use the System Configuration setting "Ticket::Service::KeepChildren", but most of the time it doesn't make sense and might lead to a really long list.

As in some cases this makes sense, maybe a checkbox (or something similar) could make sense where you have the possibility to show de-activated source strings.

Some de-activated services:
![image](https://github.com/user-attachments/assets/8e92653b-a695-4387-8cd6-d0d3c4e773db)

All services as proposed strings:
![image](https://github.com/user-attachments/assets/3adb9d74-cebc-467e-8490-de8ce488ad17)

I tested it on ov270 with OTOBO 11.0.5

**Comment by svenoe** [comment]
This was a decision to enable preparation of new queues/services/..., where you would set up the new objects as "invalid", then translate them (or let your coworkers from 2 other countries translate them for you via ImportExport and csv), and only after translation is done set the objects to valid.

This does not belong here, as it is not a development todo at this point. I will close the issue, please discuss internally first.
