### ISSUE TITLE
DF Reference (to any object) with settings Dropdown + Multi Value (Multivalue) + Empty Value creates a superficial mandatory field

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#3730]
When you create any DF Reference (Referenced Object Type doesn't matter) and set up the following settings:
Input mode: Dropdown (I did not test it with Multiselect, but it is not reproducable with AutoComplete)
Add empty value: yes (It is not reproducable with No)
Multiple Values: Yes (I think it is not reproducable with No, but I'm not sure anymore)

When you now fill out all mandatory fields and don't fill out your DF Reference (which is not a mandatory field), then you get an error message: "One or more errors occured.", as if you didn't fill out a mandatory field:
![image](https://github.com/user-attachments/assets/911e0b43-e73b-48f7-9379-6f4652f7ae2c)

Action=AdminLog doesn't tell you more information.
It doesn't matter if you use e.g. AgentTicketPhone or CustomerTicketMessage.
I reproduced this on ov270 with OTOBO 11.0.5
I also reproduced this with a DF Reference CI with a CMDB on ov275), but as this is not CMDB exclusive, I created this in the OTOBO Framework repository)

Maybe this is somehow connected to Issue#3719:
https://github.com/RotherOSS/otobo/issues/3719

**Comment by stefanhaerter** [comment]
At least a similar bug has been observed again with dynamic field Contract-Distributor (CustomerUser reference df) in CMDB Ready2Adopt classes.

**Comment by stefanhaerter** [comment]
Additional bug description: The bug occurs again when typing into the field, focussing on another field, clearing the reference field again and submitting the form.

**Comment by stefanhaerter** [comment]
Reason for the buggy behavior is related to #3078 (and, thus, #3064 and #2298), where the FormCache mechanism was introduced for reference dynamic fields.
