### ISSUE TITLE
CMDB Search has fewer additional filter attributes

### ISSUE THREAD

**Issue by fabbaum** [RotherOSS/otobo#3735]
OTOBO 11.0.5 has fewer additional filter attributes in the CMDB search than in version 10.1.

For example, I miss the owner. Can these be added manually? If so, where?

![image](https://github.com/user-attachments/assets/e30e4a9f-679c-425c-9b56-bc0c4de4c0db)

**Comment by fabbaum** [comment]
I have found the option in the dynamic fields interfaces.

**Comment by bschmalhofer** [comment]
Marked as 'invalid', not because the question was invalid, but because the issue did not result in any code change.
