### ISSUE TITLE
Please re-think the behaviour of views concerning tickets having state-type "pending auto"

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#3742]
Please think about unifying the behaviour of views concerning state-type "pending auto". We experienced some behaviour we can't explain, not always makes sense (depending on the use-case) and also is different in different views.

- In case a ticket has a state of state type "pending auto", it is not shown in AgentTicketQueue at all. This might make sense if it is e.g. pending autoclose. But if it has a target state which opens it (or something similar) it would be practical for it to be seen. So maybe make it configurable or make it depending on the target state in "Ticket::StateAfterPending"

- The toolbar button for My Responsible Tickets (AgentTicketResponsibleView) only appears, if there is a ticket (for which I am responsible and) that has a state of state-type new, open or pending reminder. Pending auto is not sufficient for this.
- In AgentTicketResponsibleView a ticket with the state of state-type "pending auto" only appears in the tab(?) for Pending tickets, but not for "All" tickets.
- In My locked tickets "AgentTicketLockedView" it is different, even though the view is quite similar. Here a ticket with the state of state-type "pending auto" appears in the tab(?) for Pending tickets AND ALSO for "All" tickets.
- Also here the target state in "Ticket::StateAfterPending" doesn't make a difference.

- Maybe a dependency concerning the target state (Ticket::StateAfterPending) could also make sense concerning Dashboard widget 0100-TicketPendingReminder, but as you can configure shown state types, this is not toooooooo important (in my eyes). But also might be worth a discussion.

Please make this open for discussion

**Comment by svenoe** [comment]
Not the right place here. See the settings (Customer)ViewableStateType.

**Comment by bschmalhofer** [comment]
Removed the 'enhancement' label, as there were no code changes.
