### ISSUE TITLE
Performance issue in Kernel/Output/HTML/Preferences/Language.pm

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#3780]
Hi,

we have a performance issue in Kernel/Output/HTML/Preferences/Language.pm. It looks on some systems up to 12 seconds to load the module, we replace it for a test with the Language.pm version from OTOBO 10.1, after that the preference page loads in 2-3 seconds.

Please review the code, the module is used inside AdminCustomerUser, CustomerPreferences, AgentPreferences, etc., so it´s very important.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
This must be the LanguageList() method. Investigating this is a good use case for the NYTProf profiler. See #3769.

**Comment by bschmalhofer** [comment]
Cranked up NYTProf for OTOBO 11.0. The first goal would be to make `Locale::CLDR::language_name()` faster. There is not really a need to create 50 `Locale::CLDR` objects just for getting 50 language names in the currently selected language.

![grafik](https://github.com/user-attachments/assets/cc0f1aa5-df71-4d05-bf1c-815fecb8bcdc)

**Comment by bschmalhofer** [comment]
Just a note for my future self. When testing with Italian don't be confused that there an not Italian translation of language names.
See _bin/otobo.CheckModules.pl_ .

```
1233 # Add CLDR language packs. It is not decided yet whether all 50 languages are added.
1234 # So let's first go for the languages that have a translation quote of more than 80%.
1235 # See https://translate.otobo.org/projects/otobo10/otobo/.
1236 for my $Code (qw(Ar De Es Fr Hu Ko Nb Pt Ru Sr Zh)) {
```

**Comment by bschmalhofer** [comment]
Did some optimizations.

TODO:

- [x] test
- [x]  Another optimization: only check once whether Locale::CLDR is available.

**Comment by bschmalhofer** [comment]
Doing no further optimizations as some of the spent time goes away when the modules are loaded.
The output of Devel::NYTProf is not always easy to unterstand. Wasted some time looking why `LanguageList()` is called several times, but it looks like that was a false alert.

Another observation is that module refreshing seems to act strangely. For instance NYTProf reported that Data::Dx was used, but Data::Dx had been removed from _Kernel/Modules/AgentPreferences.pm_

Anyways, `LanguageList()` is faster now. PR is merged. Closing this issue.
