### ISSUE TITLE
Database connect attempted in Installer Intro

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#38]
When running installer.pl for a new installation the database host is not yet known. Yet the intro page of the Installer calls  `$Output .= $LayoutObject->Footer();` Within that call there is an attempt to get the list of states from the otobo database. However the Database connect fails when the MySQL database does not run on the local host.

**Comment by bschmalhofer** [comment]
Same applies for most of the other pages in installer.pl

**Comment by svenoe** [comment]
[Fixed](https://github.com/RotherOSS/otobo/commit/e0372cd40e4a5ecd66c52b384e7dc96e9b543cec), thanks.
