### ISSUE TITLE
Error with the "AppointmentToTicket" package.

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#3803]
When creating a ticket from an appointment and selecting the customer user, the ticket is generated without the customer user and associated data (In OTOBO 10.1 and 11). 
![Bildschirmfoto 2024-09-20 um 16 50 28](https://github.com/user-attachments/assets/ba8fc831-24b3-4740-80e6-5a859c681e3d)

**Comment by stefanhaerter** [comment]
Bug reproduced. Fix is pushed, will be included into next package release. Closing the issue.

**Comment by stefanhaerter** [comment]
Versions with the fix included have been released.
