### ISSUE TITLE
DF ContactWD has issues being used as lens attribute DF

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3809]
When searching for a lens attribute ContactWD DF, the following message pops up in the browser console:

```
Uncaught TypeError: Label is undefined
    _renderItem http://localhost/otobo-web/js/Core.UI.Autocomplete.js:118
    jQuery 14
    source http://localhost/otobo-web/js/Core.Agent.DynamicFieldContactWDSearch.js:139
    success http://localhost/otobo-web/js/Core.AJAX.js:957
    jQuery 4
```

**Comment by svenoe** [comment]
Question is, whether we really need this for lenses, as contact wd makes sense only in TicketZoom where there is a separate widget. Putting this on hold.
