### ISSUE TITLE
CustomerDashboard tiles: Ordering is fundamentally broken

### ISSUE THREAD

**Issue by dreng** [RotherOSS/otobo#3863]
### Environment

- Server OS Distribution: Debian 12
- OTOBO installation typ: Docker
- Browser: Firefox
- OTOBO version: 11.0.5

### Expected behavior

After reordering tiles for the customer dashboard, I'd expect any logic behind the entered numbers. Order no. 1 should be topmost left, 2 should be right of 1 or, if 1 fills the whole width of the screen, underneath 1. Higher numbers should follow the same concept.

I'd also expect tiles to keep CSS behavior (min/max size) if they have been reordered.

Maybe the word "Order" in the preferences is completely misleading and I got it wrong. But I can't figure out what other benefit this option could have.

I suggest to:
1. Make width and height units configurable in the system configuration.
2. Do NOT use fixed CSS ids. Set each configured width and height directly to the tiles.
3. Do NOT set grid-area at all. Use Flexboxes and flex-wrap instead. This will not only place the tiles in the correct order but also is a responsible design.

### Actual behavior

Changing the “Order” number results in the tiles being placed somewhere in an incomprehensible manner.

Not only the tile placement seems to be out of any logic. If you change numbers of two tiles, let's say 1 becomes 2 and 2 becomes 1, then the (hard coded) CSS changes as well. So, when 1 has been assigned to the id "oooTile01", it would get assigned to "oooTile02". This changes the grid-area and may lead to misformed, misplaced or broken tiles.

If you use high numbers, there's obviously no CSS assigned to that numbers which leads to correctly ordered but very tall and narrow tiles that cannot fulfill their purpose in this form.

### How to reproduce

1. Go to Admin > Systemkonfiguration
2. Navigate to Frontend > Customer > View > Dashboard > Tiles
3. Change order numbers of two tiles, e.g. set 1 to 2 and 2 to 1.
4. Notice that the tile for "New Ticket" is extremely tall.
5. Notice that No. 1 is not being placed at the top left.

Use high numbers:

1. Go to Admin > Systemkonfiguration
2. Navigate to Frontend > Customer > View > Dashboard > Tiles
3. Change numbers of all tiles to a number above 7, e.g. 8, 9, 10, 11, 12
4. Notice that all tiles have been placed in ascending order but are tall and narrow.

_Note: If you reset all tile preferences to default, your layout may not correspond to the screenshots below_

### Screenshots

![ordering_1](https://github.com/user-attachments/assets/06bedf8f-aed2-480b-80ab-0f43be153d40)
![ordering_2](https://github.com/user-attachments/assets/22187e20-f24f-4b80-9f56-a98d1a69fbc5)
![css_1](https://github.com/user-attachments/assets/d435c453-f6ef-4796-a8b1-87a327c8f79c)
![css_2](https://github.com/user-attachments/assets/b9bc8e69-938d-45df-b857-61a06c2f1bcd)
![highnumbers](https://github.com/user-attachments/assets/d85b9a74-2b04-48be-9654-12dd3e3edc27)

**Comment by svenoe** [comment]
Hi Mario,

thanks for the detailed issue. The wording "order" is a bit misleading, probably, but the intention has never been to show the tiles one after the other, but instead to give an identifier to the tile, which can be used in the css file var/httpd/htdocs/skins/Customer/default/css/Core.Dashboard.Default.css to position the tiles at fixed places.

The suggestions regarding technical changes of course have some advantages, other things with different tile sizes and especially regarding responsive design would suffer, though - in any case, there currently is no plan to completely restructure the dashboard.

I hope that answers some questions, I will close the issue, as there is no todo, feel free to comment, anyways.
Best regards, Sven
