### ISSUE TITLE
[BUG] CMD function in GenericAgent not available in 11.0.5

### ISSUE THREAD

**Issue by escix** [RotherOSS/otobo#3869]
### Environment

- Server OS Distribution: 
- OTOBO installation typ: 
- Browser: 
- OTOBO version: 

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![image](https://github.com/user-attachments/assets/8d79ecb6-54f2-46b2-8d8d-116411f7b365)

in Online manual:

![image](https://github.com/user-attachments/assets/ea15d048-cc58-4a31-b6c2-87700152f4a0)

**Comment by svenoe** [comment]
If something changes but does not throw any errors, please don't assume bugs, and visit our forums, first. This was patched out from the standard config as part of a step by step path to separate OTOBO admin and system user access, probably a year ago. Please search for "GenericAgentAllowCustomScriptExecution" in the Defaults.pm.

Edit: The docs should be updated, though, of course.
