### ISSUE TITLE
[BUG] Not possible to create a custom translation for "Issue a ticket"

### ISSUE THREAD

**Issue by MarkusHlinka-OTOBO** [RotherOSS/otobo#3907]
### Environment

- OTOBO version: 11.0.7

### Expected behavior

The string "Issue a ticket" in the customer dashboard should be changeable to a custom string via a custom translation.

### Actual behavior

If a new translation of Object "General Label" with Content "Issue a ticket" and Translation "Create new ticket" is added and deployed, the custom translation is not shown in the customer dashboard (even after making sure, that the selected language is the correct one, for which the custom translation was created).

### How to reproduce

1. Create a new translation as described in "Actual behavior".
2. Login as customer user and change the language to the language for which the custom translation was created.

**Comment by stefanhaerter** [comment]
This is due to the fact that the actual used string is not 'Issue a ticket':

https://github.com/RotherOSS/otobo/blob/b04d3c2cea86fd75ad17ba9ee1dc9750c5d77bdc/Kernel/Output/HTML/Templates/Standard/Dashboard/TileNewTicket.tt#L17

I admit that this is far from intuitive, but using this string should work, like this:

https://github.com/RotherOSS/otobo/blob/b04d3c2cea86fd75ad17ba9ee1dc9750c5d77bdc/Kernel/Language/de.pm#L3384-L3385

**Comment by MarkusHlinka-OTOBO** [comment]
Good to have a functional workaround, but from a user perspective it's not that practical.

From a design perspective it's understandable to have "a ticket" in a separate line, instead of "Issue a" in the first and "ticket" in the second line, but it breaks the ability to easily translate that specific string (or maybe others too).
I guess this topic should be kept open for discussion and the final decision should be documented in this issue.

If the decision is to keep it like it is now, it might be a good idea to have a list of strings, on which the translation doesn't work by default and what string has to be used to properly create a custom translation in such a case.

**Comment by svenoe** [comment]
There are not many places where this is done this way, in fact it might be the only one. Enforcing line breaks with translations is not so easy otherwise. We decided on this solution some years ago, and currently I don't see this having a high enough priority to reopen the discussion.
