### ISSUE TITLE
AgentTicketProcess and CustomerTicketProcess: Pass ticket id to ACL GetFieldStates

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3911]
The ticket id params passed to GetFieldStates are empty in the two modules.

**Comment by StefanRother-OTOBO** [comment]
The real problem is that our new ACLs in AgentTicketProcess and CustomerTicketProcess do not work in some cases. ACLs that contain restrictions on the database using ‘PropertiesDatabase’ do not work as intended.
