### ISSUE TITLE
inconsistent borders/shadows in customer ticket zoom mask 

### ISSUE THREAD

**Issue by chzauleck** [RotherOSS/otobo#3923]
In the ticket zoom mask of the customer portal, the borders and shadows are not consistent (see ticket information / article list / individual article).
<img width="1166" alt="Bildschirm_foto 2024-11-07 um 09 22 23" src="https://github.com/user-attachments/assets/c4106195-2dd2-43fb-b395-d516fa4c87fc">

**Comment by chzauleck** [comment]
comments: look at version 10.1
also check with changed config Ticket::Frontend::CustomerTicketZoom###TicketInfoDisplayType

**Comment by stefanhaerter** [comment]
Regarding the latter: Issue #2932, PR #2933
