### ISSUE TITLE
Remove support for param KeepScriptTags for Kernel::Output::HTML::Layout::Template::Output()

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#394]
In _Kernel/Output/HTML/Layout/Template.pm_ there is the following deprecation note:

  `  KeepScriptTags - DEPRECATED, please use the parameter "AJAX" instead
`
TODO:

- [x] Check whether KeepScriptTags is used anywhere in OTOBO core

- [x] Refrain from checking OTOBO modules, there is no guarantee that no adaption are required for 10.1.

- [x] Remove support for the legacy feature

**Comment by svenoe** [comment]
Raus mit 11; deprecation note.

**Comment by bschmalhofer** [comment]
Move to milestone 10.0, just to have future developments in one place.

**Comment by bschmalhofer** [comment]
Removed the support for KeepScriptTags. It was not used in core and is likely not used in core.
But adding a deprecation documentation is still a good idea.
