### ISSUE TITLE
Change handling of undef values and empty strings in webservice XSLT mapping

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3961]
The default behavior of XML::Simple is to map undef values or empty strings into empty hash refs. This causes problems e.g. when updating config items via webservice. Decision is to change this, undef values and empty strings should get mapped to empty string.

Further reference: https://metacpan.org/pod/XML::Simple#SuppressEmpty-%3D%3E-1-%7C-%27%27-%7C-undef-%23-in%2Bout-handy

**Comment by bschmalhofer** [comment]
I think that empty strings are currently not turned into empty hashrefs.

Note that the test script  XSLT.t needs to be adapted as well.

**Comment by bschmalhofer** [comment]
I cherry-picked the additional test cases from the rel-11_1 branch.
