### ISSUE TITLE
[BUG] State translation not consistent

### ISSUE THREAD

**Issue by dreng** [RotherOSS/otobo#3968]
### Environment

- Server OS Distribution: Debian 12
- OTOBO installation typ: Docker
- Browser: Firefox
- OTOBO version: 11.0.7

### Expected behavior

Since you are able to change the names of existing States and also add your own States, whose name can be anything, I think it is generally a very bad design decision to translate the States, which, to make it even worse, seem to be used as a hard coded unique identifier. However, if you do translate, it should at least be consistent.

### Actual behavior

The default States are shown in english on the AdminState page. In the setting "Ticket::Frontend::AgentTicketResponsible###StateDefault", however, they are shown translated.

### How to reproduce

1. Make sure that your language is not set to english.
2. Go to System Configuration > Ticket::Frontend::AgentTicketResponsible###StateDefault
3. Click the drop down field in order to show all available States > All States are translated
4. Go to the Admin section > States > All States are shown untranslated

### Screenshots

![grafik](https://github.com/user-attachments/assets/69739b27-2539-4436-95d4-c59b262fe96e)

![grafik](https://github.com/user-attachments/assets/ed2de501-5b49-4e12-927c-9228ad6dae60)

**Comment by svenoe** [comment]
Hi Mario,
this is a quirk which won't be fixed, although I agree that it is not completely consistent - sometimes pragmatism beats ideas about perfect code design, especially when working on a twenty year old code base. States are useful for people to have them translated (for multilingual teams, but also just to roll out a useful default,...), but in AdminState you are working on and thus have to see the untranslated base strings, of course. I think this example is something, which an admin should be able to handle.
Best regards, Sven
