### ISSUE TITLE
[BUG] German translation for 'Change Ticket'  incorrect

### ISSUE THREAD

**Issue by dreng** [RotherOSS/otobo#3969]
### Environment

- Server OS Distribution: 
- OTOBO installation typ: 
- Browser: 
- OTOBO version: 11.0.7

### Expected behavior

The correct translation for "Change Ticket" should be "Ticket ändern".

### Actual behavior

The german translation for "Change Ticket" seems very arkward. "Ticket kategorisieren" has got a complete different meaning and does not fit the function at all.

### How to reproduce

1. Make sure you are using german language.
2. Open any ticket in AgentTicketZoom.
3. See "Ticket kategorisieren" in the menu.

### Additional information

These are the lines that have to be changed. Let me know if you prefer a PR.

https://github.com/RotherOSS/otobo/blob/ab931353cdba487858f409e65054d9e3c3c85842/i18n/otobo/otobo.de.po#L17883

https://github.com/RotherOSS/otobo/blob/ab931353cdba487858f409e65054d9e3c3c85842/i18n/otobo/otobo.de.po#L18007

https://github.com/RotherOSS/otobo/blob/ab931353cdba487858f409e65054d9e3c3c85842/i18n/otobo/otobo.de.po#L18231

**Comment by svenoe** [comment]
Generally: Please make translation (suggestions) on [translate.otobo.org](translate.otobo.org), if applicable they will be included automatically. If you would like to have custom translations, but don't want to change the official translation, or it is not accepted, you can also go to Admin->Translations to just adapt your individual system.

Specifically: Das ist ein bisschen Ansichtssache. Meines Wissens nach ist "Ticket kategorisieren" schon seit OTRS6-Zeiten drinnen und man weist dem Ticket ja auch gewisse Kategorien zu. Ich selbst bin da relativ leidenschaftslos, glaube aber ehrlich gesagt nicht, dass das geändert wird, auch wenn du es vorschlägst, auch einfach deshalb, weil dann plötzlich tausende Systeme anders aussehen. Wie oben geschrieben, kannst du den String aber ja einfach unter Admin->Übersetzungen selbst übersetzen, bei dir.

Viele Grüße, Sven

**Comment by dreng** [comment]
Hi Sven,

danke für deine ausführliche Erläuterung. Ich kann das schon irgendwie nachvollziehen, wobei "war schon immer so" noch nie irgendwo ein guter Begleiter war. Zu oft trifft "war schon immer Scheiße" gleichermaßen zu. Wenn du sagst, es würde vermutlich ohnehin nicht geändert werden, kann ich mir den Vorschlag an anderer Stelle natürlich sparen.

Was mich nicht wirklich überzeugt, ist das Argument der Bedeutung des Ausdrucks "Ticket kategorisieren". Aus meiner Sicht ist das ziemlich unerheblich, weil wir hier über eine Übersetzung reden. Im Umkehrschluss müsste sonst die britische Variante "categorise ticket" heißen. Das Wort "change" bedeutet einfach nicht "kategorisieren".

Generell bin ich kein großer Freund von Sonderwünschen und rosa Schleifchen, sondern von Lösungen, die für alle Nutzer einen Vorteil/Nutzen bedeuten. Ansonsten muss man jedes rosa Schleifchen neu bauen, wenn es durch eine Änderung am Master Branch kaputt geht. Deswegen begrüße ich zwar die Möglichkeit, selbst alles anpassen zu können, empfinde aber die Änderung im Repository als eleganter.

**Comment by svenoe** [comment]
Ich würde dir Recht geben, wenn das "es war schon immer so" das einzige Gegenargument wäre, das gegen eine eindeutige Verbesserung spricht. Zum einen ist das hier aber einfach eher eine Geschmacksfrage, wie nah, rein sprachlich, eine Übersetzung ist, ist in meinen Augen z.B. ziemlich irrelevant. Sprachen sind nie 1:1-Abbildungen, und das wichtige ist, dass der Kontext passt. Zum anderen ist Stabilität auf existierenden Systemen auch nicht einfach so wegzuwischen. Leute arbeiten mit dem Tool, und da wäre es eher nervig wenn jeden Patch fünf Sachen anders aussehen. Aber ja, ist halt eine Abwägungssache.

Wo ich auch nicht sehe, dass wir einfach mal schnell was ändern, ist das "Change Ticket" umzubenennen. Die Übersetzung da dann selbst zu pflegen sollte ebenfalls ziemlich stabil sein. Und selbst wenn, geht da nichts kaputt, sondern es wäre halt dann einfach ein anderer englischer String (vmtl mit einer anderen deutschen Übersetzung) da, und die angepasste Übersetzung würde an der Stelle einfach nicht mehr genutzt.
