### ISSUE TITLE
Rights to updated articles / latest changes articles on the client portal

### ISSUE THREAD

**Issue by keksoler1000** [RotherOSS/otobo#3971]
Hello! There is one more question. There is one point in the client portal that I cannot resolve. There is an item in the FAQ: last updated articles. The category is moderated by group and is displayed correctly. But for a group that does not have the ability to view a specific FAQ category, the latest articles are visible, when you go to them - yes, they are not shown, no rights. Is it possible to completely remove them from visibility?

**Comment by keksoler1000** [comment]
I mean this: latest updated FAQ

![image](https://github.com/user-attachments/assets/9a7ae9ae-d3db-45f2-8a62-77ebfd37d157)

**Comment by svenoe** [comment]
Hi keksoler,
we use github solely for development purposes. For general questions and community support please instead visit our [forums](https://otobo.io/forums/otobo/otobo-forum/), or you can also write an email to hello@otobo.io for professional support. I don't know the answer to your question out of my head, also, so I'll just close the issue to keep things halfway tidied.
Thanks for your understanding, best regards, Sven
