### ISSUE TITLE
[BUG] unitest DefaultSettingList.t needs update

### ISSUE THREAD

**Issue by MichaelThumes** [RotherOSS/otobo#3980]
### Environment

- Server OS Distribution: Ubuntu 24.04
- OTOBO installation typ: Docker
- Browser:Chrome (Selenium)
- OTOBO version: rel-11_1

### Expected behavior

bin/otobo.Console.pl Dev::UnitTest::Run --verbose scripts/test/SysConfig/DB/DefaultSettingList.t reports "All tests successful"

### Actual behavior

Test fails, bad expectation

### How to reproduce

inside docker, run the UnitTest
bin/otobo.Console.pl Dev::UnitTest::Run --verbose scripts/test/SysConfig/DB/DefaultSettingList.t

### Additional information

The description the test is validating has changed - the unittest expectation needs to be updated

### Screenshots

na/

**Comment by bschmalhofer** [comment]
The change had been applied to rel-11_1.  The test failure no longer occurs. Closing this issue.
