### ISSUE TITLE
Require and use Cpanel::JSON::XS

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#399]
Currently `JSON::XS`is listed as not required in _bin/otobo.CheckModules.pl_ . This means that `Kernel::System::JSON`will use either `JSON::PP`or `JSON::XS` for the backend of `JSON`. Both modules are compatible so this should be no problem. But requiring JSON::XS reduces the numbers of variants that con occur in the wild.

**Comment by svenoe** [comment]
Check for supported systems.

**Comment by bschmalhofer** [comment]
If we go that way we should use the correct and fast JSON module: Cpanel::JSON::XS.

**Comment by bschmalhofer** [comment]
Another alternative: Mojo::JSON which uses Cpanel::JSON::XS if available.

**Comment by bschmalhofer** [comment]
Cpanel::JSON::XS is available as a package for the major Linux distributions. Let's require it, so that we have less diversity.

**Comment by bschmalhofer** [comment]
Tentatively switched to Cpanel::JSON::XS. Got some failures in the test suite again. These failure might be timing issues, as there is no obvious connection to JSON.

```

Test Summary Report
-------------------
/opt/otobo/scripts/test/Selenium/Agent/Admin/AdminQueueTemplates.t                                        (Wstat: 512 (exited 2) Tests: 38 Failed: 2)
  Failed tests:  37-38
  Non-zero exit status: 2
/opt/otobo/scripts/test/Selenium/Agent/Admin/AdminSystemConfigurationExampleSessionID.t                   (Wstat: 256 (exited 1) Tests: 43 Failed: 1)
  Failed test:  25
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/Agent/MultiAttachmentUpload/CreateScreens.t                              (Wstat: 256 (exited 1) Tests: 41 Failed: 1)
  Failed test:  41
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/Customer/MultiAttachmentUpload/TicketMessage.t                           (Wstat: 256 (exited 1) Tests: 13 Failed: 1)
  Failed test:  13
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/TestingMethods.t                                                         (Wstat: 0 Tests: 36 Failed: 0)
  TODO passed:   21, 24, 28
Files=958, Tests=80176, 4387 wallclock secs (15.47 usr  2.06 sys + 784.71 cusr 105.85 csys = 908.09 CPU)
Result: FAIL
ran tests for product OTOBO 11.0.x on host b83fc4a9d6b9 .

```

**Comment by bschmalhofer** [comment]
During testing I found that `Kernel::System::JSON` is encoding the number 0 incorrectly. Instead of `0` the string `""` is returned. There might have been a reason for that behavior, but IMHO it does not make sense at all.

**Comment by bschmalhofer** [comment]
I'm not aware of any problems. Let's wait for the next run of the test suite before closing this issue, just to be on the safe side.

**Comment by bschmalhofer** [comment]
Closing this issue as #2375 seems to be unrelated.

**Comment by bschmalhofer** [comment]
I noticed that Cpanel::JSON::XS is still part of a feature. But it needs to be a required module.

 ```
762     # Feature performance
 763     {
 764         Module    => 'Cpanel::JSON::XS',
 765         Features  => ['performance:json'],
 766         Comment   => 'correct and fast JSON support, used by Mojo::JSON',
 767         InstTypes => {
 768             aptget => 'libcpanel-json-xs-perl',
 769             emerge => 'dev-perl/Cpanel-JSON-XS',
 770             yum    => 'perl-Cpanel-JSON-XS',
 771             zypper => 'perl-Cpanel-JSON-XS',
 772             ports  => 'converters/p5-Cpanel-JSON-XS',
 773         },
 774     },

```

**Comment by bschmalhofer** [comment]
Requiring Cpanel::JSON::XS was done in https://github.com/RotherOSS/otobo/commit/bab92acd41e1ccda044b1d081c6b20bdfa76ede5 .  Closing this issue again.

**Comment by bschmalhofer** [comment]
The usage of Cpanel::JSON::XS was rolled back in work for #2595. But there were some discussions to migrate again. So this might come back again.
