### ISSUE TITLE
Turn Kernel::System::Log into a wrapper around Log::Log4perl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#402]
`Log::Log4perl`gives a great amount of flexibility but is a major undertaking. This deserves its own issue.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/73#issuecomment-683271423_

**Comment by svenoe** [comment]
I see that there could be upsides. Maybe if we use Kernel::System::Log as wrapper around Log::Log4perl? I put it to medium priority, let us discuss this at some meeting in the future.

**Comment by stefanhaerter** [comment]
Perhaps this could be useful if we implement this ome day - leaving it here: https://metacpan.org/pod/Log::Log4perl::Config::YamlConfigurator

**Comment by bschmalhofer** [comment]
> I see that there could be upsides. Maybe if we use Kernel::System::Log as wrapper around Log::Log4perl? I put it to medium priority, let us discuss this at some meeting in the future.

Keeping the interface of Kernel::System::Log would be essential as otherwise all looging calls would have to updated. But that should be a thin wrapper, not like my first idea that used Log4perl as just another backend for Kernel::System::Log.

**Comment by bschmalhofer** [comment]
> Perhaps this could be useful if we implement this ome day - leaving it here: https://metacpan.org/pod/Log::Log4perl::Config::YamlConfigurator

Yes, these kind of things can easily be employed with Log4perl. Another option is the Log4perl simply gets a Perl data structure as configuration.

**Comment by stefanhaerter** [comment]
Throwing another piece of information into the discussion:

>  One should also think carefully about at what level one should be logging. To aid in this, prefer modules like `Log::Any` (as opposed to `Log4Perl`) because it is more fine-grained.

Quote from @paultcochrane's [blog post on the #GPW2025](https://peateasea.de/german-perl-raku-workshop-2025-a-retrospective/), summarizing the talk "You Only Log Once" from Nicholas Clark.

(I have no personal opinion on this topic, but wanted to preserve the information in the corresponding issue.)
