### ISSUE TITLE
CI: build Docker images via Github actions

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#403]
Currently there are some Github actions and automated builds on https://hub.docker.com/. Maybe it is good to minimise the number of tools used. Docker images can also be built by a Github action and then be pushed to Docker hub.

**Comment by svenoe** [comment]
Hard for me to judge the pros and cons. I mean, we will use hub.docker.com anyways, will we?

**Comment by bschmalhofer** [comment]
@svenoe : Yes, my idea is that Github actions build the Docker image and then push it to hub.docker.com. This would allow continous integration checks before publishing the image. On the other hand: hub.docker.com can also run integration tests. So, it's basically a question of what is more convienent and easier to grasp.

**Comment by bschmalhofer** [comment]
Closing this issue as it was specifically about Github actions. But the plan is to move to Gitlab.

**Comment by bschmalhofer** [comment]
An argument for building the images in GitHub is that the check for updated base Docker images is less of a hassle here.
