### ISSUE TITLE
"Send a bugreport" in Layout->FatalError links to bugzilla.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#412]
This should be linked to github issues. Maybe something should prevent that everytime a custom package destroys something, people start to create issues, here, however...

**Comment by bschmalhofer** [comment]
Github seems to provide templates for creating new issues. Not sure whether POST forms are supported.
See https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository and https://stackoverflow.com/questions/34146618/pre-populate-the-github-new-issue-form-using-the-querystring and http://ez34.net/2016/12/publish-anonymous-issues-on-github.html .

**Comment by svenoe** [comment]
Seems done. Opened another issue for possible beautification.
