### ISSUE TITLE
Fix TreeView combined with HideShow.

### ISSUE THREAD

**Issue by squidy** [RotherOSS/otobo#413]
I created some dropdown fields configured as tree view and set them to show on CustomerTicketMessage screen using ACL. However, when the customer tries to select those fields, the message "Loading" shows and the values never apears.

Otobo 10.0.2

![OTOBO-loading-select-tree](https://user-images.githubusercontent.com/43784/92128427-644d7600-edd0-11ea-9855-7c56daf07166.png)

![OTOBO-loading-select-tree-Admin](https://user-images.githubusercontent.com/43784/92127998-e9845b00-edcf-11ea-86d8-6ac5f40b46c8.png)

**Comment by svenoe** [comment]
Hi squidy,

to me it looks like somewhere in the process you encounter a Javascript error, which cancels the buildup of the page. (For example those small tree icons on the right should be hidden, too.) As for me it works, it's not so easy to debug this. Could you try to open the console of the browser, to see if there are any error messages? (If you tell me, which one you are using, I can help you to get there.)

For Firefox you could for example right-click somewhere on the screen, select "Inspect element", and then switch the tab to the console. On my German Firefox it looks like this:
<img width="443" alt="grafik" src="https://user-images.githubusercontent.com/48322755/92132629-acd45600-ee07-11ea-88f0-a57559a04475.png">

If you reload the page, please check, if any error messages are shown.

Thanks, Sven

**Comment by squidy** [comment]
Hi Sven..
I'm using Google Chrome on Linux.
Take a look at the error message from my console..

![OTOBO-loading-dropdown-tree-debug](https://user-images.githubusercontent.com/43784/92134241-4afbf800-edd7-11ea-9a4c-93ce3d8489b3.png)

**Comment by svenoe** [comment]
Hi squidy,

sorry, I was too quick, yesterday - could you please do the following:

1. Go to the SysConfig in the Admin area, search there for "Loader::Enabled::JS" and deactivate it by unchecking the box and deploying those settings.
2. Probably not needed but just to be sure; you could try without: Go to the terminal of the machine you installed otobo on, and as otobo user execute: /opt/otobo/bin/otobo.Console.pl Maint::Loader::CacheCleanup
3. Clear the cache of your browser. (In the settings of chrome you can just search for "cache". All other stuff, cookies and so on can remain.)
4. Reproduce the error and send it to me again, please.

This time the error should be more verbose, which would be a great help. You can activate the loader again after that.

Thanks again!

**Comment by squidy** [comment]
Hi Sven,

I did what you said, but I think that nothing changed.. Take a look.

![OTOBO-loading-dropdown-tree-debug3](https://user-images.githubusercontent.com/43784/92243518-9bcf2780-ee8f-11ea-8bd3-eeec0243ed7a.png)

![OTOBO-loading-dropdown-tree-debug2](https://user-images.githubusercontent.com/43784/92243308-4abf3380-ee8f-11ea-9fb8-12e75cb95c47.png)

**Comment by svenoe** [comment]
Hi squidy,

I think there is still something cached, somewhere, but it doesn't matter: I'm a bit further - the error is produced in one of the thirdparty routines, namely the jstree. I unfortunately (or fortunately ;) cannot reproduce it, though (also when using GoogleChrome):

<img width="1042" alt="grafik" src="https://user-images.githubusercontent.com/48322755/92260920-f0e35b80-eed8-11ea-82e0-0acd4cb1c578.png">
<img width="927" alt="grafik" src="https://user-images.githubusercontent.com/48322755/92260932-f640a600-eed8-11ea-828b-f4cfef9bceec.png">

Two things you could do: If it is not so important for you, try disabling the Tree View. For us it would be interesting though, if we'd try to fix it, or find, what causes the error, and throw a more understandable error message somewhere. If you are up for the latter, please download the following file: [jquery.jstree.js.zip](https://github.com/RotherOSS/otobo/files/5175907/jquery.jstree.js.zip)
It is a changed version of the jstree-plugin, which prints out some lines of debugging information. You would have to:
1. Backup your old file: cp /opt/otobo/var/httpd/htdocs/js/thirdparty/jquery-jstree-3.3.7/jquery.jstree.js /opt/otobo/var/httpd/htdocs/js/thirdparty/jquery-jstree-3.3.7/jquery.jstree.js_bkp
2. Unpack the zip-file and replace /opt/otobo/var/httpd/htdocs/js/thirdparty/jquery-jstree-3.3.7/jquery.jstree.js
3. Clear your browser cache, and if the JS-Loader is active run: /opt/otobo/bin/otobo.Console.pl Maint::Loader::CacheCleanup
4. Reproduce the error and send me the log messages (this time there should be more information, see below for an example).
5. Restore the original file: mv /opt/otobo/var/httpd/htdocs/js/thirdparty/jquery-jstree-3.3.7/jquery.jstree.js_bkp /opt/otobo/var/httpd/htdocs/js/thirdparty/jquery-jstree-3.3.7/jquery.jstree.js

I can not promise, that this will suffice, but hopefully it will provide further information on what of the things passed breaks the tree.

Sven

<img width="516" alt="Bildschirmfoto 2020-09-04 um 18 26 51" src="https://user-images.githubusercontent.com/48322755/92263243-977d2b80-eedc-11ea-8f7d-3d7032bf3bf8.png">

**Comment by squidy** [comment]
Hi Sven.
Sorry for the delay..
Check it out..

![Otobo-Debug1](https://user-images.githubusercontent.com/43784/92413658-12358900-f11f-11ea-9571-4ee4092360f5.jpg)

**Comment by svenoe** [comment]
Hi squidy,
thanks for the output. Seemingly Outro works, but Teste has a problem. The place is clear now, and I will have a look at it, but my next two or three days are really busy, so you will need some patience. Just to let you know.
Have a nice day/evening, Sven

**Comment by svenoe** [comment]
Hi squidy,
I had time to look a bit further. Actually I think that what you are seeing is only a side product of your page not loading properly, and I fear that it could get quite difficult to track down the real reason, if that's our only clue. Nonetheless, there are at least some additional things we could try. First, I would be interested in your html again. When you right-click on the Teste-field and inspect it, there should be a select-element a bit below the input-element of the field. Please expand it, and show the whole div to me. For me it looks like this:

<img width="692" alt="Bildschirmfoto 2020-09-15 um 11 40 55" src="https://user-images.githubusercontent.com/48322755/93195314-63f69880-f749-11ea-8352-6b8d366459db.png">

I would assume, that there are some differences here. As your site shows those small icons next to your fields, I guess, it's not loading properly, and I would imagine those differences are rather a result than the cause. To test this, however, please disable all your dynamic fields for CustomerTicketMessage except Teste, and see whether it loads properly, and if it does not, please disable Teste, too, and enable Setor again, and see, whether this loads, by chance. If any of those work, you can maybe track down which field is causing trouble. If neither work, try if disabling tree view helps with loading the fields. Hopefully we get some further information this way.

**Comment by squidy** [comment]
I have an ACL on the first line that hide all dynamic fields from form, then others ACLs that show fields based on the service..
**I deactivated the ACL that hide all fields** from CustomerTicketMessage and **the tree load correctly**...
When I active it, the tree stops on "loading".

Take a look the ACL that hide all..
![OTOBO-loading-dropdown-tree-ACL1](https://user-images.githubusercontent.com/43784/93248232-9611f580-f75d-11ea-80d8-93ab57367aa5.png)

**Comment by squidy** [comment]
So if I enable the ACL CustomerTicketMessage_HIDE_ALL, the field campoTeste does not load.

Inspecting the element I can view the following div:

![OTOBO-loading-dropdown-tree-ACL2](https://user-images.githubusercontent.com/43784/93268466-39253800-f77b-11ea-877c-276908de62b1.png)

**Comment by svenoe** [comment]
Hi squidy,
thanks, now the problem is clear. It is a bug and we will fix it.
Sven

**Comment by svenoe** [comment]
Fixed.

@squidy - We will release OTOBO 10.0.3 today or at the beginning of next week. If you can't wait, you can download and replace the following file on your system: https://github.com/RotherOSS/otobo/blob/rel-10_0/var/httpd/htdocs/js/Core.UI.InputFields.js

Thanks for pointing out the bug and helping to narrow it down, again. :)
