### ISSUE TITLE
Stopwords missing for most supported languages

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#425]
In `Kernel/Config/Files/XML/Ticket.xml` stopwords are only provided for the languages EN, DE, NL, ES, FR, IT but not for all ~50 languages.

**Comment by wollmers** [comment]
If it is useful in which format should I provide the stopwords for the other languages? As pull request directly into `Ticket.xml` or as plain files one word per line?

How many should I select? The top x (e.g. 100 or 200) or cut off at e.g. cumulated 50%? In German the most frequent 207 words form ~50% of all words in texts.

**Comment by bschmalhofer** [comment]
@wollmers : As far as I see the stopwords are not specific for OTOBO. Is there a CPAN module or a Debian package that provides stopword lists? I only found https://metacpan.org/release/Lingua-StopWords which does not support many languages either. Maybe supplying your lists to Lingua::StopWords would be the best approach.

**Comment by wollmers** [comment]
@bschmalhofer I have frequency lists (`word\tcount`) for 2200 languages, most frequent 50 K words each. I could compile the lists myself. They are e.g. base of my CPAN module Text::Guess::Language (58 Languages).

Wrote a mail now to adopt Lingua::StopWords and provide more languages there. The answer can take some time.

Stopword lists are not always exactly the same depending on the underlying corpus. 

If the stopword list for a language changes, the indexing of documents must be rebuilt with the new list. Means I must keep the existing lists in Lingua::StopWords, because Lingua::StopWords has 33 dependents.

Same for OTOBO. Change of the stopwords needs reindexing.

Are the stopwords in OTOBO for MariaDB/PostGresql or for ElasticSearch?

**Comment by bschmalhofer** [comment]
@wollmers My impression is that Stopword support in OTOBO is a bit of a mess currently. As far as I see the stopwords are only used for MariaDB/PostGresql/Oracle. But the design is not very good. Two issues spring to my mind:

The lists are eventually stored in ZZZAAuto,pm. This means that they are loaded again for every request. This does not look economical to me.
Update: its not as bad as I feared. ZZZAAuto,pm is loaded with **require**. This means that the file is not read for every reuest.

OTOBO seems to have no information in  which language an article is written in. The Stopwords for all supported langues is simple thrown into one large bag. Thus a French Stopword masks words in a German text. 

I'm not really concerned about the effect of different corpus  on the stopwords. If there are really Domain specific terms that should be masked, then they could be added to MariaDB/PostGresql. When the list is hidden in a module, then the module could be monkey patched.

**Comment by wollmers** [comment]
@bschmalhofer 

1) stored in ZZZAAuto.pm

As I understand roughly, ZZZAAuto.pm caches XML. This should only be done at coldstart and reload after changes.

2) OTOBO could get the language(s) a ticket is written in by one of CPAN modules for language identification. 
This is never perfect because it's based on statistical models. Also they tickets can contain mixed language.

3) Putting the stopwords into one big bag doesn't matter much. Could test this sort of false positives with all stopwords against larger dictionaries. Some stopwords like "in" appear in many languages:

```
'in'=>['af','de','en','fa','it','la','ms','nl','ro','si','sl','sq','sv','th','tr',],
```

The purpose of stopwords is to reduce the indexing of text. According to Zipf's law the most frequent ~200 words make ~50% in a text in European languages. Because they are so frequent, they don't carry important information, they can be ignored in the index and in the query.

4) domain specific terms

Domain specific terms will not make it into stopwords, they rank somewhere behind position 500,000. But it makes a difference if the stoplist is based on movie subtitles, the bible, wikipedia, newspapers or famous poetry. Merging them from different domains by weighted frequency and cutting down to ~200 should work perfect.

But I wouldn't go to deep into theory. Stopword methods are heuristics with a false-positive and false-negative rates somewhere around 1%. It can't be expected if someone uses e.g. a domain or product specific acronym which is a stopword in some language.

**Comment by wollmers** [comment]
Investigated the capabilities of Solr (used by ElasticSearch), MySql/MariaDB, PostgreSql a little bit.

The stopword list in MySql seems system wide. Needs restart of `mysql` after changes (not completely sure), and reindexing afterwards. But better than nothing.

PostgreSql has very advanced language support for fulltext indexing and search. It also allows to have the language (config_name) in a column of the table, which uses different, customizable logic (parsing of words, normalizing, stemming, stopwords) for indexing and queries.

Solr (used by ElasticSearch) supports many languages prebuilt (parsing of words, normalizing, stemming, stopwords). Depends on the API of ElasticSearch what's usable.

Parsing/tokenizing into words is not easy for writing systems without word boundaries. In OTOBO they are:

ja - Japanese
th_TH - Thai (Thailand)
zh_TW - Chinese (Taiwan)
zh_CN - Chinese (Simplified)

This means that word based logic will not work for these four languages.
