### ISSUE TITLE
Fulltext indexing regexes should be reviewed

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#426]
The regexes for fulltext indexing in `Kernel/Config/Files/XML/Ticket.xml` are maybe broken in some cases.

This can cause that the indexing is not perfect.

```
    <Setting Name="Ticket::SearchIndex::Filters" Required="1" Valid="1" ConfigLevel="200">
        <Description Translatable="1">Fulltext index regex filters to remove parts of the text.</Description>
        <Navigation>Core::Ticket::FulltextSearch</Navigation>
        <Value>
            <Array>
                <Item><![CDATA[[,\&\<\>\?"\!\*\|;\[\]\(\)\+\$\^=]]]></Item>
                <Item><![CDATA[^[':.]|[':.]$]]></Item>
                <Item><![CDATA[^[^\w]+$]]></Item>
            </Array>
        </Value>
    </Setting>
```
1. `[,\&\<\>\?"\!\*\|;\[\]\(\)\+\$\^=]` does not include all punctuation, e.g. “”«» are missing.

IMHO `[^\w':.-]` should do better what's intended.

2. `^[':.]|[':.]$]` misses other apostrophe-like characters.

3. `^[^\w]+$` assuming `\w` includes all Unicode letterish and decimal characters plus `_`, then it's ok.

**Comment by bschmalhofer** [comment]
Yes, that kind of full text search is a bit strange. I looks like bed&breakfast would be only found with bedbreakfast.

**Comment by svenoe** [comment]
Tidying
