### ISSUE TITLE
COPYING vs. LICENSE

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#43]
The files COPYING and LICENSE in the OTOBO root are identical. I'm sure whether both have a purpose or one of the files is redundant.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO :
https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project suggest that any of COPYING, COPYING.txt. LICENSE, LICENSE.txt is fine. And that duplicates should be avoided.

**Comment by StefanRother-OTOBO** [comment]
Removed file COPYING.
