### ISSUE TITLE
Add the possibility to define max-allowed-package in scripts/backup.pl

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#432]
Hi,

we don not like to change the MariaDB docker image. But for backup reason, we need the possibility to change max-allowed-package for mysqldump.

Please change scripts/backup.pl and add a new param max-allowed-package= size. After that add the param like mysqldump --max-allowed-packet=681574400.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Implemented, but still needs testing.

**Comment by bschmalhofer** [comment]
The option is actually  called `--max-allowed-packet`, not `--max-allowed-package`.
Tested by doing a dummy backup of OTOBO running under Docker. Looks fine. 
Documentation has been updated. Closing the issue.
