### ISSUE TITLE
Integrate Rocketchat into Otobo

### ISSUE THREAD

**Issue by KriegerV** [RotherOSS/otobo#433]
Rocketchat can provide a complete live chat module to Otobo through which bots can interact.

by just focussing on Rocketchat integration, Otobo will be enhanced with 2 services: livechat and chatbot.

And chatbot integration will be covered by Rocketchat community -> less efforts for Otobo's one.

**Comment by svenoe** [comment]
Hi KriegerV,
thanks for your suggestion, we will definitely discuss this internally and let you know of our plans.
Have a nice day, Sven

**Comment by svenoe** [comment]
Hi KriegerV,

we came to the conclusion, that for now we want to focus on an internal chat functionality first. We will keep other chat platforms in mind, and try to make it as easy as possible, to link external services though.

Thanks for your suggestion, again, Sven

**Comment by KriegerV** [comment]
Hi Sven,

Thanks for the information. In this case, what can be interesting is to
think about having the possibility to let a bot chat into this internal
chat through web services.

Have a nice day too,

Vincent
