### ISSUE TITLE
PSGI: Consistent use of DBIx::Connector

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#434]
In `Kernel::System::DB::Connect` there is currently  both a reuse of `$Self->{dbh}` and reconnection with `DBIx::Connector`. While this works it is probably not best practice.

TODO:

- [x] Investigate what best practice actually is
- [x] Check whether rel-10_0 and rel-10_1 already diverge
- [x] Run the DB::Connect statements as Callbacks
- [x] implement

**Comment by bschmalhofer** [comment]
According to https://metacpan.org/pod/release/DWHEELER/DBIx-Connector-0.47/lib/DBIx/Connector.pm#dbh and  http://perladvent.org/2011/2011-12-22.html it looks like simply using the method `dbh`  of the connector object is best practice. The method ``dbh``pings the database itself, this means that the pings in `Kernel::System::DB` can be skipped.

The downside is that this would increase the number or pings when running under PSGI.
The upside is that reliability should be improved.
No changes for command line, cron and Daemon processes as F#for non-web processes the old behavior can be used for now.

For avoiding too frequent pings one can use the fixup connection mode. See https://metacpan.org/pod/release/DWHEELER/DBIx-Connector-0.47/lib/DBIx/Connector.pm#Connection-Modes. But this is beyond the scope of this ticket.

**Comment by bschmalhofer** [comment]
Also, in OTOBO 10.0.2 there is bug in the PSGI case. The attribure 'RaiseError => 0' was not passed to `DBIx::Connector->new()`. It is not clear whether this had noticable effects.

**Comment by bschmalhofer** [comment]
There are some issues regarding the UnitTests in the non-PSGI. The cause is not obvious. So let's be more conservative and avoid any code changes for the non-PSGI case.

**Comment by svenoe** [comment]
We should probably keep the non-PSGI case like this for OTOBO 10.0.

**Comment by bschmalhofer** [comment]
No new problems surfaces. @svenoe did a code review. Closing the issue.
