### ISSUE TITLE
In some packages are OTRS Verify Logos shown

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#453]
Hi,

in some OTOBO packages (if tested FAQ and Time Accounting) are "OTRS Verified" Logos shown inside Package Manager installation process.

Thanks,

Stefan

**Comment by svenoe** [comment]
Which otobo version and where exactly?
<img width="808" alt="grafik" src="https://user-images.githubusercontent.com/48322755/93793238-d9c19f00-fc36-11ea-898e-b6903489f6cb.png">

**Comment by StefanRother-OTOBO** [comment]
Hi Sven,

sorry, I installed the wrong version.

Close.
