### ISSUE TITLE
Step DB creation during installation is slow

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#454]
On a nearly empty server

```
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (4C/4T)
30 of 32 GB memory free
HDD in RAID-1
```

the initial creation of the database (MariaDB) takes ~5:45 min.

In comparison a msqldump of a DB (comparable hardware, hundreds of tables, dump ~10 GB) takes 10-15 min and a restore 15-20 min.

**Comment by bschmalhofer** [comment]
The work done for #534 might improve this. But doing batch INSERT even when the source is a remote database sounds like a worthwhile idea to explore.

**Comment by StefanRother-OTOBO** [comment]
Hi,

I think we have no task here at the moment. I do the installation process every day, and I don't see problems like this. 
I think that's a lokal problem, on my virtual instance the duration time is always smaller than 20 seconds.

Anyway, it's not the fastest step, but you need to do it only one time per installation.

Thanks for your help!

Stefan
