### ISSUE TITLE
Support change of user interface language for installation

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#455]
Maybe I didn't see it, but `installer.pl` uses the language preference of the browser.

It would be convenient to change the language to e.g. English, which many system administrators prefer.

**Comment by bschmalhofer** [comment]
@wollmers I second that. It would be nice to be able to switch to English in installer.pl.

**Comment by StefanRother-OTOBO** [comment]
@wollmers: Sorry, I´m not sure. If he prefers English, he use an English spoken browser. That's what I see with German admins often.
