### ISSUE TITLE
Mail configuration in install.pl is broken

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#456]
Otobo version 10.0.2

I guess it breaks during check MX records or DNS lookup isn't smart enough, exceptions are not catched.

Or maybe it was a real network problem.

```
Die Verbindung wurde nach einer temporären Unterbrechung wiederhergestellt. 
Möglicherweise funktionieren deshalb einige Elemente der aktuellen Seite nicht (mehr) korrekt. 
Um alle Elemente wieder wie gewünscht nutzen zu können, sollten Sie die aktuelle Seite neu laden.

-> Diesen Schritt überspringen
```

**Comment by svenoe** [comment]
This is a potential duplicate of issue #375 - I guess this whole step has to be worked through. (I don't know how to merge issues. Should we just close this one and mention it in the other issue?)

**Comment by wollmers** [comment]
Both descriptions are unspecific and can be treated as same. I close it.
