### ISSUE TITLE
install.pl: if mail configuration breaks, DB creation must be repeated

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#457]
If mail creation during web-based installation breaks, and is not skipped, then the DB schema and DB user must be deleted manually and all steps of the installation must be repeated.

**Comment by wollmers** [comment]
See also #456

**Comment by bschmalhofer** [comment]
A similar effect is when the database access fails. Effectively the complete migration has to be started from the beginning. I would have expected a 'Try again' button.

**Comment by svenoe** [comment]
Would be nice, yes, but the installation is not done so frequently (if it works at least ^^'), so nice, but not so important.
