### ISSUE TITLE
Provide convenient mail configuration in admin backend

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#458]
The existing mail configuration in the admin backend

`index.pl?Action=AdminSystemConfigurationGroup;RootNavigation=Core::Email`

is very technical and needs knowledge of Perl modules and their options.

An additional configuration in the same layout of the mail configuration screen/form would be more convenient and less error-prone. 

Share the code?

**Comment by svenoe** [comment]
Would be nice, there are more important things though, at the moment.
