### ISSUE TITLE
Is it really necessary to use root for MySql during installation?

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#459]
Guess it's only a documentation problem.

It should be enough to to create the schema `otobo`, the user `otobo` and the privileges on the command line, and then enter these credentials into the web-interface during installation.

**Comment by svenoe** [comment]
You have the option to use an existing database. Here the root user is not needed. If you want to setup a new database however, you need to specify a user with grant option, or how it is called, which typically is root. I am not particularly fond of this, either, especially if the installer is used via http only, but I haven't come up with an equally straight forward solution, so we kept the OTRS-default for now. Suggestions are welcome.

**Comment by wollmers** [comment]
Then it's a documentation issue only. For security reasons `root@localhost` should never be used in a web-interface. Can you trust browsers or malware-scanners having access to unencrypted content? Sure they could also read the password of `otobo@localhost` during a man-in-the-middle attack, but then they are restricted to the DB-schema `otobo` and can't access other DB-schemas on the server.

Good practice is (that's how I use it):

- restrict root to localhost and have a password 
- have a user e. g. `svenoe` as a DB-admin
- have extra users for backup, monitoring
- predefine schema (otobo), user (otobo) and user2schema-privileges for the web-app on the command line (or using some applications like MySQLWorkbench, WebMin if you know the risks)

**Comment by svenoe** [comment]
Actually I'm also not 100% happy with how the setup of the db works with respect to the password. You can however use a temporary user etc. to make things better, at least. I'll put it to the enhancements project. Especially for docker, this can surely be done more streamlined.
