### ISSUE TITLE
CustomerTicketZoom: JavaScript is not enabled or not supported

### ISSUE THREAD

**Issue by squidy** [RotherOSS/otobo#475]
Hi again...
In the screen CustomerTicketZoom some articles are displaying the message "JavaScript is not enabled or not supported" and I can't read the content of the articles, only of the last one.

I've tested with Google Chrome and Firefox (javascript is enabled on those browsers).

![OTOBO-customerticketzoom-javascript](https://user-images.githubusercontent.com/43784/94302811-d3833980-ff3a-11ea-89f2-6ee62ba330b3.png)

**Comment by svenoe** [comment]
Hi squidy,

this is a problem, when you cannot automatically log in to otobo using your session information (which is done in those article fields). Do you know what caused this problem? Possible reasons are usually a change in your FQDN, with multiple domains being used for otobo, maybe cookies (switching between http and https can sometimes cause unwanted behaviour, this is still an open issue),...

Sven

**Comment by squidy** [comment]
That's it.
I'm using OTOBO in a test environment. Because of that I'm using only http in the webserver, and OTOBO was configured to use https. After changed to http it worked.

Thanks again.

**Comment by svenoe** [comment]
Good. This is on my list, but I thought it would not occur too often, so the priority was not so high. I'll try to fix it soon.
See issue #251 .

**Comment by svenoe** [comment]
On second thought, this is not a duplicate. Actually it is just a setting problem. It makes me question, whether our switch to HttpType=https in standard was a good one. Usually when you setup https, you are automatically setting up a redirect from http, and this error would not occur. In the other direction, however, you don't do all that stuff, you just use http which still works for your own login and stuff, but you just end up with this. (Yes, the setting is wrong, but it's just very obscure what is happening.)
