### ISSUE TITLE
Should we switch back to http as standard HttpType?

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#477]
Using OTOBO via the "wrong" http type has some consequences, which are very hard to see through when you don't know what you are doing. As the switch to https usually is done with more awareness, it might be good, to use http as standard type again, or in the longer run ask in the installer or so.

See Issue #475 as an example (and my explanation in the last messages there).

**Comment by StefanRother-OTOBO** [comment]
Hi,

I don´t like the idea going back to "http", cause I had the same problem in another tool, and I need a lot time to find the setting...:) .
 I think the best idea is to ask the information inside the installer process. 
That's not really difficult and after that we are save. 

What do you think?

Stefan

**Comment by svenoe** [comment]
Yes, probably good.

**Comment by bschmalhofer** [comment]
Perhaps this can be combined with the setting for FQDN. Maybe have a single setting for "URL used by Agents".

**Comment by StefanRother-OTOBO** [comment]
I spoke with @bschmalhofer and we think ewe do not need "URL used by Agents".
