### ISSUE TITLE
CronTask RebuildEscalationIndex updates tickets despite no changes are present.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#490]
See https://otobo.de/de/forums/topic/weird-behavior-tickets-are-being-updated/

Regardless of the settings this should not occur. I assume we will find something connected to our EscalationSuspend implementation.

**Comment by bschmalhofer** [comment]
@svenoe , @StefanRother-OTOBO : One question remains. Should we generally leave the change time at the old value when only updating the escalation times? Because updating the escalation time is not really a change in the ticket.

**Comment by bschmalhofer** [comment]
During the devel meeting on October 16th, it was decided that these updates can be removed. The removal can be done, when there is no danger that the removal will have unwanted side effects.

**Comment by bschmalhofer** [comment]
The updating of the change_time has been implemented.

One test failure cropped up in _test/Event/Escalations.t_ . In needs to be checked whether the test or the implementation must be adaped

**Comment by bschmalhofer** [comment]
Let's fix the test failure after the 10.0.5 release.

**Comment by bschmalhofer** [comment]
The test failures happened because a SQL update statement was inadvertently deleted. Looks better after the fix.

**Comment by bschmalhofer** [comment]
Tests look fine now. Closing this issue.
