### ISSUE TITLE
Command Maint::Ticket::EscalationIndexRebuild does not handle all tickets

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#505]
When EscalationSuspendStates ist activated and contains at least one state, then the command looks only at tickets in the configured states. IMHO this behavior is unexpected and at least not documented. I propose to revert to the OTRS 6 behavior where the TicketSearch is not restricted to specific states.

When EscalationSuspendStates is not activated then all tickets are handled. This is fine.

It is not clear whether the parem `Suspend => 1 ` for `TicketEscalationIndexBuild()` should be reverted too.

See also #490. The difference is that #490 is about the cron job, not the Console command.

**Comment by bschmalhofer** [comment]
After discussion with @svenoe  and @StefanRother-OTOBO  it was decided that the OTRS 6 behavior should be restored. Optionally the command could be converted to call `Kernel::System::Ticker::RebuildEscalationIndex()` in order to avoid code duplication.

**Comment by bschmalhofer** [comment]
The OTRS 6 behavior has been restored. The parameter Suspend is also no longer passed.

**Comment by bschmalhofer** [comment]
Implementation has been changed for 10.0.4 already, but let's test some more and close the issue only for 10.0.5

**Comment by svenoe** [comment]
Had a quick look at it, don't think there's anything to expect. If something comes up, we can reopen this issue.
