### ISSUE TITLE
Add, or consistenly use, a method that can parse the file RELEASE

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#510]
I have encountered at least two locations where the file _RELEASE_ is parsed. IMHO there should a dedicated function for that. A dedicated module is probably overkill. Maybe a function in Kernel::System::Main suffices.

Alternatively: Convert RELEASE to JSON or YAML

**Comment by bschmalhofer** [comment]
A similar thing might apply to parsing the file _Kernel/Config.pm_ .

**Comment by svenoe** [comment]
I think a method like "Version" in Kernel::System::Main returning program and version is a good idea. Converting to YAML/JSON in principle would be ok, but I guess some people writing external scripts (me^^) would not be happy...

Why or where do you want to parse Kernel/Config.pm?

**Comment by bschmalhofer** [comment]
@svenoe , _Kernel/Config.pm_ is parsed during the migration. This is problematic because this is Perl code that can be formated in is strange ways.

**Comment by svenoe** [comment]
But it is probably not done anywhere else, I mean the only reason it is not loaded, is because one OTOBO version has to read out the information of another installation, and I cannot imagine another place where this is necessary. Concerning the parsing itself, it would probably be best, to just eval the complete Load-subroutine (that is basically the "parser") - if you call it, passing a $Dummy (={}) variable, you should be able to just use the DB info directly from that variable, or is it more complicated? (Not so sure...)

**Comment by bschmalhofer** [comment]
Yes, evaling the method `Load`would be the way to go.

**Comment by bschmalhofer** [comment]
It might be useful to include the Git branch and the Git commit in the RELEASE file. Either when creating a distribution package or when creating a Docker image. One use case would be in _bin/docker/run_test_suite.sh_. The name, or the content, of the result file could then include that information.

**Comment by bschmalhofer** [comment]
So let's go with the method `Kernel::System::Main::GetReleaseInfo()`. This method parses the file _RELEASE_ and returns the content as a simple hash. The file _RELEASE_ won't be changed.

**Comment by bschmalhofer** [comment]
TODO:

- [x] test a migration to OTOBO 10.1.x, as GetReleaseInfo() is used in one of the migration modules

**Comment by bschmalhofer** [comment]
Tests looked fine, even though scripts/test/Selenium/Customer/CustomerTicketAttachment.t had a sporadic error. Testing an actual migration is still TODO.

**Comment by bschmalhofer** [comment]
Finally, a test migration to OTOBO 10.1.1 has been performed. The version check looked fine. Closing this issue.
