### ISSUE TITLE
Migration: SecureMode is not the current value in migration.pl

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#540]
When testing migration frim OTRS 6 to OTOBO 10 is followed the instructions in the installation manual. I deactivated SecureMode and deployed the changed setting. However migration.pl still complained about secure mode being active. 
That SecureMode was deactivated could be confirmed by checking the deployment history and by inspecting _Kernel/Config/Files/ZZZAAuto.pm_ .

Calling `docker-compose restart web` solved the issue. But that should not be necessary.

**Comment by bschmalhofer** [comment]
It looks like ZZZAAuto.pl is not reloaded reliably. In the Webapp there was the message "The configuration is being updated, please be patient..." after the first deployment. 
A check of _Kernel/Config/Files/ZZZAAuto.pm_ showed no strangeness. The changed setting was there and CurrentDeploymentID was set to 2.

But apparently some delay is accepted:
```
$Self->{'Frontend::NotifyModule'}->{'6050-SystemConfiguration-OutOfSync-Check'} =  {
  'AllowedDelayMinutes' => '5',
  'Module' => 'Kernel::Output::HTML::Notification::SystemConfigurationOutOfSyncCheck'
};

```

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO  I still don't really understand how ZZZAAuto,pm is reloaded when it has been changed. ``Kernel::Config::Defaults::new`` requires the _Kernel/Config/Files/*.pm_ files. But require does not check whether the module has changed. Did the classic OTOBO rely on `Apache::Reload` ? If that is so, then maybe `Plack::Middleware::Refresh`does no work for_ ZZZAAuto.pm_

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I don't know how it works detailed, but I'm sure Apache::Reload is not the mechanism, cause the mechanism work without Apache::Reload, if I remember right. 

In my last test it was no problem to disable the secure_mode in docker and open migration.pl.

Could it be that you had already started the migration and then the configuration of the other system was already taken over, with secure-mode enabled?

I have often experienced this phenomenon.

Thanks!

Stefan

**Comment by bschmalhofer** [comment]
It is not clear whether this problem persists with OTOBO 10.0.5 under Docker. This can't be checked with the agent interface, as the agent interface does not care about SecureMode.

**Comment by bschmalhofer** [comment]
This seems to work in the devel version of 10.0.6. Closing this issue.
