### ISSUE TITLE
DynamicField default value not working

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#543]
Hi,

I use Otobo 10.0.4 -> ITSM Package installed. If I juice another value as default value in DynamicField type "Dropdown" (in my example "nein"), the wrong value is shown inside the agent interface. If I use "-", it's work like a charm.

Thanks!

Stefan

**Comment by svenoe** [comment]
It happens for initially hidden fields and is most likely independent of ITSM. I will have a look.

**Comment by svenoe** [comment]
Fixed.
