### ISSUE TITLE
CustomerID is not correctly added, when creating a new ticket via AgentTicketPhone or -Email.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#544]
This is an unwanted side effect of taking the CustomerID out of the forms. I will redo this and just hide the fields.

**Comment by svenoe** [comment]
Done.

**Comment by bschmalhofer** [comment]
Reopening the issue because scripts/test/Selenium/Agent/AgentTicketPhone/CustomerAutoCompletion.t needs to be adapted.

**Comment by bschmalhofer** [comment]
_CustomerAutoCompletion.t_ looks fine now. Closing this issue again.
