### ISSUE TITLE
Eliminate  Kernel::System::FileTemp

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#545]
I see no benefits of this module over using `File::Temp` directly. It does set up a non-standard location for temporary dirs. But I don't think that this is a benefit.

**Comment by svenoe** [comment]
I don't know every way otobo is set up on systems. If someone wants to give minimal access to the otobo-user, or just have all otobo-files in one place for a better overview, or maybe disk space limitations, it's not a bad thing to be able to, in my opinion.

**Comment by bschmalhofer** [comment]
Reading the documentation of File::Temp I find that this is trickier than expected, and I agree that keeping Kernel::System::FileTemp might be useful.
However, looking at the code in _Kernel/Modules/AgentTicketAttachment.pm_, I still find that the object oriented interface of File::Temp would be the better approach. My impression is that Kernel::System::FileTemp first makes an effort to make the created file handle persistent, and then makes an effort to clean up after the end of the current request. File::Temp::new() does kind of the same thing, but makes it easy to limit the life time of the temporary file to a small scope.

Thomas Fahle tells it like it is in https://perl-howto.github.io/2008/07/temporare-dateien-sicher-erzeugen.html:

> File::Temp ist seit Perl 5.6.1 ein Standardmodul, d.h. es wird mit Perl ausgeliefert und läuft auf jeder Plattform, die von Perl unterstützt wird.
> 
> Dokumentation und API werden selbst von sehr gutmütigen Menschen bestenfalls als verwirrend bezeichnet. 


So I propose to keep this issue open, until we find the best solution.

**Comment by bschmalhofer** [comment]
There was an inconstent usage of the file handle returned from Kernel::System::FileTemp::TempFile(). The applied PR aligns the usage in Kernel/Modules/AgentTicketAttachments.pm with the saner usage Kernel/System/Crypt/PGP.pm, A test with the formatter wc -l gave the expected result.
