### ISSUE TITLE
Docker: Enhance the update process

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#567]
During the last devel meeting it was decided to simplify the upgrade process:

TODO:

- [x] keep the general strategy where the new _/opt/otobo_ is copied over the existing _/opt/otobo_
- [x] no funny version check, currently there is a check that old and new version mustn't be devel versions
- [x] no automatic upgrade, upgrading must always be triggered manually
- [x] execute actions automatically 
- [x] Think about whether 'docker-compose` is necessary, if so check the installation manual
- [x] split up copying and maintainance tasks, as maintainance tasks need the database
- [x] test, e.g. update from local image to latest from the rotheross repository
- [x]  update the installation manual, mention that scripts/update.sh will be available in 10.0.8

The following action must be executed manually:

    bin/otobo.Console.pl Admin::Package::ReinstallAll
    bin/otobo.Console.pl Admin::Package::UpgradeAll
    bin/otobo.Console.pl Maint::Config::Rebuild
    bin/otobo.Console.pl Maint::Cache::Delete

**Comment by bschmalhofer** [comment]
An initial test looked fine. But more testing is needed.

**Comment by bschmalhofer** [comment]
A script that automates the commands given in the installation guide would be nice. Maybe a script that also adapts the .env file and does the docker-compose pull.

**Comment by bschmalhofer** [comment]
There is now a preliminary script _scripts/update.sh_ . Needs to be tested and polished.

**Comment by bschmalhofer** [comment]
TODO:

- [x] add support to update.sh for switching between HTTP and HTTPS

**Comment by bschmalhofer** [comment]
The current state of affairs is checked into the docker-compose repository.
m4 is now only needed for creating the sample .env files and for a special mode for development.

**Comment by bschmalhofer** [comment]
TODO:

- [x] confusing error messages when _update.sh_ calls `docker-compose pull`

Errors are emitted for local images. This might be fixable by passing `--ignore-pull-failures[=service:name]` for the local images.

**Comment by bschmalhofer** [comment]
Found no easy was to suppress the error messages, so I added an message that the errors can be ignored.
Simplified _scripts/update.sh_ so that it basically only runs the statements documented in the installation manual.
The .env generation feature is now in _scripts/devel/generate_dot_env.sh_. For conistency sake, I moved the other helper scripts also into _scripts/devel_. 

@svenoe Could you update the release instructions. _scripts/create_sample_env_files.sh_ is now _scripts/devel/generate_sample_env_files.sh_ .

Not closing the issue yet, as the changed script needs to be tested again.
The plan is to add a note in the installation manual, stating that _scripts/update.sh_ can be used in 10.0.8 or later.

**Comment by svenoe** [comment]
> @svenoe Could you update the release instructions. _scripts/create_sample_env_files.sh_ is now _scripts/devel/generate_sample_env_files.sh_ .

Done.

**Comment by bschmalhofer** [comment]
The test of _scripts/update.sh_ looked fine. The installation guide is updated. Closing this issue.
