### ISSUE TITLE
Require the module Class::Method::Modifiers

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#573]
I think that `Sub::Override` is useful for writing extension. Let's discuss this. See also #73 .

**Comment by bschmalhofer** [comment]
Switched my preference from Sub::Override to Class::Method::Modifiers. The latter module looks more modern and better supported. It also isn't really a new requirement, as the required module Moo depends on it.

**Comment by bschmalhofer** [comment]
Discussed this with @svenoe . The conclusion was that using Class::Method::Modifiers in Autoload modules is a good idea. So let's officially require it for 10.0.11. This is no major change, as Class::Method::Modifiers is already required by Moo.

**Comment by svenoe** [comment]
It would be nice to have a small proof of principle and maybe a sample file, which can be used as template. Priority is not so high, though.

**Comment by bschmalhofer** [comment]
Requirement has been added. Issue for improving the documentation has been created. Closing this issue.

**Comment by bschmalhofer** [comment]
Ah well, it turns out the Class::Method::Modifiers is not useful at all for Autoload modules. These provided functionality is just for derived classed, not for behind the back modifications of existing subroutines. The alternative Sub::Override overrides subs in lexical context, which does not help either. So, let's go back to the old recommendation of simply overwriting the symbol table entry.

TODO:

- [x] Remove the explicit requirement of Class::Method::Modifiers. this won't break anything as C::M::M is required implicitly already

**Comment by bschmalhofer** [comment]
The explicit requirement is gone. See #1230. Closing this issue again.

**Comment by bschmalhofer** [comment]
See also #1406.
