### ISSUE TITLE
Many links to documentation are broken

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#585]
A quick check with an invalid URL in the current branch `rel-10_0`:

```
$ grep -Ri --exclude-dir={.git} 'doc.otobo.org/doc/' . | wc -l
     229
```

Needs a commitment to an URL scheme stable over longer periods.

Needs coordination across all repositories, websites and tool chains.

See https://github.com/RotherOSS/doc-otobo-admin/issues/3

**Comment by svenoe** [comment]
Tidying
