### ISSUE TITLE
Bug in AgentTicketPrint with DynamicField Type Title

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#590]
Hi,

The AgentTicketPrint view is not beauty at the moment. All fields from type Title are shown like:

Title: 1

We need to remove the value from print screen and format the view.

Thanks,

Stefan

**Comment by StefanRother-OTOBO** [comment]
Good Morning,

this error occurs not only in AgentTicketPrint but also in AgentTicketZoom. Titles are always displayed with Title=1.

Thanks,

Stefan

**Comment by StefanRother-OTOBO** [comment]
Good Morning, 

i have found another error, if a RexEx is entered in a dynamic field of type text, it does not appear in the customer interface.

Thanks!

Stefan

**Comment by svenoe** [comment]
PDFs are included in 63de46dced7e54784f31506bc070a2206f0747f5 except underlining.

**Comment by svenoe** [comment]
Is included in TicketZoom. There are probably other occurrences of this, I'm for implementing other places as soon, as they are needed, at the moment.

In general the code around the title fields is not very pretty, as their general functionality differs quite a bit. If there are good ideas for this... (Maybe one should get rid of them altogether and introduce proper "sections" to the ticket masks as a separate feature.)

**Comment by svenoe** [comment]
Closing this issue for now. More work in this direction will be done in a separate issue.
