### ISSUE TITLE
Button "Save" in DynamicField Type "Title" leaves the view

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#591]
Hi,

If I click the Button "Save" in AdminDynamicFieldTitle we leave the view. 
In all other DynamicFields types we stay inside the view.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO This is fixed in the rel-10_0 branch. Could you check whether it works for you?

**Comment by svenoe** [comment]
Seems fixed to me.
