### ISSUE TITLE
Remove AdminDynamicFieldScreen in OTOBO

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#593]
Hi,

if I like to add a form in OTOBO, I need to add the fields first, than add the fields to the screens in AdminDynamicFieldScreen and after that I configure the form using ACL´s.

In my opinion is the best way, to add in each dynamic field create or change screen the possible to choose the screens, not anymore in AdminDynamicFieldScreen.

Thanks,

Stefan

**Comment by svenoe** [comment]
While you are in the process of creation I agree, but if you are working on an older system, having especially the "screen"-overview with all active dynamic fields of AdminDynamicFieldScreen can be very helpful to have an overview, in my opinion. So I am not so much in favor of getting rid of AdminDynamicFieldScreen.

As an at least temporary solution which is much less work, I'm very much for adding a button to the dynamic fields, which lets you jump to AdminDynamicFieldScreen (if you from overview to overview, or from the specific dynamic field to the specific dynamic field). What do you think?

**Comment by StefanRother-OTOBO** [comment]
Button exists, done.
