### ISSUE TITLE
Quickclose in AgentTicketZoom is possible on locked tickets

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#594]
Hi,

1.) Another Agent has locked the ticket.
2.) In OTOBO (ITSM) is it possible to select quick close in AgentTicketZoom and the ticket will closed.

Please change it like the "close" standard with a config option. Default quick close is only shown, if I'm the owner of the locked ticket.

Thanks!

Stefan

**Comment by wollmers** [comment]
Hi @StefanRother-OTOBO,

as far as I understand it should only prevent to show the menu entry `quick close` in AgentTicketZoom, and not check and show an `NoPermission` message after clicking. Makes sense to hide the menu entry.

ad 2) The same is possible in a default installation of OTOBO.

There is still a similar sounding (but not the same) config option `Ticket::Frontend::AgentTicketClose###OwnerMandatory`.

So we should create an config option like `Ticket::Frontend::AgentTicketZnuny4OTOBOQuickClose###SameOwnerMandatory`(better names welcome) for this purpose.

**Comment by svenoe** [comment]
I would just use Ticket::Frontend::AgentTicketClose###OwnerMandatory - I think there will almost never be a case, where you want the non-owner to be able to close the ticket in the standard way, but not in the quick way, and certainly never the other way around.

**Comment by wollmers** [comment]
@svenoe Thx for the quick response. I guessed that it makes sense to have same option for same behaviour of close and quickclose.

**Comment by svenoe** [comment]
I looked at the code now. OwnerMandatory is something different (it sets the "New Owner" selection mandatory for real forms), "RequiredLock" does the trick (as implemented by you). What I meant earlier was also to use the AgentTicketClose settings directly, so I changed the code accordingly.

Can be closed after a quick test.

**Comment by wollmers** [comment]
Without `Ticket::Frontend::AgentTicketZnuny4OTOBOQuickClose###RequiredLock` enabled it still displays the the menu entry `Quick Close`

![Bildschirmfoto 2020-12-16 um 21 43 56](https://user-images.githubusercontent.com/1275557/102405841-fed16e00-3fe9-11eb-8c90-f0044a224675.png)

thus not solving the original issue:

> 1.) Another Agent has locked the ticket.
2.) In OTOBO (ITSM) is it possible to select quick close in AgentTicketZoom and the ticket will closed.

> Please change it like the "close" standard with a config option. Default quick close is only shown, if I'm the owner of the locked ticket.

The changes in `AgentTicketZnuny4OTOBOQuickClose.pm` only close the backdoor, if someone directly sets `Action=AgentTicketZnuny4OTOBOQuickClose` into the URL, i.e. behave similar like the permission checks in case of `AgentTicketClose`.

**Comment by svenoe** [comment]
After talking with Stefan I added AgentTicketQuickClose specific options again. Helmut is right, that this is not yet solved though, as the action is still shown.
