### ISSUE TITLE
MigrateFromOTRS: handle Blob columns

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#601]
It looks like Blob Columns were never correctly converted between dabase types that have different DirectBlob settings.
Either fix this, or remove the remnants of the code that once did the conversion.

Maybe check whether there still is a need to support Base64 encoded binary data.

**Comment by bschmalhofer** [comment]
I added support for Blob conversion in `Kernel::System::MigrateFromOTRS::CloneDB::Driver::Base` in the rel-10_0 branch. This should not affect MySQL to MySQL migration, as the `DB::DirectBlob` check is still honored.

However it looks like the conversion is not as straightforward as assumed. Let's take for example the table columns *article_data_mime.email* and *sysconfig_default_version.description*. For the first column there is an explicit check of `DB::DirectBlob` in `Kernel::System::Ticket::Article::Backend::MIMEBase::ArticleStorageDB`.

```
    # encode attachment if it's a postgresql backend!!!
    if ( !$DBObject->GetDatabaseFunction('DirectBlob') ) {

        $Kernel::OM->Get('Kernel::System::Encode')->EncodeOutput( \$Param{Email} );

        $Param{Email} = encode_base64( $Param{Email} );
    }

```
But, for the latter column, there seems to be no such check in `Kernel::System::SysConfig::DB`.

This seems to indicate that some more testing of the PostgreSQL to MySQL migration needs to be done. As this is not super urgent, let's move the issue to OTOBO 10.1.x.

**Comment by StefanRother-OTOBO** [comment]
Dublicate with Issue #1006, #800 and #601
