### ISSUE TITLE
Standardize on otobo.org or on otobo.de

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#604]
Checking the source code I found that otobo.de and otobo.org are both used. IMHO it make sense to standardize on either one.

```
bernhard@bernhard-HP-250-G6-Notebook-PC:~/devel/OTOBO/otobo$ grep -r 'otobo.de' . | grep -v Copyright | grep -v '@otobo.de'  | wc -l
410
bernhard@bernhard-HP-250-G6-Notebook-PC:~/devel/OTOBO/otobo$ grep -r 'otobo.org' | wc -l
960

```

**Comment by GritRother-OTOBO** [comment]
Hi Bernhard, 

otobo.org is supposed to be used for the Open Source Project, otobo.de for the company / product / services. 
I think we also need to have a look at the email addresses given. 

Let's discuss how to proceed in detail in our meeting next week.

Thanks, 
Grit

**Comment by bschmalhofer** [comment]
See also #585

**Comment by svenoe** [comment]
This is not time critical.

**Comment by bschmalhofer** [comment]
I checked this again with the command:

`grep -r -i  'otobo\.de' | grep -v 'Rother OSS' | grep -v 'Contact us at hello@otobo.de' | grep -v 'Contact us at hello@otobo.de' | grep -v 'https://local.otobo.de:8000/Webservice/Example' | grep -v 'https://www.otobo.de:10745/api/v1.0' | grep -v 'http://www.otobo.de/GenericInterface/' | grep -v '^i18n/' | grep -v '^scripts/test/'  > ../grep.out`

The remaining output looks sane to me. Let's close this issue and fix the remaining glitches when they are noticed.
