### ISSUE TITLE
Remove Templating Directives: InsertTemplate, RenderBlockStart, RenderBlockEnd

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#608]
It looks like these directives were added for compatability with the DTL, the templating mechanism that used to be used by OTRS. It should be investigated whether this compatability is still required. If not, I propose to remove these directives.

**Comment by svenoe** [comment]
I have overlooked this so far. This is the base of probably 90% of the templates we use. In the perl file you have $LayoutObject->Block(); (e.g. Kernel/Modules/AgentTicketPhone.pm line 3133), which prepares those blocks (here Name => 'DynamicField') and then can output multiple of those blocks, or just show them conditionally (e.g. Kernel/Output/HTML/Templates/Standard/AgentTicketPhone.tt line 188). InsertTemplate is used too, afaik.

Do I miss the point somehow? :)

**Comment by bschmalhofer** [comment]
Hi @svenoe,

I propably misunderstood that the old, OTRS 3 or OTRS 4 , DTL syntax would still be supported by these tags. I'm still not a fan ot the tags `RenderBlockStart` and `RenderBlockEnd`.
Currently in OTOBO the Following syntax is used:

```
[% RenderBlockStart("ActionOverview") %]
                    <li>
                        <a href="[% Env("Baselink") %]Action=[% Env("Action") %]" class="CallForAction Fullsize Center"><span><i class="fa fa-caret-left"></i>[% Translate("Go to overview") | html %]</span></a>
                    </li>
[% RenderBlockEnd("ActionOverview") %]

```
I gather that is not regular Template::Toolkit syntax, which violates the principle of least surprise. `Kernel::Output::Template::Provider` turns this into

```
[% PerformRenderBlock("ActionOverview") %][% BLOCK "ActionOverview" -%]
                    <li>
                        <a href="[% Env("Baselink") %]Action=[% Env("Action") %]" class="CallForAction Fullsize Center"><span><i class="fa fa-caret-left"></i>[% Translate("Go to overview") | html %]</span></a>
                    </li>
[% END -%]
```
This version is nice, as it seems to be regular Template::Toolkit syntax. But it is really ugly because the name 'ActionOverview' must be stated twice. The effect is that a named block is created in the the template file and the macro `PerformRenderBlock` is processed when `Kernel::Output::HTML::Layout::Template::Output()` is called,

The macro is defined in _Kernel/Output/Template/Document.pm_ and it does a couple of things:

1.  provide support for BlockHooks. Block hooks seem to be used only by Znuny4OTOBOAdvancedDynamicFields
2. grab the relevant block data that has been submitted by `Kernel::Output::HTML::Layout::Block()`
3. localize variables and call `process()`. But that sounds much like INCLUDE, which is a regular Template::Toolkit command .
```
Directly adding the macro and the named block in the .dtl file is possible but inconvenient and error prone. So I would not recommend this. 

However, I aggree with the recommendation given in https://doc.otobo.org/manual/developer/stable/en/content/how-it-works/templates.html.

> Please note that the blocks commands were added to provide better backwards compatibility to the old DTL system. They might be deprecated in a future version of OTOBO and removed later. We advise you to develop any new code without using the blocks commands. You can use standard Template::Toolkit syntax like IF/ELSE, LOOP and other helpful things for conditional template output.

**Comment by bschmalhofer** [comment]
The support for _GenerateBlockHooks_ is a rather obscure feature. It is documented for OTRS 7, https://doc.znuny.org/doc/manual/developer/7.0/en/content/how-to-extend-otrs/otrs-module-layers/outputfilter.html, but not for OTOBO 10, https://doc.otobo.org/manual/developer/stable/en/content/index.html. As far as I can tell, it is only used for Znuny4OTOBOAdvancedDynamicFields. There it could easily be replaced by adding the hooks for the output filter directly in the .dtl file.

In the spirit of trying to simplify things, I propose to remove support for GenerateBlockHooks.

**Comment by bschmalhofer** [comment]
Aknowledging that _InsertTemplate_, _RenderBlockStart_, and _RenderBlockEnd_ are widely used in OTOBO I withdraw the request. For _GenerateBlockHooks_ I opened #948 .
