### ISSUE TITLE
Fix regular expressions for dynamic fields in CustomerInterface.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#625]
Good Morning, 

i have found another error, if a RexEx is entered in a dynamic field of type text, it does not appear in the customer interface.

Thanks!

Stefan

_Originally posted by @StefanRother-OTOBO in https://github.com/RotherOSS/otobo/issues/590#issuecomment-722897929_

**Comment by svenoe** [comment]
Commit 63de46dced7e54784f31506bc070a2206f0747f5 is labeled wrong, belongs to Issue #590 .

**Comment by stefanhaerter** [comment]
What exactly is the wanted behavior in this case?

Additionally, the label for a text field with regular expression in the customer interface is located on the right, unlike other fields. Is this correct?

**Comment by svenoe** [comment]
Basically the error messages are not working properly in the customer interface atm. This issue is mostly a css/ui-problem. (Compare wrongly filled fields in agent and customer interface for the functionality. I have no plan for the design, but probably a simple, small, red text message under the field.)

And yes, text fields are not properly designed yet, either.

**Comment by stefanhaerter** [comment]
Investigating the issue, I recommend to fix this within Issue #1132. Noteworthy details here are:

- different behaviour between agent and customer interface
- adding the error message behind the label
- handling the error message text in template files

Moving the milestone to 10.1.

**Comment by stefanhaerter** [comment]
Idea: Displaying ServerError Tooltip as label and not as div in CustomerInterface.
Problem: The input field may already have a label.
