### ISSUE TITLE
Check whether the input "Expand" for the different forms is still needed, remove it if not.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#632]
In CustomerTicketMessage.tt and others there is a hidden input named "Expand". This was introduced with Type, Service and SLA, and if I understand it correctly it is the ancient way of an ajax update. I am not sure though, why this is still there, and whether this is still used somewhere. (Also I'm a bit confused, why it is handled as "Error" in the respective perl modules, e.g. CustomerTicketMessage.pm, but I guess this was just convenient back then...)

For reference see commit 6f7e6a6b4bfff97279538d29a971f8b22b4c8b21 of otrs for its first introduction, and eade32018474721e02db944319c582f450674162 which is a commit which changes where the expand input is set. I have not further looked into it, yet.

**Comment by bschmalhofer** [comment]
I looked at the code and my impression is also that Expand can be removed. Let's check whether there are similar cases.

**Comment by bschmalhofer** [comment]
More greping on OTRS and OTOBO source code. Here are the cases that need to be investigated:

- [x] ExpandCustomerName[12]? in AgentTicketEmail and AgentTicketPhone:

```
./Kernel/Modules/AgentTicketEmail.pm:        my $ExpandCustomerName = $ParamObject->GetParam( Param => 'ExpandCustomerName' )
./Kernel/Modules/AgentTicketEmail.pm:            my $Item = $ParamObject->GetParam( Param => "ExpandCustomerName$Number" ) || 0;
./Kernel/Modules/AgentTicketPhone.pm:            my $Item = $ParamObject->GetParam( Param => "ExpandCustomerName$Count" ) || 0;
./Kernel/Modules/AgentTicketPhone.pm:        my $ExpandCustomerName = $ParamObject->GetParam( Param => 'ExpandCustomerName' )
./Kernel/Output/HTML/Templates/Standard/AgentTicketPhone.tt:                <input type="hidden" name="ExpandCustomerName" id="ExpandCustomerName" value="0"/>
./Kernel/Output/HTML/Templates/Standard/AgentTicketPhone.tt:#    <input type="hidden" name="ExpandCustomerName" value="1"/>
./Kernel/Output/HTML/Templates/Standard/AgentTicketEmail.tt:                <input type="hidden" name="ExpandCustomerName" id="ExpandCustomerName" value="0"/>
./Kernel/Output/HTML/Templates/Standard/AgentTicketEmail.tt:#    <input type="hidden" name="ExpandCustomerName" value="2"/>

```
- [x] ExpandCustomerName in links used by Kernel/Modules/AdminCustomerUser.pm

- [x] OwnerAllRefresh in AgentTicket[Email|Phone]

- [x] ResponsibleAllRefresh in AgentTicket[Email|Phone]

- [x] ExpandCustomerName[12] in AgentTicketCustomer:

```
./Kernel/Modules/AgentTicketCustomer.pm:        my $ExpandCustomerName1 = $ParamObject->GetParam( Param => 'ExpandCustomerName1' )
./Kernel/Modules/AgentTicketCustomer.pm:        my $ExpandCustomerName2 = $ParamObject->GetParam( Param => 'ExpandCustomerName2' )
```

hidden input field "Expand":

- [x]  ./Kernel/Output/HTML/Templates/Standard/ProcessManagement/ActivityDialogHeader.tt

- [x] ./Kernel/Output/HTML/Templates/Standard/ProcessManagement/CustomerActivityDialogHeader.tt

- [x] ./Kernel/Output/HTML/Templates/Standard/CustomerTicketMessage.tt

- [x] ./Kernel/Output/HTML/Templates/Standard/AgentTicketActionCommon.tt

```

**Comment by bschmalhofer** [comment]
The difference between **Expand** and **ExpandCustomerName** is that **ExpandCustomerName** is used in at least one location. Furthermore, removing **ExpandCustomerName** would change the existing interface, even if it is not well documented.
So, I'd like to leave **ExpandCustomerName** and only remove **Expand**.

**Comment by bschmalhofer** [comment]
The usage of Expand looked very much obsolete. 
Flagging Expand as an error looked like a check that the old interface is no longer used.
Closing this issue.
