### ISSUE TITLE
Migration sanity check on db fails on MySQL 8

### ISSUE THREAD

**Issue by Wolverine80** [RotherOSS/otobo#639]
Migrationskript auf OTOBO 10 ist ein separates issue

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/6#issuecomment-625306880_

Ist das problem eigentlich behoben? Ich versuche gerade meine OTRS6 unter Ubuntu 20.04 (mit mysql8) zu migrieren und sehe im Log dass die Migration versucht die groups Tabelle ohne Escape zu lesen und bricht dann natürlich ab.

**Comment by bschmalhofer** [comment]
Hallo @Wolverine80,

die Lösung für #6 war dass in OTOBO 10.0.x die Tabelle *groups* nach *groups_table* umbenannt wurde. Diese Umbenennung ist auch ein Teil der Migrationsroutinen. Die Migration geht aber immer noch davon aus das für die Abfragen in der Quell-Datenbank kein Quoting notwendig ist. Demzufolgen gibt es wohl einen Fehler bei der Migration von OTRS 6 unter MySQL 8. Ich baue aber für OTOBO 10.0.7 noch das Quoting ein. Das wäre ja sowieso best practice.

Eine Frage noch zum Qellsystem. Dort läuft ja OTRS 6 unter MySQL 8. Ich vermute daher dass da für die groups-Tabelle Anpassungen notwendig waren. Waren diese Anpassungen bereits in OTRS 6 enthalten, oder waren das kundenspezifische Anpassungen?

Viele Grüße,
   Bernhard Schmalhofer

**Comment by Wolverine80** [comment]
Hi,

interessanterweise trat das Problem bisher nicht auf. Die betroffenen Dateien sind nicht gepatcht. Fehler gab es erst beim Versuch zu migrieren auf Otobo. 
Vielleicht bisher Glück gehabt da wir keine CustomerGroups nutzen und sonst nicht viel i der Tabelle gelesen oder geschrieben wird.

**Comment by Wolverine80** [comment]
Bisher wohl wirklich Glück gehabt. Gab zwar einige Fehlermeldungen laut dem Log, aber keine großen Auswirkungen bei der Benutzung. Habe die betroffenen Dateien von Hand korrigiert und hoffe bald auf Otobo umsteigen zu können.

**Comment by bschmalhofer** [comment]
Implemented quoting of the source table names during migration.
Added the method `Kernel::Systerm::DB::QuoteIdentifier()` for that purpose.
TODO:
- [ ] Test OTRS with MySQL < 8 to OTOBO with MariaDB  10
- [x] Test OTRS with MySQL 8  to OTOBO with MariaDB  10

**Comment by bschmalhofer** [comment]
@Wolverine80 , I have added the quoting of the source tables to OTOBO 10.0.7. I have tested it with a migration from OTRS 6 on MySQL 8  to OTOBO on MariaDB 10. For that test case I didn't bother to make OTRS 6 actually work on MySQL 8.

I think before the release on OTOBO 10.0.7 we will test a couple more migration scenarios. But in the meantime you could grab the devel version of OTOBO and test whether the fix works for you.

**Comment by Wolverine80** [comment]
Looks good now with the changes. A test migration was successful.

**Comment by StefanRother-OTOBO** [comment]
Hi Wolverine80,

thanks very much for your help!

We release OTOBO 10.0.7 next week.

Have a nice day!

Stefan
Team OTOBO
