### ISSUE TITLE
MigrateFromOTRS: migrate database using the commands mysqldump and mysql

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#644]
In #534 an migration strategy was implemented that relied on moving table between database schemas using "ALTER TABLiE ... RENAME TO ...". This seemed to work in the considered case. However the considered cased is the well behaved cased where there are just about no differences between the source and the target schema. In real migrations there are problems when some of the attributes types have diverged. This divergence causes that some foreign key relationships can't be recreated during the migration process.

See also #575.

An example:

In a regular OTRS 6 or OTOBO 10 Installation:
```
CREATE TABLE auto_response ( 
  id smallint(6) NOT NULL AUTO_INCREMENT,
```
At the customers site:
```
CREATE TABLE auto_response ( 
  id INTEGER NOT NULL AUTO_INCREMENT, 
```
Leads to the error:
`errno: 150 "Foreign key constraint is incorrectly formed"`

Probably depending on the order in which the tables are migrated these error can occur when renaming the table or when re-adding foreign key constraints.

The suspicion is that these kind of errors might also occur with other migration strategies.

This problem was discussed by @StefanRother-OTOBO  and @bschmalhofer . The conclusion was to abolish the 'RENAME TO' solution and to provide support for a database  migration strategy based on mysqldump, sed, and mysql.

TODO:

- [x] Make the OTOBODatabaseMigrate step in migration.pl optional
- [ ] Provide instructions and enhance _scripts/backup.pl_ for a direct database migration
- [x] consider charset changed to utf8mb4
- [x] avoid double replacements of the the charset
- [ ] rename the database to the DatabaseName from _Kernel/Config.pm_
- [x] consider skipped tables, maybe checking foreign key relationship of these tables
- [x] consider renamed tables
- [x] consider  InnodB max key size in MySQL 5.6 or earlier: 191 = int( 767 / 4 )
- [x] don't consider DirectBlob conversion
- [x] don't check for concurrent migrations
- [x] don't limit to Docker based installations
- [x] no thorough check of the migrated schema
- [x] no support for restarting interrupted migrations
- [x] do not reset auto increment fields, as this is not neccessary for MySQL
- [x] allow to skip Database copy in migration.pl

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO 
I have addrf the generation of the SQL scripts to _scripts/backup.pl_ . The changes is available in the pull request #645.
Using backup.pl means that currently it is expected that an OTOBO installation is available and that the OTRS database is reachable from there. This is purely for convenience, as standalone script could do the job as well.

For testing I have called something like that:

```
scripts/backup.pl -t migratefromotrs --db-name homebernharddeve --db-host=127.0.0.1 --db-user homebernharddeve --db-password=homebernharddeve
docker exec -i otobo_db_1 mysql -u root -potobo_root < homebernharddeve_schema_varchar_191.sql
docker exec -i otobo_db_1 mysql -u root -potobo_root < homebernharddeve_data.sql
docker exec -it otobo_db_1 mysql -u root -potobo_root
docker exec -i otobo_db_1 mysql -u root -potobo_root < homebernharddeve_fixup.sql

```
More testing is required. I only did a sanity check, whether the SQL script can be executed.

Documentation is missing too.

**Comment by bschmalhofer** [comment]
It's not obvious whether the problem with foreign key checks are avoided with this approach. Testing is needed.
Perhaps all tables need to be dropped first, before they are recreated.

**Comment by bschmalhofer** [comment]
If I understand https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_foreign_key_checks correctly, then disabling foreign key check does not prevent the 'error 150' from existing foreign keys. A workaround might be to drop all relevant tables beforehand. For that i added yet another SQL script.

Not that in case of errors, `show engine innodb status` can give useful info.

**Comment by bschmalhofer** [comment]
'sed' is now no longer used.
The target database name is now no longer in the SQL scripts.
The commands for the DB - migration are now something like:

```
scripts/backup.pl -t migratefromotrs --db-name homebernharddeve --db-host=127.0.0.1 --db-user homebernharddeve --db-password=homebernharddeve
docker exec -i otobo_db_1 mysql -u root -potobo_root otobo < 2020-11-23_17-41-56/homebernharddeve_pre.sql
docker exec -i otobo_db_1 mysql -u root -potobo_root otobo < 2020-11-23_17-41-56/homebernharddeve_schema_for_otobo.sql
docker exec -i otobo_db_1 mysql -u root -potobo_root otobo < 2020-11-23_17-41-56/homebernharddeve_data.sql
docker exec -i otobo_db_1 mysql -u root -potobo_root otobo < 2020-11-23_17-41-56/hhomebernharddeve_post.sql
```

**Comment by StefanRother-OTOBO** [comment]
We still need to revise the script backup.pl. Partly the call must be done with an =, partly without:

script/backup.pl -t migratefromotrs --db-name otrs --db-host=127.0.0.1 --db-user otrs --db-password=secret_otrs_password


Please also have a look at the documentary again. E.g. the call with maxallowedpackage is not properly documented and did not work in my test with the above command.

Thanks a lot!

Stefan

**Comment by wollmers** [comment]
IMHO `max-allowed-packet` could default to `64M` in `backup.pl`.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO The '=' is not needed. I have adapted the installation docs accordingly.

I propose to merge the current state of affairs into the rel-10_0 branch and proceed in the issues #648 and #649.

**Comment by svenoe** [comment]
@bschmalhofer - is my assumption correct, that the skipped tables from your check list in principle are already handled with ecbc9699031a1ffced0522f4efbe73b5264cc30a (or maybe even earlier; currently line 428 and 429 of backup.pl), and the point is just not checked, because of possible foreign keys stuff? I would ignore this then, for now. Those tables, from what I see, are standing pretty much on their own or only hold temporary data in the first place (logs, process ids,...). I think we can tackle this, if we start to encounter problems, and up until now I'm aware of none, concerning this.

**Comment by bschmalhofer** [comment]
@svenoe Exactly. The tables that should not be migrated are already taken into account by `backup.pl --backup-type=migratefromotrs`. But I didn't investigate table by table whether foreign key issues could arise. IMHO the best approach is to not worry about that now, but focus on doing some test migration with real live databases.

**Comment by svenoe** [comment]
Stefan will incorporate some instructions into the manual. Reading the db name out of the config would just result in instructions easier to copy paste, as I understand it. Nice to have, but this can be incorporated somewhen else, too.
