### ISSUE TITLE
MigrateFromOTRS: Provide dedicated skripts for dumping from OTRS and  importing to OTOBO

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#649]
It probably make sense to have a script that helps with importing the SQL-Dumps and SQL-Scripts from OTRS.
It also might make sense to provide a dedicated script that dumps the Data from OTRS. The feature is only in backup.pl because it seemed convenient when the feature was added.

@StefanRother-OTOBO : Do you have a suggestion what the most convenient workflow is?

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I think the manual migration is a expert function and we do not really a script like that at the moment. It would be nice yes, but I think I add a detailed description to our tutorial, thats fine too.

Thanks very much!

Stefan
