### ISSUE TITLE
Read-Only flag in CustomerCompany Map

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#65]
I had a strange setup with additional fields in CustomerCompany. In the config these were marked as readonly. Consequently the additional fields could not be changed. Because of a direkt update in the table customer_company different values were shown in the GUI as were in the table. When updating in the GUI the values from the GUI were inserted in the table.

My guess is that the readonly fields were still POST input fields. And all it takes to make these fields writable is to use a Browser extension that make ro input fields writable. IMHO this is a security bug.

**Comment by svenoe** [comment]
Confirmed. We have to introduce a server side check, probably in the module files.

**Comment by bschmalhofer** [comment]
The readonly flag was not checked in AdminCustomerCompany.pm. The solution is to pass the old values for the readonly values.

**Comment by bschmalhofer** [comment]
Tested with Firefox Webdevelopper 'Make Form Fields Writeable' . Looks good. Closing the issue.
