### ISSUE TITLE
QuickClose error when Article Option is active

### ISSUE THREAD

**Issue by Wolverine80** [RotherOSS/otobo#652]
Error
` Can't locate object method "ArticleCreate" via package "Kernel::System::Ticket::Article" at /opt/otobo/Kernel/Modules/AgentTicketZnuny4OTOBOQuickClose.pm line 89.\n`
when trying die QuickClose a ticket when the Option to create an article text is active. 

AgentTicketZnuny4OTOBOQuickClose.pm seem so call the wrong CreateArticle function. 

I changed a line in attached patch to make it work. I don't know if it's the right function though. #notaprogrammer

**Comment by Wolverine80** [comment]
Forgot the patch.

[AgentTicketZnuny4OTOBOQuickClose.pm AgentTicketZnuny4OTOBOQuickClose.pm.txt](https://github.com/RotherOSS/otobo/files/5615198/AgentTicketZnuny4OTOBOQuickClose.pm.AgentTicketZnuny4OTOBOQuickClose.pm.txt)

**Comment by svenoe** [comment]
Thanks Wolverine, I'll have a look at it!

**Comment by svenoe** [comment]
Implemented - thanks again.
