### ISSUE TITLE
Updating: remove files that are no longer in the new version

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#663]
Currently there are some DataTime test failures in the rel-10_0 branch. Needs to be investigated.

Test Summary Report
-------------------
/opt/otobo/scripts/test/DateTime/TimeStamp2SystemTime.t                                                   (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 11 tests but ran 1.
/opt/otobo/scripts/test/DateTime/WorkingTime.t                                                            (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
/opt/otobo/scripts/test/ObjectManager/Can.t                                                               (Wstat: 256 Tests: 784 Failed: 1)
  Failed test:  758
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/SysConfig/AgentSetting.t                                                 (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=955, Tests=55249, 1824 wallclock secs (11.02 usr  2.34 sys + 1158.84 cusr 126.47 csys = 1298.67 CPU)
Result: FAIL
ran tests for product OTOBO 10.0.x on host 17cf455480a5 .

**Comment by bschmalhofer** [comment]
The files _scripts/test/DateTime/TimeStamp2SystemTime.t_ and _scripts/test/DateTime/WorkingTime.t_ came from the previous OTOBO 10.1.x installation that was updated to 11.0.x. So, it's not surprising that the test scripts do not work.

A related case is _Kernel/cpan-lib/Selenium_ , which is removed in OTOBO 10.1.x.

The check which files were removed can be done with the help of the _ARCHIVE_ file. 

TODO:

- [ ] back up and remove the files that have been removed in the new version

**Comment by svenoe** [comment]
Stefan and I decided that this should usually not happen between different patch levels, so the priority is not so high.

**Comment by bschmalhofer** [comment]
Issues in triage are set to closed.

**Comment by bschmalhofer** [comment]
This will be handled on #5077
