### ISSUE TITLE
Testing: Selenium test use skin ivory, but that skin does not exist

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#678]
See the failing test in _scripts/test/Selenium/SysConfig/AgentSetting.t_ .
Providing a sample skin should resolve the issue.

**Comment by bschmalhofer** [comment]
Another instance is the skin **highcontrast** which is used in _scripts/test/Selenium/Agent/AgentTicketZoom.t_ .

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO : Why is there only the default skin in _var/httpd/htdocs/skins/Agent_ and in  _var/httpd/htdocs/skins/Customer_ ?  Especially a highcontrast skin would be good to have.

**Comment by svenoe** [comment]
Hi Bernhard,
with our changes to the agent interface, we disabled non standard skins. But you are right that enabling them at one point would be good.
Sven

**Comment by bschmalhofer** [comment]
See also #682.

**Comment by svenoe** [comment]
Is this test just about testing this skin? Then we could just skip it for the moment.

**Comment by wollmers** [comment]
@svenoe It just tests, that the skin selection/switch to another skin works. A manual test works. So no big risk to skip it at the moment.

Improvement could be to skip, if there is only one (the default) skin.

**Comment by svenoe** [comment]
Thanks Helmut - yes, ok, at least for the moment this is unimportant then and could be skipped, in my opinion.

**Comment by bschmalhofer** [comment]
For #682 some  test cases  were set to TODO because of this issue.

Test cases in the following scrips must be un-TODOed when this issue is resolved:

- [ ] _scripts/test/Selenium/Agent/AgentPreferences.t_
- [ ] _scripts/test/Selenium/Agent/AgentTickerZoom.t_ 
- [ ] _scripts/test/Selenium/SysConfig/AgentSetting.t_

**Comment by bschmalhofer** [comment]
There are no immediate plans to add skin. The existing test the depend on a skin are TODOed. Let's leave them in place, in case that skins will be added in future. Closing this issue.
