### ISSUE TITLE
Clarify status of OTOBOCommunity

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#681]
In the OTOBO source code and in the test scripts there are some references to OTOBOCommunity. In the original OTRS 6 Community Edition this was OTRSBusiness. 
What is the status of OTOBOCommunity? Can all references be removed?

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

OTOBO has no Community or Business version, I think this is simply a result of the search and replace from the fork.
I'm not sure if it's possible to remove all old OTRSBusiness stuff. Perhaps have a look which test is needed?

I would like to leave the code itself, because I'd like to implement some more business stuff.

@svenoe, what do you think?

Thanks,

Stefan

**Comment by svenoe** [comment]
Yes, this is the renaming of our scripts, quite probably everywhere it occurs. In our first migrations I searched for every instance of OTRS Business and threw out a lot of it, so a lot of what's left should be stuff which I either found interesting, or where I was unsure, and in the end every occurrence should be investigated separately.

We should tidy this up somewhen, but probably after 10.1 is done and we are thinking more about 11.0 features, I guess...

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO  As far as I see, the directory _Kernel/Config/Files/User_ is used in _Kernel/System/Web/InterfaceAgent.pm_ and in _Kernel/System/SysConfig/Base/OTOBOCommunity.pm_ . So is this, whatever it is, still supported in OTOBO ? Or is it an OTRS Business feature?  In the latter case, I would remove it for the 10.1 release.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO  clarified that user configs in  _Kernel/Config/Files/User_ is a rarely used, but potentially useful, feature. It won't be removed. Still, I think that moving the code into a module like _Kernel/System/SysConfig/UserSpecificSettings.pm_ would be a good idea. 
Note that support for user specific config is not implemented in `Kernel::Config` but in `Kernel::System::Web::InterfaceAgent`.

**Comment by bschmalhofer** [comment]
References to OTOBOSTORM and OTOBOCONTROL can be removed as well.

**Comment by bschmalhofer** [comment]
Removed a couple of places where OTOBOCommunity is mentioned. The remaining mention could be removed too, but this is not really required.
Still nice to have is splitting up _Kernel/System/SysConfig/Base/OTOBOCommunity.pm_  into _Kernel/System/SysConfig/Base/SettingHistory.pm_ and _Kernel/System/SysConfig/Base/UserSettings.pm_ .

**Comment by bschmalhofer** [comment]
_OTOBOCommunity.pm_ is broken up now. The test suite looks fine. Closing this issue.

**Comment by bschmalhofer** [comment]
Found another occurence:

> grep -r 'OTOBO Community' . | more
> ./Kernel/Output/HTML/Templates/Standard/AdminDynamicField.tt:                <h2>[% Translate("New OTOBO Community  Fields") | html %]</h2>

**Comment by bschmalhofer** [comment]
There are still a few instances of OTOBOCommunity in the SysConfig.

```
egrep -rl '00.{1}-OTOBOCommunity'
Kernel/Output/HTML/NavBar/AdminContactWD.pm
Kernel/Config/Files/ZZZAAuto.pm
Kernel/Config/Files/XML/Framework.xml
Kernel/Config/Files/XML/OTOBODynamicFields.xml
Kernel/Modules/AgentTicketZoom.pm

```
These could be cleaned up in rel-11_0.
