### ISSUE TITLE
Testing: Resolve remaining failures of Selenium tests

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#682]
Currently there are 103 failures from running the Selenium tests under Docker. These should be resolved. When fixing the test is too much effort, then skipping the test is fine too,

See also #175, #681, #678, #907, #909, #921, #929

**Comment by bschmalhofer** [comment]
Some fixes:

- mount /opt/otobo for the sample files
- Don't try to load Kernel::System::OTOBOCommunity

Current status: 89 test scripts failing

**Comment by wollmers** [comment]
Selenium tests of installed packages, e. g. FAQ, are not skipped and need adaption.

```
root@ubuntu:/opt/otobo-docker# grep -i 'selenium' prove_10.0.x_2020-12-28-101043.out
[...]

Can't call method "Get" on an undefined value at /opt/otobo/scripts/test/Selenium/Agent/AgentFAQAdd.t line 25.
[11:03:15] /opt/otobo/scripts/test/Selenium/Agent/AgentFAQAdd.t ........................................................ 
Can't call method "Get" on an undefined value at /opt/otobo/scripts/test/Selenium/Agent/AgentFAQCategory.t line 24.
[11:03:15] /opt/otobo/scripts/test/Selenium/Agent/AgentFAQCategory.t ................................................... 
Can't call method "Get" on an undefined value at /opt/otobo/scripts/test/Selenium/Agent/AgentFAQDelete.t line 24.

[...]
```

**Comment by bschmalhofer** [comment]
For window size issues the following link might be relevant:
https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification

**Comment by bschmalhofer** [comment]
There is still a problem with the mounted volume _/opt/otobo_ in the container otobo_selenium-chrome_1 . The sample files are in _/opt/otobo/scripts/test/sample_ , but they are not readable because of file  permissions.
```
seluser@709d1d3578b8:/$ ls -l /opt/otobo/scripts/test/sample/NotificationEvent/Export_Notification_Appointment_reminder_notification.yml
-rw-rw---- 1 1000 1000 8418 Sep 25 15:15 /opt/otobo/scripts/test/sample/NotificationEvent/Export_Notification_Appointment_reminder_notification.yml
seluser@709d1d3578b8:/$ id
uid=1200(seluser) gid=1201(seluser) groups=1201(seluser),27(sudo)
```
The following assumes that all required sample files are in  _scripts/test/sample_  and that the browser needs no other files from _/opt/otobo_ . Then a workaround could be to:

- create a dir /opt/otobo/scripts/test in the running container
- 'docker cp' the dir sample into the created dir

These actions would need to be redone when restarting the container.

An alternative would be to create yet another OTOBO specific Docker image that already includes _/opt/otobo/scripts/test/sample_.

**Comment by bschmalhofer** [comment]
Current status: 64 Selenium test scripts failing

**Comment by bschmalhofer** [comment]
Fixed login to the customer interface: 56 scripts still failing

**Comment by bschmalhofer** [comment]
Mühsam ernährt sich das Eichhörnchen: down to 54 test scripts failing

**Comment by bschmalhofer** [comment]
Worked on making the printed TAP more understandable. However the number of failed scripts is up to 58 now.

**Comment by bschmalhofer** [comment]
Fixed a problem with DragAndDrop(). But some failures are heisenbugs. So it was 59 failed scripts in the last run.

**Comment by bschmalhofer** [comment]
Fixed AgentLinkObject.t by adapting the offset from the top left.

**Comment by bschmalhofer** [comment]
Login in the customer.pl was broken again. 50 failing tests after fixing it.

**Comment by bschmalhofer** [comment]
Latest run: 49 failing test scripts

**Comment by bschmalhofer** [comment]
Latest run: 46 failing test scripts

**Comment by bschmalhofer** [comment]
Latest run: 44 failing test scripts

**Comment by bschmalhofer** [comment]
some more fixes: 42 failing test scripts

**Comment by bschmalhofer** [comment]
latest run: 40 failing test scripts

**Comment by bschmalhofer** [comment]
latest run: 38 failing test scripts

**Comment by bschmalhofer** [comment]
Current state:
- 38 scripts failing
- 5 scripts with TODO test cases
- unexpectedly succeeding: 1 of the 2 TODO cases in _scripts/test/Selenium/Agent/AgentSplitSelectionACL.t_

**Comment by bschmalhofer** [comment]
Fixed scripts/test/Selenium/Agent/AgentTicketProcessAttachment.t 
37 Selenium failures in the last run.

**Comment by bschmalhofer** [comment]
In the meantime there was more grinding away at the Selenium tests. Some simplification was done by #902. Down to 29 failing, and not TODO, test scripts.

**Comment by bschmalhofer** [comment]
Some more grinding, now down to 25 test script with failures, not considering TODO and SKIP.

**Comment by bschmalhofer** [comment]
Some strangeness when setting the ProcessID, failures up the 26.

**Comment by bschmalhofer** [comment]
Marked some tests as TODO, 21 failing scripts in the lates run

**Comment by bschmalhofer** [comment]
Latest run with 18 failing test scripts. Still a couple of sporadic failures and successes.

**Comment by bschmalhofer** [comment]
Let's close this epic issue. Three consecutive runs reported no failures. This does not mean that the Selenium test are all passing, just that the, maybe sporadically, failing tests are marked as TODO, and have an issue assigned.
