### ISSUE TITLE
Decide on handling of Kernel::System::Time

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#69]
We incorporated some packages which rely on Kernel::System::Time (or its former duplicate Kernel::System::ZnunyTime). In OTRS Kernel::System::Time is handled as legacy. In principle we are not bound to deprecate it, too, but with Kernel::System::DateTime being present, too, the current situation messy.

In my opinion, at some point we should probably add the missing functionality of Kernel::System::Time to Kernel::System::DateTime, and get rid of the former.

**Comment by bschmalhofer** [comment]
Sounds good to me.

**Comment by bschmalhofer** [comment]
@svenoe I aggree with porting the existing usage of `Kernel::System::Time` to `Kernel::System::DateTime`. Missing methods can be added to the DateTime object. If there are no objections from your side I'll start an issue-branch for the 10.1 release.

The only downside I see I that Kernel::System::Time would no longer be supported by *rpc.pl*.

**Comment by bschmalhofer** [comment]
The hard question is wheter Kernel::System::Time is used in other packages. However it safe to migrate away from Kernel::System::Time in OTOBO core.

**Comment by bschmalhofer** [comment]
After the migration of OTOBO modules one could put Kernel::System::Time into an OTOBO package. This could then be a required package for those packages that don't want to migrate to `Kernel::System::DateTime`.

**Comment by svenoe** [comment]
Kernel::System::Time will be removed in 11.0. It won't be used in core code until then, but stay for compatibility of third party packages. Two tasks remain open:

- [ ] Document this in the developers manual, when it is up.
- [x] Check for possible performance issues connected to Kernel::System::DateTime (Sven).

**Comment by bschmalhofer** [comment]
@svenoe I have opened separate issues for the remaining tasks. Do you still want to investigate performance issues? Or can Í close this issue?

**Comment by StefanRother-OTOBO** [comment]
No Performance issues. Close
