### ISSUE TITLE
Enable customer preferences

### ISSUE THREAD

**Issue by mo-azfar** [RotherOSS/otobo#693]
Accessing to customer.pl?Action=CustomerPreferences return inconvenience display 

![Capture](https://user-images.githubusercontent.com/62957738/103359761-724ba300-4af3-11eb-832a-5c421857503a.PNG)

**Comment by svenoe** [comment]
Hi Mohd,

this screen is not implemented, yet (there shouldn't be a link to it, we seemingly forgot to disable direct access, though). Eventually it would be good to make this available, though, I guess. Thanks for pointing it out,

Sven

**Comment by mo-azfar** [comment]
> Hi Mohd,
> 
> this screen is not implemented, yet (there shouldn't be a link to it, we seemingly forgot to disable direct access, though). Eventually it would be good to make this available, though, I guess. Thanks for pointing it out,
> 
> Sven

Hi Sven,

Thanks for the update..
Any way we can just access at least access only 'password update screen' and '2 FA secret key screen' at the moment?

As OTRS 6 CE is no longer pushing security update, my team are looking to move over to OTOBO.

**Comment by svenoe** [comment]
Hi Mohd,

not without some development, I fear. We will definitely reimplement this, I cannot make promises when it will happen, exactly, though. If you need it straight away, you can send us a message to hello@otobo.de to hire us, or if you have the capability, enhance OTOBO yourself (please open a pull request, if you do :) ).

Best regards, Sven

**Comment by bschmalhofer** [comment]
When CustomerPreferences is enabled, then the following test scripts should be reactivated too:

- [x] scripts/test/Selenium/Customer/CustomerPreferences.t
- [x] scripts/test/Selenium/Output/Preferences/Customer/Language.t
- [x] scripts/test/Selenium/Output/Preferences/Customer/Password.t
- [x] scripts/test/Selenium/Output/Preferences/Customer/TimeZone.t

**Comment by svenoe** [comment]
Should be fixed. Standard settings still need some overhaul, but that is true for the agent interface, too and will be done in a separate issue.

**Comment by bschmalhofer** [comment]
The is_displayed() test of CustomerPreferences.t can stay at TODO for now. The elements are enabled, just not visible on the screen.
The other TODO tests for #693 habe been un-TODOed.
