### ISSUE TITLE
CSS: menu can disappear

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo#695]
With many toolbar elements enabled in the agent interface, the menu can disappear on low window widths (e.g. 1025 pixels).

This is caused by the fixed height of the `Header` containing `ToolBar` of liquid size.

![Bildschirmfoto 2020-12-31 um 06 00 26](https://user-images.githubusercontent.com/1275557/103396019-30415200-4b31-11eb-961d-bcad3637b928.png)

**Comment by wollmers** [comment]
A possible solution could be 

- restrict the toolbar to 1 line
- scrollable toolbar
- fixed position of logo

**Comment by wollmers** [comment]
In responsive mode the toolbar should also be scrollable, or render in an usable way

![Bildschirmfoto 2020-12-31 um 06 52 00](https://user-images.githubusercontent.com/1275557/103396660-c0cd6180-4b34-11eb-8f64-4606184fcd11.png)

**Comment by StefanRother-OTOBO** [comment]
Fixed with our new Elasticsearch module.
