### ISSUE TITLE
Regenerate or remove scripts/database/*.sql

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#7]
The purpose of the SQL scripts in the dir _scripts/database_ is not obvious. For the installation, the .xml files in scripts/database are used.  I did not see where the .sql files are used. I also did not see a generation script, so they might have been updated manually.

- [ ] remove the .sql files in case they are not needed

- [ ] find are write a generation script in case that they are needed

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

thanks very much for your help.

The scripts you are looking for are otobo.Console.pl scripts:

 bin/otobo.Console.pl Dev::Tools::Database::XML2SQL     - Convert OTOBO database XML to SQL.
 bin/otobo.Console.pl Dev::Tools::Database::XMLExecute - Convert an OTOBO database XML file to SQL and execute it in the current database.

If we change the data model in OTOBO, we only need to change the xml files and create in the next step the sql files automatically for a new release.

Best regards,

Stefan

**Comment by svenoe** [comment]
Can be closed, I guess... :)
