### ISSUE TITLE
Fix SysConfig changes on package (un)install.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#704]
I am not 100% sure what the problem is, but at least sometimes installing or uninstalling packages breaks the current config. I noticed that after uninstalling one package (the FAQ, albeit on a very untidy test system of mine) didn't remove the package specific options (in this case breaking the system), I had to run Maint::Config::Rebuild --cleanup. Also we had the case now, where installing a package reset the SysConfig to a former state, changing one option manually fixed the rest.

The guess is, that this was introduced with 10.0.6, we are not sure though. This should be fixed asap, especially if it is a general thing. Unfortunately I have not yet a way to clearly reproduce this, so some investigation has to be done and maybe it is a false alarm...

**Comment by wollmers** [comment]
@svenoe Do you remember some details, e.g. patch level of OTOBO, patch level of FAQ, name of the config items, deployment history, command line history?

Otherwise it would be necessary to reengineer the requirements for install, uninstall, reinstall, update in detail and rework the test cases.

**Comment by svenoe** [comment]
For the test system, no, it's somewhere on the 10.0-branch, no specific release, but there are plenty of manual changes, so I wouldn't count this too much. The other system is otobo 10.0.6 on docker, migrated from otrs 6, with not much extra stuff installed. I'm certain that neither install nor uninstall were directly linked to the package itself, as the rebuild of the SysConfig happens independently of this, also the FAQ was uninstalled by then, and the other, installed package were mainly just two template files, nothing with bigger functionality.

Some playing around will definitely be necessary. If current systems normally do the installation/uninstallation part correctly (check for package specific or changed sysconfig-values), this would be a meaningful information, too, and then I had to get more specific.

**Comment by svenoe** [comment]
I did quite a lot of testing now with normal (de)installations with or without migration, I cannot reproduce it. I will close the issue for now, please inspect what exactly is the problem and try to understand what caused it and/or let me have a look, too, if anything like this happens again.
