### ISSUE TITLE
EventHandler for Kernel::System::User

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#72]
` Kernel::System::CustomerUser` handles registered event, but `Kernel::System::User` doesn't provide support for events. It might be useful to add that capability.

**Comment by svenoe** [comment]
In my opinion it can be added rather easily, as soon, as we have a reason, don't you think?

(It would be useful to have something like "suggestions", or "requests" as label for stuff like this...I will have a look at this somewhen.)

**Comment by bschmalhofer** [comment]
One use case is when the email or an agent changes which might break mappings that are based on the email.

**Comment by svenoe** [comment]
I would implement this as part of another feature, which is going to use this, but not before. (It shouldn't be too much work anyways.)
