### ISSUE TITLE
Suggestion: Expand list of required and recommended modules

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#73]
`List::MoreUtils` has many useful subroutines. It would be nice to be able these subs in framework and in extension code.

**Comment by bschmalhofer** [comment]
So let's think about a list. Module suggestions that are mentions in #449,#192, #380, and #402 have been removed from the original suggestions.

- [ ] Kavorka or Type::Params or Function::Parameters
- [ ] Type::Tiny provides Types::Standard and works together with Function::Parameters, already in _Kernel/cpan-lib_
- [ ] Module::Loader or Module::Load or Module::Runtime
- [ ] Regexp::Common
- [ ] Regexp::Grammars
- [ ] Data::Printer
- [ ] App::Fatpacker
- [ ] Sereal
- [ ] Memoize
- [ ] Hash::Merge, Hash::Util
- [ ] Task::OTRS
- [x] Sub::Override
- [x] DBIx::Class,  Declined as this change would be too big
- [ ] Role::Basic, Moo, Moose

**Comment by bschmalhofer** [comment]
I checked how Request Tracker handles CPAN dependencies. The relevant file is https://github.com/bestpractical/rt/blob/stable/sbin/rt-test-dependencies.in is comparable to bin/otobo.CheckModules.pl.  The difference is RT does not provide support for installing via the repository of the distro. The other difference is that RT calls cpanm directly, not via cpanfile as is possible in OTOBO.

**Comment by bschmalhofer** [comment]
`Const::Fast` was added for #255.

**Comment by svenoe** [comment]
I think we need to somehow estimate a), how often those modules would help with regards to OTOBO, and b), how big their influence on coding would be in those situations. I will go through your list and write my initial judgement to each, and maybe you could comment on that, Bernhard. Numbers are given from 1 (no) to 10 (very) frequent/helpful.

1. List::More/AllUtils - 2/5: Actually lists don't see much usage in OTOBO, I would say - maybe an any() here, or there...?
2. Const::Fast - 1/?: Not sure in which situations you want to use it. Is it important for #255? I would have guessed that that's maybe good, if you integrate it into your coding policy, but I would say that makes no sense for a project already this big.
3. Type::Params/Function::Parameters - ?/?: Principally I would be very much for incorporating signatures. Namely I would choose the named ones from Function::Parameters, as it aligns very well with the usual way methods are called in OTOBO. I don't know how ever how logging works with this; is there an easy way to still use Kernel::System::Log, if a method is called in a wrong way? I'm not so sure about Type::Params. Maybe incorporated into Kernel::System::VariableCheck to use eval to then be able to call Kernel::System::Log? I don't know...please tell us, how you see both used.
4. Type::Tiny - ?/?: Similar to 2. It would be quite a change in how OTOBO classes are built, so far... Is there a specific reason you want it?
5. Path::Class - 3/1: We are only on Linux, have some file handling in Kernel::System::Main, why would you want to use it?
6. Log::Log4perl - ?/?: Too big too fully read - I don't see Kernel::System::Log being replaced, it's present in almost every module. Is there a reason to build it into Kernel::System::Log?
7. Module::x - ?/?: I don't see Module::Loader, when would you want to search for a module, the other two maybe? But could please provide a significant example?
8. Syntax::Keyword::Try - 3/7: Looks nice. Is it stable? Any downsides? I mean it won't be used very often...
9. Regexp::Common - 2/3: Am I missing something?^^
10. Regexp::Grammar - ?/?: Looks mighty - can you please provide some OTOBO specific examples?
11. Data::Printer: Looks nice, too, I will use it. But I don't see it incorporated into OTOBO, it's useful only for development, and I can just install it locally and use it within my personal development process.
12. App::FatPacker: To provide a version of OTOBO "without any dependencies"?
13. Sereal: ?
14. Memoize: Too many caveats, in my opinion, and we have Kernel::System::Cache to do that sort of stuff (albeit manually, but still...).
15. Hash::Merge/Hash::Util: Both look potentially very useful. Not sure, though, how often one would run into situations where any of the functionality is needed. Do you have scenarios in mind?
16. Task::OTRS: Haha :) - not needed I guess, with the ability to write a cpanfile from CheckModules.
17. String::Dump: See 11.
18. Text::Trim - 4/2: Here it's really hard for me to decide. On the one hand, why not, it's small, clear, helps a bit sometimes,... On the other, I don't want to end up having to install 100+ libraries, when installing OTOBO. I'd like to hear Stefans opinion.
19. Sub::Override: I'm against Sub::Override, I think. At least against including it without a very thought out way on how to use it. I very much liked the way you used it for a package you wrote some time ago, but we already have the "Custom" directory to "override" modules, the Kernel/Autoload directory for specific subroutines, and for some modules, such as Kernel::System::Ticket, additional custom overrides can be installed and loaded via the SysConfig. I know that Sub::Override provides more flexibility in itself, but we have to really be careful, to keep things comprehensible. So for an OTOBO package I don't care so much, but for the Core, I don't know. At least I would like to talk about this a bit more.
20. DBIx::Class: This probably would deserve its own issue... Can you provide some main reason, why you think we should incorporate it?
21. Teststuff: This should be discussed after or together with setting up our CI.
22. SQL::Interp: Could be nice, yes - would like to hear Stefans opinion.
23. Email::Stuffer: Don't understand where you would want to use this. To replace something of Kernel::System::Email?
24. Object oriented stuff: Let's discuss this, when we meet somewhen, I suggest.

**Comment by bschmalhofer** [comment]
`Log::Log4perl`gives a great amount of flexibility but is a major undertaking. This deserves its own issue.

**Comment by bschmalhofer** [comment]
This issue is a hodgepodge of different issues. Some are about adding utilitiy modules, some are about changing the archtecture of OTOBO. Let's collect the list of small utility modules and manage them in a separate issue.

**Comment by bschmalhofer** [comment]
I shortened the list, as there is now #449 and other related issues.

**Comment by bschmalhofer** [comment]
The list is too mixed. The better approach is to open an issue for each module that is proposed to be added. For `Sub::Override` I added #573 . This other modules are not pressing right now. Closing this issue.

**Comment by bschmalhofer** [comment]
See also #1406.
