### ISSUE TITLE
Make Fred available on Github

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#731]
Fred, https://github.com/OTRS/Fred/tree/master/Kernel, is neat. It might even work with OTOBO, or could easily be ported to OTOBO. Bit it works AFAIK with an output filter and thus makes no use of the nifty Plack middlewares. So let's either port Fred to middlewares or creater a more shiny replacement.

**Comment by svenoe** [comment]
We have Fred already as package for otobo - I seemingly have not added it to github yet, though. I will do this. (You can install it via the package manager from the otobo addons.)

**Comment by bschmalhofer** [comment]
Fred would also be a good test case in case #737 will be implemented.

**Comment by svenoe** [comment]
I added it: https://github.com/RotherOSS/fred
