### ISSUE TITLE
Decide about Kernel::Output::HTML::Notification::AgentSessionLimit

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#734]
As of OTOBO 10.0.7 the notification Kernel::Output::HTML::Notification::AgentSessionLimit is only a stub. In OTRS this notification is presented when the session limit is approached. As OTOBO has no session limit I would surmise that this notification is not needed in OTOBO. @StefanRother-OTOBO: Is that correct?

When no session limit checks are needed, then it should be decided whether this notification should be kept for just in case, or removed completely.

TODO:

- [x] decide and act accordingly
- [x] fix or remove the TODO test in _scripts/test/Selenium/Agent/Login.t_

**Comment by svenoe** [comment]
I think we can remove it. In the end the code is not lost as it's in git. There is no need for keeping it "just in case".

**Comment by bschmalhofer** [comment]
Ah, I just found out that there still is a session limit in OTOBO. See _Framework.xml_:

```
    <Setting Name="AgentSessionLimit" Required="0" Valid="1">
        <Description Translatable="1">Sets the maximum number of active agents within the timespan defined in SessionMaxIdleTime.</Description>
        <Navigation>Core::Session</Navigation>
        <Value>
            <Item ValueType="String" ValueRegex="^[0-9]{1,8}$">100</Item>
        </Value>
    </Setting>
```
The relevant check is in _Kernel/System/AuthSession.pm_ . Now tthis is a bit inconsistent. When there is a session limit, then a notification that the limit is approaching does make sense. Or should the agent session limit feature be also removed from OTOBO?

**Comment by bschmalhofer** [comment]
Discussed this with @svenoe  and @StefanRother-OTOBO . The conclusion is:

- The agent session check will be kept as currently set up, currently the limit is 100 sessions
- The notification that the limit is approaching will reactivated,

**Comment by bschmalhofer** [comment]
Started to reintegrate the config, tests and implementation of the notification module.

**Comment by bschmalhofer** [comment]
Tests look fine. Closing this issue.
