### ISSUE TITLE
Update the copyright year

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#740]
The customer footer. _./Kernel/Output/HTML/Templates/Standard/CustomerFooter.tt_ is still in 2020.

Is the year really needed for the copyright message? It would be nice if the yearly update were not needed.

**Comment by svenoe** [comment]
Ah...I forgot this in the latest release... I assume it is necessary, at least in the headers of all files, so I guess it doesn't make a significant difference whether we include the footer or not...
