### ISSUE TITLE
Formatting and links in Dashboard Plaintext Tile

### ISSUE THREAD

**Issue by GritRother-OTOBO** [RotherOSS/otobo#744]
An option to format text in the plaintext dashboard tile (line breaks, esp.) and to insert links would be great

**Comment by bschmalhofer** [comment]
Sorry, the above commits are actually for #755.

**Comment by bschmalhofer** [comment]
Instead of enhancing the Plaintext tile I suggest to add a markdown tile. This adds flexibility and might reduce the danger of allowing arbitrary HTML.

**Comment by bschmalhofer** [comment]
@GritRother-OTOBO  Is this still relevant? If so I'll file it as being in the wishlist.

**Comment by svenoe** [comment]
Will be less relevant with the addition of the CustomerDashboard InfoTile
