### ISSUE TITLE
Avoid magic number 1 for determining the super user

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#745]
In _Kernel/System/Ticket/TicketACL.pm_ there is a check for the super user:

`   return if $Param{UserID} && $Param{UserID} == 1;
`
The constant 1 is very magic. I propose to add a method  `Kernel::System::User::IsSuperUser()` that does this check.
This should make it easier to see where the super user is special cased.

**Comment by svenoe** [comment]
This would probably be cleaner for a new program, but I think in OTOBO we will not get rid of the 1. It is commonly used to call subroutines with super user rights (every call of TicketSearch, for example, is done with `UserID => 1,` to indicate that all respective Tickets should be returned, etc.). Changing the check, but not the call is pointless in my opinion, and we cannot get around this, without major effort and incompatibility issues with packages,...

If you don't have objections, I think we can close this issue.

**Comment by bschmalhofer** [comment]
I propose to leave it open and at least provide the possibility to do it in a cleaner way:

- a check function that checks for UserID == 1
- a constant $SUPER_USER_ID that has the value 1 and can be used for the calls.

IMHO, it's not absolutely necessary that all code it converted at once,
