### ISSUE TITLE
SeleniumTesting: fix TODO tests for setting Owner, Responsible, State 

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#748]
In _scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketFreeText.t_ some tests are commented out because Selenium could not perform the action. This manifested itself in a time out. The relevant lines start on line 395.

My impression is that for these fields there are extra JS callbacks that prevent setting the fields Owner, Responsible, and State to an empty value. I suppose that this functionality is as intended and that only the test scripts should be enhanced to handle that case.

**Comment by bschmalhofer** [comment]
The timeouts still occur, but not consistently at the same changes. The cause is not clear. Probably not related to problems with changing the config settings.

**Comment by bschmalhofer** [comment]
Still some TODO tests in scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketFreeText.t

**Comment by bschmalhofer** [comment]
I still don't understand what is going on. Still looks like the selection list  .InputField_ListContainer is not removed when an input field is set.
Refactored the test script a little but, such that tests are reorganized in subtests.

**Comment by stefanhaerter** [comment]
Done with commit e6abd29edd3937c164d32ed2c4a9dd058bd9b3f7 for issue #3100.

Closing the issue.

**Comment by bschmalhofer** [comment]
Set the milestone to OTOBO 11.0.3, the first patch level release that contained the patch,
