### ISSUE TITLE
Implement CustomerPreferences

### ISSUE THREAD

**Issue by joserribeiro26** [RotherOSS/otobo#750]
Hi,
We noticed here a problem with the CustomerPreferences Layout.

Below the image with the broken Layout, today also does not appear in the list of side menu.

![image](https://user-images.githubusercontent.com/475022/105395394-7011cb80-5bfd-11eb-93cc-9d809d58a8f8.png)

**Comment by svenoe** [comment]
Hi José,

thanks for pointing it out. We are aware of this, we have not yet included it to OTOBO (actually there shouldn't be a way to reach the site without directly accessing it via the browser, we should have really disabled it completely). It definitely will be fully implemented though.

Sven

**Comment by svenoe** [comment]
When implementing this, also take care of https://github.com/RotherOSS/otobo/issues/779.

**Comment by svenoe** [comment]
This has been done in #693 (without the repairing of the password changes #779 though).
