### ISSUE TITLE
Align AgentTicketPhone and AgentTicketEmail

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#755]
I noticed this when looking at #632 . The frontend modules AgentTicketPhone and AgentTicketEmail are fairly similar. This means that a fix in either module should ofter also be applied in the other module. However, it is kind of hard to see the real differences in the behavior, at there are unneeded divergences in the code.

- [x] align the code of these modules, without function changes

**Comment by svenoe** [comment]
In principle I agree, but I think we should think about this on a larger scale to be honest. This holds true for AgentTicketPhone, -Email, -ActionCommon, -PhoneCommon,... All those ticket masks only differ in some minor functionality but their code is totally nonuniform.

In my opinion we should really think about maybe having an AgentTicketBase or so as parent and then just have individual constructors, probably special methods to handle the submitted form (most differences are here, I guess), etc. So I'm not sure whether it's a good time investment to just align the code of -Email and -Phone, now.

**Comment by bschmalhofer** [comment]
Ah, I messed up the commit messages and noticed only after merging the PR. The changes for #755 were annotated as being for #744. 
Manual testing looked fine, including the link on AgentCustomerInformationCenter.
So, let's close this issue anyways.
