### ISSUE TITLE
Elasticsearch missing after migration

### ISSUE THREAD

**Issue by frankii91** [RotherOSS/otobo#765]
The missing Elasticsearch after migration disappeared from the panel and it is not possible to search.
How do I get him back?

**Comment by svenoe** [comment]
Hi frankii91,

did you use OTOBO 10.0.7 for the migration? And what exactly is missing? If you go to Admin->Webservices, is the Elasticsearch webservice still there?

Sven

**Comment by frankii91** [comment]
Last stable release from yesterday, migration disables elasticsarch.

But today I found a solution:
must be enabled in the otobo system configuration

Elasticsearch :: Active
and
Frontend :: Module ### AgentElasticsearchQuickResult

However, you have to test it and it is best to add it to the migration instructions

**Comment by svenoe** [comment]
Yes, the activation of Elasticsearch is not done automatically after migration, at the moment. I've added issue #770 which proposes this enhancement.

**Comment by frankii91** [comment]
One small piece of information is missing from the installation documentation
that you should add elastic to systemd to start after restarting the server, most of you may know about it, but the default installation does not add this option to the autostart.

sudo systemctl enable elasticsearch

**Comment by frankii91** [comment]
When the elasticsearch daemon is not running
there are error_log apacha logs but on the agent's site the plugin is active but it doesn't search and the agent doesn't know that something is wrong.
It would be nice if there was a message for the agent, or a mail to the system administrator, preferably both.
