### ISSUE TITLE
Clean up direct usage of '/opt/otobo'

### ISSUE THREAD

**Issue by frankii91** [RotherOSS/otobo#766]
Edit by @svenoe - There are some instances of direct usage of /opt/otobo instead of $ConfigObject->Get('Home'), mostly in the migration routines. This should be replaced.

---
You might think to make it easier to run / install in a directory other than the default (/ opt / otobo) = this should be configured before installing. one script would be enough to determine this folder, manual change is quite time consuming and many files. Especially useful if someone uses Plesk

**Comment by svenoe** [comment]
Hi frankii91,

this is easily doable by changing `$Self->{Home} = '/opt/otobo';` to something else in the Config.pm for normal installations. To change the path within docker might be a bit more tricky, I haven't tried this, to be honest, but is this really necessary? For Plesk specific customizations please see https://github.com/RotherOSS/otobo/issues/767#issuecomment-771469004 also.

Sven

**Comment by frankii91** [comment]
np.
$ Self -> {Home} = '/ opt / otobo';
This is not enough, in many files there is '/ opt / otobo' hard and must be edited ...
e.g.

find -type f -exec grep -q '/opt/otobo' {} \; -print
find -type f -exec grep -q '$HOME' {} \; -print

and others because in some files e.g. cron there is $ HOME not mentioning tests etc.
Additionally, in a large part of the comments, translations ...
There is also a lot of "trash" OTRS ....

It doesn't really matter in docker, but who knows ...

**Comment by svenoe** [comment]
You are right. Although most are examples and translations, especially in the migration routines there are some occurrences which have to be replaced. Thanks for pointing it out. :)

**Comment by niccord** [comment]
I think this can be closed, what do you think?

**Comment by svenoe** [comment]
Yes, I don't see it anywhere anymore (except in the pods).
