### ISSUE TITLE
Sendmail binary in OTOBO daemon docker image missing

### ISSUE THREAD

**Issue by rbr101** [RotherOSS/otobo#768]
I'm porting OTOBO docker to kubernetes, and everything seems to run fine except sending mails because the sendmail binary is missing in the daemon docker image. Is this related to to my conversion or is this also the case with the docker-compose installation? 

-->
ERROR: OTOBO-otobo.Console.pl-Maint::Email::MailQueue-76 Perl: 5.32.0 OS: linux Time: Wed Feb 3 10:30:20 2021
Message: CommunicationLog(ID:16,AccountType:-,AccountID:-,Direction:Outgoing,Transport:Email,ObjectLogType:Message,ObjectLogID:16)::Kernel::System::MailQueue => Temporary problem returned from server, requeuing message for sending. Message: SMTPCode: -, ErrorMessage: No such binary: /usr/sbin/sendmail!

**Comment by rbr101** [comment]
Ok, the option SystemConfig->SendMailModule -> Kernel::System::Email::SMTP should be used.
By default sendmail is enabled resulting in the error. Change the above setting and it will work.

**Comment by bschmalhofer** [comment]
@rbr101 Cool, very nice to see than people are running OTOBO in kubernetes. Glad to learn that it is, mostly, working.
