### ISSUE TITLE
Implement automatic activation of Elasticsearch for migration.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#770]
This can more or less be copied from the installation process.

**Comment by bschmalhofer** [comment]
Activating Elasticsearch when it is available does make sense for the migration. But for that we need to query the correct host, whether the Elasticsearch is running there. Up to now, only localhost is assumed to be the host. But in the Docker case the host elastic is actually used.

**Comment by bschmalhofer** [comment]
Added the setup for the SysConfig. Added support for host 'elastic' when running under Docker.
Did a testmigration from OTRS 6 (on Docker host, PostgreSQL) to OTOBO 10 (in Docker, MySQL) and the result looked fine. Not closing yet, as having a couple more test migrations would be nice to have.

- [x] more testmigrations

**Comment by bschmalhofer** [comment]
Took a look at the latest test migration. Frontend::Module###AgentElasticsearchQuickResult and Elasticsearch::Active are both enabled. Looking good. Closing this issue.
