### ISSUE TITLE
Update buggy JavaScript::Minifier to version 1.16

### ISSUE THREAD

**Issue by ymyasoedov** [RotherOSS/otobo#771]
JavaScript::Minifier 1.14 has some problem that has been found in https://github.com/znuny/Znuny/issues/6 (it is corrupting some JS code). There is also alternative package JavaScript::Minifier::XS, that could be used instead of JavaScript::Minifier. Znuny will use JavaScript::Minifier::XS and CSS::Minifier::XS if they are installed on system.

**Comment by svenoe** [comment]
Hi Yuri,

thanks very much for the note. We will definitely incorporate the relevant bugfixes of the Znuny team in general.

Sven

**Comment by svenoe** [comment]
To me it looks like this was related to CKEditor 4.15.1 and does not occur with 4.16.0. We should consider switching to the XS versions anyways, I guess. I will postpone it to 10.0.9 though.

**Comment by bschmalhofer** [comment]
There is now JavaScript::Minfier with more fixes. See https://github.com/zoffixznet/JavaScript-Minifier/pull/12. I think that this can safely be rolled out with OTOBO 10.0.13.

**Comment by bschmalhofer** [comment]
Updated the Perl module. Did a quick test whether the UI still works. Merged the PR. 
See #1197 about a possible switch to JavaScript::Minifier::XS. Closing this issue.
