### ISSUE TITLE
Question: Sending e-mails, sendmail cofniguration more than one e-mail

### ISSUE THREAD

**Issue by frankii91** [RotherOSS/otobo#782]
I have worked at otrs for many years but never tried to implement sending from several different queue-dependent emails but in a different domain.

You can sign multiple incoming addresses and download them mailae to different queues

Currently it is possible to add a sending email to the queue and new / replied tickets are sent from this email.

But missing:
- outgoing SMTP server settings more than 1 and assigning to the outgoing address, I do not understand why the outgoing mail server configuration is not at the address (AdminSystemAddress)

The current configuration allows sending from multiple addresses, even though the address is in a different domain, however, there are problems with anti-spam filters.

Despite the correct DNS configuration of the MX record, e.g. gmail treats it as spam and an spoofing attempt.

The email headers contain a lot of information that they probably shouldn't, not to mention the address / domain / ip otobo that they shouldn't contain for security reasons (if we're hiding behind e.g. cloudflare)

My proposal is to move the outgoing mail server configuration to the email address settings. Along with configuring the name of the sending system, etc. (what's in the email headers)

Unless there is another way to do it and I don't know it and can't find it?

**Comment by wollmers** [comment]
> But missing:
> 
> * outgoing SMTP server settings more than 1 and assigning to the outgoing address, I do not understand why the outgoing mail server configuration is not at the address (AdminSystemAddress)
> 
> The current configuration allows sending from multiple addresses, even though the address is in a different domain, however, there are problems with anti-spam filters.

That's a configuration problem of the relaying SMTP server. Well configured, a SMTP server can send mail for multiple domains. 

Using authenticated SMTP is more flexible. 

> Despite the correct DNS configuration of the MX record, e.g. gmail treats it as spam and an spoofing attempt.

Again a configuration problem of the sending SMTP. Most receiving SMTP servers check basic things like MX, SPF, reverse DNS and HELO.

Some big players do other questionable filtering. Gmail e.g. rejects mail, if a rate limit is reached.

> The email headers contain a lot of information that they probably shouldn't, not to mention the address / domain / ip otobo that they shouldn't contain for security reasons (if we're hiding behind e.g. cloudflare)

Again, most of the headers come from mail transport. Needs configuration there.

**Comment by StefanRother-OTOBO** [comment]
Hi,

Perl Services build a package for this behavior at https://otopar.perl-services.de/package/download/1655

Best wishes from Germany!

Stefan
Team OTOBO

**Comment by frankii91** [comment]
I will be great to update it then I will check it.
