### ISSUE TITLE
Improvement: Signature and Salutation depending on queues

### ISSUE THREAD

**Issue by frankii91** [RotherOSS/otobo#783]
Suggestion for improvement:
There is something like:
AdminTemplate
and is AdminQueueTemplates
this allows you to associate templates with queues, but this option is missing for signatures and salution

is
AdminSignature and AdminSalutation

The proposal to add the possibility of assigning signatures and salution to queues. (AdminSignatureTemplates and AdminSalutationTemplates)

**Comment by StefanRother-OTOBO** [comment]
Hi Frankii,

sorry for the late answer. It's possible to add the salutation and signature directly at AdminQueue.

Best wishes from Germany!

Stefan
