### ISSUE TITLE
Provide templates for issue creation in GitLab

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#784]
Github seems to provide templates for creating new issues. Not sure whether POST forms are supported.
See https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository and https://stackoverflow.com/questions/34146618/pre-populate-the-github-new-issue-form-using-the-querystring and http://ez34.net/2016/12/publish-anonymous-issues-on-github.html .

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/412#issuecomment-751487899_

**Comment by bschmalhofer** [comment]
The same is nice to have for GitLab.

**Comment by stefanhaerter** [comment]
I suggest to close the issue as we do now have issue templates in GitHub.
