### ISSUE TITLE
Problem with SecureMode

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#789]
During testing @svenoe ran into a problematic case. The sequence of events is something like:

1. Clear the _/opt/otobo/_ volume and the database with `docker-compose down -v`
2. Configure devel-rel-10_0 in _.env_ with `./scripts/devel/generate_dot_env.sh --template dot_env.m4 --repository rotheross --tag devel-rel-10_0`
3. Enable HTTP in .env: COMPOSE_FILE=docker-compose/otobo-base.yml:docker-compose/otobo-override-http.yml
3. Start otobo with the devel-rel-10_0 images: `docker-compose up -d`
4. Run installer.pl, end up with  SecureMode = 1  in _Kernel/Config/Files/ZZZAAuto.pm_
5. Configure SecureMode = 0 in SysConfig via the admin GUI, end up with SecureMode = 0 in _Kernel/Config/Files/ZZZAAuto.pm_
6. Run migration.pl
7. Get an error:

```
Ein Fehler ist aufgetreten

SecureMode ist aktiv!

If you want to re-run migration.pl, then disable the SecureMode in the SysConfig. 
```

**Comment by bschmalhofer** [comment]
The cause for this bad outcome could be that _ZZZAAuto.pm_ is not read in by the webserver even though it has been changed on the file system. In other words, the Plack middleware `$RefreshZZZAAutoMiddleWare` did not do their job in _bin/psgi-bin/otobo.psgi_ . 

Maybe `%Module::Refresh::Cache`was not initialised in the process running migration.pl. Maybe the order of  `$RefreshZZZAAutoMiddleWare`  and `Plack::Middleware::Refresh` is incorrect.

**Comment by bschmalhofer** [comment]
I still don't really understand what is going on. My current understanding of the problem is:

1. It is assumed that everything happens within 10s, so that the reloading from Plack::Middleware::Refresh does not kick in.
2. It is assumed that everything happens within one process.
2. otobo.psgi starts, `%Module::Refresh::Cache` is initialized but ZZZAAuto.pm is not yet in %INC, and therefore not in %CACHE
3. Kernel::Config::Defaults->new() is called, but there is no ZZZAAuto,.pm yet
4. installer.pm creates a ZZZAuto.pm, SecureMode=1, the module is loaded
5. The SysConfig changes ZZZAuto.pm, but ZZZAuto still not in %CACHE 
6. migration.pl is called, but ZZZAAuto,pm is not reloaded because it is not in %CACHE
7. migration.pl emits error, because SecureMode is still 1

@svenoe , I have pushed a change that tries to alleviates 6.
But not sure whether this is the correct understanding, as AFAIK there is no warning about SecureModed in the Agent Interface.

**Comment by svenoe** [comment]
Doesn't solve the issue. I really don't understand it, either. I fiddled around with Kernel/cpan-lib/Module/Refresh.pm and looked what happened during refresh_module_if_modified, and when I produced this funny state, ZZZAAuto already always was in `%CACHE` (and `%INC`), and mtime was the same as the cached one, so nothing was done, always. To my understanding this is the state when you load a module, then change it on file level, and only then add it to `%CACHE`. What I do not understand with this though is, that this state is not persistent. You then should have the wrong module loaded until an unload comes from somewhere else, and starting then, it should always be the right one. But with multiple reloads of the page you sometimes get one version, sometimes the other, and I don't understand how two versions of the same module can exist. (The only thing which comes to my mind with this, is, that we have `/opt/otobo/bin/mojo-bin/../../` as well as `/opt/otobo/bin/psgi-bin/../../` in `@INC`. But it points to the same file, and I am not aware of it being used as Hash-Key, or so, anywhere.

In any case, what works for me, is to just replace `refresh_module_if_modified` with a `refresh_module` in `$RefreshZZZAAutoMiddleWare` in otobo.psgi. This is a small potential overhead, but we can use it for now and think about a nicer solution the next days. (We should check whether it is present in %INC and only execute it, if true, else there will be a warning. Interestingly with this my "Wait till the SysConfig is updated"-message in index.pl?Action=AdminSystemConfiguration which is present for a little time atm disappears, too. I will think and look a bit more, and then push this, if I don't have better ideas.)

**Comment by svenoe** [comment]
I set this to 10.0 - I think we should talk about this somewhen before deciding on how it should finally look.

**Comment by bschmalhofer** [comment]
When discussing this we should not forget ZZZACL.pm and ZZZProcessManagement.pm

**Comment by bschmalhofer** [comment]
I have looked at the source code of Module::Refresh::refresh_module_if_modified(), https://metacpan.org/release/Module-Refresh/source/lib/Module/Refresh.pm. The modules are not reloaded when they were not in the cache in the first time. I suppose that's the root cause of the problems. So, let's investigate where these _*.pm_ files are loaded and how to guarantee that they are reloaded.

**Comment by bschmalhofer** [comment]
Apparently the commit 7fb462d has fixed the issues with SecureMode.
However there are at least two concerns:

- Constantly reloading ZZZAAuto.pm is not elegant, not sure whether it is a noticable performance hit
- There are other Kernel/Config/File/ZZZ*.pm files which must also reliably be reloaded. The lack of reloading might be related to TODO failure in the Selenium tests

So, lets close this issue and open a new issue for the improvements.
