### ISSUE TITLE
Bug in bin/otobo.CheckModules.pl

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#79]
If I use the script Otobo.CheckModules.pl -list under ubuntu 18.04, I get the following output:

apt-get install -y DateTime::TimeZone libdatetime-perl libdbi-perl libnet-dns-perl libtemplate-perl libtemplate-perl libxml-libxml-perl libyaml-libyaml-perl

- [ ] Fix "DateTime::TimeZone" it´s not possible here. 

- [x] And if anyone changes it, please adjust -help setting. The description includes all commands with a - (example: -list), but --list also works. I would just change the description to be standard compatible.

- [x] My suggestion is, that the command otobo.CheckModules.pl opens the help page.

- [x] A categorization of the modules during output would be helpful to see what I really need.

Thanks!

Stefan

**Comment by svenoe** [comment]
Have not encountered the DateTime::TimeZone. But quite some changes were made. Please reopen separately, if it still occurs.
