### ISSUE TITLE
Define CKEditor Plugins which should be used.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#790]
With the latest update of CKEditor the Znuny team added some plugins of which I in a first step will disable exportpdf, because it is not configured properly and throws an [error](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#exportpdf-no-token-url), and secondly elementspath, which shows in which element (from a html perspective) we are when writing text etc. - this could be nice, but is probably not needed in most cases, and might be unwanted, too.

We should think about which plugins exactly are needed, build CKE just with those, and maybe think about enabling additional stuff via the SysConfig.

**Comment by bschmalhofer** [comment]
Moved this to the wishlist as it is not certain that this should be part of patch release

**Comment by bschmalhofer** [comment]
Moved to milestone to OTOBO 10.0.20 as this issue was superseeded by #2963 .
