### ISSUE TITLE
Access denied when trying to initially connect

### ISSUE THREAD

**Issue by rkarlsba** [RotherOSS/otobo#802]
After installing with new docker-compose, 1.28.2, on docker 20.10.3, all seems to work, but when I try to connect to the server in a web browser, I get this

An Error Occurred

Access denied for user 'otobo'@'172.19.0.5' (using password: YES)

As far as I can understand, this error message is from mariadb. I have set a root password in .env, otherwise, nothing special. Anything that should be done here? Can't find any clues in the docs.

This is also reported here https://github.com/RotherOSS/otobo-docker/issues/45

Please close whatever bug that is irrelevant, but one of them is clearly relevant

**Comment by svenoe** [comment]
Hi Roy,

I can not confirm this behaviour. I just updated to the same versions of docker and docker-compose, and it works for me. Have you called otobo/installer.pl before otobo/index.pl? If you have done everything according to the [instructions](https://doc.otobo.org/manual/installation/stable/en/content/installation-docker.html), maybe you did a reinstall and didn't properly clean up your system? If you do not have anything important in any container or volume on the system, you could completely reset everything (**careful - all data will be removed!**):
```
docker-compose down -v
docker system prune -a
docker system prune --volumes
```

**Comment by M1NTI** [comment]
You have to open http://localhost/otobo/installer.pl first
