### ISSUE TITLE
installer.pl should warn about unsupported database version

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#81]
A version check of the database would be nice to have.

**Comment by stefanhaerter** [comment]
Could the get_info method be of use here? https://metacpan.org/pod/DBI#get_info
As far as I understand the code, the version check could be placed in Kernel/Modules/Installer.pm, function CheckDBRequirements. Is this correct?

**Comment by bschmalhofer** [comment]
Yes, using a database driver independent method sounds like a good idea. In case that doesn't suffice there are also driver specific methods and attributes, like https://metacpan.org/pod/DBD::mysql#Private-MetaData-Methods.

CheckDBRequirements() looks like a good place where this check can be added.

**Comment by stefanhaerter** [comment]
In a post from perlmonks it was stated that the get_info method was (only?) for OCDB. The post origins from 2010, so I hope that the method was adapted to other database drivers in the meantime. I will research for further information on this possibility.

**Comment by bschmalhofer** [comment]
This is an old issue but still desirable. I propose to finally implement it for OTOBO 11.0.   Using the approach taken by @daxim in https://github.com/RotherOSS/otobo/commit/e060b61f450d0cd0a574dae32bd1dfaf4f217352 but using only [version.pm](https://metacpan.org/dist/version/view/lib/version.pod)

**Comment by bschmalhofer** [comment]
The change is merged. Let's keep this issue open, in case any problems crop up.

**Comment by jduke-halls** [comment]
Thinking as a DBA, in MySQL and MariaDB there's the variable @@version.  Would this be useful for this instance?  When running on my OTOBO server:

`mysql> select @@version;`
`+-------------------------+`
`| @@version               |`
`+-------------------------+`
`| 8.0.31-0ubuntu0.22.04.1 |`
`+-------------------------+`

**Comment by bschmalhofer** [comment]
Yes, this should be the same string that is returned by [DBI::get_info](https://metacpan.org/pod/DBI#get_info). Another way of getting the version string is `SELECT VERSION()`. This way is effectively used by the SupportDataCollector.

**Comment by bschmalhofer** [comment]
The detection of MariaDB and the appropriate version check must also still be implemented. MariaDB gives versions as e.g. `10.5.18-MariaDB-1:10.5.18+maria~ubu2004`. According to https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/ a MariaDB 10.0 is compatible to MySQL 5.6. So I guess that a minimum version of MariaDB 10.0 should be fine.

**Comment by stefanhaerter** [comment]
Just tested installation of rel-11_0 with mariadb version 10.11.2-MariaDB-1. As implicated by @bschmalhofer , the database version check fails with "Invalid version format (non-numeric data)". Reopening the issue.

**Comment by bschmalhofer** [comment]
Apparently the reported version needs to be cleaned before it can be fed to version.pm. I also propose to do the version check only for MySQL and MariaDB. Those are the most relevant database systems which can be tested with reasonable effort.

**Comment by bschmalhofer** [comment]
TODO:

- [x] sanitize versions reported by the database 
- [x] skip version check for Oracle and PostgreSQL 
- [x] Check that MariaDB has at least version 10.0
- [ ] Test version check for MySQL (not MariaDB)

**Comment by stefanhaerter** [comment]
I encountered a seemingly strange problem when trying to install a fresh rel-11_0 OTOBO. I did several version checks for the database:

```
$ mysqld --version
mysqld  Ver 10.6.12-MariaDB-0ubuntu0.22.04.1 for debian-linux-gnu on x86_64 (Ubuntu 22.04)
```

```
$ mariadb --version
mariadb  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

```
MariaDB [(none)]> select @@version;
+----------------------------------+
| @@version                        |
+----------------------------------+
| 10.6.12-MariaDB-0ubuntu0.22.04.1 |
+----------------------------------+
1 row in set (0,000 sec)
```

However, the Installer kept complaining about me not matching the wanted database version of 10.0. When debugging, I saw the following:

```
#line 1268  /opt/otobo/bin/psgi-bin/../../Kernel/Modules/Installer.pm
$ReportedVersion = "5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1"
```

I couldn't figure out where the `5.5.5-` stems from, but wanted to leave this here, merely as a note if someone has an idea or encounters a similar problem.

**Comment by jduke-halls** [comment]
@stefanhaerter It looks like the PHP devs ran into [this behavior from MariaDB](https://github.com/php/php-src/commit/f9f4a68368406a2ba2bd9fab0494261090183e8e) and found a way around it and documented it [here](https://github.com/php/php-src/issues/7972)
It looks like it has to do with the driver being used.  

I don't know Perl well enough to say this is the best fix, but a hack to implement something like PHP's hack for how to drop "5.5.5-" if the installer encounters it in the DB string of MariaDB could look something like this
```
if (index($ReportedVersion,"5.5.5-") == 0) {
    $ReportedVersion = s/^5.5.5-//;
}
```
inserted between 1270 and 1271.  

I'll defer to actual Perl programmers on the speed/performance of using the index function vs regex.

**Comment by bschmalhofer** [comment]
I did some quick google searches and remained confused about this issue. I think that the ""5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1" is returned indeed by the MySQL C-library. This looks like a bug in the C-library to me. So I second  the suggestion of @jduke-halls  to simply strip the '5.5.5-' in _Installer.pm_, when MariaDB is detected.

See also #1860 .

**Comment by bschmalhofer** [comment]
I checked how `DBD::MariaDB` handles this issue. I looks like the leading "5.5.5-" is simply stripped there too. In https://metacpan.org/release/PALI/DBD-MariaDB-1.23/source/dbdimp.c we have:

```
else if (memEQs(key, kl, "mariadb_serverinfo"))
    {
      const char *serverinfo = imp_dbh->pmysql ? mysql_get_server_info(imp_dbh->pmysql) : NULL;
#ifndef MARIADB_BASE_VERSION
      /* serverinfo for MariaDB server from MySQL client is prefixed by string 5.5.5- */
      if (serverinfo && strBEGINs(serverinfo, "5.5.5-"))
          serverinfo += sizeof("5.5.5-")-1;
#endif
      result = serverinfo ? sv_2mortal(newSVpv(serverinfo, 0)) : &PL_sv_undef;
      sv_utf8_decode(result);
    } 
```

TODO:

- [x] strip the '5.5.5-' in _Kernel/Modules/Installer.pm_

**Comment by stefanhaerter** [comment]
I am a bit baffled about this actually being a real bug in mysql - however, thank you very much for the research to both of you, @jduke-halls and @bschmalhofer !

**Comment by bschmalhofer** [comment]
@stefanhaerter , yes, I'm also a bit baffled. I understand how the need for the workaround with the prefix 5.5.5- arises. But it is not clear to me why it shows up only in some settings. I tried it with the regular Docker images and there the prefix was not present.

Anyways, I have added a check to strip the 5.5.5- when it occurs. Could you test that in your setup?

**Comment by stefanhaerter** [comment]
Yes, I will definitely do that and report the result as soon as I'm done.

**Comment by stefanhaerter** [comment]
Fix works fine. I debug-printed the version string before and afterwards and it looks good:

```
#line 1276  /opt/otobo/bin/psgi-bin/../../Kernel/Modules/Installer.pm
$ReportedVersion = "5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1"

#line 1278  /opt/otobo/bin/psgi-bin/../../Kernel/Modules/Installer.pm
$ReportedVersion = "10.6.12-MariaDB-0ubuntu0.22.04.1"
```

**Comment by bschmalhofer** [comment]
Closing, as there are no current findings.
