### ISSUE TITLE
Customer portal ticket history problem

### ISSUE THREAD

**Issue by kbalcius** [RotherOSS/otobo#810]
Otobo version 10.0.8
After OTRS 6 migration when customer tries to view his ticket communication history only last message is shown.
In other message windows there is a log in screen. With message about java script
Java script is enabled.
Tried with several browsers with same result.

With newly created tickets problem also persists.

![2021-02-19_08h21_21](https://user-images.githubusercontent.com/79300795/108466053-b6edf200-728b-11eb-954a-1e792387e378.png)

**Comment by svenoe** [comment]
Hi kbalcius,

please check the SysConfig for the option HttpType. Most of the time this error occurs, it is set to the wrong value (either it is set to http, but you are using https now, or vice versa).

Sven

**Comment by kbalcius** [comment]
Thanks svenoe. 
Changing http type fixed this problem.
