### ISSUE TITLE
Allow article cache in Redis

### ISSUE THREAD

**Issue by niccord** [RotherOSS/otobo#814]
Currently, you can only have articles cache on Memcached:
```perl
return $Self if $CacheModule ne 'Kernel::System::Cache::MemcachedFast';
```
by removing this row, you can achieve article storage on filesystem and _caching onto Redis_, which becomes incredibly faster than without caching.

https://github.com/RotherOSS/otobo/blob/cacfb8a8547ed79e16aa322e2b873dc36d8bce91/Kernel/System/Ticket/Article/Backend/MIMEBase/ArticleStorageFS.pm#L83

**Comment by svenoe** [comment]
Hi niccord,

thanks for the suggestion. Simply removing this line is not a valid solution as there are still systems running without Redis. Also it should be tested first, how big the impact of this on memory usage is. But of course we can enable caching specifically for Redis, too, here, and it is definitely something we should look into. :)

Best regards, Sven

**Comment by svenoe** [comment]
I merged the pr, thank you.

I will also close this issue, I would be interested in some benchmarks of how much faster various actions get, with this. If anyone has data, by chance... ;)
