### ISSUE TITLE
Migration: column size in PostgreSQL

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#836]
Some database fields are limited in OTOBO to 191 characters. When migrating to MySQL the values are truncated silently. PostgreSQL throws an error.

TODO:

- [x] decide what to do with migrations to PostgreSQL
- [x] act accordingly

**Comment by bschmalhofer** [comment]
This is a bit related to #873, therefore try to pull in some of the changes before applying the changes for #873. First feature is removal of support for batch inserts. This was deactivated anyways. Second feature is declaring the skipped tables as an array.

**Comment by bschmalhofer** [comment]
Changes are merged, but PostgreSQL migration still needs to be tested.

**Comment by svenoe** [comment]
(Not sure whether my last commit fits perfectly, and it also has an oracle change, but it is important for the truncating stuff, too, at least.)

**Comment by svenoe** [comment]
Standard migrations are passing.
