### ISSUE TITLE
Migration: ResetAutoIncrementFields for PostgreSQL 

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#837]
Looks like ResetAutoIncrementFields does not do the expected thing. 
The working command is listed in https://stackoverflow.com/questions/4448340/postgresql-duplicate-key-violates-unique-constraint/21639138.

`SELECT setval(pg_get_serial_sequence('sysconfig_modified_version', 'id'), coalesce(max(id), 0)+1 , false) FROM table_name;`

Also: https://wiki.postgresql.org/wiki/Fixing_Sequences

**Comment by kess-net** [comment]
Works for me on 10.0.9.
If you wish, I could setup a newer Version and test again.

**Comment by kess-net** [comment]
Works for me on 10.0.9 with mysql. 
ah, i see now, thos is an postgresql issue. I'll test again - sorry

**Comment by kess-net** [comment]
I did just two migration tests. Everything worked fine. Looks good for me

**Comment by bschmalhofer** [comment]
Closing this issues as test migrations look fine.
