### ISSUE TITLE
Implement Subaction DisplayActivityDialog for CustomerTicketZoom

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#842]
in a Process Ticket which has an dialog for the customer, we need the "next step" action in the CustomerTicketZoom.

**Comment by svenoe** [comment]
Hi Olli,

Stefan told me, you discussed this as well as #843 and that he will plan things with another party, so that the whole process tickets on the customer interface will be taken care of. (Just to show some reaction here. :)

Best regards, Sven

**Comment by StefanRother-OTOBO** [comment]
Implemented in OTOBO 10.1. Thanks!
