### ISSUE TITLE
Enable CustomerTicketProcess

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#843]
Accessing to customer.pl?Action=CustomerTicketProcess return inconvenience display
![image](https://user-images.githubusercontent.com/80096822/110096875-b03ca000-7d9e-11eb-94a5-cfdf4d9197ea.png)

**Comment by bschmalhofer** [comment]
I can confirm that, seen in Selenium test script  _scripts/test/Selenium/Customer/CustomerTicketProcess.t_

**Comment by bschmalhofer** [comment]
This still does not look better when running CustomerTicketProcess.t in the rel-10_0 branch.
![remmina_localhost_localhost_2021430-10485,963514](https://user-images.githubusercontent.com/46019/116685390-8aa0d100-a9b2-11eb-9448-905050c2fa9e.png)

**Comment by svenoe** [comment]
This is not yet enabled, @bschmalhofer - we are in discussion with some partners, including @OlliW on how to include this, but things are going a bit slow, admittedly.

**Comment by svenoe** [comment]
I opened another issue for this, to plan things a bit, and will close this issue here. Please continue in https://github.com/RotherOSS/otobo/issues/1002 or in separate issues for the implementation of distinct parts.
