### ISSUE TITLE
SystemLog: Can't write '/opt/otobo/var/stats/ITSMStats-001-Ticket.xml.installed': Permission denied

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#846]
Hi!

After migration from OTRS to OTOBO 10.0.9 (Docker) I get a lot of permission denied errors, eg.

```
OTOBO-CGI-31 Can't write '/opt/otobo/var/stats/ITSMStats-001-Ticket.xml.installed': Permission denied
OTOBO-CGI-31 Can't write '/opt/otobo/var/stats/ITSMStats-002-Ticket.xml.installed': Permission denied
OTOBO-CGI-31 Can't write '/opt/otobo/var/stats/ITSMStats-200-ITSMTicketFirstLevelSolutionRate.xml.installed': Permission denied
OTOBO-CGI-31 Can't write '/opt/otobo/var/stats/ITSMStats-406-ITSMChangeManagement.xml.installed': Permission denied
```

I am not sure, if this is a mirgation issue.

Indeed all the ITSM*.installed files have this permission:
`-r--r-----.  1 otobo otobo`

In the old OTRS installation they have "rw" permissions.

Regards,
Michael

**Comment by StefanRother-OTOBO** [comment]
Hi Micha,

thanks for the info, but I can't reproduce this error in the last 50 Migrations. So I think we have fixed this error.

Best wishes,

Stefan
