### ISSUE TITLE
Docker Restore expects empty database

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#847]
Hi!

As shortly explained in the documentation, to restore data from a backup, the database has to exist but may not contain any table.

I think, you should add an instruction to the documentation, how to delete all existing tables from the database otobo.

I used these commands. If you would do it better, please do it, but please add this step to the documentation.
```
docker exec -i otobo_db_1 mysql -u root -p<your_secret_password> -e "DROP DATABASE otobo"
docker exec -i otobo_db_1 mysql -u root -p<your_secret_password> -e 'CREATE DATABASE otobo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
docker exec -i otobo_db_1 mysql -u root -p<your_secret_password> -e "GRANT ALL PRIVILEGES ON otobo.* TO 'otobo'@'%'"

```

Cheers,
Michael

**Comment by svenoe** [comment]
Hi Michael,

thanks, this belongs to the documentation, though. I opened the issue here: https://github.com/RotherOSS/doc-otobo-installation/issues/63

Best regards, Sven
