### ISSUE TITLE
Support for MySQL running on a non-default port

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#85]
I had an use case where I wanted to run MySQL in Docker. On the host there was another MySQL running on port 3306. In order to avoid the conflicting port I mapped the port 3306 in the container to the port 5003 on the host. However in installer.pl I could not specify the port.

IMHO it would be a nice feature it the MySQL port could be specified. If the GUI should be kept as simple as possible, then it would be nice if the port could be specified in Config.pm.

**Comment by stefanhaerter** [comment]
I took a quick look into perldoc DBD::mysql, and as far as I understand it, you can indeed specify the port in Config.pm by adding the parameter to the DatabaseDSN property, like so:

[Old] $Self->{'DatabaseDSN'} = "DBI:mysql:database=$Self->{Database};host=$Self->{DatabaseHost}";
[New] $Self->{'DatabaseDSN'} = "DBI:mysql:database=$Self->{Database};host=$Self->{DatabaseHost};port=5003";

Probably, a starting point could be to specify a DatabasePort property (which has to default to 3306 in the relevant code, of course):

$Self->{'DatabasePort'} = '5003';

$Self->{'DatabaseDSN'} = "DBI:mysql:database=$Self->{Database};host=$Self->{DatabaseHost};port=$Self->{DatabasePort}";

I would consider the decision whether to include the port configuration into the installation process a design decision which should be discussed.

**Comment by stefanhaerter** [comment]
Side note: https://github.com/RotherOSS/otobo/blob/0dcdb0b93a45960ca8b4026979537602ad8bbac0/Kernel/Modules/Installer.pm#L1050

**Comment by stefanhaerter** [comment]
Currently, it seems to be possible to set the port via the Host input field, like 127.0.0.1;port=33000 - since only the case 127.0.0.1:33000 is handled (the :33000 is then stripped). I would suggest to handle this cases consistently, either both should be permitted or both should be prohibited. Since the issue is about building an input field for the port, I would opt for the latter. @bschmalhofer @svenoe what do you think?

**Comment by bschmalhofer** [comment]
I agree, both cases should be handled in the same way. As the input field is called  _Host_ I would opt for stripping in both cases. Adding the field __Port__ is fine with me. Personally I would not mind an advanced possibility to specify the complete DSN, like it it the case when Oracle is used.

**Comment by stefanhaerter** [comment]
Interesting idea. Maybe another input field for the fully qualified FQDN, hidden behind an 'Advanced'-Button?

**Comment by stefanhaerter** [comment]
Is this still considered relevant for 11.0 / 11.1? Else I would suggest to move this to the wishlist.

**Comment by bschmalhofer** [comment]
Moved to the wishlist like @stefanhaerter suggested

**Comment by stefanhaerter** [comment]
Leaving this as a note here: Affects not only installer.pl but also scripts/backup.pl.

**Comment by bschmalhofer** [comment]
I just tested passing `db:3306` as the database name in the installer. This setting was passed unaltered into _Kernel/Config.pm_ and became part of the DSN. The connection to the database worked fine as DBD::mysql supports the `name:port` syntax. See  https://metacpan.org/pod/DBD::mysql#port .

I kind of like the `name:port` syntax, so I argue in favor of not stripping the port from the host. But if this syntax is officially supported it should be properly documented.

**Comment by stefanhaerter** [comment]
Is there any chance that said DSN somehow ends up in the backup script? I have in mind that there were problems with the backup script not supporting the classical DSN notation, but not exactly what the problem was.

**Comment by bschmalhofer** [comment]
I think that _backup.pl_ does not support alternative ports at all. My guess is that the scripts would fail if _Kernel/Config.pm_ had a hostname like `db:3306`.  From my side it would make sense if _backup.pl_ would look at the hostname and the DSN for determining the port. 

Edit: maybe it would be nicer to only look at the DSN, as this is the thingy that should provide everything needed for a connection

**Comment by stefanhaerter** [comment]
> I think that backup.pl does not support alternative ports at all.

It does, since https://github.com/RotherOSS/otobo/pull/4789.

> My guess is that the scripts would fail if Kernel/Config.pm had a hostname like `db:3306`.

This was my suspicion as well and the reason for the question, to be honest.
