### ISSUE TITLE
Docker: GenericInterface TicketCreate - uninitialized value in pattern match

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#853]
Hi!
Using the GenericInterface to create Tickets, i get this warning message:
`plackup: Use of uninitialized value in pattern match (m//) at /opt/otobo/bin/psgi-bin/../../Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm line 1472.`

If I remember well, this issue was a general issue in OTRS as well.

This is the incoming data before mapping in the SOAP array for the article:
```
'Article' => {
    'Body' => 'XXX',
    'Charset' => 'utf8',
    'CommunicationChannel' => 'Email',
    'From' => 'XXX',
    'IsVisibleForCustomer' => '1',
    'MimeType' => 'text/plain',
    'SenderType' => 'customer',
    'Subject' => 'XXX'
  },
```

Regards,
Michael

**Comment by svenoe** [comment]
Hi Michael,

could you download this file https://github.com/RotherOSS/otobo/blob/4aebc9d9d137789de238f2844f70671b635ace3c/Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm (right click on "raw" and "save target as"), replace your Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm and see if the problem persists? This should only be a warning in the first place, though, but the above change should have cleaned it up.

Thanks, Sven

**Comment by micha2021** [comment]
Hi @svenoe 

Danke für Deine prompte Hilfe.

Ich habe die Datei in den Docker Mount Point in das Verzeichnis Custom/Kernel/GenericInterface/Operation/Ticket hochgeladen. Der Fehler tritt nicht mehr auf! Perfekt. Test erfolgreich durchgeführt.

Ich denke, ich stelle die TicketCreate.pm jetzt in das Kernel-Verzeichnis (ohne Custom/), da sie wahrscheinlich dann in 10.0.10 ausgeliefert/überschrieben werden wird. Korrekt?

Viele Grüsse,
Michael

**Comment by svenoe** [comment]
> Ich denke, ich stelle die TicketCreate.pm jetzt in das Kernel-Verzeichnis (ohne Custom/), da sie wahrscheinlich dann in 10.0.10 ausgeliefert/überschrieben werden wird. Korrekt?

Korrekt. :)

Danke dir, für die Bestätigung.
