### ISSUE TITLE
OTOBO Scheduler Daemon SystemConfigurationSyncManager: ConfigurationDeploySync 

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#861]
Confused about this:
What happens?
```
Use of uninitialized value $CleanupSuccess in numeric ne (!=) at
/opt/otobo/Kernel/System/SysConfig.pm line 3759.
```

`Message: There are invalid deployments in the database that could not be removed!`

Here are the last lines of the log:
se of uninitialized value $CleanupSuccess in numeric ne (!=) at
/opt/otobo/Kernel/System/SysConfig.pm line 3759.
ERROR: OTOBO-otobo.Daemon.pl - Daemon
Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-31 Perl: 5.32.0 OS:
linux Time: Tue Mar 9 15:54:53 2021

 Message: There are invalid deployments in the database that could not be removed!

 ```
Traceback (3624):
   Module: Kernel::System::SysConfig::ConfigurationDeploySync Line: 3760
   Module: (eval) Line: 137
   Module: Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager::Run
Line: 124
   Module: (eval) Line: 383
   Module: main::Start Line: 383
   Module: bin/otobo.Daemon.pl Line: 162
```
Regards,
Michael

**Comment by svenoe** [comment]
Hi Michael,

please visit our [forums](https://otobo.de/en/forums/otobo/otobo-forum/) for questions like this, or contact us directly at hello@otobo.de for professional support requests. Please describe what you did to end up in that state, if you do. You could investigate this further via `bin/otobo.Console.pl Admin::Config::ListInvalid` in the meantime.

Best regards, Sven
