### ISSUE TITLE
Config Option Frontend::Navigation###ExternalURLJump###1 not possible to change

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#867]
Hi,

I can't activate Frontend::Navigation###ExternalURLJump###1, cause missing description.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Adding the value in Framework.xml did the trick for a new installation. Installation pre 10.0.10 can upgrade if they want to avoid this effect. Manually editing Framework.xml and running bin/otobo.Console.pl Maint::Config::Rebuild should work too.
Closing this issue.
