### ISSUE TITLE
bin/otobo.Console.pl Admin::Article::StorageSwitch --target ArticleStorageDB does not delete directories

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#870]
Hi!

Playing around with the switch between the allowed values in `Ticket::Article::Backend::MIMEBase::ArticleStorage` I noticed, that if you go  back from `ArticleStorageFS` to `ArticleStorageDB` the script `bin/otobo.Console.pl Admin::Article::StorageSwitch --target ArticleStorageDB` does not delete the directories in `var/article`, but only the files.

I think, the scipt should delete also all directories.

Regards,
Michael

**Comment by svenoe** [comment]
Hi again,

honestly I don't know why the directory is left untouched. It probably could be changed, but people won't switch between both backends very often, if at all, and the directory doesn't break anything, I guess. At the moment this has too low priority, I guess.

Best regards, Sven
