### ISSUE TITLE
Backup: /var/article in Application.tar.gz

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#871]
Hi!

For testing, I switched to ArticleStorageFS.

In the backup, the articles - with the standard configuration of Ticket::Article::Backend::MIMEBase::ArticleDataDir - end up in the file "Apllication.tar.gz". In that file, you can find the configuration, the Kernel, bins, Customer settings, documentation and so on. 

I think, the "var" directory should go into a separate file. The backup of "**application**" is kind of static, var datas are not.

Regards,
Michael

**Comment by svenoe** [comment]
Hi Micha,

thanks for your contribution. We are quite busy with a lot of stuff, at the moment, so no one answered so far, to your older issues, as well. I will quickly go through them.

This suggestion could be incorporated, I guess, but the priority for this is really low, from my standpoint. For most use cases there is no real benefit, I guess...

I will put this to our enhancement suggestions and close it for now, to tidy up a bit.

Best regards, Sven
