### ISSUE TITLE
Admin -> ACL -> CustomerTicketMessage missing in ACLKeysLevel3

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#878]
Hi,

When I create or edit an ACL, the default value "CustomerTicketMessage" is missing. 
Please add it to: ACLKeysLevel3::Actions###100-Default

Thanks!

Stefan

**Comment by bschmalhofer** [comment]
Added the missing value _CustomerTicketMessage_to _Ticket.xml_. Tested this on a fresh OTOBO installation in Docker. First import the ACL export file _scripts/test/sample/ACL/Actions33.yml_ . When editing the imported ACL the value _CustomerTicketMessage_ is then available as action in the GUI.
The added value is available to new installations automatically. Older installations get it during the upgrade via the console command `Maint::Config::Rebuild`.

Closing this issue.
