### ISSUE TITLE
No longer use XML::Parser and XML::Parser::Lite, switch to XML::LibXML

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#88]
For some reason both XML::LibXML and XML::Parser are used in OTOBO. I propose to standardise on XML::LibXML.

**Comment by svenoe** [comment]
In principle there is no reason against it, priority is very low however.

**Comment by bschmalhofer** [comment]
`XML::Parser` is also used in `Kernel::System::XML` which adds another layer of brokenness. Examples of the brokenness are now included in _scripts/test/XML.t_ .

**Comment by bschmalhofer** [comment]
Enhanced the documentation for Kernel::System::XML and added some tests.

**Comment by bschmalhofer** [comment]
`Kernel::System::XML` also uses `XML::Parser::Lite` when `XML::Parser` has problems. Let't test without the fallback first, before migrating Kernel::System::XML to XML::LibXML.

**Comment by bschmalhofer** [comment]
`Kernel::System::XML` could be migrated to `XML::LibXML` by using `XML::LibXML::SAX::Parser`. Let's see whether it can be made bug compatible.

**Comment by bschmalhofer** [comment]
In _Kernel/GenericInterface/Mapping/XSLT.pm_ there is an usage of `XML::Simple`. `XML::Simple` falls back to `XML::Parser` for parsing XML. A first idea is to switch to `Kernel::System::XML::Simple`, but that module does not have a `XMLOut()` method. `XMLOut()` can't be easily added, as the underlying module  `XML::LibXML::Simple` does not have `XMLOut()`. So let's stick with `XML::Simple`. But let's tell XML::Simple to use XML::LibXML::SAX::Parser for the parsing part.

**Comment by bschmalhofer** [comment]
Replaced all usages of XML::Parser that I found. The test suite looks fine. Closing this issue.

**Comment by bschmalhofer** [comment]
After removing `XML::Parser` the feature _div:xmlparser_ can also be removed on _bin/otobo.CheckModules.pl_

**Comment by bschmalhofer** [comment]
For those that are wondering why `XML::Parser` is still part of the Docker installation in rel-11_0.. This info can be deduced from _cpanfile.docker.snapshot_. In that file we see that `Selenium::Remote::Driver` requires `XML::Simple`. `XML::Simple` requires `XML::SAX::Expat`. And finally `XML::Sax::Expat` requires `XML::Parser`.

Also note that `XML::Parser` is also used by `SOAP::Lite`.
