### ISSUE TITLE
Migration OTRS -> OTOBO: Postmaster-Filter

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#891]
Hi!
After migration from OTRS 6 to OTOBO 10.0.9 all the Postmaster Filters are corrupt.

The original entries X-OTRS.... have not been migrated to X-OTOBO..... The values are still there but the X-entries have been replaced by space.

Regards,
Michael

**Comment by svenoe** [comment]
Hi Micha,

Could you please check in your OTRS system, whether you have changed the SysConfig option "PostmasterX-Header"? If so, on your OTOBO system please first reset this exact option to its default and check whether this fixes your problem, and then reintroduce your changes from the OTRS-system to the OTOBO system by hand for now, if it helped.

Regards, Sven
