### ISSUE TITLE
Elastic Search after Migration from OTRS

### ISSUE THREAD

**Issue by imadevel** [RotherOSS/otobo#894]
Hi, 
someone seemes to had a similar problem like me. 
https://github.com/RotherOSS/otobo/issues/765
But since it is closed and my system does not seem to have elastic search after migration I ask the question.
It is a docker installation. The first test installation had elastic search. After I did the migration that took quite some time I can not see elastic search
As in the other Issue I enabled elastic search under webservice. I also looked at Module ### AgentElasticsearchQuickResult witch seems ok
But I don't see the elastic search field.
Also tried to enter the remote name under webservice (the docker name otobo_elastic_1)

Help would be much apreciated.

**Comment by svenoe** [comment]
Hi imadevel,

the Elasticsearch activation is currently not yet done automatically after the migration. Please use our forums for general questions like this: https://otobo.de/en/forums/otobo/otobo-forum/

Best regards, Sven
