### ISSUE TITLE
Setting EnhancedSearchFields is no longer used

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#90]
When looking at the code for CustomerCompanySearchDetail() I found that CustomerCompany::EnhancedSearchFields are mentioned in the POD. This seems to be a leftover from a previous implementation, as the code indicates that the search fields are taken from the CustomerCompanyMaps.

Same applies to CustomerUser.

**Comment by svenoe** [comment]
Merged, thanks.
