### ISSUE TITLE
Github Actions: Combine prove and CodePolicy?

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#913]
For CodePolicy I was not aware, that basically all cpan dependencies of the tested files will have to be installed (see https://github.com/RotherOSS/otobo/runs/2248680414?check_suite_focus=true). For resource efficiency I propose to do both tasks in one github action. We can just install CodePolicy in the docker-otobo of the prove action and run it there.

For the same reason I propose to run this resulting action only on pull requests and commits to the release branches. Any objections @bschmalhofer?

**Comment by bschmalhofer** [comment]
I'm not too happy with using the otobo-docker image for compile checking and for the CodePolicy, even though this was the easiest way when I wrote the prove action. A better way might be to create create an artefact with all the CPAN dependencies and copy that into the standard image. Alternatively we could create a slim image for testing that is the standard image plus the CPAN dependencies.
