### ISSUE TITLE
Elasticsearch doesnt find renamed ticket titles

### ISSUE THREAD

**Issue by butterwecksolutions** [RotherOSS/otobo#917]
Hello, i think if you rename a ticket title by the change ticket function,
you cannot search for this new title with elasticsearch. It will not find anything.
I used 10.0.8 for testing.

Regards
Christian

**Comment by svenoe** [comment]
Hi Christian,

I cannot confirm this. I assume you have not tampered with the TicketManagement invoker settings in the Elasticsearch webservice, so maybe you changed your search settings and didn't put in the title?

<img width="399" alt="Bildschirmfoto 2021-04-08 um 08 40 25" src="https://user-images.githubusercontent.com/48322755/113980543-e8744a00-9846-11eb-863c-ff09d8be160c.png">

Also we have to overhaul Elasticsearch a little bit in the future and e.g. don't use the standard analyzer - maybe you were searching for a "-" or so, which is in the new title? This doesn't work atm.

Best regards, Sven
