### ISSUE TITLE
Setting ViewableTicketsPage no longer used

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#92]
The sysconfig setting ViewableTicketsPage seems to be no longer used. It looks like the number of displayed tickets is now taken from the user preferences.
I also removed manually the now obsolete translation. There is propably a tool for that, but I'm clueless about it.

**Comment by bschmalhofer** [comment]
Leaving out the translations, as there are tools for that.

**Comment by svenoe** [comment]
Merged, thanks.
