### ISSUE TITLE
Customer portal RTL support

### ISSUE THREAD

**Issue by sparse91** [RotherOSS/otobo#927]
Hello
Customer portal has no support for RTL languages (Translations and CSS alignments). Do you have any plan to fix that? Or Is it possible to use older view?

**Comment by svenoe** [comment]
Hi sparse,

the plan would be to implement that at one point, but for the moment there unfortunately is no real capacity, and none of our customers has requested this feature so far. I will add this to our list of requested enhancements, to be honest, I unfortunately don't expect this to be done within the next couple of months...

As you are writing on github and not in our forums - we gladly accept pull requests... ;)

Best regards, Sven
