### ISSUE TITLE
Rework standard settings for passwords and other preferences.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/otobo#935]
We have to look over the current standard preference settings. Especially the password settings are not optimal and are defined twice atm.

**Comment by bschmalhofer** [comment]
Once the defaults are reworked, the test script can be adapted and the TODO test cases reactivated again.

- [x] eliminate TODOs in _scripts/test/Selenium/Output/Preferences/Customer/Password.t_

**Comment by svenoe** [comment]
Surely not completely finished...
