### ISSUE TITLE
Missleading docs about customer user authentication over LDAP

### ISSUE THREAD

**Issue by Djuka** [RotherOSS/otobo#953]
I was working on setting up customer authentication over LDAP (specifically Active Directory) on a clean installation of Otobo. Following the admin docs about Customer User Backend I was able to get a list of customer users after configuring:

```
$Self->{CustomerUser} = {
        Name => 'LDAP Backend',
        Module => 'Kernel::System::CustomerUser::LDAP',
        Params => {
        ...
}
```

I was convinced that was is all that is needed for customer user to authenticate through customer frontend. After hours of failing to  realize what is the problem I got the hang of it. Frontend was using DB authentication, since I didn't change `Customer::AuthModule` settings. After realizing this I got it working in no time.

This configuration is not mentioned at all in admin docs. If this is by design then I think it should be added to admin docs. I would gladly make a pull request to doc-otobo-admin repo.

**Comment by svenoe** [comment]
Hi Ivan,

thanks for pointing this out. I copied this and opened an issue in the admin manual repo. https://github.com/RotherOSS/doc-otobo-admin/issues/25

Best regards, Sven
