### ISSUE TITLE
Elasticsearch Migration: Archived Tickets (Archive Flag)

### ISSUE THREAD

**Issue by RokkuCode** [RotherOSS/otobo#966]
Archived Tickets are not indexed with the Elasticsearch Migration.
In https://github.com/RotherOSS/otobo/blob/59dda3b9806c602d1b8cd5da8f1c15b7fc32f9ab/Kernel/System/Console/Command/Maint/Elasticsearch/Migration.pm#L398 the TicketSearch does not contain:

```
ArchiveFlags => ['y', 'n']  // index all tickets (archived and unarchived)
````
In the end it should be possible to specify if archived tickets should be indexed or not.

**Comment by svenoe** [comment]
A late answer, but this will probably not be included anytime soon, as it seems like a very niche requirement. We'll keep it as a suggestion anyways.
