### ISSUE TITLE
CodePolicy.pl complains about ModuleRequired and PackageRequired

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#98]
With OTRSCodePolicy 1.0.47 I have seen complaints about  ModuleRequired and PackageRequired in .sopm files. However these tags seem to be supported. Did I used the wrong version of the CodePolicy package?

**Comment by svenoe** [comment]
I guess this is a question concerning OTRS packages - maybe it didn't like your ordering, or the TargetVersion is missing? I'll close this here, messaged you via Telegram... ;)
