### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by giomf** [RotherOSS/otobo#993]
I'm just wondering if I'm really using the new UI.
I have tried OTOBO via docker-compose.
When I compare the images on the website (https://otobo.de/en/otobo-features/kundenportal/) with the UI I'm using, it's hard to believe that I'm using the same product.
Do I have to activate the new UI somehow?

For example, the dashboard looks like this:
![image](https://user-images.githubusercontent.com/35076723/117497454-ccb0b080-af78-11eb-9c99-670e89b303ae.png)

**Comment by joserribeiro26** [comment]
The new interface is for the customer portal /otobo/customer.pl

**Comment by giomf** [comment]
Oh ok I see.
Are there any plans to change the UI for the agents as well?

**Comment by joserribeiro26** [comment]
There is an item talking about the agent interface review.

https://otobo.de/en/feature-add-ons/

**Comment by giomf** [comment]
Thanks. I will have a look.
